### ISSUE TITLE
GitHub actions failing

### ISSUE THREAD

**Issue by burstfreeze-alt** [WhiskeySockets/Baileys#10]
Just spent 2 hours trying to get the GitHub Actions working. I give up now.

The workflow can't fetch libsignal via ssh because there is no ssh key, if you make a rule to use https over ssh it will not be able to push the docs. Adding a rule doing the reverse doesn't fix it unfortunately. I was wondering why it insists on ssh when the package.json explicitly allows https and found the answer in the yarn.lock. If I remove the yarn.lock and run yarn again it does introduce https however then the action fails with https://github.com/burstfreeze-alt/Baileys/actions/runs/4764988082/jobs/8470216597#step:5:12 

I suppose there is something being fetched wrong when using https. We could add an ssh key and add some code to make the action generate the request with the ssh key in mind however I don't think that's the right direction given that in the original repo it wasn't required either. The only exception to that would be that ssh keys aren't required for public repos within the same user but that seems unlikely do me.

Ideas?

**Comment by burstfreeze** [comment]
Solved with #11
