### ISSUE TITLE
[REQ] Reaction love Story WA

### ISSUE THREAD

**Issue by rizkanugrha** [WhiskeySockets/Baileys#1000]
How make reaction story WA with Baileys?

**Comment by DannOfficial** [comment]
> How make reaction story WA with Baileys?

wait for more update sir

**Comment by rizkanugrha** [comment]
> I don't think it's possible
> 
> But you can use if (citel.chat.endsWith("broadcast")) Then u take the jid and send message Must add this to your index.js main file

emm, if that's the case I know, but i use this logic before you tell me about it, i use this logic and success. But liked button don't turn on 😁

**Comment by faxxcoders** [comment]
> > How make reaction story WA with Baileys?
> 
> wait for more update sir

Dannton

**Comment by SatzzDev** [comment]
any update?

**Comment by rizkanugrha** [comment]
done

**Comment by Sadaru-OFC** [comment]
> done

how do it ?
