### ISSUE TITLE
[BUG] send media error 

### ISSUE THREAD

**Issue by hattatazure** [WhiskeySockets/Baileys#1007]
send media error 

request url:"https://media.fasr1-1.fna.whatsapp.net/mms/document/...?auth=...&token=token"
response:
{"debug_info":{"retriable":false,"type":"BAD_CHECKSUM","message":"Hash mismatch"}}

**Comment by candidoalbertosilva** [comment]
I have the same problem. How did you solve it?

**Comment by hattatazure** [comment]
Check out the fork on my profile.

> I have the same problem. How did you solve it?
