### ISSUE TITLE
[BUG] I have a problem with reading the QR code; it does not appear

### ISSUE THREAD

**Issue by mohammad-montaser** [WhiskeySockets/Baileys#1011]
I don’t have much experience in finding solutions since I’m not a developer. This is the error that appears to me when I try to troubleshoot the problem

> 0|whatsbot |   requireStack: []
0|whatsbot | }
0|whatsbot | Error: Cannot find module '/www/wwwroot/app.whatsbot.me_new/wa_server/app.js'
0|whatsbot |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
0|whatsbot |     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
0|whatsbot |     at Object.<anonymous> (/www/server/nodejs/v16.18.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|whatsbot |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
0|whatsbot |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
0|whatsbot |     at Module.load (node:internal/modules/cjs/loader:1033:32)
0|whatsbot |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
0|whatsbot |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
0|whatsbot |     at node:internal/main/run_main_module:22:47 {
0|whatsbot |   code: 'MODULE_NOT_FOUND',
0|whatsbot |   requireStack: []

> 

I hope someone can help me by explaining things step-by-step, considering that I am not a developer. Thank you very much

I will attach a picture of what appears in place of the QR code
![2024-08-24_11-30-11](https://github.com/user-attachments/assets/c4a560a9-8f74-4499-a610-3a5ed77fa86e)

**Comment by MahmoudSlameh** [comment]
Change Version Of WA Socket To This Version
It Work For Me

`makeWASocket({
  auth: state,
  version: [2, 3000, 1015901307],
});`

**Comment by mohammad-montaser** [comment]
What are the steps, please?

**Comment by DannOfficial** [comment]
> What are the steps, please?

change and add ur client connection at makeWASocket, the example :
makeWASocket({
        printQRInTerminal: !pairing,
        version: (await (await fetch("https://raw.githubusercontent.com/WhiskeySockets/Baileys/master/src/Defaults/baileys-version.json")).json()).version,
        isLatest: true,

**Comment by mohammad-montaser** [comment]
I'm trying now
