### ISSUE TITLE
[BUG] Error accessing bot command

### ISSUE THREAD

**Issue by SenpaiCookies** [WhiskeySockets/Baileys#1013]
![eerr](https://github.com/user-attachments/assets/2e4367dc-c5dd-4c2e-805d-f5c7ee54cd70)

Hi! It became like this after the update, how do I solve it?

**Comment by Guru322** [comment]
Downgrade your node version to 20

**Comment by Guru322** [comment]
And join baileys discord server

**Comment by SenpaiCookies** [comment]
> Downgrade your node version to 20

Thank you, it's working perfectly again, you are my hero! <3
