### ISSUE TITLE
[BUG] the first loading in ubuntu take so long time

### ISSUE THREAD

**Issue by roysG** [WhiskeySockets/Baileys#1028]
**Describe the bug**
why the loading in ubuntu take so long time?

**To Reproduce**
1. Start simple project in ubuntu
2. You will see the fist initail loading take too much time

**Expected behavior**
Fast loading as like in mac

I also attached the part that take too much time to load

<img width="648" alt="Screenshot 2024-09-04 at 11 24 43" src="https://github.com/user-attachments/assets/ce573854-4b3f-4899-b75b-efc31b5841cf">

**Comment by roysG** [comment]
@w3nder, 
 why do you thumb down?

When i load the bail eyes lib is take very long time in linux

**Comment by w3nder** [comment]
> @w3nder, why do you thumb down?
> 
> When i load the bail eyes lib is take very long time in linux

This problem is not with Baileys, but with your code.

**Comment by roysG** [comment]
but when i run the same code in mac, it load in sec..

**Comment by w3nder** [comment]
I run my APIs on Ubuntu servers without any problems, this problem is with you, node version, poorly written code.

**Comment by roysG** [comment]
Hi,
What is your version of node?
What do you mean poorly code? I tried also run the default example,

I think the problem is that I compile the to. While running. So at Mac is
fast cause I have high cou and memory and Ubuntu is small vps.

Can you please share the command you start your Nodejs app?

Thanks

בתאריך יום ג׳, 10 בספט׳ 2024 ב-21:54 מאת Wender Teixeira <
***@***.***>:
