### ISSUE TITLE
How Invite Admin channel in bot??

### ISSUE THREAD

**Issue by cifumo** [WhiskeySockets/Baileys#1045]
howwww

**Comment by Akkun3704** [comment]
You mean sending channel admin invitation using bot?

**Comment by cifumo** [comment]
> You mean sending channel admin invitation using bot?

yess

**Comment by Akkun3704** [comment]
![Screenshot_2024-09-19-12-36-06-397_com whatsapp](https://github.com/user-attachments/assets/868401e7-eb93-490a-a8cb-f990a837cd2a)
Yeah you can

**Comment by Akkun3704** [comment]
My code

```javascript
const {
	getBinaryNodeChild,
	getBinaryNodeChildString,
	generateWAMessageFromContent,
	isLidUser,
	S_WHATSAPP_NET
} = require('baileys')

const fetchUserLid = async (jid) => {
	// based on https://github.com/WhiskeySockets/Baileys/blob/master/src/Socket/chats.ts#L142-L181
	const [result] = await conn.sendInteractiveQuery([
		{
			tag: 'lid',
			attrs: {}
		}
	], [
		{
			tag: 'user',
			attrs: { jid }
		}
	])
	if (result) {
		const lid = getBinaryNodeChild(result, 'lid')
		return lid.attrs.val
	}
}

const getNewsletterInvite = async (newsletterJid, userLid) => {
	const encoder = new TextEncoder()
	const node = await conn.query({
		tag: 'iq',
		attrs: {
			to: S_WHATSAPP_NET,
			xmlns: 'w:mex',
			type: 'get'
		},
		content: [{
			tag: 'query',
			attrs: { query_id: '6826078034173770' },
			content: encoder.encode(JSON.stringify({
				variables: {
					newsletter_id: newsletterJid,
					user_id: userLid
				}
			}))
		}]
	})
	const result = JSON.parse(getBinaryNodeChildString(node, 'result'))
	// if (result.errors) throw result.errors
	return result.data['xwa2_newsletter_admin_invite_create']
}

const sendNewsletterAdminInvite = async (jid, content, options) => {
	jid = isLidUser(jid) ? jid : await fetchUserLid(jid)
	
	const inviteResp = await getNewsletterInvite(content.newsletter.jid, jid)
	const fullMsg = await generateWAMessageFromContent(jid, {
		newsletterAdminInviteMessage: {
			newsletterJid: inviteResp.id,
			newsletterName: content.newsletter.name,
			jpegThumbnail: content.newsletter.thumbnail,
			caption: content.newsletter.text,
			inviteExpiration: inviteResp.invite_expiration_time
		}
	}, options)
	await conn.relayMessage(jid, fullMsg.message, options)
	return fullMsg
}

return sendNewsletterAdminInvite('xxx@s.whatsapp.net', {
	newsletter: {
		jid: 'xxx@newsletter',
		name: 'Test',
		text: 'Masuk gan',
		thumbnail: Buffer.alloc(0) // customize your own thumbnail 
	}
}, {})
```

**Comment by cifumo** [comment]
> My code
> 
> ```js
> const {
> 	getBinaryNodeChild,
> 	getBinaryNodeChildString,
> 	generateWAMessageFromContent,
> 	isLidUser,
> 	S_WHATSAPP_NET
> } = require('baileys')
> 
> const fetchUserLid = async (jid) => {
> 	// based on https://github.com/WhiskeySockets/Baileys/blob/master/src/Socket/chats.ts#L142-L181
> 	const [result] = await conn.sendInteractiveQuery([
> 		{
> 			tag: 'lid',
> 			attrs: {}
> 		}
> 	], [
> 		{
> 			tag: 'user',
> 			attrs: { jid }
> 		}
> 	])
> 	if (result) {
> 		const lid = getBinaryNodeChild(result, 'lid')
> 		return lid.attrs.val
> 	}
> }
> 
> const getNewsletterInvite = async (newsletterJid, userLid) => {
> 	const encoder = new TextEncoder()
> 	const node = await conn.query({
> 		tag: 'iq',
> 		attrs: {
> 			to: S_WHATSAPP_NET,
> 			xmlns: 'w:mex',
> 			type: 'get'
> 		},
> 		content: [{
> 			tag: 'query',
> 			attrs: { query_id: '6826078034173770' },
> 			content: encoder.encode(JSON.stringify({
> 				variables: {
> 					newsletter_id: newsletterJid,
> 					user_id: userLid
> 				}
> 			}))
> 		}]
> 	})
> 	const result = JSON.parse(getBinaryNodeChildString(node, 'result'))
> 	// if (result.errors) throw result.errors
> 	return result.data['xwa2_newsletter_admin_invite_create']
> }
> 
> const sendNewsletterAdminInvite = async (jid, content, options) => {
> 	jid = isLidUser(jid) ? jid : await fetchUserLid(jid)
> 	
> 	const inviteResp = await getNewsletterInvite(content.newsletter.jid, jid)
> 	const fullMsg = await generateWAMessageFromContent(jid, {
> 		newsletterAdminInviteMessage: {
> 			newsletterJid: inviteResp.id,
> 			newsletterName: content.newsletter.name,
> 			jpegThumbnail: content.newsletter.thumbnail,
> 			caption: content.newsletter.text,
> 			inviteExpiration: inviteResp.invite_expiration_time
> 		}
> 	}, options)
> 	await conn.relayMessage(jid, fullMsg.message, options)
> 	return fullMsg
> }
> 
> return sendNewsletterAdminInvite('xxx@s.whatsapp.net', {
> 	newsletter: {
> 		jid: 'xxx@newsletter',
> 		name: 'Test',
> 		text: 'Masuk gan',
> 		thumbnail: Buffer.alloc(0) // customize your own thumbnail 
> 	}
> }, {})
> ```

arigatoo

**Comment by cifumo** [comment]
> My code
> 
> ```js
> const {
> 	getBinaryNodeChild,
> 	getBinaryNodeChildString,
> 	generateWAMessageFromContent,
> 	isLidUser,
> 	S_WHATSAPP_NET
> } = require('baileys')
> 
> const fetchUserLid = async (jid) => {
> 	// based on https://github.com/WhiskeySockets/Baileys/blob/master/src/Socket/chats.ts#L142-L181
> 	const [result] = await conn.sendInteractiveQuery([
> 		{
> 			tag: 'lid',
> 			attrs: {}
> 		}
> 	], [
> 		{
> 			tag: 'user',
> 			attrs: { jid }
> 		}
> 	])
> 	if (result) {
> 		const lid = getBinaryNodeChild(result, 'lid')
> 		return lid.attrs.val
> 	}
> }
> 
> const getNewsletterInvite = async (newsletterJid, userLid) => {
> 	const encoder = new TextEncoder()
> 	const node = await conn.query({
> 		tag: 'iq',
> 		attrs: {
> 			to: S_WHATSAPP_NET,
> 			xmlns: 'w:mex',
> 			type: 'get'
> 		},
> 		content: [{
> 			tag: 'query',
> 			attrs: { query_id: '6826078034173770' },
> 			content: encoder.encode(JSON.stringify({
> 				variables: {
> 					newsletter_id: newsletterJid,
> 					user_id: userLid
> 				}
> 			}))
> 		}]
> 	})
> 	const result = JSON.parse(getBinaryNodeChildString(node, 'result'))
> 	// if (result.errors) throw result.errors
> 	return result.data['xwa2_newsletter_admin_invite_create']
> }
> 
> const sendNewsletterAdminInvite = async (jid, content, options) => {
> 	jid = isLidUser(jid) ? jid : await fetchUserLid(jid)
> 	
> 	const inviteResp = await getNewsletterInvite(content.newsletter.jid, jid)
> 	const fullMsg = await generateWAMessageFromContent(jid, {
> 		newsletterAdminInviteMessage: {
> 			newsletterJid: inviteResp.id,
> 			newsletterName: content.newsletter.name,
> 			jpegThumbnail: content.newsletter.thumbnail,
> 			caption: content.newsletter.text,
> 			inviteExpiration: inviteResp.invite_expiration_time
> 		}
> 	}, options)
> 	await conn.relayMessage(jid, fullMsg.message, options)
> 	return fullMsg
> }
> 
> return sendNewsletterAdminInvite('xxx@s.whatsapp.net', {
> 	newsletter: {
> 		jid: 'xxx@newsletter',
> 		name: 'Test',
> 		text: 'Masuk gan',
> 		thumbnail: Buffer.alloc(0) // customize your own thumbnail 
> 	}
> }, {})
> ```

![Screenshot_20240919_175258](https://github.com/user-attachments/assets/634d782f-46a8-4bad-9beb-22988b502387)
nooo error huhu

**Comment by Akkun3704** [comment]
> > My code
> > ```js
> > const {
> > 	getBinaryNodeChild,
> > 	getBinaryNodeChildString,
> > 	generateWAMessageFromContent,
> > 	isLidUser,
> > 	S_WHATSAPP_NET
> > } = require('baileys')
> > 
> > const fetchUserLid = async (jid) => {
> > 	// based on https://github.com/WhiskeySockets/Baileys/blob/master/src/Socket/chats.ts#L142-L181
> > 	const [result] = await conn.sendInteractiveQuery([
> > 		{
> > 			tag: 'lid',
> > 			attrs: {}
> > 		}
> > 	], [
> > 		{
> > 			tag: 'user',
> > 			attrs: { jid }
> > 		}
> > 	])
> > 	if (result) {
> > 		const lid = getBinaryNodeChild(result, 'lid')
> > 		return lid.attrs.val
> > 	}
> > }
> > 
> > const getNewsletterInvite = async (newsletterJid, userLid) => {
> > 	const encoder = new TextEncoder()
> > 	const node = await conn.query({
> > 		tag: 'iq',
> > 		attrs: {
> > 			to: S_WHATSAPP_NET,
> > 			xmlns: 'w:mex',
> > 			type: 'get'
> > 		},
> > 		content: [{
> > 			tag: 'query',
> > 			attrs: { query_id: '6826078034173770' },
> > 			content: encoder.encode(JSON.stringify({
> > 				variables: {
> > 					newsletter_id: newsletterJid,
> > 					user_id: userLid
> > 				}
> > 			}))
> > 		}]
> > 	})
> > 	const result = JSON.parse(getBinaryNodeChildString(node, 'result'))
> > 	// if (result.errors) throw result.errors
> > 	return result.data['xwa2_newsletter_admin_invite_create']
> > }
> > 
> > const sendNewsletterAdminInvite = async (jid, content, options) => {
> > 	jid = isLidUser(jid) ? jid : await fetchUserLid(jid)
> > 	
> > 	const inviteResp = await getNewsletterInvite(content.newsletter.jid, jid)
> > 	const fullMsg = await generateWAMessageFromContent(jid, {
> > 		newsletterAdminInviteMessage: {
> > 			newsletterJid: inviteResp.id,
> > 			newsletterName: content.newsletter.name,
> > 			jpegThumbnail: content.newsletter.thumbnail,
> > 			caption: content.newsletter.text,
> > 			inviteExpiration: inviteResp.invite_expiration_time
> > 		}
> > 	}, options)
> > 	await conn.relayMessage(jid, fullMsg.message, options)
> > 	return fullMsg
> > }
> > 
> > return sendNewsletterAdminInvite('xxx@s.whatsapp.net', {
> > 	newsletter: {
> > 		jid: 'xxx@newsletter',
> > 		name: 'Test',
> > 		text: 'Masuk gan',
> > 		thumbnail: Buffer.alloc(0) // customize your own thumbnail 
> > 	}
> > }, {})
> > ```
> 
> ![Screenshot_20240919_175258](https://private-user-images.githubusercontent.com/146169339/368958056-634d782f-46a8-4bad-9beb-22988b502387.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDk2NjksIm5iZiI6MTcyNjc0OTM2OSwicGF0aCI6Ii8xNDYxNjkzMzkvMzY4OTU4MDU2LTYzNGQ3ODJmLTQ2YTgtNGJhZC05YmViLTIyOTg4YjUwMjM4Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMjM2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmExOTliYWM0YWRkZWZhOTFmM2Q3MGZmMmNkODczMmIwYTY4ZWJkYjcyOWQzNzI5OTZhYjBiYjYwMTlkODA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2KYSun9vfIHdSm51kt0tMleOaY9lHUlvnzTWow5DvDE) nooo error huhu

Yeah, because [interactiveQuery function](https://github.com/WhiskeySockets/Baileys/blob/master/src/Socket/chats.ts#L142-L181) is not exported by baileys, so you have to create/export the function yourself
