### ISSUE TITLE
[BUG] QR generated, scanned but not captured by system.

### ISSUE THREAD

**Issue by rudranshgoel1** [WhiskeySockets/Baileys#1049]
**Describe the bug**
My site uses this code, it generates a QR, QR is shown, I scan it but it does not capture in the system. Its just stuck on the QR Page, and in the phone, it shows Syncing for a long time.

**Expected behavior**
It should be captured and shown in the panel.

**Environment (please complete the following information):**
 - Is this on a server?
 - > Yes, AAPanel (Hostinger (Mumbai, India))

**Comment by cvchelles** [comment]
Did you fix it?

**Comment by rudranshgoel1** [comment]
No.

**Comment by tr-wa2el** [comment]
+1

**Comment by rudranshgoel1** [comment]
Found the Solution

Contact me on +91 9310294656 if you want it fixed.
