### ISSUE TITLE
[BUG] Message Command Not Show

### ISSUE THREAD

**Issue by VanzRevoer** [WhiskeySockets/Baileys#1050]
![Screenshot_20240920-212258](https://github.com/user-attachments/assets/ef3966b6-b8bb-4528-999d-0656d2ab4816)
![Screenshot_20240920-212238](https://github.com/user-attachments/assets/bb561ec7-2a69-4db1-b6ee-bf284c093d36)

Message command is not showing while I try to type (menu) command. 
If its a my code failure, why connection success message ( Revoer Botz Telah Aktif Dan Siap Untuk Digunakan) is send? and command is not send any message? please help me. 
Previous sincerely I try 3 days ago it's working and now is not.
Please help

**Comment by mrfzvx12** [comment]
> ![Screenshot_20240920-212258](https://private-user-images.githubusercontent.com/182244336/369441873-ef3966b6-b8bb-4528-999d-0656d2ab4816.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzAxMjEsIm5iZiI6MTcyNjkyOTgyMSwicGF0aCI6Ii8xODIyNDQzMzYvMzY5NDQxODczLWVmMzk2NmI2LWI4YmItNDUyOC05OTlkLTA2NTZkMmFiNDgxNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNDQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGNkM2JhZjQ5ZWE5YjQ2ZGZkY2UyNDk1MjU0NGY5ZjdhZjNkYTk1NzBmZTk4ZmE4YzJjZWRlZjYxN2U0NjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HKda4aLNo3KGgqMEc9by7BZFdaGjG2rOVlCNw7YUE8s) ![Screenshot_20240920-212238](https://private-user-images.githubusercontent.com/182244336/369441902-bb561ec7-2a69-4db1-b6ee-bf284c093d36.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzAxMjEsIm5iZiI6MTcyNjkyOTgyMSwicGF0aCI6Ii8xODIyNDQzMzYvMzY5NDQxOTAyLWJiNTYxZWM3LTJhNjktNGRiMS1iNmVlLWJmMjg0YzA5M2QzNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNDQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGFhNGRjMDNhOTliYjM2Y2FjY2IwOGM2NmI5ODQzMTc0YzhmZDdjNTExZDkxMDBlMGNlNjdiOWRiZmQyZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HfINjrM9KJKbqGjaTT2RZxt-QvAImK58A6m8CxJqq6o)
> 
> Message command is not showing while I try to type (menu) command. If its a my code failure, why connection success message ( Revoer Botz Telah Aktif Dan Siap Untuk Digunakan) is send? and command is not send any message? please help me. Previous sincerely I try 3 days ago it's working and now is not. Please help

error in your code, not from baileys
