### ISSUE TITLE
[BUG]QR Code not Scan , Waziper also not working 

### ISSUE THREAD

**Issue by spacesoft321** [WhiskeySockets/Baileys#1054]
we are try to scan qr code , but its not working 

we try also in waziper but same issue 

we use proxy server also but same issue 

**i try also in FastWSapi.com or API4ws.com but same issue** 

please update qr code issue for waziper + other application

**Comment by rudranshgoel1** [comment]
Is it fixed yet?

**Comment by AnandPatel404** [comment]
brother check out this www.whatsme.in i built it on this library this work fine

**Comment by rudranshgoel1** [comment]
brother i want waziper to work, is there any developer you know that can help, please

**Comment by rudranshgoel1** [comment]
and how much does whitelabel cost for whatsme.in??

**Comment by achalag1** [comment]
QR Code Scan Not Working, Any one has solutions ?/

**Comment by AnandPatel404** [comment]
i also face this issue my qr code also not showing and show the no session find error, i just do 3 things and working properly 
1 remove all node modules and package-lock.json
2 re install it by npm i or yarn add
note: my baileys version is ^6.7.5

**Comment by rudranshgoel1** [comment]
My baileys version is 6.5.0
I am not very good in web handling.
Please guide me how to upgrade my baileys version to 6.7.7 of 6.7.5 as you wish.

**Comment by AnandPatel404** [comment]
please backup your current project then do it
1 : remove node_module  and package-lock.json
2 : now got to package.json of your project and change like this in dependencies "@whiskeysockets/baileys": "^6.7.5"
3 : now if you use npm then npm i or if you use yarn then yarn add 
4 : check your qr route

**Comment by rudranshgoel1** [comment]
can you contact me through whatsapp?
I want to resolve other queries as well and you look like a nice guy!

+919310294656

**Comment by AnandPatel404** [comment]
np bro i will contact you 👍

**Comment by rudranshgoel1** [comment]
🫂

**Comment by AnandPatel404** [comment]
and my number is +918849036222

**Comment by sahilbrandwala** [comment]
Any issue will do fix contact me on WhatsApp 919647504140

**Comment by achalag1** [comment]
Does A

> please backup your current project then do it 1 : remove node_module and package-lock.json 2 : now got to package.json of your project and change like this in dependencies "@whiskeysockets/baileys": "^6.7.5" 3 : now if you use npm then npm i or if you use yarn then yarn add 4 : check your qr route

Is This Solution Working With Waziper.. ?? Has Anyone tested ?

**Comment by mrblackeg** [comment]
> Does A
> 
> > please backup your current project then do it 1 : remove node_module and package-lock.json 2 : now got to package.json of your project and change like this in dependencies "@whiskeysockets/baileys": "^6.7.5" 3 : now if you use npm then npm i or if you use yarn then yarn add 4 : check your qr route
> 
> Is This Solution Working With Waziper.. ?? Has Anyone tested ?

yes i test it and it's worked

**Comment by spacesoft321** [comment]
now all error fix

you can test now 

**FastWSapi.com**

and

**API4ws.com**

Just Change Server IP , maybe WhatsApp block your Server IP

**Comment by spacesoft321** [comment]
> and how much does whitelabel cost for whatsme.in??

we provide free whitelabel and hosting also , with lifetime validity and free update as per update code by WhiskeySockets/Baileys

you can check live demo on FastWSapi.com

https://www.facebook.com/kavita.mantri.50

![FastWSapi](https://github.com/user-attachments/assets/cc3b9560-63a4-4709-be62-c01021ae6594)

**Comment by jmd-2000** [comment]
WhiskeySockets/Baileys is working properly. However, there is an issue with the Waziper script. I found a solution. WhatsApp me at +91 8263884847 if you need it fixed.

**Comment by shadyrasmy** [comment]
> Please backup your current project and then do it 1 : remove node_module and package-lock.json 2 : now got to package.json of your project and change like this in dependencies "@whiskeysockets/baileys": "^6.7.5" 3 : now if you use npm then npm i or if you use yarn then yarn add 4 : check your qr route

after deleting node_modules folder where can I get the new one?
and that's what package.jason looks like where to change 
![Screenshot 2024-09-23 214120](https://github.com/user-attachments/assets/f2a41805-1c73-40a9-95ef-05dad9e2a58e)
ps I am using waziper
