### ISSUE TITLE
[BUG] Error in uploading to mmg.whatsapp.net and Error in uploading to media-hou1-1.cdn.whatsapp.net

### ISSUE THREAD

**Issue by allanlisboa** [WhiskeySockets/Baileys#1057]
I'm getting a lot of media upload errors to the WhatsApp server as you can see in the screenshot below

Errors:
Error in uploading to media-hou1-1.cdn.whatsapp.net
Error in uploading to mmg.whatsapp.net

![Captura de Tela 2024-09-21 às 10 55 10](https://github.com/user-attachments/assets/b8c27ff4-303d-44af-ae82-f51b80c77636)

**Comment by leoffx** [comment]
The error message says "cannot process empty file". If your image file is fine, there's probably an error on the way you are using the function. Can you post your code here?

**Comment by allanlisboa** [comment]
Yes! Here is my function and the complete error log:

Error log: 

{"level":40,"time":"2024-09-21T14:41:21.210Z","pid":400886,"hostname":"dal-sm2029bt-hntr-4-3","class":"baileys","trace":"AxiosError: Request failed with status code 400\n    at settle (/home/deploy/sender-sessions-server/node_modules/axios/dist/node/axios.cjs:2015:12)\n    at IncomingMessage.handleStreamEnd (/home/deploy/sender-sessions-server/node_modules/axios/dist/node/axios.cjs:3131:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/home/deploy/sender-sessions-server/node_modules/axios/dist/node/axios.cjs:4262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.upload (/home/deploy/sender-sessions-server/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:542:30)\n    at async /home/deploy/sender-sessions-server/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:122:28\n    at async Promise.all (index 0)\n    at async prepareWAMessageMedia (/home/deploy/sender-sessions-server/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:120:40)\n    at async generateWAMessageContent (/home/deploy/sender-sessions-server/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:415:13)\n    at async generateWAMessage (/home/deploy/sender-sessions-server/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:507:59)\n    at async Object.sendMessage (/home/deploy/sender-sessions-server/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:621:33)","uploadResult":{"debug_info":{"retriable":false,"type":"EMPTY_FILE_V4","message":"Cannot process empty file"}},"msg":"Error in uploading to media-hou1-1.cdn.whatsapp.net , retrying..."}

nodeJS with express controller: 

![Captura de Tela 2024-09-21 às 14 12 42](https://github.com/user-attachments/assets/26a3bf5f-a65f-4374-aa83-b6fbd1e9a742)

Routing using upload with express and multer: 

![Captura de Tela 2024-09-21 às 14 15 15](https://github.com/user-attachments/assets/d68b8bca-da00-4852-acce-c5a253eced92)

![Captura de Tela 2024-09-21 às 14 14 20](https://github.com/user-attachments/assets/9f949eef-a1ba-48aa-b3c4-b61fb39a872a)

**Comment by drauber** [comment]
Hello @allanlisboa! 
I have exactly same problem, you can find and solve the problem?

Thanks!
