### ISSUE TITLE
[BUG] , There is an (explanatory video.) The session error appears to the client and does not appear on the site. 

### ISSUE THREAD

**Issue by mohammad-montaser** [WhiskeySockets/Baileys#1059]
"The issue, in brief, is that the client scans the QR code. It shows as active on the phone but doesn't appear on the website. Then the usual error appears where the QR code is located."
video   

https://youtu.be/5-pAqilEsRk

Can anyone help me solve the problem?
Thank you very much in advance and for your patience

**Comment by priyanshuChovatiya** [comment]
Same error occurred here..

**Comment by priyanshuChovatiya** [comment]
> Guess it's a problem in your code rather than Bailey

Some day ago the code are working fine. then this issue are facing many developers then i think WhatsApp release measure changes.

**Comment by priyanshuChovatiya** [comment]
> Someone got fix it in Waziper?

Yes.

**Comment by nastasache** [comment]
Try Bailyes 6.7.8 or try with timeout (#3 param) in ppurl, ie: profilePictureUrl(<your_whatsapp_user_id>, 'preview', 3000);

**Comment by cvchelles** [comment]
> > Someone got fix it in Waziper?
> 
> Yes.

Can you share?

**Comment by mohammad-montaser** [comment]
> > Someone got fix it in Waziper?
> 
> Yes.
