### ISSUE TITLE
[BUG] Is it true that message buttons or interactive messages cannot be used on WhatsApp desktop and web?

### ISSUE THREAD

**Issue by Rmgs06** [WhiskeySockets/Baileys#1065]
in WhatsApp Web does not display buttons
![wabug](https://github.com/user-attachments/assets/6acbda8e-5b27-4563-a5a6-7de2a0ddf075)
in WhatsApp mobile display it
![WhatsApp Image 2024-09-28 at 10 09 11](https://github.com/user-attachments/assets/fe350ac8-191f-4f7c-933f-d62cde40514c)

**Comment by Sansekai** [comment]
Ya

**Comment by spacesoft321** [comment]
Bulk Whatsapp New Update

Get Reply In Dashboard

For More Details ContactUS

-

Whatski Technologies
https://whatski.co

**Comment by Darkking1098** [comment]
yes, it's true. in that case whatsapp send message response as "unsupported message type".

**Comment by Rmgs06** [comment]
> yes, it's true. in that case whatsapp send message response as "unsupported message type", Also, it doesn't display order, product and catalog messages

Is there an option to checking the sender using WhatsApp desktop/web?

**Comment by Darkking1098** [comment]
Till now in my knowledge, there is not a way to do so. As message is forwarded to all channels (mobile and desktop) and it is decided by whatsapp. 
Means user can see that message in mobile too, if not appeared in desktop or web.

**Comment by Darkking1098** [comment]
Can you tell me, if i can use this library to use 3000 users on a single server without any ban??

**Comment by Rmgs06** [comment]
sorry,i don't know, I've only used it on a small scale

**Comment by bobslavtriev** [comment]
??????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by FaelN1** [comment]
> Você pode me dizer se eu posso usar esta biblioteca para usar 3000 usuários em um único servidor sem qualquer banimento

Yes you can

**Comment by FaelN1** [comment]
> Can you tell me, if i can use this library to use 3000 users on a single server without any ban??

Yes you can

**Comment by Darkking1098** [comment]
> > Can you tell me, if i can use this library to use 3000 users on a single server without any ban??
> 
> Yes you can

Can you help me to choose a right server ?

**Comment by FaelN1** [comment]
> > > Can you tell me, if i can use this library to use 3000 users on a single server without any ban??
> > 
> > 
> > Yes you can
> 
> Can you help me to choose a right server ?

Of course, send me an email so we can talk better; contato@faeldev.com.

**Comment by lifanwar** [comment]
> > > Can you tell me, if i can use this library to use 3000 users on a single server without any ban??
> > 
> > 
> > Yes you can
> 
> Can you help me to choose a right server ?

i think you can use https://builderbot.vercel.app/en and send api with any proramming do you use like python, js etc. i have try it 1 week ago that's 3000 people
