### ISSUE TITLE
Manage Labels (Create, Update, Remove)

### ISSUE THREAD

**Issue by eduardochaves1** [WhiskeySockets/Baileys#1069]
From what I've look, Baileys still doesn't have a CRUD for WhatsApp Labels. Was this already discussed? Do we have limitations on trying to do it?

Having this ability would be perfect so I wouldn't need to ask for my customers to create new labels manually from the app.

**Comment by purpshell** [comment]
They do. Please look at the functions provided (add/removeChatLabel and addLabel functions)
addLabel can remove labels, and edit them by keeping the id of the label intact

**Comment by eduardochaves1** [comment]
> They do. Please look at the functions provided (add/removeChatLabel and addLabel functions)
> addLabel can remove labels, and edit them by keeping the id of the label intact

Yes, I just did a `npm install` and with the updated Baileys version I found it. I'll be testing it later on with my app.
