### ISSUE TITLE
[BUG]

/home/container/node_modules/@protobufjs/base64/index.js: 105

throw Eror

### ISSUE THREAD

**Issue by FahmiOFFC** [WhiskeySockets/Baileys#1098]
![IMG_20241021_204450.jpg](https://github.com/user-attachments/assets/bdbf2f95-4952-4953-a332-f669722042bf)

**Comment by AyGemuy** [comment]
> ![IMG_20241021_204450.jpg](https://private-user-images.githubusercontent.com/183330785/378452708-bdbf2f95-4952-4953-a332-f669722042bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzI0MzQsIm5iZiI6MTczMjMzMjEzNCwicGF0aCI6Ii8xODMzMzA3ODUvMzc4NDUyNzA4LWJkYmYyZjk1LTQ5NTItNDk1My1hMzMyLWY2Njk3MjIwNDJiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QwMzIyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjM4MTM4MDhmODYzMjNiMjM1MjE0M2QxMjQ3NjI1ZTM3ZTBiZDMxYTM4MGMzZGVlNmJiMzg4Njg1ZjA4NDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hiYTCM7lZ42zzsbMjldgZPkvXSWqi1be46fnU4rNT4Y)

Woilah cik

**Comment by ywxzyy** [comment]
stop your stupid shit

**Comment by DannOfficial** [comment]
weladalah, itu yang error bukan module, tapi scnya

**Comment by skyzyycode** [comment]
nguwawor

**Comment by DannOfficial** [comment]
weladalah cik

**Comment by rizkiwibu** [comment]
tetot

**Comment by rizkiwibu** [comment]
![825a5d0d-1ff2-4019-8b5d-93821cb3d69f](https://github.com/user-attachments/assets/b154ade0-62f9-4f76-a1b5-2988e3f4c439)

**Comment by FuadBoTz-MD** [comment]
Tot

**Comment by xmhddafa** [comment]
Ngentod
