### ISSUE TITLE
Whatsapp removed interactiveMessage?

### ISSUE THREAD

**Issue by Salientekill** [WhiskeySockets/Baileys#1102]
I use interactiveMessage to send payment messages, and I noticed that I can no longer send them. Could someone help me?

**Comment by Miyan0001** [comment]
up

**Comment by clicknetcafe** [comment]
Yes, im using whatsapp beta.
But still shown on whatsapp bussines.

**Comment by mateusantos24** [comment]
same, i'm using WhatSapp beta RIP

**Comment by DGXeon** [comment]
Button patched but i have private code that enables the button again.. if interested to buy you can telegram me for demo @DGXeon

**Comment by sahilbrandwala** [comment]
Private code available for button contact us @mediabytex on TG

**Comment by Salientekill** [comment]
@DGXeon @sahilbrandwala Called you on TG

**Comment by DevTamaOfficial** [comment]
🥲

**Comment by SINNOMBRE22** [comment]
Ya ay nuevos botones interactivos para Whatsapp o aún no

**Comment by Salientekill** [comment]
> Ya ay nuevos botones interactivos para Whatsapp o aún no

It has always existed, but with modified baileys
