### ISSUE TITLE
Can this library send a whatsapp button and list menu? what the code?

### ISSUE THREAD

**Issue by Jeative** [WhiskeySockets/Baileys#1106]
Can i send a whatsapp button message?

**Comment by radhesolution** [comment]
Hi,

In our software, you can send different types of WhatsApp messages, including btn messages.

To ensure everything is working correctly, please follow the steps below to test various message types. Send your test messages to +917878222906:

> Poll Message > Type .poll to test a poll message.

> BTN Message > Type .btn to test a standard reply btn.

> Call to Action BTN > Type .cta to test a call-to-action btn (call & URL).

> BTN with Media Message > Type .btnmedia to test the btn integrated with media content.

> Menu Message > Type .menu to test the menu btn.

By following these steps, you can ensure that all the different types of WhatsApp messages function as expected.

Digi Bulk Marketing
