### ISSUE TITLE
[BUG] I can't send button message

### ISSUE THREAD

**Issue by tolgakocadag** [WhiskeySockets/Baileys#1123]
"@whiskeysockets/baileys": "^6.7.9",

                            let buttons = [];
                            req.body.buttons.forEach((button,index) => {
                                buttons.push({ buttonId: "id"+index, buttonText: { displayText: button }, type:1});
                            });

                            result = await spc.whatsapp.sock.sendMessage(`${phoneNumber}@s.whatsapp.net`, {
                                text: message,
                                buttons: buttons,
                                headerType: 1
                            });
                            
--------------
                The text content is gone but the buttons are not coming. How can I do it?

**Comment by Akkun3704** [comment]
#956 button is deprecated

**Comment by radhesolution** [comment]
Hi,

In our software, you can send different types of WhatsApp messages, including btn messages.

To ensure everything is working correctly, please follow the steps below to test various message types. Send your test messages to +917878222906:

> Poll Message > Type .poll to test a poll message.

> BTN Message > Type .btn to test a standard reply btn.

> Call to Action BTN > Type .cta to test a call-to-action btn (call & URL).

> BTN with Media Message > Type .btnmedia to test the btn integrated with media content.

> Menu Message > Type .menu to test the menu btn.

By following these steps, you can ensure that all the different types of WhatsApp messages function as expected.

Digi Bulk Marketing
