### ISSUE TITLE
Please support the function of sending updates

### ISSUE THREAD

**Issue by xiaohuwei** [WhiskeySockets/Baileys#1126]
At present, the web version of WhatsApp can send account updates, text, images, or videos. Please support it
![](https://cdn-fusion.imgcdn.store/i/2024/bccd721b0b203961.png)

**Comment by DikaArdnt** [comment]
> At present, the web version of WhatsApp can send account updates, text, images, or videos. Please support it ![](https://camo.githubusercontent.com/73818509585d7d27d905c39140f4eaa7a122ad6840a070e046ef3acc59ab139c/68747470733a2f2f63646e2d667573696f6e2e696d6763646e2e73746f72652f692f323032342f626363643732316230623230333936312e706e67)

sending status/stories? it can already be done, you just need to change the jid to `status@broadcast` and add `statusJidList: ['target@s.whatsapp.net']` to the options

```js
conn.sendMessage('status@broadcast', { text: 'Hello World' }, { statusJidList: [conn.user.id] })
```

**Comment by firdausiregar** [comment]
after the WhatsApp application is updated 

function of: 
`sock.sendMessage('status@broadcast', { text: 'I am here' }, { statusJidList: [sock.user.id] })`
can not be used

**Comment by Riders004** [comment]
> > At present, the web version of WhatsApp can send account updates, text, images, or videos. Please support it ![](https://camo.githubusercontent.com/73818509585d7d27d905c39140f4eaa7a122ad6840a070e046ef3acc59ab139c/68747470733a2f2f63646e2d667573696f6e2e696d6763646e2e73746f72652f692f323032342f626363643732316230623230333936312e706e67)
> 
> sending status/stories? it can already be done, you just need to change the jid to `status@broadcast` and add `statusJidList: ['target@s.whatsapp.net']` to the options
> 
> ```js
> conn.sendMessage('status@broadcast', { text: 'Hello World' }, { statusJidList: [conn.user.id] })
> ```


How to send media  and media with captions
