### ISSUE TITLE
[BUG] Interactive messages are not visible on regular WA or on WA business. The WA message interface does not display text or buttons

### ISSUE THREAD

**Issue by Dewinet** [WhiskeySockets/Baileys#1127]
Interactive messages are not visible on regular WA or on WA business. The WA message interface does not display text or buttons

**Comment by MyDapitt** [comment]
Some features like sending interactive texts will be patched in the future. I was very surprised to hear this news. 
Maybe, WhatsApp patched the interactive messaging feature from Baileys because it is illegal.

**Comment by bobslavtriev** [comment]
?????????????????????????????????????????????????????????????????????

**Comment by DGXeon** [comment]
I have button working,  you can contact me on telegram for purchase, my telegram is @DGXeon
