### ISSUE TITLE
help please on m.keys.fromme

### ISSUE THREAD

**Issue by RyuGameDev** [WhiskeySockets/Baileys#1130]
Why when using version 6.7.6 and above when I send a message via Baileys it will trigger 

m.keys.fromme=true

This makes it impossible for us to differentiate between messages sent by Baileys and messages sent manually via WhatsApp.
even though in the previous version if Baileys sent a message by baileys would not trigger that event, I prefer version 6.7.5 and below but there the profile picture feature is not available

**Comment by mrfzvx12** [comment]
> Why when using version 6.7.6 and above when I send a message via Baileys it will trigger
> 
> m.keys.fromme=true
> 
> This makes it impossible for us to differentiate between messages sent by Baileys and messages sent manually via WhatsApp. even though in the previous version if Baileys sent a message by baileys would not trigger that event, I prefer version 6.7.5 and below but there the profile picture feature is not available

use message id (m.key.id), message id sent via baileys are different from messages sent manually via whatsapp

**Comment by SheIITear** [comment]
Your code probably uses the old style message id. You will have to update your code to fit the new message id style.

**Comment by RyuGameDev** [comment]
> > Why when using version 6.7.6 and above when I send a message via Baileys it will trigger
> > m.keys.fromme=true
> > This makes it impossible for us to differentiate between messages sent by Baileys and messages sent manually via WhatsApp. even though in the previous version if Baileys sent a message by baileys would not trigger that event, I prefer version 6.7.5 and below but there the profile picture feature is not available
> 
> use message id (m.key.id), message id sent via baileys are different from messages sent manually via whatsapp


how to differentiate between sent via baileys are different from messages sent manually via whatsapp

**Comment by mrfzvx12** [comment]
> > > Why when using version 6.7.6 and above when I send a message via Baileys it will trigger
> > > m.keys.fromme=true
> > > This makes it impossible for us to differentiate between messages sent by Baileys and messages sent manually via WhatsApp. even though in the previous version if Baileys sent a message by baileys would not trigger that event, I prefer version 6.7.5 and below but there the profile picture feature is not available
> > 
> > 
> > use message id (m.key.id), message id sent via baileys are different from messages sent manually via whatsapp
> 
> how to differentiate between sent via baileys are different from messages sent manually via whatsapp

message sent via baileys selects the same id in front of it, try this

```javascript
let isBaileys = msg.key.id.startsWith("BAE5") || msg.key.id.startsWith("3EB0")
```

**Comment by RyuGameDev** [comment]
> > > > Why when using version 6.7.6 and above when I send a message via Baileys it will trigger
> > > > m.keys.fromme=true
> > > > This makes it impossible for us to differentiate between messages sent by Baileys and messages sent manually via WhatsApp. even though in the previous version if Baileys sent a message by baileys would not trigger that event, I prefer version 6.7.5 and below but there the profile picture feature is not available
> > > 
> > > 
> > > use message id (m.key.id), message id sent via baileys are different from messages sent manually via whatsapp
> > 
> > 
> > how to differentiate between sent via baileys are different from messages sent manually via whatsapp
> 
> message sent via baileys selects the same id in front of it, try this
> 
> ```js
> let isBaileys = msg.key.id.startsWith("BAE5") || msg.key.id.startsWith("3EB0")
> ```

thanks🙏🏻🙏🏻
