### ISSUE TITLE
Button message

### ISSUE THREAD

**Issue by Kumis-XD** [WhiskeySockets/Baileys#1132]
Please help me send message with button, is it still supported? if still supported, please tell me how to do it?

**Comment by sahilbrandwala** [comment]
Contact for button code at telegram @mediabytex

**Comment by Kumis-XD** [comment]
> Contact for button code at telegram @mediabytex

Keep going?

**Comment by Akkun3704** [comment]
> Please help me send message with button, is it still supported? if still supported, please tell me how to do it?

Nah. Buttons, list and template are deprecated #956

**Comment by mohamed-2010** [comment]
> > Please help me send message with button, is it still supported? if still supported, please tell me how to do it?
> 
> Nah. Buttons, list and template are deprecated #956 

It's still working with hidden methods i don't know how but i know persons have this options with same package

**Comment by Kumis-XD** [comment]
> > > Please help me send message with button, is it still supported? if still supported, please tell me how to do it?
> > 
> > 
> > Nah. Buttons, list and template are deprecated #956
> 
> It's still working with hidden methods i don't know how but i know persons have this options with same package

Please help me, I really need it. If you know, please give me a little snippet of code.

**Comment by Salientekill** [comment]
![Screenshot_2024-11-13-18-24-39-521_com whatsapp-edit](https://github.com/user-attachments/assets/f6b62e01-ffce-48e1-9b89-15b57044f149)
