### ISSUE TITLE
[BUG] Buttons Not Displaying on WhatsApp Beta (Latest Version) with Baileys v6.7.9 and Node.js v18

### ISSUE THREAD

**Issue by HamzLegendz** [WhiskeySockets/Baileys#1137]
Describe the Bug

Buttons sent using Baileys v6.7.9 do not display on the latest WhatsApp Beta version. This includes:

Quick Reply Buttons

URL Buttons

List Message Buttons

While the message text or media is delivered successfully, the buttons themselves are missing entirely. This issue did not occur in previous versions of WhatsApp, suggesting a compatibility issue with the latest Beta.

---

To Reproduce

1. Create a new connection using Baileys v6.7.9.

2. Authenticate using Node.js v18 as the runtime environment.

3. Send a message containing buttons (Quick Reply, URL, or List).

4. Open the message using the latest WhatsApp Beta version (Android/iOS).

5. Observe that the buttons are not visible, although other content is delivered correctly.

---

Expected Behavior

The buttons should be displayed as intended and remain functional. For example:

Quick Reply buttons should allow a single-tap response.

URL buttons should redirect the user to the specified link.

List message buttons should show the available options for selection.

---

Environment (please complete the following information):

Baileys version: 6.7.9

Node.js version: 18.x

WhatsApp version: Latest Beta (as of now)

Device: Tested on Android/iOS Beta versions.

Is this on a server? Yes, tested on a remote server.

---

What do your connectOptions look like?

Do you have multiple clients on the same IP?
No, only a single instance of the client is running on the server.

Are you using a proxy?
No, no proxy is being used for the connection.

---

Additional Context

Buttons are critical for interactive bots, and their absence severely impacts user experience.

This issue might be due to changes in the WhatsApp Beta protocol.

Requesting guidance on adapting to these changes if they are the root cause or a fix if this is a bug in Baileys.

Thank you for your hard work on maintaining Baileys. Any assistance on this matter would be greatly appreciated.

**Comment by SheIITear** [comment]
Buttons are not supported.

**Comment by HamzLegendz** [comment]
> Buttons are not supported.

Thank you for your response!

I understand that the current version of Baileys might not support buttons with the latest WhatsApp Beta. However, I’ve heard that there might be updates or new methods to handle buttons according to the latest WhatsApp protocol changes.

Could you confirm if there’s any ongoing work or a new implementation for buttons that we should be aware of? Alternatively, is there any documentation or workaround you’d recommend to make buttons functional with the latest WhatsApp Beta?

I appreciate the hard work you’ve put into maintaining Baileys, and I’d be happy to test or provide more details if needed. Looking forward to your guidance!

**Comment by SheIITear** [comment]
We won't add support for buttons to baileys. This was decided a long time ago and we have not had any official support since. Read more here - #956.

**Comment by HamzLegendz** [comment]
> We won't add support for buttons to baileys. This was decided a long time ago and we have not had any official support since. Read more here - #956.

thanks its the information sorry i asked a lot because i just started coding for bots
