### ISSUE TITLE
get Last seen by id

### ISSUE THREAD

**Issue by RyuGameDev** [WhiskeySockets/Baileys#1141]
is there a feature to see last seen on WhatsApp? i tried using presenceSubscribe and it just returns {}

**Comment by lauriolasw** [comment]
To receive presence updates from a user, last seen privacy settings must be set to 'Everyone' for both you and the user in question

**Comment by purpshell** [comment]
tPresence updates are not returned by the subscription function. Look for presence updates in the presence update events
