### ISSUE TITLE
[BUG] groupName error

### ISSUE THREAD

**Issue by solution01** [WhiskeySockets/Baileys#1144]
I have this error in all my code:
TypeError: Cannot use 'in' operator to search for 'text' in ReferenceError: Cannot access 'groupName' before initialization

It started happening yesterday and today I'm already on the latest version of Baileys.

**Comment by Akkun3704** [comment]
This is an error from your script, not a bug from Baileys

**Comment by solution01** [comment]
Yes, I already found the error, thank you very much for your feedback.
