### ISSUE TITLE
how to know the message is viewoncemessage?

### ISSUE THREAD

**Issue by RyuGameDev** [WhiskeySockets/Baileys#1149]
how to see mtype of a view once message? After updating to version 6.7.0 and above, m.mtype cannot see the type view once message

![IMG-20241127-WA0001](https://github.com/user-attachments/assets/e775253e-6c77-4a8b-b152-e0706cc5f8ee)
above is when using baileys 6.6.0 it says viewonce message but in baileys 6.7.0 above it does not work as below

![IMG-20241127-WA0002](https://github.com/user-attachments/assets/443d1ea3-586f-474c-b661-1d469f0c092e)

**Comment by tonykx** [comment]
Pq foi fechado?

**Comment by CSFelix** [comment]
@RyuGameDev @tonykx 

In order to know whether a message is view once or not, you can check if its object contains `viewOnceMessage` property like this:

```ts
const isViewOnceMessage = msg?.message?.viewOnceMessage || msg?.message?.viewOnceMessageV2 || msg?.message?.viewOnceMessageV2Extension;
```
