### ISSUE TITLE
WhatsApp session not able to connect

### ISSUE THREAD

**Issue by aniakg** [WhiskeySockets/Baileys#116]
Hi, 

For a few of the numbers, WhatsApp is not getting connected after scanning the QR code. 

We have checked the logs and it seems keys values are not getting synched 

Here is the session log file

{
  "creds": {
    "noiseKey": {
      "private": {
        "type": "Buffer",
        "data": "sE6GvZGoGoXkr7ruuxno6E0QigmYVaZ405MnyBTAvWE="
      },
      "public": {
        "type": "Buffer",
        "data": "pB1Vj1Gw3ty9/o1VQG7UdS6dmOsTu+pzhGJ1RRKAv1w="
      }
    },
    "signedIdentityKey": {
      "private": {
        "type": "Buffer",
        "data": "0FTNMQ7pVgr84w97hAIqCq5LA9c9W3RpRO61uwqaI3A="
      },
      "public": {
        "type": "Buffer",
        "data": "Q3Mh336UCrpjTlKPr0MxFWiJwBP/AVnnbhyjqrq1V2s="
      }
    },
    "signedPreKey": {
      "keyPair": {
        "private": {
          "type": "Buffer",
          "data": "2OKIstDYd/bHFg31BwB+uG7Blu8RNJRZapGYhO6UFkw="
        },
        "public": {
          "type": "Buffer",
          "data": "edCzjTmbxMYsDHGBs32m8TURaNcwskkugOg7aU/3WS0="
        }
      },
      "signature": {
        "type": "Buffer",
        "data": "jMzNKdud8NDtaKGuZxbyL998y0A7IstQUbgfZGk9+KgLFFIu3Z1+fgIj9jXyLsCGr+QwzSebcptuJ6m9U7LLiA=="
      },
      "keyId": 1
    },
    "registrationId": 167,
    "advSecretKey": "ellM4Z2WfIYVMc/QoMXQUqIWJMrdy/I/a+/haa6Y3f4=",
    "nextPreKeyId": 1,
    "firstUnuploadedPreKeyId": 1,
    "serverHasPreKeys": false,
    "account": {
      "details": "CMPM9r4BENOPh6QGGAE=",
      "accountSignatureKey": "7zR+YYwd7EYQY5bBrEqmPlWYaNWbyg3YlCBvaSwsmXk=",
      "accountSignature": "SBgz24TUGH0VicSJILmvPPg+CzFYXcZxn0X88z3qCZ8QMT1fTN3SaEjMtrjLoR4Zwm47RJVvtQIhuwqdiySdAQ==",
      "deviceSignature": "t5deRuBgygzZ9i0aaQ5FarOXfSR4N+E9zDFTSSoZjaeDOz516wbLO6+x5tSWfUlxWtR8KD+W7xxL3UKKCbZmhg=="
    },
    "me": {
      "id": "xxxxxxxxx:38@s.whatsapp.net",
      "verifiedName": "Mkts"
    },
    "signalIdentities": [
      {
        "identifier": {
          "name": "xxxxxxxxx:38@s.whatsapp.net",
          "deviceId": 0
        },
        "identifierKey": {
          "type": "Buffer",
          "data": "Be80fmGMHexGEGOWwaxKpj5VmGjVm8oN2JQgb2ksLJl5"
        }
      }
    ]
  },
  "keys": {}
}

**Comment by manishswami** [comment]
Unable to login in latest 2.23.11.77  and above whatsapp vesrion

**Comment by skosovsky-test** [comment]
Invalid QR code
Make sure you scan the QR code displayed on WhatsApp Web, WhatsApp for desktop,
Portal or other official WhatsApp application. If the scan fails, refresh the app or refresh the page, and then try again.

**Comment by skosovsky-test** [comment]
Change "version": [2, 2323, 4] - and repeat scan QR

**Comment by aniakg** [comment]
> Change "version": [2, 2323, 4] - and repeat scan QR - Work :)
> 
> From [63575e9#diff-56a3ced2746140ddaabda6dde35270fba0da08e89a25168e830b0f6732881c80](https://github.com/WhiskeySockets/Baileys/commit/63575e9b85520bd7621bd16ac0508cdd523a3a43#diff-56a3ced2746140ddaabda6dde35270fba0da08e89a25168e830b0f6732881c80)

Wow, that's a great help, Thanks a lot :)

**Comment by unrealmaow** [comment]
thanks, worked for me <3

**Comment by jefaokpta** [comment]
Works for me too! Thanks

**Comment by aniakg** [comment]
WhatsApp server connection file, In server folder.
