### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fzkunzz** [WhiskeySockets/Baileys#1163]
I can't add the button feature, while other people using this library can use the button feature!
![20241214_072424](https://github.com/user-attachments/assets/e06917c0-635c-481c-8425-ef43062a7281)

**Comment by fzkunzz** [comment]
help me, i want to use this feature🥹

**Comment by MuhammadRestu999** [comment]
gk usah ngarep ada beton lagi bang, toh button itu sering bat dijadikan bug oleh jebe dengan sdm rendah :v

#956

**Comment by fzkunzz** [comment]
> gk usah ngarep ada beton lagi bang, toh button itu sering bat dijadikan bug oleh jebe dengan sdm rendah :v
> 
> #956
do you know how to make it?
