### ISSUE TITLE
Connect using otp instead of scanning qr

### ISSUE THREAD

**Issue by mmmahne** [WhiskeySockets/Baileys#1164]
Is baileys capable of connecting to the WhatsApp through otp instead of scanning qr code? I saw some library that are capable of doing that

**Comment by Rippanteq7** [comment]
You mean [pairing](#252)?
It's already available in [example](https://github.com/WhiskeySockets/Baileys/blob/master/Example/example.ts#L63-L69)

**Comment by mmmahne** [comment]
Oh yeah thank you, didnt saw that before
