### ISSUE TITLE
[BUG] TypeError: import_baileys.default is not a function.

### ISSUE THREAD

**Issue by jdic** [WhiskeySockets/Baileys#1168]
**Describe the bug**
`TypeError: import_baileys.default is not a function. (In 'import_baileys.default(config)', 'import_baileys.default' is an instance of Object)`

**To Reproduce**
1. `bun build ./app.ts --outdir ./dist --target bun --sourcemap`
2. `node dist/app.js`

```sh
bun dist/app.js
87 |       logger: logger as unknown as any,
88 |       auth: this.state,
89 |       ...this.config,
90 |     }
91 | 
92 |     this.socket = makeWaSocket(config) as Socket
                       ^
TypeError: import_baileys.default is not a function. (In 'import_baileys.default(config)', 'import_baileys.default' is an instance of Object)
      at /home/jdi/Desktop/@jdic/pndjin/src/Client.ts:92:19

Bun v1.1.38 (Linux x64)
```

**Environment:**
`tsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"],
    },

    // Enable latest features
    "lib": ["ESNext", "DOM"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    // Bundler mode
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    // Best practices
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,

    // Some stricter flags (disabled by default)
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noPropertyAccessFromIndexSignature": false
  }
}
```

`Client.ts`
```ts
import makeWaSocket, { type UserFacingSocketConfig } from '@whiskeysockets/baileys'
import type { Socket } from '@/types/Global'

...

export class Client
{
  ...

  const config: UserFacingSocketConfig =
  {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    logger: logger as unknown as any,
    auth: this.state,
    ...this.config,
  }

  this.socket = makeWaSocket(config) as Socket
}
```

Using CommonJS is **not** an option, it could be a feature request for this library to add a good support for TypeScript.

I already saw the issues #452 and #459.

**Comment by jdic** [comment]
This is a **Hot Fix**, but it is **NOT** ideal, it would be nice to be able to do this without having to make changes like this or change the compilation.

The code only works when running it using bun, so this fix is not entirely convenient.

`bun build ./app.ts --outdir ./dist --target bun --sourcemap`

```ts
import * as baileys from '@whiskeysockets/baileys'

const { makeWASocket } = baileys
```

**Comment by hacxk** [comment]
> **Describe the bug** `TypeError: import_baileys.default is not a function. (In 'import_baileys.default(config)', 'import_baileys.default' is an instance of Object)`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. `bun build ./app.ts --outdir ./dist --target bun --sourcemap`
> 2. `node dist/app.js`
> 
> ```shell
> bun dist/app.js
> 87 |       logger: logger as unknown as any,
> 88 |       auth: this.state,
> 89 |       ...this.config,
> 90 |     }
> 91 | 
> 92 |     this.socket = makeWaSocket(config) as Socket
>                        ^
> TypeError: import_baileys.default is not a function. (In 'import_baileys.default(config)', 'import_baileys.default' is an instance of Object)
>       at /home/jdi/Desktop/@jdic/pndjin/src/Client.ts:92:19
> 
> Bun v1.1.38 (Linux x64)
> ```
> 
> **Environment:** `tsconfig.json`
> 
> ```json
> {
>   "compilerOptions": {
>     "baseUrl": "./",
>     "paths": {
>       "@/*": ["./src/*"],
>     },
> 
>     // Enable latest features
>     "lib": ["ESNext", "DOM"],
>     "target": "ESNext",
>     "module": "ESNext",
>     "moduleDetection": "force",
>     "jsx": "react-jsx",
>     "allowJs": true,
> 
>     // Bundler mode
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "verbatimModuleSyntax": true,
>     "noEmit": true,
> 
>     // Best practices
>     "strict": true,
>     "skipLibCheck": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     // Some stricter flags (disabled by default)
>     "noUnusedLocals": false,
>     "noUnusedParameters": false,
>     "noPropertyAccessFromIndexSignature": false
>   }
> }
> ```
> 
> `Client.ts`
> 
> ```ts
> import makeWaSocket, { type UserFacingSocketConfig } from '@whiskeysockets/baileys'
> import type { Socket } from '@/types/Global'
> 
> ...
> 
> export class Client
> {
>   ...
> 
>   const config: UserFacingSocketConfig =
>   {
>     // eslint-disable-next-line @typescript-eslint/no-explicit-any
>     logger: logger as unknown as any,
>     auth: this.state,
>     ...this.config,
>   }
> 
>   this.socket = makeWaSocket(config) as Socket
> }
> ```
> 
> Using CommonJS is **not** an option, it could be a feature request for this library to add a good support for TypeScript.
> 
> I already saw the issues #452 and #459.

```js

import { makeWASocket } from "@whiskeysockets/baileys";

```

**Comment by jdic** [comment]
> **Try to import like this**
> 
> ```js
> import { makeWASocket } from "@whiskeysockets/baileys";
> ```

For some reason I tried to do this before and it didn't work, probably bun's hot reload is caching wrongly, just happened to me the other project... That works now, ty.
