### ISSUE TITLE
[BUG] interactive buttons are no longer working

### ISSUE THREAD

**Issue by ZexFork** [WhiskeySockets/Baileys#1173]
interactive buttons and lists can no longer be used (cannot be sent using the latest WA version)

**Comment by AstroX11** [comment]
Wa patched them

**Comment by SashaMaz** [comment]
[https://github.com/WhiskeySockets/Baileys/pull/956](url)  deprecated

**Comment by SashaMaz** [comment]
#956 decreated

**Comment by bobslavtriev** [comment]
Search on google: "how to read documentation on github"

Thanks!
