### ISSUE TITLE
Link Preview for Youtube Video

### ISSUE THREAD

**Issue by ahmadkeren** [WhiskeySockets/Baileys#1176]
Excuse me sir, I want to ask.. does anyone know how to create a video preview link from YouTube so that it can be played directly in WhatsApp without having to be redirected to a web browser?

Expected:
![Untitled](https://github.com/user-attachments/assets/8db5f841-cf9a-437d-8d85-f87f461cb00e)

Currently my code;
---------------------------------
```javascript
const linkPreview = await getUrlInfo(urlYt, {
            thumbnailWidth: 1024,
            fetchOpts: {
                timeout: 30 * 1000,
            },
            uploadImage: paimon.waUploadToServer,
        });
        return await paimon.sendMessage(m.from,
            {
                text: `${urlYt}`,
                linkPreview,
            }, { quoted: m, previewType: 1 }
        );
```
---------------------------------
my code result (no play button):
![image](https://github.com/user-attachments/assets/e1adf490-23f7-44ac-b673-f9d1ce20eb7f)

**Comment by suhwr** [comment]
Pake externalAdReply juga bisa

```js
paimon.sendMessage(m.from, 
    {
        text: "test",
        contextInfo:{
            externalAdReply: {
                title: 'title',
                body: `body`,
                thumbnailUrl: 'https://i.ytimg.com/vi/1ZDJMMTA4ag/hqdefault.jpg',
                sourceUrl: `https://youtu.be/1ZDJMMTA4ag?si=8lFZJr2fcI7t-gaG`,
                mediaUrl: `https://youtu.be/1ZDJMMTA4ag?si=8lFZJr2fcI7t-gaG`,
                mediaType: 2, // 1: image, 2: video
                renderLargerThumbnail: true,
            }
        }
    }, { quoted: m }
)
````

**Comment by ahmadkeren** [comment]
terima kasih tuan @suhwr

**Comment by LcfherShell** [comment]
> terima kasih tuan [@suhwr](https://github.com/suhwr)

bagaimana caranya agar link thumbnail diredirect ke url originalnya?

**Comment by LcfherShell** [comment]
> Pake externalAdReply juga bisa
> 
> paimon.sendMessage(m.from, 
>     {
>         text: "test",
>         contextInfo:{
>             externalAdReply: {
>                 title: 'title',
>                 body: `body`,
>                 thumbnailUrl: 'https://i.ytimg.com/vi/1ZDJMMTA4ag/hqdefault.jpg',
>                 sourceUrl: `https://youtu.be/1ZDJMMTA4ag?si=8lFZJr2fcI7t-gaG`,
>                 mediaUrl: `https://youtu.be/1ZDJMMTA4ag?si=8lFZJr2fcI7t-gaG`,
>                 mediaType: 2, // 1: image, 2: video
>                 renderLargerThumbnail: true,
>             }
>         }
>     }, { quoted: m }
> )

Bagaimana caranya agar user saat menekan thumbnail dapat diredirect ke url originalnya?
