### ISSUE TITLE
Feature Request : Connet Device with 8-digit code 

### ISSUE THREAD

**Issue by tls-jil** [WhiskeySockets/Baileys#1180]
Currently, we only use QR codes to connect to WhatsApp; if an 8-digit code is an even better choice, then use it. 

![image](https://github.com/user-attachments/assets/1de78bf2-a3a5-40be-9474-acbfca6dd691)

**Comment by Akkun3704** [comment]
Its already exists #252, you can see it in the [example](https://github.com/WhiskeySockets/Baileys/blob/master/Example/example.ts#L63-L69)

**Comment by tls-jil** [comment]
@Akkun3704  i do that as per example but didn't get any kind of code  for more if possible can you look up the code which mention on issue 1181

https://github.com/WhiskeySockets/Baileys/issues/1181
