### ISSUE TITLE
[BUG] Qr code does not update when starting and provider does not connect

### ISSUE THREAD

**Issue by Frxnn** [WhiskeySockets/Baileys#120]
**Describe the bug**
When I start my bot, it doesnt send the "proveedor conectado y listo" message and the qrcode.png does not update.

**To Reproduce**
-Start with the "npm start" command on terminal
-Debug logs appear as expected.
-Provider never connects and qrcode does not update.

**Expected behavior**

**Environment (please complete the following information):**
this is on my own pc in a node.js whatsapp chatbot.

**Comment by lonelypx** [comment]
`const sock = makeWASocket({
        version: [2,2323,4],
        ...
});`

https://github.com/WhiskeySockets/Baileys/issues/107

**Comment by Frxnn** [comment]
I dont understand

**Comment by jhernancanom** [comment]
How should I proceed?
