### ISSUE TITLE
[BUG] contacts.upsert

### ISSUE THREAD

**Issue by raphaelvserafim** [WhiskeySockets/Baileys#121]
**Describe the bug**
 contacts.upsert Events no longer work.

```JS
  socket.ev.on("contacts.upsert", async (contacts: Contact[]) => {
      console.log("contacts", contacts)

    });
```

**Comment by kbiits** [comment]
@raphaelvserafim  Use this for temporary workaround https://github.com/kbiits/Whiskey-Baileys

**Comment by mateus-p** [comment]
My workaround:

**Comment by PurpShell** [comment]
NO! Also, it is part of messaging-history.set now
