### ISSUE TITLE
Issue installing "baileys" package using yarn

### ISSUE THREAD

**Issue by mikelx99** [WhiskeySockets/Baileys#123]
I attempted to install the "baileys" package using yarn, following the provided instructions. However, I encountered an error during the installation process.

Could you please guide me on how to successfully install the "baileys" package using yarn or any other method. 
thank you

![image](https://github.com/WhiskeySockets/Baileys/assets/124032862/bffe5fec-fa9e-4aa7-8043-2471ee1e2e29)

**Comment by kbiits** [comment]
Install git before come here and open an issue
