### ISSUE TITLE
[BUG] ECONNRESET

### ISSUE THREAD

**Issue by waaplog** [WhiskeySockets/Baileys#129]
After connection i am getting this error. When this error occurs the app shut down itself. Could anyone can help me about it. Thanks

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by HelderSi** [comment]
same issue.

**Comment by PurpShell** [comment]
Restarts. You need to restart the connection after a while
