### ISSUE TITLE
[BUG] Receiving invalid message from events['messages.upsert'] 

### ISSUE THREAD

**Issue by satriowicaksn** [WhiskeySockets/Baileys#132]
**Describe the bug**
On events['messages.upsert'] I got invalid message content with structure like this : 

{
  "key": {
    "remoteJid": "xxxxxx@s.whatsapp.net",
    "fromMe": false,
    "id": "sensored"
  },
  "messageTimestamp": 1686622027,
  "pushName": "My Customer Name",
  "messageStubType": 2,
  "messageStubParameters": [
    "Message absent from node"
  ]
}

**To Reproduce**
1. Created a new connection
2. Send message to connected number
3. console.log() on events['messages.upsert'] value or save every events to DB

**Expected behavior**
Message content displayed are appropriate on whatsapp (only normal text)

**Environment (please complete the following information):**
 - Is this on a server? yes 
 - What do your `connectOptions` look like? 
   const sock = makeWASocket({
    version: [2,2323,4],
    printQRInTerminal: true,
    patchMessageBeforeSending: (message) => {
      const requiresPatch = !!(
        message.buttonsMessage ||
        message.templateMessage ||
        message.listMessage
      );
      if (requiresPatch) {
        message = {
          viewOnceMessage: {
            message: {
              messageContextInfo: {
                deviceListMetadataVersion: 2,
                deviceListMetadata: {},
              },
              ...message,
            },
          },
        };
      }

      return message;
    },
    auth: state,
    markOnlineOnConnect: false,
    generateHighQualityLinkPreview: true,
    shouldIgnoreJid: jid => isJidStatusBroadcast(jid),
    defaultQueryTimeoutMs: undefined
  });

 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**

**Comment by satriowicaksn** [comment]
up

**Comment by garis-project** [comment]
#oot
Can you share complete source code for send message using this project?

**Comment by satriowicaksn** [comment]
anyone know to solve this issue ??

**Comment by boonkahming** [comment]
I am facing the same issue here. Some of the numbers initiating their messages seems to have the "Message absent from node" issue, and the text message is not available. Any pointers on how to solve such issue?

**Comment by Fonnte** [comment]
> I am facing the same issue here. Some of the numbers initiating their messages seems to have the "Message absent from node" issue, and the text message is not available. Any pointers on how to solve such issue?

are you guys not having the message later? it's just failed on first decryption and will be retried. you'll get the message later after successful decryption, in my case the longest take +- 5 seconds.

**Comment by boonkahming** [comment]
> > I am facing the same issue here. Some of the numbers initiating their messages seems to have the "Message absent from node" issue, and the text message is not available. Any pointers on how to solve such issue?
> 
> are you guys not getting the message later? it's just failed on first decryption or else and will be retried. you'll get the message later after successful decryption or retry, in my case the longest take +- 5 seconds.

I am not getting any message later, and also not getting any retries. The sender sent the second message and still get the similar "Message absent from node" issue. 

But after asking the sender to add our number as contact, the third message is able to be retrieved. However, it would be impossible to ask all our users to add our number as contact. How do you manage to retrieve the decrypted message?

**Comment by Fonnte** [comment]
> > > I am facing the same issue here. Some of the numbers initiating their messages seems to have the "Message absent from node" issue, and the text message is not available. Any pointers on how to solve such issue?
> > 
> > 
> > are you guys not getting the message later? it's just failed on first decryption or else and will be retried. you'll get the message later after successful decryption or retry, in my case the longest take +- 5 seconds.
> 
> I am not getting any message later, and also not getting any retries. The sender sent the second message and still get the similar "Message absent from node" issue.
> 
> But after asking the sender to add our number as contact, the third message is able to be retrieved. However, it would be impossible to ask all our users to add our number as contact. How do you manage to retrieve the decrypted message?

are you messing with auth keys? are you using useMultiFileAuthState or custom storage? i don't do any fancy code, but the incoming message will be retried and available some time later, 

![Screenshot_133](https://github.com/WhiskeySockets/Baileys/assets/23734341/ac911b93-8086-41fb-afab-90ffaffe160b)

this happen few minutes ago and i have it few seconds later.

**Comment by boonkahming** [comment]
> > > > I am facing the same issue here. Some of the numbers initiating their messages seems to have the "Message absent from node" issue, and the text message is not available. Any pointers on how to solve such issue?
> > > 
> > > 
> > > are you guys not getting the message later? it's just failed on first decryption or else and will be retried. you'll get the message later after successful decryption or retry, in my case the longest take +- 5 seconds.
> > 
> > 
> > I am not getting any message later, and also not getting any retries. The sender sent the second message and still get the similar "Message absent from node" issue.
> > But after asking the sender to add our number as contact, the third message is able to be retrieved. However, it would be impossible to ask all our users to add our number as contact. How do you manage to retrieve the decrypted message?
> 
> are you messing with auth keys? are you using useMultiFileAuthState or custom storage? i don't do any fancy code, but the incoming message will be retried and available some time later,
> 
> ![Screenshot_133](https://user-images.githubusercontent.com/23734341/252916590-ac911b93-8086-41fb-afab-90ffaffe160b.png)
> 
> this happen few minutes ago and i have it few seconds later.

I run the Baileys node with the --no-store option because the store writing is taking up much server resources and eventually slows down the server. Do I need to enable store in order for the retry to work?

**Comment by azudindaem** [comment]
Message absent from node, most probably a bug from WA itself, especially when it comes to adreply (advertising link from FB) message.

Just to clarify, you can compare the actual message that appears on our device but not on web WA. When this happens, Bailey will not be able to decrypt the message since it is already broken within web WA itself.

The situation is completely different when sending a message through baileys. We have a function to retry and resend the failed message.

**Comment by boonkahming** [comment]
> Message absent from node, most probably a bug from WA itself, especially when it comes to adreply (advertising link from FB) message.
> 
> Just to clarify, you can compare the actual message that appears on our device but not on web WA. When this happens, Bailey will not be able to decrypt the message since it is already broken within web WA itself.
> 
> The situation is completely different when sending a message through baileys. We have a function to retry and resend the failed message.

@azudindaem Just to confirm, can I say that for now this issue is still an unknown, and there is no way for us to retrieve the actual message when we get the "Message absent from node" response, correct?

**Comment by paulohsilvestre** [comment]
UP

**Comment by leifermendez** [comment]
I have the same issue I think is because some setting like this 
![image](https://github.com/WhiskeySockets/Baileys/assets/15802366/1b26d45d-9874-4074-9a68-cbf9a484bd32)

**Comment by andresayac** [comment]
> I have the same issue I think is because some setting like this ![image](https://user-images.githubusercontent.com/15802366/260255896-1b26d45d-9874-4074-9a68-cbf9a484bd32.png)

It is correct this message is generated when there is a time update of messages that disappear I share with you one of these update messages, therefore you should keep this update on the chat in mind to avoid having this inconvenience


![image](https://github.com/WhiskeySockets/Baileys/assets/16548795/d21efced-ea36-4895-adb6-f2cca1efa1c8)

**Comment by azudindaem** [comment]
guys, disappearing message aren't the same issue – they aren't even an issue.

**Comment by Anuudek** [comment]
up

**Comment by asdasdad123be** [comment]
up

**Comment by jaison-x** [comment]
up

**Comment by PurpShell** [comment]
Investigating, been noticing this more and more

**Comment by jaison-x** [comment]
I am getting this for new chats too. It seems random. The retry system sometimes works and sometimes not.

**Comment by tiagomatrixd** [comment]
I don't know if it's the same problem but here the ev['messages.upsert'] out of nowhere stops working and sometimes even restarting the application it still doesn't receive the messages only after restarting several times it works fine again, but it's a bug that has happened frequently

**Comment by PurpShell** [comment]
> I don't know if it's the same problem but here the ev['messages.upsert'] out of nowhere stops working and sometimes even restarting the application it still doesn't receive the messages only after restarting several times it works fine again, but it's a bug that has happened frequently

Out of topic, you need to restart frequently

**Comment by PurpShell** [comment]
> I am getting this for new chats too. It seems random. The retry system sometimes works and sometimes not.

Same thing here. i am working on a proper fix for the retry system so I am getting a few logs from some clients who have this issue. We'll work on this and get it just as pristine as the official whatsapp web app

**Comment by ericdesaoficial** [comment]
> > Também estou recebendo isso para novos bate-papos. Parece aleatório. O sistema de nova tentativa às vezes funciona e às vezes não.
> 
> Mesma coisa aqui. estou trabalhando em uma correção adequada para o sistema de nova tentativa, por isso estou recebendo alguns registros de alguns clientes que têm esse problema. Trabalharemos nisso e o deixaremos tão puro quanto o aplicativo web oficial do Whatsapp

Hello friend @PurpShell . I got some solution on this, I'm having a lot of problems with some customers

**Comment by jaison-x** [comment]
Has anyone got progress on this?

**Comment by PurpShell** [comment]
Solution found, fixing.

**Comment by kyraex** [comment]
> Message absent from node, most probably a bug from WA itself, especially when it comes to adreply (advertising link from FB) message.
> 
> Just to clarify, you can compare the actual message that appears on our device but not on web WA. When this happens, Bailey will not be able to decrypt the message since it is already broken within web WA itself.
> 
> The situation is completely different when sending a message through baileys. We have a function to retry and resend the failed message.

Does this means if first we were getting a message absent from node, baileys will retry to decrypt again and send another upsert event when it was successful?

**Comment by azudindaem** [comment]
after testing on active fbads there are still appear
```json
 {
		"messages": [
			{
				"key": {
					"remoteJid": "xxx@s.whatsapp.net",
					"fromMe": false,
					"id": "C667337FC2A7xxxx"
				},
				"messageTimestamp": 1703033961,
				"pushName": "xxx",
				"broadcast": false,
				"messageStubType": 2,
				"messageStubParameters": [
					"Message absent from node"
				]
			}
		],
		"type": "notify",
		"jid": "xxxxx@s.whatsapp.net",
		"hasNewMessage": true
	}
```

**Comment by PurpShell** [comment]
> > Message absent from node, most probably a bug from WA itself, especially when it comes to adreply (advertising link from FB) message.
> > Just to clarify, you can compare the actual message that appears on our device but not on web WA. When this happens, Bailey will not be able to decrypt the message since it is already broken within web WA itself.
> > The situation is completely different when sending a message through baileys. We have a function to retry and resend the failed message.
> 
> Does this means if first we were getting a message absent from node, baileys will retry to decrypt again and send another upsert event when it was successful?

It will send a message.update!
@azudindaem as well, this is expected. What happened before was that we couldn't parse the response, we were sending a retry but not parsing the response. After parsing, messages.update gives you the new message. Handle it there

**Comment by Zedmerlol** [comment]
> > > Message absent from node, most probably a bug from WA itself, especially when it comes to adreply (advertising link from FB) message.
> > > Just to clarify, you can compare the actual message that appears on our device but not on web WA. When this happens, Bailey will not be able to decrypt the message since it is already broken within web WA itself.
> > > The situation is completely different when sending a message through baileys. We have a function to retry and resend the failed message.
> > 
> > 
> > Does this means if first we were getting a message absent from node, baileys will retry to decrypt again and send another upsert event when it was successful?
> 
> It will send a message.update! @azudindaem as well, this is expected. What happened before was that we couldn't parse the response, we were sending a retry but not parsing the response. After parsing, messages.update gives you the new message. Handle it there

It works very nice, thanks you @PurpShell 
![2023-12-26_10h41_31](https://github.com/WhiskeySockets/Baileys/assets/54508766/c3098685-19d1-490f-944d-e78411bf40a6)

**Comment by clairton** [comment]
When a new version with this PR is release?
