### ISSUE TITLE
[BUG] Arabic language wrong encoding with getLinkPreview

### ISSUE THREAD

**Issue by AtefR** [WhiskeySockets/Baileys#134]
When trying to send an Arabic link sometimes it appears in Whatsapp as wrong encoding question marks.
And it also doesn't wait for javascript websites to load. ie vue.js or reactjs websites to get the title and another information.

https://github.com/WhiskeySockets/Baileys/blob/master/src/Utils/link-preview.ts

**To Reproduce**
1.Send a random Arabic website url and It'll auto parsed for info using getLinkPreview library 

**Expected behavior**
To be readable text, Instead its black question marks

**Environment (please complete the following information):**
 - Latest Release
 
**Additional context**
we can use this library instead https://github.com/AndrejGajdos/link-preview-generator I've tried it and it works flawlessly.

**Comment by PurpShell** [comment]
You use that library. We can't ship puppeteer with Baileys

**Comment by Ai80-8** [comment]
Delete it all ‼️
