### ISSUE TITLE
[FEATURE_REQUEST] Login with Phone Number

### ISSUE THREAD

**Issue by bluej4ker** [WhiskeySockets/Baileys#136]
Many of you have seen the new feature of Whatsapp. Thanks to this feature, there is no need to scan the qr code.

![wp-web](https://github.com/WhiskeySockets/Baileys/assets/33478397/de41f7d2-4b81-443d-a433-f0b27c5da585)

**Comment by yepestore** [comment]
Example/example.ts

check it here

**Comment by mkhotib20** [comment]
hello @bluej4ker can you login with code??

**Comment by mkhotib20** [comment]
i've run the example.ts but it's not like whatsapp web link with phone number, example.ts refer to standalone mobile api
