### ISSUE TITLE
[BUG] First Connection

### ISSUE THREAD

**Issue by Piyoxz** [WhiskeySockets/Baileys#137]
the first time I run it, it doesn't show anything, everything is undefined , it doesn't bring up qr, why ? 
![image](https://github.com/WhiskeySockets/Baileys/assets/102013178/7e1a4d20-9d9e-42e6-948f-987c1aa8a36f)

**Comment by Guilherme-j10** [comment]
up

**Comment by yepestore** [comment]
can you provide your implemetation? (code)

**Comment by makanSukros** [comment]
> the first time I run it, it doesn't show anything, everything is undefined , it doesn't bring up qr, why ? ![image](https://user-images.githubusercontent.com/102013178/245457660-7e1a4d20-9d9e-42e6-948f-987c1aa8a36f.png)

does this happen after the number has been connected before? if yes maybe can delete session/session file before starting to bring up qr, as this didn't happen to me

**Comment by yepestore** [comment]
> > the first time I run it, it doesn't show anything, everything is undefined , it doesn't bring up qr, why ? ![image](https://user-images.githubusercontent.com/102013178/245457660-7e1a4d20-9d9e-42e6-948f-987c1aa8a36f.png)
> 
> does this happen after the number has been connected before? if yes maybe can delete session/session file before starting to bring up qr, as this didn't happen to me

show me your code

**Comment by Piyoxz** [comment]
> > the first time I run it, it doesn't show anything, everything is undefined , it doesn't bring up qr, why ? ![image](https://user-images.githubusercontent.com/102013178/245457660-7e1a4d20-9d9e-42e6-948f-987c1aa8a36f.png)
> 
> does this happen after the number has been connected before? if yes maybe can delete session/session file before starting to bring up qr, as this didn't happen to me

I'm using the latest version 6.2.1 / 6.2.0 and it's like that but when I downgrade to 6.1.0 nothing happens

**Comment by Piyoxz** [comment]
> > > the first time I run it, it doesn't show anything, everything is undefined , it doesn't bring up qr, why ? ![image](https://user-images.githubusercontent.com/102013178/245457660-7e1a4d20-9d9e-42e6-948f-987c1aa8a36f.png)
> > 
> > 
> > does this happen after the number has been connected before? if yes maybe can delete session/session file before starting to bring up qr, as this didn't happen to me
> 
> show me your code
![carbon](https://github.com/WhiskeySockets/Baileys/assets/102013178/fc800dbc-f341-4ebd-be42-cbe890242372)
