### ISSUE TITLE
 migrating lib

### ISSUE THREAD

**Issue by LucasJosiasAdamchuk** [WhiskeySockets/Baileys#138]
I'm doing a library migration from @adiwajshing/baileys for @whiskeysockets/baileys, but I had a problem that is to find a substitute for the import "import makeWALegacySocket from './LegacySocket';", does anyone have any ideas to help me or went through something similar?.

I'm also having trouble replacing the "import { LegacyAuthenticationCreds } from "@whiskeysockets/baileys";

**Comment by w3nder** [comment]
Everything related to Legacy was removed after 4.4
It doesn't exist, you can remove all Legacy references from your application

**Comment by LucasJosiasAdamchuk** [comment]
mais uma coisa, sobre o AnyWASocket tambem foi descontinuado?

**Comment by luqmansolihin** [comment]
I have same problem.
Then, I replace makeWALegacySocket with makeWASocket.
But, I have new problem with creds.update on
```
const wa = makeWASocket.default(waConfig)
wa.ev.on('creds.update', saveState)
```

Cannot read properties of undefined (reading 'creds')

**Comment by PurpShell** [comment]
English only.
