### ISSUE TITLE
Deadlock situation

### ISSUE THREAD

**Issue by yepestore** [WhiskeySockets/Baileys#139]
i get this log

`{"level":40,"time":"2023-06-14T01:38:35.040Z","pid":25,"hostname":"94073bd7-3be3-44a9-8711-b225eb6fa820","stack":"Error: mutex start\n    at /home/container/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/home/container/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleMessage (/home/container/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/home/container/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/home/container/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/home/container/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (node:events:513:28)\n    at /home/container/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/home/container/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/home/container/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}`

is this bug or something wrong in my implementation?

**Comment by zennn08** [comment]
update your baileys to @whiskeysockets/baileys@6.2.1
