### ISSUE TITLE
SessionError: No sessions [BUG]

### ISSUE THREAD

**Issue by DeveloperNewton** [WhiskeySockets/Baileys#14]
I updated Baileys to the latest version (at this very moment), but now I get the "No Sessions" error

```
C:\b\node_modules\libsignal\src\session_cipher.js:71
                throw new errors.SessionError("No sessions");
```

**Comment by andresayac** [comment]
share more details please

**Comment by iosahil** [comment]
Started to face the same issue.

When I interact with messages of large groups, (mine had 1024 members and is a community's group), it gives the error:
```
C:\Users\Person\GigaChat\node_modules\libsignal\src\session_cipher.js:71
                throw new errors.SessionError("No sessions");
                      ^

SessionError: No sessions
    at 918658474599:7.0 [as awaitable] (C:\Users\Person\GigaChat\node_modules\libsignal\src\session_cipher.js:71:23)      
    at async _asyncQueueExecutor (C:\Users\Person\GigaChat\node_modules\libsignal\src\queue_job.js:20:29)

Node.js v18.14.2
```
This issue wasn't there in Baileys's stable version, 5.0.0 and I faced this error only & only when I tried to upgrade to Baileys's GitHub version.

I'm currently searching a way to get my project back to rely on the stable version, Baileys 5.0.0.

Note: This issue isn't experienced on Groups < 100 (don't know the exact value but group with 10 person works perfectly) & non-community groups.

**Comment by andresayac** [comment]
@iosahil Don't worry, it has already been identified and we expect to solve it with the pull mentioned earlier.

**Comment by andresayac** [comment]
@RedTNT-Official  can you please update to the latest version or provide more details I still can't recreate it

**Comment by RedTNT-Official** [comment]
> @RedTNT-Official can you please update to the latest version or provide more details I still can't recreate it

I am on the latest version and the error happens when I try to send a message anywhere except for my own chat

**Comment by andresayac** [comment]
> > @RedTNT-Official can you please update to the latest version or provide more details I still can't recreate it
> 
> I am on the latest version and the error happens when I try to send a message anywhere except for my own chat

can you let me see the package.json

**Comment by RedTNT-Official** [comment]
> > > @RedTNT-Official can you please update to the latest version or provide more details I still can't recreate it
> > 
> > 
> > I am on the latest version and the error happens when I try to send a message anywhere except for my own chat
> 
> can you let me see the package.json

![image](https://user-images.githubusercontent.com/90536700/234088271-5588719b-04c8-4929-88f1-be45580d21c9.png)

**Comment by eduardochaves1** [comment]
Also with this problem on v6.7.8

**Comment by eduardochaves1** [comment]
![image](https://github.com/user-attachments/assets/842ef2fc-3d6a-4fbd-8ba7-e6727ef27bc8)

I noticed that when the No Sessions error occurs in the instance, these documents appear in the registry of that mongo instance. Simply removing them does not solve the problem, as they appear again.
