### ISSUE TITLE
status code 515 'Stream Errored (restart required)'

### ISSUE THREAD

**Issue by arhamroshan** [WhiskeySockets/Baileys#141]
I was previously using "@adiwajshing/baileys" v5.0.0 and it suddenly stopped working from yesterday after some diagnose I figure out that its throwing an error with status code of 405 'Method Not Allowed'

After this I have switched to "@whiskeysockets/baileys" v6.2.1 but its also not working giving error with status code 515 'Stream Errored (restart required)'

FInd the both screenshots below

<img width="1440" alt="Screenshot 2023-06-14 at 1 37 31 PM" src="https://github.com/WhiskeySockets/Baileys/assets/111501793/866bf253-aadf-43c4-bdfb-36cb146d327a">
<img width="1124" alt="Screenshot 2023-06-14 at 1 09 01 PM" src="https://github.com/WhiskeySockets/Baileys/assets/111501793/79f50e2b-0d00-4b96-99b9-beff62a70e83">

**Comment by zei666** [comment]
handle with :

if (shouldReconnect) {
            if (lastDisconnect?.error?.message === 'Stream Errored (conflict)') {
              console.log(colors.red('CONFLICT ERROR!'));
            } else {
              connectToWhatsApp();
              console.log(colors.green('RESTARTING CONN!'));
            }
          }
  /////
  process.on('uncaughtException', (error) => {
console.error(colors.green('UNCAUGHT EXCEPTION:'), error);
setTimeout(connectToWhatsApp, 2000);
});
process.on('unhandledRejection', (reason, promise) => {
console.error(colors.green('UNHANDLED REJECTION:'), reason);
setTimeout(connectToWhatsApp, 2000);

**Comment by arhamroshan** [comment]
@zei666 I have tried the solution you provide but still same error. Can you confirm this library working for you properly?

**Comment by iosahil** [comment]
#130 & #107

**Comment by eldoncosta1** [comment]
any update?

**Comment by onurguven** [comment]
Any update?

**Comment by bobftool** [comment]
bumping

**Comment by bielslima** [comment]
bump
