### ISSUE TITLE
[BUG] button not working 

### ISSUE THREAD

**Issue by sairmali** [WhiskeySockets/Baileys#145]
button only working on web but not working on Android phone

**Comment by sairmali** [comment]
any can give me solution ?

**Comment by canove** [comment]
see https://github.com/WhiskeySockets/Baileys/issues/56#issuecomment-1542947921

closing

**Comment by kayaliabd** [comment]
I think Cobalt got a solution [https://github.com/Auties00/Cobalt#cobalt](https://github.com/Auties00/Cobalt#cobalt)
and he is talking about a new node & media type to fix it
would you take a look pls

**Comment by Auties00** [comment]
> I think Cobalt got a solution [https://github.com/Auties00/Cobalt#cobalt](https://github.com/Auties00/Cobalt#cobalt)
> and he is talking about a new node & media type to fix it
> would you take a look pls
> 

I've legit got a pinned issue that says I'll not work on buttons. I'm sorry but I've got no solution
