### ISSUE TITLE
[BUG] Erro to send media message

### ISSUE THREAD

**Issue by rafaelvmedeiros** [WhiskeySockets/Baileys#149]
hi everyone. 
does anyone getting this error?
I'm using      "@whiskeysockets/baileys": "^6.2.1"
and i'm getting error when i try to send a image only.

sharecontacts and text works fine.
but when i try to send an image, i got this error.

 const sentMessage = await wbot.sendMessage("12345@s.whatsapp.net",
    {
       image: fs.readFileSync('C:\Projects\backend\public\img-2.jpg',
       caption: "img-2.jpg"
    }
  );

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/4409c1c2-6c71-415e-8bd2-1e7a91a33942)

{
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: "Internal Server Error",
      message: "An internal server error occurred",
    },
    headers: {
    },
  },

Stack Error

'Media upload failed on all hosts'

'Error: Media upload failed on all hosts\n    at Object.upload (C:\\Projects\\optinchat-old\\backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\messages-media.js:539:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at C:\\Projects\\optinchat-old\\backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\messages.js:110:28\n    at async Promise.all (index 0)\n    at prepareWAMessageMedia (C:\\Projects\\optinchat-old\\backend\\node_modules\\@whiskeysockets\\….js:472:59)\n    at Object.sendMessage (C:\\Projects\\optinchat-old\\backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:606:33)\n    at SendWhatsAppMedia (C:\\Projects\\optinchat-old\\backend\\src\\services\\WbotServices\\SendWhatsAppMedia.ts:173:25)\n    at C:\\Projects\\optinchat-old\\backend\\src\\controllers\\MessageController.ts:86:11\n    at async Promise.all (index 0)\n    at store (C:\\Projects\\optinchat-old\\backend\\src\\controllers\\MessageController.ts:84:7)'

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/55515b75-0de4-43b5-93de-f90cde0eecf8)

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/5a84ac5c-56a3-455e-8f17-7c83fde4628b)

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/de3ffdb9-3d39-4511-a89e-a210121db54e)

**Comment by lukasportal** [comment]
same here:

```
Cannot read properties of undefined (reading 'destroy')
TypeError: Cannot read properties of undefined (reading 'destroy')
    at encryptedStream (/.../node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:346:16)
    at async prepareWAMessageMedia (/.../node_modules/@adiwajshing/baileys/lib/Utils/messages.js:101:109)
    at async generateWAMessageContent (/.../node_modules/@adiwajshing/baileys/lib/Utils/messages.js:327:13)
    at async generateWAMessage (/.../node_modules/@adiwajshing/baileys/lib/Utils/messages.js:472:59)
    at async Object.sendMessage (/.../node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:606:33)
```

**Comment by Luxemburgo** [comment]
WhatsApp service isn't working properly today for file uploads, nothing to do with Baileys. Relax

**Comment by rafaelvmedeiros** [comment]
> WhatsApp service isn't working properly today for file uploads, nothing to do with Baileys. Relax

I've been having this problem for three days already.
So.. this is from whatsapp service?

**Comment by lukasportal** [comment]
Not sure though
If you send an image using a Readable stream instead of an URL, it works
so you can indeed upload an image to whatsapp if you pass a Readable stream to Baileys instead of a url

**Comment by rafaelvmedeiros** [comment]
> Not sure though If you send an image using a Readable stream instead of an URL, it works so you can indeed upload an image to whatsapp if you pass a Readable stream to Baileys instead of a url

I'm not using URL. I´m using buffer.

    options = {
        image: fs.readFileSync(`${publicFolder}/${media.filename}`),
        caption: body,
      };
      
I´m seeing in the interface 
I´ll try use Redable instead Buffer.

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/58542e31-6d17-4d91-b723-4120b890bd87)

**Comment by rafaelvmedeiros** [comment]
> not saying this is good or the way to go.. i do think sending a URL is so much better just saying that this may not be due to whatsapp being down today

I'll try.
But i think it´s a problem in media url from what´s service.
Because the error is about 'invalid certificate'.

I've changed the axios parameters to ignore invalid certificate, but it not works.

**Comment by rafaelvmedeiros** [comment]
messages-media.js

When Baileys try to send media data and get any error..
it try to request using another links, but anyone are works.

https://media.fgig22-1.fna.whatsapp.net/mms/image/LiV9gwf77Cc07ViNV77_lsEf0Xc-N-BsbxIwjpgFTSM?auth=AWT0NDbF11F7nTEqUfEwaYPz1iI05i5oFxpZzMH0rlLG8WeO4I3Yn4nMiH8&token=LiV9gwf77Cc07ViNV77_lsEf0Xc-N-BsbxIwjpgFTSM

https://mmg.whatsapp.net/mms/image/LiV9gwf77Cc07ViNV77_lsEf0Xc-N-BsbxIwjpgFTSM?auth=AWT0NDbF11F7nTEqUfEwaYPz1iI05i5oFxpZzMH0rlLG8WeO4I3Yn4nMiH8&token=LiV9gwf77Cc07ViNV77_lsEf0Xc-N-BsbxIwjpgFTSM

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/cda6697b-279c-4d1a-8aad-806dab3c6f02)

**Comment by rafaelvmedeiros** [comment]
I generated a link using what'sapp web
If i try it in browser works well. 
https://media.fgig22-1.fna.whatsapp.net/mms/image/9vQ9LJcArnC56c9X_1qTk6dRY5GGrJKotol5DgTUleQ=?auth=Ac0IB0T44fwyM-c1EK6cQpFqP50Kkxu7qguzQyeQk0gv3Q&token=9vQ9LJcArnC56c9X_1qTk6dRY5GGrJKotol5DgTUleQ%3D&resume=1&media_id=579306653185760

I've setted this link in code,
But i got the same error.

Anyone knows why i'm getting this error?

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/5a66def5-1954-4a2d-a843-1d2990edddbe)

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/f028454c-79d9-4038-87b8-75af1d7abc09)

**Comment by rafaelvmedeiros** [comment]
I fix that.
If anyone has this issue.
I solved this way:

I downloaded the whatsapp crt file from whatsapp web.

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/0819c919-286b-4274-af31-62a4911f94b0)

const certsPath = resolve(__dirname, "..", "..", "certs");
const cert = readFileSync(`${certsPath}/whatsapp.crt`);

and i loaded it there:

![image](https://github.com/WhiskeySockets/Baileys/assets/39308435/2f70a822-1e6e-4b6a-b755-aff657c7f80d)

Now all is working fine.
