### ISSUE TITLE
[BUG] Waiting for this message

### ISSUE THREAD

**Issue by Bulbul6827738392748287** [WhiskeySockets/Baileys#152]
Help me to solve the problem, Waiting for this message
![Screenshot_20230617-194504](https://github.com/WhiskeySockets/Baileys/assets/121987367/eed1e970-cae9-4d41-ba93-6ee347635460)

**Comment by Piyoxz** [comment]
using store

**Comment by Piyoxz** [comment]
![image](https://github.com/WhiskeySockets/Baileys/assets/102013178/d45ec700-17b3-4a20-a59c-1d9cfde90116)

**Comment by Piyoxz** [comment]
https://github.com/WhiskeySockets/Baileys#implementing-a-data-store

**Comment by Bulbul6827738392748287** [comment]
> https://github.com/WhiskeySockets/Baileys#implementing-a-data-store

Thanks thanks for the advice I will try it

**Comment by tomiheneldra** [comment]
> Help me to solve the problem, Waiting for this message ![Screenshot_20230617-194504](https://user-images.githubusercontent.com/121987367/246610043-eed1e970-cae9-4d41-ba93-6ee347635460.jpg)

restart aja nanti juga normal

**Comment by Riders004** [comment]
> Help me to solve the problem, Waiting for this message ![Screenshot_20230617-194504](https://user-images.githubusercontent.com/121987367/246610043-eed1e970-cae9-4d41-ba93-6ee347635460.jpg)

Restart your phone or your bot

**Comment by Piyoxz** [comment]
> i had the same problem and i solved it with this script (CommonJS)
> 
> ```
> 
> const store = makeInMemoryStore({});
> store.readFromFile('./baileys_store.json');
> 
> setInterval(() => {
>   store.writeToFile('./baileys_store.json');
> }, 10_000);
> 
> const sock = makeWASocket({});
> store.bind(sock.ev);
> 
> sock.ev.on('chats.set', () => {
>   console.log('got chats', store.chats.all());
> });
> 
> sock.ev.on('contacts.set', () => {
>   console.log('got contacts', Object.values(store.contacts));
> });
> ```

using getMessage
