### ISSUE TITLE
[BUG] Mobile (native) version doesn't work - Connection Terminated

### ISSUE THREAD

**Issue by allburov** [WhiskeySockets/Baileys#154]
**Describe the bug**
I'm trying to run "native" version of Baileys and get the error when `makeWASocket` called

```python
{"level":30,"time":1687089348216,"pid":136275,"hostname":"aburovqs-ubuntu","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"DINBRArqH6Pqe9t4NbrnlIZ6ZKxCX3YwQ86IV5L5Qlk="}},"msg":"connected to WA"}
{"level":30,"time":1687089348600,"pid":136275,"hostname":"aburovqs-ubuntu","trace":"Error: Connection Terminated\n    at MobileSocketClient.<anonymous> (/home/aburovqs/git/whatsapp-http-api/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:378:30)\n    at MobileSocketClient.emit (node:events:513:28)\n    at MobileSocketClient.emit (node:domain:489:12)\n    at Socket.<anonymous> (/home/aburovqs/git/whatsapp-http-api/node_modules/@adiwajshing/baileys/lib/Socket/Client/mobile-socket-client.js:44:100)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at TCP.<anonymous> (node:net:313:12)","msg":"connection errored"}
```

**To Reproduce**
1. Created a new connection with `mobile: true`
2. Observe the error

**Expected behavior**
It works and waits for code request.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? 
```javascript
    return {
      auth: state,
      printQRInTerminal: true,
      logger: logger,
      mobile: true,
    };
```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
- Node v18.12.0
- Ubuntu 20.04

**Comment by allburov** [comment]
I tried to run example to see if it's my app's problem or not, but it doesn't work and I can't test it :( https://github.com/WhiskeySockets/Baileys/issues/153

Any ideas\suggestions how I can investigate or fix the error?

**Comment by w3nder** [comment]
up

**Comment by allburov** [comment]
It works after I removed all `js` files from `src`!
```bash
cd src
 rm -rvf */*.js
```
