### ISSUE TITLE
[BUG] no account exists if whatsapp number have eleven digits including the country code 

### ISSUE THREAD

**Issue by ekoilkom** [WhiskeySockets/Baileys#156]
**Describe the bug**
I have error when i have number with only have eleven character like this 6280158**** , This user has a whatsapp number, I checked with the group feature to find out. the number is registered as a grub member. But every time I send a message, the account doesn't exist. All numbers with a total of eleven digits including the country code experience the same problem

{
"error": true,
"code": 500,
"message": "Error: no account exists"
}

**Comment by edgardmessias** [comment]
@ekoilkom, would you test with plus sign at beginning, like `+6280158****`?

**Comment by ekoilkom** [comment]
> @ekoilkom, would you test with plus sign at beginning, like `+6280158****`?
I intentionally removed the number to maintain privacy.
i use this number in image i attached in this comment.

<img width="298" alt="Screenshot 2023-06-20 at 16 15 04" src="https://github.com/WhiskeySockets/Baileys/assets/10483613/79f7903a-3ea8-4d29-a7e0-e92e04235022">

the number is exists in whatsapp, but always show no account exists. If u check in wa.me, This number exists

**Comment by caiogrigoleto** [comment]
In Brazil, I have a very similar problem, but with the ninth digit.
Example:
id: "5511999999999";
That way he sends the message but the whatsapp application does not find the user implying that he does not exist ..

But if I send it like this:
Example:
id: "551199999999";

The user receives the message normally..

**Comment by caiogrigoleto** [comment]
Is there any treatment for this model?

**Comment by edgardmessias** [comment]
@caiogrigoleto , could you test with plus sign at beginning, like +551199999999 and +5511999999999?

**Comment by Fonnte** [comment]
> @caiogrigoleto , could you test with plus sign at beginning, like +551199999999 and +5511999999999?

I also experienced this and already use + for  validate number. It works well. I implement double check to make sure the number did or did not exist.

**Comment by Fonnte** [comment]
> > @ekoilkom, could you test with plus sign at beginning, like `+6280158****`?
> 
> I use +62811586862 to check the number whatsapp but still no account exists.

true, the workaround is try use +08 instead of +628 and it works. using my api, the result is the number is registered while using +628 is not registered.
![Screenshot_76](https://github.com/WhiskeySockets/Baileys/assets/23734341/0a84117d-e38a-45c5-9b6d-227d897ad89a)

**Comment by ekoilkom** [comment]
> > > @ekoilkom, could you test with plus sign at beginning, like `+6280158****`?
> > 
> > 
> > I use +62811586862 to check the number whatsapp but still no account exists.
> 
> true, the workaround is try use +08 instead of +628 and it works. using my api, the result is the number is registered while using +628 is not registered. ![Screenshot_76](https://user-images.githubusercontent.com/23734341/247785592-0a84117d-e38a-45c5-9b6d-227d897ad89a.png)

you can send message with +0811586862 or 0811586862?

i check number +085257476232 no account exists. I am confused which pattern should be used

**Comment by ekoilkom** [comment]
Does anyone know any information about this issue?

**Comment by ratnokustiawan** [comment]
> > > @ekoilkom, could you test with plus sign at beginning, like `+6280158****`?
> > 
> > 
> > I use +62811586862 to check the number whatsapp but still no account exists.
> 
> true, the workaround is try use +08 instead of +628 and it works. using my api, the result is the number is registered while using +628 is not registered. ![Screenshot_76](https://user-images.githubusercontent.com/23734341/247785592-0a84117d-e38a-45c5-9b6d-227d897ad89a.png)

working

**Comment by rayidetriawan** [comment]
> working
Can you send message to that number?

**Comment by rayidetriawan** [comment]
@ratnokustiawan Can you send a message to that number ?

**Comment by ratnokustiawan** [comment]
> @ratnokustiawan Can you send message to that number ?

yes

**Comment by rayidetriawan** [comment]
> yes, if length=11 then replace 62 with +0

Can you tell me the npm version?

**Comment by ratnokustiawan** [comment]
> > yes, if length=11 then replace 62 with +0
> 
> Can you tell me your npm version?

![image](https://github.com/WhiskeySockets/Baileys/assets/13693767/6d67af4f-188f-40ec-854a-d6c29f6ff67c)

**Comment by ratnokustiawan** [comment]
> @ratnokustiawan Can you send message to that number ?

for check onWhatsapp
if length=11 then replace 62 with +0
for send message
62xx

**Comment by 1-pq** [comment]
> @ekoilkom，你能在开头用加号测试吗，比如`+6280158****`？

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
> > > > @ekoilkom，你能在开头用加号测试吗，比如`+6280158****`？
> > > 
> > > 
> > > 我使用+62811586862检查号码whatsapp，但仍然没有帐户存在。
> > 
> > 
> > 确实，解决方法是尝试使用 +08 而不是 +628，它可以工作。使用我的api，结果是该号码已注册，而使用+628未注册。![截图_76](https://user-images.githubusercontent.com/23734341/247785592-0a84117d-e38a-45c5-9b6d-227d897ad89a.png)
> 
> 您可以使用+0811586862或0811586862发送消息吗？
> 
> 我检查号码+085257476232 没有帐户存在。我很困惑应该使用哪种模式

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
> > > > @ekoilkom，你能在开头用加号测试吗，比如`+6280158****`？
> > > 
> > > 
> > > 我使用+62811586862检查号码whatsapp，但仍然没有帐户存在。
> > 
> > 
> > 确实，解决方法是尝试使用 +08 而不是 +628，它可以工作。使用我的api，结果是该号码已注册，而使用+628未注册。![截图_76](https://user-images.githubusercontent.com/23734341/247785592-0a84117d-e38a-45c5-9b6d-227d897ad89a.png)
> 
> 在职的

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
> @ratnokustiawan您可以向该号码发送消息吗？

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
> > > > @ekoilkom，你能在底层用加号测试吗，比如`+6280158****`？
> > > 
> > > 
> > > 我使用+62811586862检查号码whatsapp，但仍然没有账户存在。
> > 
> > 
> > 确实，解决方法是尝试使用+08而不是+628，它可以工作。使用我的api，结果是该号码已注册，而使用+628未注册。![截图_76](https://user-images.githubusercontent.com/23734341/247785592-0a84117d-e38a-45c5-9b6d-227d897ad89a.png)
> 
> 在职的

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
> > @ekoilkom，你能在开头用加号测试吗，比如`+6280158****`？
> 
> 我使用+62811586862检查号码whatsapp，但仍然没有帐户存在。

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by 1-pq** [comment]
> 在巴西，我有一个非常类似的问题，但是是第九位数字。 示例： id：“5511999999999”； 这样他发送了消息，但 Whatsapp 应用程序缺少用户，这意味着他不存在...
> 
> 但如果我这样发送： 示例： id: "551199999999";
> 
> 用户正常收到消息。

https://t.me/azc856
最新协议注册直接起飞，whastapp,过ip限制，注册速度快稳定高效，不懂的可以来问。找实力合作

**Comment by diorgenesgrzesiuk** [comment]
> 6280158

Did you make any progress? I have the same problem...

**Comment by diorgenesgrzesiuk** [comment]
> In Brazil, I have a very similar problem, but with the ninth digit. Example: id: "5511999999999"; That way he sends the message but the whatsapp application does not find the user implying that he does not exist ..
> 
> But if I send it like this: Example: id: "551199999999";
> 
> The user receives the message normally..


6280158

Did you make any progress? I have the same problem...

**Comment by ratnokustiawan** [comment]
> > In Brazil, I have a very similar problem, but with the ninth digit. Example: id: "5511999999999"; That way he sends the message but the whatsapp application does not find the user implying that he does not exist ..
> > But if I send it like this: Example: id: "551199999999";
> > The user receives the message normally..
> 
> 6280158
> 
> Did you make any progress? I have the same problem...

for check onWhatsapp
if length=11 then replace 62 with +0
for send message
62xx

**Comment by rayidetriawan** [comment]
> > In Brazil, I have a very similar problem, but with the ninth digit. Example: id: "5511999999999"; That way he sends the message but the whatsapp application does not find the user implying that he does not exist ..
> > But if I send it like this: Example: id: "551199999999";
> > The user receives the message normally..
> 
> 6280158
> 
> Did you make any progress? I have the same problem...

I just deleted node_modules and reinstalled npm, it worked for me

**Comment by renerlemes** [comment]
@caiogrigoleto the same problemn occurs with me:

- If I send with the 9 digit, the message is not received
- If I send with the + in the start of number, the message is not received

I need to remove the 9 digit and the +

What do you do to resolve this?

**Comment by caiogrigoleto** [comment]
> @caiogrigoleto the same problemn occurs with me:
> 
> * If I send with the 9 digit, the message is not received
> * If I send with the + in the start of number, the message is not received
> 
> I need to remove the 9 digit and the +
> 
> What do you do to resolve this?

Cara, tive mais problemas com os DDDs a cima ou iguais a 31, não sei se pode ser algo do próprio whatsapp..

Mas fiz o seguinte, todo numero que entra se o DDD é >= 31 ele remove o nono digito.. Até agora pra mim isso funcionou.

**Comment by luizcaiafa** [comment]
> > [@caiogrigoleto](https://github.com/caiogrigoleto) the same problemn occurs with me:
> > 
> > * If I send with the 9 digit, the message is not received
> > * If I send with the + in the start of number, the message is not received
> > 
> > I need to remove the 9 digit and the +
> > What do you do to resolve this?
> 
> Cara, tive mais problemas com os DDDs a cima ou iguais a 31, não sei se pode ser algo do próprio whatsapp..
> 
> Mas fiz o seguinte, todo numero que entra se o DDD é >= 31 ele remove o nono digito.. Até agora pra mim isso funcionou.

Fala Caio, boa noite, tudo bem? Alguma evolução sobre esse tema?

**Comment by luizcaiafa** [comment]
> > [@caiogrigoleto](https://github.com/caiogrigoleto) , could you test with plus sign at beginning, like +551199999999 and +5511999999999?
> 
> I also experienced this and already use + for validate number. It works well. I implement double check to make sure the number did or did not exist.

Fala Caio, tudo bem? Como realizou essa dupla checagem?

**Comment by renerlemes** [comment]
@luizcaiafa eu fiz dessa forma e parei de ter problemas

```javascript
private async getWhatsAppId(rawId: string): Promise<string> {
  // Remove tudo que não seja dígito ou +
  let id = rawId.replace(/[^\d+]/g, '');

  // Deve começar com +
  if (!id.startsWith('+')) {
    throw new ApiError(`O número '${rawId}' não é um número de WhatsApp válido`);
  }

  // Tratamento específico para Brasil (+55)
  if (id.startsWith('+55') && id.length === 14) {
    const ddd = Number(id.slice(3, 5));
    if (ddd >= 31) {
      // remove nono dígito
      id = id.slice(0, 5) + id.slice(6);
    }
  }

  // Remove o +
  id = id.replace('+', '');

  // Garante o sufixo correto
  if (!id.endsWith('@g.us') && !id.endsWith('@s.whatsapp.net')) {
    id = id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`;
  }

  // Consulta ao WhatsApp
  const [result] = await this.Socket?.onWhatsApp(id);
  if (!result?.exists) {
    throw new ApiError(`O número '${rawId}' não é um número de WhatsApp válido`);
  }

  return id;
}
```

**Comment by luizcaiafa** [comment]
> [@luizcaiafa](https://github.com/luizcaiafa) eu fiz dessa forma e parei de ter problemas
> 
> private async getWhatsAppId(rawId: string): Promise<string> {
>   // Remove tudo que não seja dígito ou +
>   let id = rawId.replace(/[^\d+]/g, '');
> 
>   // Deve começar com +
>   if (!id.startsWith('+')) {
>     throw new ApiError(`O número '${rawId}' não é um número de WhatsApp válido`);
>   }
> 
>   // Tratamento específico para Brasil (+55)
>   if (id.startsWith('+55') && id.length === 14) {
>     const ddd = Number(id.slice(3, 5));
>     if (ddd >= 31) {
>       // remove nono dígito
>       id = id.slice(0, 5) + id.slice(6);
>     }
>   }
> 
>   // Remove o +
>   id = id.replace('+', '');
> 
>   // Garante o sufixo correto
>   if (!id.endsWith('@g.us') && !id.endsWith('@s.whatsapp.net')) {
>     id = id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`;
>   }
> 
>   // Consulta ao WhatsApp
>   const [result] = await this.Socket?.onWhatsApp(id);
>   if (!result?.exists) {
>     throw new ApiError(`O número '${rawId}' não é um número de WhatsApp válido`);
>   }
> 
>   return id;
> }

Obrigado! Vou seguir dessa forma e, caso descubra outra solução, compartilho aqui.
