### ISSUE TITLE
HOW TO GET LINKS

### ISSUE THREAD

**Issue by Riders004** [WhiskeySockets/Baileys#158]
How to generate links like [This](https://whiskeysockets.github.io/)  and [this](https://whiskeysockets.github.io/Baileys/) 

@PurpShell  @pokearaujo @andresayac

**Comment by andresayac** [comment]
> How to generate links like [This](https://whiskeysockets.github.io/)  and [this](https://whiskeysockets.github.io/Baileys/) 
> 
> @PurpShell  @pokearaujo @andresayac 

can you explain more

**Comment by Riders004** [comment]
> > How to generate links like [This](https://whiskeysockets.github.io/)  and [this](https://whiskeysockets.github.io/Baileys/)
> > @PurpShell  @pokearaujo @andresayac
> 
> can you explain more

How can I generate link like :- https://whiskeysockets.github.io/ and https://whiskeysockets.github.io/Baileys
