### ISSUE TITLE
will they keep updating?

### ISSUE THREAD

**Issue by DavidModzz** [WhiskeySockets/Baileys#16]
Will they keep updating the project or is it just to save the files? :)

**Comment by edgardmessias** [comment]
Yes, we will keep it, this first moment we are organizing the project

**Comment by DavidModzz** [comment]
thank you so much <3

**Comment by andresayac** [comment]
hello friend, use the discussion section to comment on these topics or questions and we use this for bug

**Comment by BrunoSobrino** [comment]
And if WhatsApp wants to close this project anyway? I find it strange that amiruldev20 has closed his repository anyway.

**Comment by andresayac** [comment]
baileys was not from *amiruldev20* I don't understand when you say why he closed it from discord the boys organized for it to be this

**Comment by DavidModzz** [comment]
> Hello friend, use the discussion section to comment on these topics or questions and we use this for bug
> 
> https://github.com/WhiskeySockets/Baileys/discussions

ok
