### ISSUE TITLE
[BUG] I don't get the poll vote

### ISSUE THREAD

**Issue by DavidsonGomes** [WhiskeySockets/Baileys#164]
I don't get any message.update when a poll message is voted, it only arrives in the event message.upsert but it arrives encrypted.

I saw here in the files that it should be sent
https://github.com/WhiskeySockets/Baileys/blob/master/src/Utils/process-message.ts#L337

**Comment by stactus** [comment]
I have the same problem here... I'll wait for the solution that is informed...

**Comment by andresayac** [comment]
Read this please
https://github.com/WhiskeySockets/Baileys/issues/38

**Comment by DavidsonGomes** [comment]
> Read this please #38

I made my code that way, but it doesn't even reach the messages.update event

**Comment by DeveloperNewton** [comment]
Same problem. I don't get pollUpdates update in messages.update

**Comment by DavidsonGomes** [comment]
> Very curious, it works perfectly for me. Here I have a base for a bot that I develop and it works. latest version baileys
> 
> https://github.com/andresayac/bot_baileys/blob/2b3a2e3ec828377699d357116ae1645d13cffbfc/baileys.js#L202
> 
> https://github.com/andresayac/bot_baileys
> 
> ![image](https://user-images.githubusercontent.com/16548795/248292914-b8a33e71-5792-42fd-8c6e-4ddc63c80cd7.png)

Yeah, that's pretty strange, because here's the same code for the messages.update event, but putting a console.log at the beginning of the event doesn't even get the information there, nothing gets there

**Comment by andresayac** [comment]
I see that you are not reading well, you must create the getMessage store and that's it, the event will work, use my code as a guide

**Comment by DavidsonGomes** [comment]
> I see that you are not reading well, you must create the getMessage store and that's it, the event will work, use my code as a guide

Look, here is my condition where I define the connection and where I listen to the messages.update event

Connection waSocket
https://i.imgur.com/C48ggJo.png

messages.update
https://i.imgur.com/yJXoXQL.png

**Comment by andresayac** [comment]
I see that you need to declare the store 
I share all the necessary lines

https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L21
https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L22C38-L22C38
https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L24
https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L51
https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L54
https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L250

**Comment by DavidsonGomes** [comment]
> I see that you need to declare the store I share all the necessary lines
> 
> https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L21
> 
> 
> https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L22C38-L22C38
> https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L24
> 
> 
> https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L51
> 
> 
> https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L54
> 
> 
> https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L250

I solved the issue by adding the store to the project. thank you very much!

**Comment by clssh** [comment]
meu <Buffer >  do messageSecret retorna vazio alguem ajuda?

**Comment by clssh** [comment]
> > I see that you need to declare the store I share all the necessary lines
> > https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L21
> > 
> > https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L22C38-L22C38
> > https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L24
> > 
> > https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L51
> > 
> > https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L54
> > 
> > https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/Example/example.ts#L250
> 
> I solved the issue by adding the store to the project. thank you very much!

my messageSecret Buffer returns empty
