### ISSUE TITLE
[BUG] Cannot find package '/home/mirudev/Desktop/Luna-Base/node_modules/@whiskeysockets/baileys/' imported from /home/mirudev/Desktop/Luna-Base/system/bot.js

### ISSUE THREAD

**Issue by miruchigawa** [WhiskeySockets/Baileys#170]
I have no idea what going on

`Cannot find package '/home/mirudev/Desktop/Luna-Base/node_modules/@whiskeysockets/baileys/' imported from /home/mirudev/Desktop/Luna-Base/system/bot.js`

**Comment by bentacos** [comment]
you certainly shouldn't use Bailey's if you don't know any JavaScript. creating an issue like this just adds unnecessary overhead to the maintainers. go hire a developer or just continue being a normal person.

**Comment by miruchigawa** [comment]
I'm sorry if I can't use JavaScript programming. But can you explain to me why, even though I have installed this module using yarn and the folder is already installed in the node_modules directory, the module is still not being recognized?

**Comment by miruchigawa** [comment]
Thank you for answering my silly question.
