### ISSUE TITLE
Video Not Playing On Whatsapp | 

### ISSUE THREAD

**Issue by ParthJohri** [WhiskeySockets/Baileys#174]
Hey so I want to send a video but the video is playing on whatsApp, I followed the readme instructions still the video its not playable 
`const videoBuffer = fs.readFileSync(filePath);

    // Send the message
    sendMessage(key.remoteJid, {
      video: videoBuffer,
      caption: "Video Generated!",
      fileLength: videoBuffer.length,
      mimetype: "video/mp4", // Set the mimetype to specify the video format
      width: 1920, // Set the video width
      height: 1080, // Set the video height
    });`
    
    Could you also suggest some libraries which can support image processing in javascript so that I can add it to my bot!

**Comment by bentacos** [comment]
this is not a baileys bug. go fix your code. 

you should open a topic in the discord channel next time instead of creating unrelated issues here.

**Comment by ParthJohri** [comment]
Well sorry about tagging it as a bug.
Actually I got a problem in my code actually the issue was the video which I was trying to send had the video format which was not supported by Whatsapp. So just ue ffmpeg to do that!
Anyways thanks would be closing thisl

**Comment by ParthJohri** [comment]
Hey so so I resolved this error by choosing a fixed quality of video to download, here is the code snippet, hope it helps!
```
const handleYTDownload = async (msg) => {
    const { key, message } = msg;
    const ss = getText(message);
    const text = ss.trim();
    const s = "@ytd";
    if (!text.toLowerCase().startsWith(s)) return;
    const str = text.slice(s.length + 1);
    const videoURL = str.trim();
    const downloadStream = ytdl(videoURL, { quality: 18 });
    downloadStream
      .pipe(fs.createWriteStream("downloads/video.m4v"))
      .on("finish", () => {
        // File download completed
        console.log("Video downloaded successfully");
        // Read the downloaded video file
        const videoBuffer = fs.readFileSync("downloads/video.m4v");

        // Send the message
        sendMessage(key.remoteJid, {
          video: videoBuffer,
          caption: "Your youtube video is downloaded",
          mimetype: "video/mp4", // Set the mimetype to specify the video format
        });
      });
  };
```

**Comment by areltiyan** [comment]
> Hey so so I resolved this error by choosing a fixed quality of video to download, here is the code snippet, hope it helps!
> 
> ```
> const handleYTDownload = async (msg) => {
>     const { key, message } = msg;
>     const ss = getText(message);
>     const text = ss.trim();
>     const s = "@ytd";
>     if (!text.toLowerCase().startsWith(s)) return;
>     const str = text.slice(s.length + 1);
>     const videoURL = str.trim();
>     const downloadStream = ytdl(videoURL, { quality: 18 });
>     downloadStream
>       .pipe(fs.createWriteStream("downloads/video.m4v"))
>       .on("finish", () => {
>         // File download completed
>         console.log("Video downloaded successfully");
>         // Read the downloaded video file
>         const videoBuffer = fs.readFileSync("downloads/video.m4v");
> 
>         // Send the message
>         sendMessage(key.remoteJid, {
>           video: videoBuffer,
>           caption: "Your youtube video is downloaded",
>           mimetype: "video/mp4", // Set the mimetype to specify the video format
>         });
>       });
>   };
> ```

i think still using ffmpeg, bcs i have same issue rn
