### ISSUE TITLE
Protocol message REVOKE overwriting the message key ID

### ISSUE THREAD

**Issue by matheusb-comp** [WhiskeySockets/Baileys#175]
While processing "protocol messages" of type `REVOKE`, the code currently overrides the message ID with the `protocolMessage.key.id` in [this line](https://github.com/WhiskeySockets/Baileys/blob/730ed7f9fabd6ee0ba9f01486ce489a7521a0fc5/src/Utils/process-message.ts#L255).
Is this correct?

In the "In-memory Store" code, the ID [used here](https://github.com/WhiskeySockets/Baileys/blob/730ed7f9fabd6ee0ba9f01486ce489a7521a0fc5/src/Store/make-in-memory-store.ts#L270) will be the "protocol message ID" and not the "message key ID" that was used to save the message (in the event `messages.upsert`).

For example, these are (modified) examples of data from both events:
![Screenshot from 2023-06-22 12-45-33](https://github.com/WhiskeySockets/Baileys/assets/1227961/172baff2-e5ba-4709-9cfa-96e6e3364cc2)

**Comment by PurpShell** [comment]
Interesting, will investigate later to see if it is still an issue

**Comment by PurpShell** [comment]
this is corrrect

**Comment by tomiheneldra** [comment]
Any update/solution? @matheusb-comp  @purpshell 

I am using version 7.0.0-rc.9 and encountering the same issue.
