### ISSUE TITLE
[BUG] I don't get pollUpdates update in messages.update

### ISSUE THREAD

**Issue by DeveloperNewton** [WhiskeySockets/Baileys#176]
I don't get pollUpdates inside [{ update: {}}] in messages.update

That's all, I can't use pollUpdates after a few updates.

Note: I'm using the latest update

**Comment by zennn08** [comment]
listen `messages.upsert`

**Comment by DavidsonGomes** [comment]
+1

I also don't receive the poll response update listening to messages.update

**Comment by andresayac** [comment]
https://github.com/WhiskeySockets/Baileys/issues/164
