### ISSUE TITLE
Implementation of Auth using MongoDB

### ISSUE THREAD

**Issue by banguncode** [WhiskeySockets/Baileys#182]
Can anyone provide an example or library for auth using MongoDB?

**Comment by bahkadomos** [comment]
https://github.com/salman0ansari/whatsapp-api-nodejs

**Comment by inrl-official** [comment]
> Can anyone provide an example or library for auth using MongoDB?

Check fantox github

**Comment by Shubhamrawat5** [comment]
Check https://github.com/Shubhamrawat5/whatsapp-bot-ts

**Comment by PurpShell** [comment]
you have to implement this yourself
