### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'subject')

### ISSUE THREAD

**Issue by DGXeon** [WhiskeySockets/Baileys#188]
![Screenshot_20230625_075018](https://github.com/WhiskeySockets/Baileys/assets/88829846/f19b264c-4e0b-491e-81e4-7ec78c11bd87)
It happens when chats are spammed.. is this bug or?? Any solution guys???
![Screenshot_20230625_075534](https://github.com/WhiskeySockets/Baileys/assets/88829846/a9f98e70-5eb7-4288-ac55-40b18d9f10f6)

**Comment by SheIITear** [comment]
Not a bug. Look up http codes.

**Comment by DGXeon** [comment]
Here we go again
