### ISSUE TITLE
Help me fix this sh*t

### ISSUE THREAD

**Issue by DGXeon** [WhiskeySockets/Baileys#189]
![Screenshot_20230625_075018](https://github.com/WhiskeySockets/Baileys/assets/88829846/8c647637-126c-495b-80f8-f9d347d31963)

**Comment by SheIITear** [comment]
Implement a cache or something similar to avoid rate limit. Also refrain from making such issues in future.

**Comment by DGXeon** [comment]
Bro what do you want.. can u stop closing my issues.. if u dong want to help just stop  doing this shits stuff

**Comment by SheIITear** [comment]
Issues are made to track and report issues with the library itself, not for issues caused by someones own code.

**Comment by DGXeon** [comment]
Stfu kid

**Comment by Daveshvats** [comment]
https://github.com/uNetworking/uWebSockets.js/issues/335

> Stfu kid

**Comment by Daveshvats** [comment]
maybe this work
