### ISSUE TITLE
[BUG] Is it supported to work with socks5 proxy?

### ISSUE THREAD

**Issue by catthecreator** [WhiskeySockets/Baileys#194]
**Describe the bug**
I'm trying to run several sessions on the same server (not for spam, I just have a CRM module that use several clients)

I'm trying two proxy options, socks5 and https. Each of them causes different errors.

When using https proxy I get an error:
```
isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'WebSocket Error (A "socket" was not created for HTTP request before 20000ms)'
    },
    headers: {}
  }
```

When using socks5 proxy I get an error:
```
isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: "WebSocket Error (Hostname/IP does not match certificate's altnames: IP: 31.13.72.52 is not in the cert's list: )"
    },
    headers: {}
  }
```

**To Reproduce**
I open the connection like this:

```

const logger = pino({ level: 'debug' });

// socks5://login:pass@1.1.1.1:2222
// https://login:pass@1.1.1.1:3333
const proxyString = `${proxytype}://${proxyUsername}:${proxyPassword}@${proxyUrl}:${proxyPort}`;
const agent = new ProxyAgent(proxyString);

makeWASocket({
            printQRInTerminal: false,
            browser: Browsers.ubuntu('Chrome'),
            agent,
            logger,
            shouldIgnoreJid: jid => isJidBroadcast(jid),
        });
```

**Expected behavior**
I expect that each instance will work through its own proxy without traffic leakage... To begin with, at least will allow to initiate a connection

**Environment (please complete the following information):**
 - Is this on a server? - No, win10
 - What do your `connectOptions` look like? - described above
 - Do you have multiple clients on the same IP? - No, 1 client 1 proxy
 - Are you using a proxy? - trying :)

**Additional context**
What am I doing wrong with http proxy? 

Is there a way to tell the proxy agent to ignore the certificate validation for socks5 proxy?

Thanks for your attention

**Comment by waynesun01** [comment]
you can try:
const proxyUrl = 'socks://user:password@ip:1080'; // SOCKS
const SocksProxyAgent = require('socks-proxy-agent');
const agent = new SocksProxyAgent(proxyUrl);

**Comment by catthecreator** [comment]
> you can try: const proxyUrl = 'socks://user:password@ip:1080'; // SOCKS const SocksProxyAgent = require('socks-proxy-agent'); const agent = new SocksProxyAgent(proxyUrl);

That's work, thanks!
