### ISSUE TITLE
[BUG] - Campaign message sending

### ISSUE THREAD

**Issue by Joao-Darwin** [WhiskeySockets/Baileys#196]
**Describe the bug**
Bug when running campaign.

**To Reproduce**
1. Created a new campaing
2. Wait send mesage's campaing

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? Ok
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? Yes

`TypeError: Cannot read properties of null (reading 'match')
3|backend  |     at extractUrlFromText (/home/deploy//backend/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:41:67)
3|-backend  |     at generateLinkPreviewIfRequired (/home/deploy//backend/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:45:48)
3|-backend  |     at generateWAMessageContent (/home/deploy//backend/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:218:71)
3|-backend  |     at generateWAMessage (/home/deploy//backend/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:472:102)
3|-backend  |     at Object.sendMessage (/home/deploy//backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:606:69)
3|-backend  |     at Queue.handleDispatchCampaign (/home/deploy//backend/dist/queues.js:443:24)
3|-backend  | ERROR [26/06/2023 21:10:00]: Cannot read properties of null (reading 'match')`

**Comment by yourlogo2018** [comment]
That there edta seems more error in its back end than in the lib. I recommend you check your code, check what's new in the lib.

**Comment by ahmeaqas** [comment]
if you want to run campaigns through whatsapp, have  a look on to https://autoapps.cc/subscription-category/waps-ultimate.
