### ISSUE TITLE
[BUG] TypeScript error - Cannot find module '@adiwajshing/baileys' or its corresponding type declarations.

### ISSUE THREAD

**Issue by allburov** [WhiskeySockets/Baileys#20]
**Describe the bug**
On the import line it gives me an error - ` Cannot find module '@adiwajshing/baileys' or its corresponding type declarations.`

```javascript
import makeWASocket, {DisconnectReason, makeInMemoryStore, isJidGroup, useMultiFileAuthState} from '@adiwajshing/baileys'
```
The same line worked fine with the previous repo, `adiwajshing/baileys`

**To Reproduce**
1. Install the library as dependency in TS project - `yarn add github:WhiskeySockets/Baileys`
2. Run `npm run build` (I'm using `nest` for that)
3. Observe the error.

**Expected behavior**
It works :) 

**Environment (please complete the following information):**
- node 18
- yarn 1.22
- typescript 4.7.4
- What else could help here?

**Additional context**
The same code with `adiwajshing/baileys` dependency from `node_modules` works fine. No changes made.

**Comment by allburov** [comment]
If I suppress it with `// @ts-ignore` it shows
```
Error: Cannot find module '/home/allburov/git/project/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by exallhost** [comment]
> If I suppress it with `// @ts-ignore` it shows
> 
> ```
> Error: Cannot find module '/home/allburov/git/project/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
> ```

I am facing the same error after tweaking for this git.
![Captura de Tela 2023-04-24 às 12 12 10](https://user-images.githubusercontent.com/48133685/234040898-df63f588-9649-4168-b238-7c38d47eb6dc.png)

**Comment by Marcoant007** [comment]
![image](https://user-images.githubusercontent.com/59663846/234157694-640a8159-70ff-44a8-9b9a-e0924d7bfc25.png)

npm i https://github.com/WhiskeySockets/Baileys --force

**Comment by allburov** [comment]
It'd be good if I can use `npm` instead of `yarn`, but it doesn't seem possible - npm gives me too much errors and with yarn project (the rest) works perfectly :( 

For now I cloned the git repo, installed, compiled and added it to my package with `yarn add file:../Baileys` :+1: 

I hope you'll be able to deploy the library in https://www.npmjs.com/ soon!

**Comment by exallhost** [comment]
> ![image](https://user-images.githubusercontent.com/59663846/234157694-640a8159-70ff-44a8-9b9a-e0924d7bfc25.png)
> 
> npm i https://github.com/WhiskeySockets/Baileys --force

I was unsuccessful in the attempt.

**Comment by Marcoant007** [comment]
OK, do the following.

1- delete the node modules

2- delete the package.lock

3- run -> yarn install.

I had the same error, when I did that it started working again and recognizing normally

**Comment by FIlham** [comment]
> OK, do the following.
> 
> 1- delete the node modules
> 
> 2- delete the package.lock
> 
> 3- run -> yarn install.
> 
> 4 - verify https ->"@adiwajshing/baileys": https://github.com/WhiskeySockets/Baileys
> 
> I had the same error, when I did that it started working again and recognizing normally
> 
> ![image](https://user-images.githubusercontent.com/59663846/235005812-5a2ac45f-4d76-442b-b486-315b1ac44f51.png)

What is "verify https" meant? What is that?

**Comment by Marcoant007** [comment]
I meant that it is necessary in dependencies of package.json that have https to reference the repository.

well... that's what worked for me.

**Comment by Teamolduser** [comment]
> uses npm, using yarn you need to run tsc manually.

You need to also tsc manually in npm

**Comment by Teamolduser** [comment]
> OK, do the following.
> 
> 1- delete the node modules
> 
> 2- delete the package.lock
> 
> 3- run -> yarn install.
> 
> 4 - verify https ->"@adiwajshing/baileys": https://github.com/WhiskeySockets/Baileys
> 
> I had the same error, when I did that it started working again and recognizing normally
> 
> ![image](https://user-images.githubusercontent.com/59663846/235005812-5a2ac45f-4d76-442b-b486-315b1ac44f51.png)



Use "@adiwajshing/baileys":  "github: WhiskeySockets/Baileys",

**Comment by yanuaraditia** [comment]
I have this same issue too

**Comment by yanuaraditia** [comment]
I just trying to change the import path and show this error

```bash
import makeWASocket from './Socket'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
```

There's my script
```ts
import makeWASocket, { DisconnectReason, UserFacingSocketConfig } from '@adiwajshing/baileys/src'
import { Boom } from '@hapi/boom'

async function connectToWhatsApp () {
    const sock = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true
    } as UserFacingSocketConfig)
    sock.ev.on('connection.update', (update: any) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
    sock.ev.on('messages.upsert', async (m: any) => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        await sock.sendMessage(m.messages[0].key.remoteJid!, { text: 'Hello there!' })
    })
}
// run in main file
connectToWhatsApp()
```

**Comment by filipeloose** [comment]
I had the same block, I just cleared the caches and it worked

yarn cache clean

**Comment by edgardmessias** [comment]
Now you can install using `npm install @whiskeysockets/baileys` or `yarn add @whiskeysockets/baileys`

You can use the git version using NPM or Yarn V2, the Yarn v1 (classic) will not work

**Comment by allburov** [comment]
>You can use the git version using NPM or Yarn V2, the Yarn v1 (classic) will not work.

For those who (as me) didn't know about that - you must run the command below to set V2 mode
```
yarn set version berry
```

after that `yarn add github:WhiskeySockets/Baileys` works fine!
