### ISSUE TITLE
[BUG] :- Not getting group Participants

### ISSUE THREAD

**Issue by marutikarad** [WhiskeySockets/Baileys#203]
this.sessions[i].ev.on('groups.upsert', item =>{
      console.log('groups.upsert',`recv ${item.length} groups`)
      db.get("groups").push(...item).write()
  })

this not give any data

**Comment by SheIITear** [comment]
Before making issues use the code provided in examples. If no such code is found make it as clear as possible following the documentation and if the issue persists, then make an issue with more detail than just ”no workey”. Issues are not made for issues in your *own* code, especially with ’BUG’ template. Hence closing this.
