### ISSUE TITLE
How to get the status when a WhatsApp number is banned?

### ISSUE THREAD

**Issue by AlanMartines** [WhiskeySockets/Baileys#204]
Hello,

I am using the Baileys library for my application and I am having trouble understanding how I can get the status when a WhatsApp number is banned.

I have tried a few approaches, but without success. I would like to know if there is a specific way to do this with the Baileys library.

Any help or guidance would be greatly appreciated.

Thank you.

**Comment by manojsitapara** [comment]
On `connection.update` event, if `DisconnectReason.loggedOut`, it means your number is banned, unless you manually log out from WhatsApp

**Comment by AlanMartines** [comment]
Right, but I would like to know if there is any parameter that I can use as a reference, because just the ```DisconnectReason.loggedOut``` event is vague.

**Comment by DwiRizqiH** [comment]
Maybe the banned status codes are `403` and `402` (temporary)
but this status code is only executed when the connection is disconnected
not when reconnecting

and the status code `402` has a banned timetamp

**Comment by AlanMartines** [comment]
Okay, I'll validate and in any situation I'll reopen the issue.

Grateful!

**Comment by lukasportal** [comment]
@AlanMartines  were you able to validate this? how did you end up doing?
