### ISSUE TITLE
who hide their Online status?

### ISSUE THREAD

**Issue by kylonrizoki** [WhiskeySockets/Baileys#206]
Hello, How can i dedect who hide their online status? I scanned qr with my Whatsapp, ı am trying understand which number hide their Online status?

For example, 

- if we are getting message but there isn’t any offline presence we can understand from here. But it is not enough. Because sometimes target dont send message 

I need the understand which number hide their Online status 

discord: kylonrizoki#3255

**Comment by SheIITear** [comment]
For what? To stalk them?

**Comment by kylonrizoki** [comment]
> For what? To stalk them?

Nope,my question is not related the spam. 

I am trying to understand who hide their online  status.

 (if they hide we can’t see their status, ı know that)

**Comment by bentacos** [comment]
why would you need to know if they hide their online status? there's a reason it's called "hide". if you can't see their status then create a handler for that, you can say it's "hidden" or "unavailable".

**Comment by kylonrizoki** [comment]
@bentacos  Do you have any advice for the handler?

**Comment by AlvaroBrasilia** [comment]
> @bentacos Do you have any advice for the handler?

`const status = await sock.fetchStatus("xyz@s.whatsapp.net") `

**Comment by kylonrizoki** [comment]
> > @bentacos Do you have any advice for the handler?
> 
> `const status = await sock.fetchStatus("xyz@s.whatsapp.net") `

Can you contact with me on discord? kylonrizoki#3255

**Comment by calix666** [comment]
const status = await sock.fetchStatus("xyz@s.whatsapp.net")  if i iterate all menbers of the group its allways return undefined regardless of the satate

**Comment by calix666** [comment]
let presencia= await sock.presenceSubscribe("xyz@s.whatsapp.net") 
allways return undefined
