### ISSUE TITLE
[BUG] `old_version` at the registration's code request

### ISSUE THREAD

**Issue by bahkadomos** [WhiskeySockets/Baileys#209]
A few days ago I started getting an `old_version` error. I have tried to update WA version using [instructions](https://github.com/WhiskeySockets/Baileys/tree/master/proto-extract):
1. After executing the script, I received updated files with a new protocol version. Here is what was written to the `Defaults/baileys-version.json`:
```
{
	"version": [2, 2326, 10]
}

```
2. Put files `WAProto/WAProto.proto`, `WAProto/index.d.ts`, `WAProto/index.js` and `Defaults/baileys-version.json` to my current baileys folder.
3. But I still get an `old_version` error.
4. Function `fetchLatestBaileysVersion()` also outputs the old version.

What am I doing wrong?

**Comment by bahkadomos** [comment]
**UPD**. If I don't pass a version from `fetchLatestBaileysVersion()` to `makeWASocket`, then the default version is initialized in it, and that it's up to date. I still can't figure out where the old version is coming from the `fetchLatestBaileysVersion()` function.

**Comment by bahkadomos** [comment]
**UPD2**. I updated the proto version to 2.2327.4 as in #169 PR and removed "version" from my `makeWASocket`. The version has changed to the current one in the log but still getting this error. :(

My socket object looks like this:
```
{
    logger,
    auth,
    agent // HttpsProxyAgent
}
```

Is this version is relevant for web session, but I need a different one for registration, am I right?

**Comment by BochilGaming** [comment]
```
const { version } = await fetchLatestBaileysVersion()

**Comment by andresayac** [comment]
make sure that you are pointing to the baileys package and run npm i --force or the one of your preference and reinstall packages or to make it easier for you delete the node_modules folder and reinstall

**Comment by cjb1234567** [comment]
Is native mobile api registration still working?  

I tried example.ts with "--mobile" option, but it failed at sending sms.  

the request to "https://v.whatsapp.net/v2/code"  is failed found in registration.ts  --->> mobileRegisterFetch() function. 
```
const response = await axios(url, opts)
var json = response.data
```
here response returns things like this
login:
'xxxxxxxxxxxx'
reason:
'old_version'
status:
'fail'

Does anyone know how to solve this?

**Comment by aayush-farmart** [comment]
> Is native mobile api registration still working?
> 
> I tried example.ts with "--mobile" option, but it failed at sending sms.
> 
> the request to "https://v.whatsapp.net/v2/code" is failed found in registration.ts --->> mobileRegisterFetch() function.
> 
> ```
> const response = await axios(url, opts)
> var json = response.data
> ```
> 
> here response returns things like this login: 'xxxxxxxxxxxx' reason: 'old_version' status: 'fail'
> 
> Does anyone know how to solve this?

I'm facing the same problem, did anyone find a solution to this?

**Comment by allburov** [comment]
The fix helped me 
https://github.com/WhiskeySockets/Baileys/issues/241#issuecomment-1633285969

I've changed these lines in **src/Defaults/index.ts**
```javascript
export const MOBILE_TOKEN = Buffer.from('0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM3d3683e76445591c0591bc3c034c3bca')
export const MOBILE_USERAGENT = 'WhatsApp/2.23.13.82 iOS/15.3.1 Device/Apple-iPhone_7'
```
