### ISSUE TITLE
Error deploying to a VPS[BUG]

### ISSUE THREAD

**Issue by josuens** [WhiskeySockets/Baileys#210]
Hello, does anyone know why I am getting this error?

I have it in my local and it worked, when I upload it to the server it gives me that error

[https://media.discordapp.net/attachments/1124571452897759252/1124571453153624137/123123123.jpg?width=404&height=147](https://media.discordapp.net/attachments/1124571452897759252/1124571453153624137/123123123.jpg?width=404&height=147)

**Comment by SheIITear** [comment]
Not baileys issue.
