### ISSUE TITLE
[BUG] Connection disconnect automatically, after sometime auto start when we go to QR page & reload multiple times 

### ISSUE THREAD

**Issue by nirajuc** [WhiskeySockets/Baileys#211]
**Describe the bug**
After successfully connecting my number through the WhatsApp QR code on my portal, the connection automatically disconnects after some time, resulting in missed messages. Reloading the QR page multiple times triggers an auto-start of the connection, but the issue persists.

**To Reproduce**
1. Connect the number through the WhatsApp QR code on the portal.
2. After some time, the connection automatically disconnects.
3. Reload the QR page multiple times to trigger an auto-start, but the issue persists.

**Expected behavior**
I expected the WhatsApp QR code connection to remain stable and not disconnect automatically, allowing me to send and receive messages consistently without interruptions.

**Environment (please complete the following information):**
- Is this on a server?
- What do your `connectOptions` look like?
- Do you have multiple clients on the same IP?
- Are you using a proxy?

**Additional context**
- The issue occurs when connecting through the WhatsApp QR code on my portal.
- Reloading the QR page multiple times triggers an auto-start of the connection, but it is not a permanent solution.
- The Plesk panel's real-time updates logs showed the following error entry:
```
Timestamp: 2023-07-01 15:16:55
Error: 103.216.212.122
Response Code: 400
Request Method: GET
Endpoint: /socket.io/?EIO=4&transport=websocket&sid=Z9_lZsPWyb6YvVa9AAAA
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
Error Code: 784
```
- Any assistance in resolving this issue would be greatly appreciated.

**Comment by SheIITear** [comment]
Literally no one knows your "qr code portal". Also this doesnt seem like a baileys issue.

**Comment by nirajuc** [comment]
I'm using Bailey's

**Comment by nirajuc** [comment]
If anyone have resolution, please let me know

**Comment by nirajuc** [comment]
@SheIITear Who are you? Why you are closing the conversation? It's not spam. I really need help

**Comment by nirajuc** [comment]
@SheIITear Do you even have a knowledge of this? Just annoying, I see you have many tickets closed by yourself without giving any resolution. Member will automatically close if he/she get any solution. This is not your job, even the author is disrespecting anyone, then who are you & why

**Comment by bentacos** [comment]
@nirajuc shut your mouth. @SheIITear is one of the top contributors of this lib. your issue doesn't look like it's because of Baileys, check your code first. 

if you don't know what you are doing, you should hire someone to do it for you. don't create unnecessary issues here.

**Comment by nirajuc** [comment]
@bentacos Before commenting anything check the ticket details first.

**Comment by bentacos** [comment]
this part:
`Endpoint: /socket.io/?EIO=4&transport=websocket&sid=Z9_lZsPWyb6YvVa9AAAA`

already tells that this is not caused by baileys, socket.io doesn't ship with baileys by default. don't make me get my belt.

**Comment by SheIITear** [comment]
> @SheIITear Who are you? Why you are closing the conversation? It's not spam. I really need help
> 
> 

1. As I said above, no one knows what your qr code portal is.
2. That endpoint is not used in baileys nor is plesk and that 400 makes it more clear that the issue is in your own code.

Hence I close your issues. This is not a baileys bug. If you want help with other stuff ask on proper places, like github discussions or the discord server.

**Comment by bentacos** [comment]
@SheIITear im thinking that this guy probably bought a script with baileys as lib somewhere and thinks baileys is owned by that script author
