### ISSUE TITLE
When editing message, where can I put the message sending options like quoted and mentions?

### ISSUE THREAD

**Issue by aidulcandra** [WhiskeySockets/Baileys#212]

**Comment by SheIITear** [comment]
Dont make issues for no reason.

**Comment by aidulcandra** [comment]
@SheIITear Then where should I ask questions?

**Comment by SheIITear** [comment]
> @SheIITear Then where should I ask questions?
> 
> If you can't answer my question then don't close it until someine answers it

Discord. Or github discussions. Issues are made to report issues with the lib itself. Not for asking stuff that can be found out by reading the documentation or issues with ones own code.

**Comment by aidulcandra** [comment]
> > @SheIITear Then where should I ask questions?
> > 
> > If you can't answer my question then don't close it until someine answers it
> 
> Discord. Or github discussions. Issues are made to report issues with the lib itself. Not for asking stuff that can be found out by reading the documentation or issues with ones own code.

This isn't found anywhere in the documentation, maybe you haven't read my question properly

**Comment by SheIITear** [comment]
> > > @SheIITear Then where should I ask questions?
> > > 
> > > If you can't answer my question then don't close it until someine answers it
> > 
> > Discord. Or github discussions. Issues are made to report issues with the lib itself. Not for asking stuff that can be found out by reading the documentation or issues with ones own code.
> 
> This isn't found anywhere in the documentation, maybe you haven't read my question properly

Eitherway making issues is not the correct place to ask, we have alternative ways for that.
