### ISSUE TITLE
How come relayMessage doesn't have its own documentation?

### ISSUE THREAD

**Issue by Jakquellyn** [WhiskeySockets/Baileys#214]
I'm confused about how relayMessage has a reply, and how do users reply to bots without a prefix?

**Comment by SheIITear** [comment]
Ask in the discord server or github discussions. Issues arent the right place.

**Comment by Jakquellyn** [comment]
> Ask in the discord server or github discussions. Issues arent the right place.

Where's that?

**Comment by SheIITear** [comment]
> > Ask in the discord server or github discussions. Issues arent the right place.
> 
> 
> 
> Where's that?

You can join discord [here](https://discord.gg/ASbw8AYD)
