### ISSUE TITLE
Fetch missed message during disconnection 

### ISSUE THREAD

**Issue by nirajuc** [WhiskeySockets/Baileys#215]
**Describe the bug**
When using the receive message and sender message webhooks in my Node.js application, if my device remains inactive for a long period of time or even after becoming active again, it gets automatically disconnected. However, restarting my Node.js server allows it to reconnect successfully. As a result, I am missing out on messages that were sent or received during the disconnection.

**To Reproduce**
1. Start the Node.js application and connect to WhatsApp using the QR code.
2. Remain inactive for an extended period or let the device disconnect.
3. Activate the device again, but observe that it remains disconnected.
4. Restart the Node.js server, and it successfully reconnects.

**Expected behavior**
I expect the device to remain connected to WhatsApp even after being inactive for a long time or after becoming active again. Automatic disconnections should not occur, ensuring that no messages are missed.

**Environment (please complete the following information):**
- Node.js version: [16.20.1]
- WhatsApp API library and version: [server.js]
- Operating system: [Ubuntu 22.04.2 LTS]

**Additional context**
- The automatic disconnection issue occurs when using receive message and sender message webhooks in my Node.js application.
- Restarting the Node.js server allows successful reconnection to WhatsApp.
- The disconnections result in missed messages during the period of disconnection.
- Is there a way to fetch old messages from WhatsApp once my device is reconnected through the QR code? This would ensure that I can import any missed sent and replied messages.

Any guidance or suggestions on resolving this issue and fetching old messages would be highly appreciated.

Note: Without the script author, don't close this ticket without reading ticket information. I don't have time to post irrelevant post or wasting other, this is real information

**Comment by bentacos** [comment]
it's you again. what script author are you talking about? this library is being managed by the community. don't be rude to moderators. hire someone if you don't know what you are doing, programming is not for everyone including you.

**Comment by nirajuc** [comment]
@bentacos Are you a developer? Why you are replying irrelevant. I can create ticket in community if I feel it's relevant, then moderator revert to that ticket, you can't say anything to me as you are also a member like me, not moderator of community 

As I see @SheIITear is a developer, I prefer more comments from him

**Comment by w3nder** [comment]
I don't have this problem in my implementation

**Comment by nirajuc** [comment]
@w3nder Which server you are using?

**Comment by w3nder** [comment]
> @w3nder Which server you are using?

I have an application running on several different servers and a different company, I have no problem with the connection being on standby

I strongly recommend that you review your application before opening an issue.

**Comment by bentacos** [comment]
> @bentacos Are you a developer? Why you are replying irrelevant. I can create ticket in community if I feel it's relevant, then moderator revert to that ticket, you can't say anything to me as you are also a member like me, not moderator of community
> 
> As I see @SheIITear is a developer, I prefer more comments from him

yes, i'm a developer, that's why i don't go around creating useless issues. what "server" are you talking about? if you bought your whatsapp script somewhere, go ask the author of that script.

**Comment by bentacos** [comment]
> I don't have this problem in my implementation

@w3nder he's the only one having that problem and thinks it was because of baileys without even checking his code. if i see @nirajuc in person, i'll probably slap the hell out of him.

**Comment by nirajuc** [comment]
@bentacos Mind your language, learn from @SheIITear the communication skills. How politely he is communicate in comments,

**Comment by nirajuc** [comment]
@w3nder I brought the script from 1 guy, I've integrate send and receive messages webhook, my device is connected & after sometime it's got auto disconnected, bcz of this I not able to send and receive messages

Please, correct me If I'm missing something. I don't know

I checked the logs, it's show socket is disconnecting automatically 

Please advise if you can help

**Comment by w3nder** [comment]
> @w3nder I brought the script from 1 guy, I've integrate send and receive messages webhook, my device is connected & after sometime it's got auto disconnected, bcz of this I not able to send and receive messages
> 
> Please, correct me If I'm missing something. I don't know
> 
> I checked the logs, it's show socket is disconnecting automatically
> 
> Please advise if you can help

I think you should hire a programmer to solve your problem.

**Comment by nirajuc** [comment]
@w3nder I tried to contact many people's, but they are not familiar with this

**Comment by HUGEIT** [comment]
my man you needa learn how to ask questions.

phrases like "extended period" get your HR manager wet but they don't mean a thing to programmers. to write a bug report, be specific in reproducing your problem, like after how many days the situation came up.

in your other issue you talk about "qr portal" - like the other guys on here said there is no "qr portal" in Baileys. you bought code somewhere and now you don't know how to make it work. your options are

1. rephrase the issue so we could potentially assist
2. ask the guy who sold you the code to assist
3. hire a programmer to write things from scratch
4. learn programming yourself

and don't be surprised when issues get closed. if I visit a mercedes dealership because my iPad won't turn on they won't serve me either. issues get closed when they aren't in the scope of baileys. whatever your problem is (we still don't know) it's probably not Baileys fault

**Comment by HUGEIT** [comment]
and don't talk down to bentacos. just because he's not a maintainer that doesn't mean he cannot reply to you. just like you as a user can open issues, bentacos and all us other users have the right to respond to you, regardless of our status.
