### ISSUE TITLE
[BUG] After I updated baileys to the Have Voice Chat with wave

### ISSUE THREAD

**Issue by ardian458** [WhiskeySockets/Baileys#219]
Please fix it

When I use the voice chat command I received this error

![Screenshot_20230703-105645](https://github.com/WhiskeySockets/Baileys/assets/83260062/47f04e1a-ecb3-4e66-b2f8-5b0aa615b250)

**Comment by vphelipe** [comment]
This PR has an error, you have to wait for it to be validated first.

**Comment by FERDIZ-afk** [comment]
> Please fix it
> 
> When I use the voice chat command I received this error
> 
> ![Screenshot_20230703-105645](https://user-images.githubusercontent.com/83260062/250433505-47f04e1a-ecb3-4e66-b2f8-5b0aa615b250.png)

Tutup isunya bang itu lain module itu bukan dari baileys error nya

**Comment by dhyZx** [comment]
kkkk

**Comment by vikodk67** [comment]
> Please fix it
> 
> When I use the voice chat command I received this error
> 
> 
> ![Screenshot_20230703-105645](https://github.com/WhiskeySockets/Baileys/assets/83260062/47f04e1a-ecb3-4e66-b2f8-5b0aa615b250)
> 

Plis bang jangan bikin malu orang indo wkwk😅☝️

**Comment by ardian458** [comment]
H

**Comment by SanzGanzs** [comment]
🗿🗿
