### ISSUE TITLE
error when sending messages [BUG]

### ISSUE THREAD

**Issue by Zarhouny** [WhiskeySockets/Baileys#221]
**Describe the bug**
I'm not quite sure, seems to e something related to the regex that checks if the message has a url or not.

**To Reproduce**
take the followng code:

class AyaCommand {
  constructor(sock, sender, args, usersSet) {
  //this string is just for demonstration, of course.
  
    var stringg = "big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big stritring big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string  string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big string  string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big str  string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big str string big string big string big string big string big string big string big string big string big string big string big string big string big string big string big str"

    function divideString(str) {
      if (str.length <= 1000) {
        console.log(str.length)
        return str;
      } else {
        
        console.log(str.length)
        
        const chunkSize = 500;
        const numChunks = Math.ceil(str.length / chunkSize);
        const chunks = [];
    
        for (let i = 0; i < numChunks; i++) {
          const start = i * chunkSize;
          const end = start + chunkSize;
          chunks.push(str.substring(start, end));
        }
        console.log(chunks)
        return chunks;
      }
    }
    try {
    let arr = divideString(stringg)
    console.log(arr.length)
    for(let i = 0; i<= arr.length; i++) {
      setTimeout(() => {
        sock.sendMessage(sender, {
          text: arr[i]
        })
      }, i * 3500)
      }
      console.log("executed with 0 error")
    } catch (e) {
      console.error("ERROR: ", e)
      return;
    }
    }
  }

module.exports = AyaCommand

When ran, you get the following error:

**return (!Defaults_1.URL_EXCLUDE_REGEX.test(text) ? (_a = text.match(Defaults_1.URL_REGEX)) === null || _a === void 0 ? void 0 : _a[0] : undefined);
                                                                  ^

TypeError: Cannot read properties of undefined (reading 'match')
    at extractUrlFromText (C:\Users\pc\Desktop\Quran-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:41:67)
    at generateLinkPreviewIfRequired (C:\Users\pc\Desktop\Quran-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:45:48)
    at generateWAMessageContent (C:\Users\pc\Desktop\Quran-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:218:71)
    at generateWAMessage (C:\Users\pc\Desktop\Quran-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:477:102)
    at Object.sendMessage (C:\Users\pc\Desktop\Quran-bot\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:606:69)
    at Timeout._onTimeout (C:\Users\pc\Desktop\Quran-bot\commands\test.js:32:14)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.2.0**

**Expected behavior**
what should happen is: the messages get sent 3.5 seconds one after another
what happens: the message do get send 3.5 seconds one after the other, but the error appears.

**Environment (please complete the following information):**
 - Is this on a server? Nope
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? NO
 - Are you using a proxy? NO

**Additional context**
this doesn't just happen in this specific case, This is, By far the most common error I get, I get this when I try to return a string from a function that's in an other file, I get this when I try to read Json files and retreve data and send it as a message, I get this sometimes when I try to check if the message content has something, and I've really had to think of some obscure ways to work around it, but' it's just un-avoidable and straight up annoying.

EDIT: I fixed it, but still read the additional context, because this really is a common bug. not just in this scenario

**Comment by SheIITear** [comment]
Youre passing empty message?
