### ISSUE TITLE
[BUG] Browser icon not showing

### ISSUE THREAD

**Issue by DavidsonGomes** [WhiskeySockets/Baileys#228]
I'm setting the browser to 'chrome', but the browser no longer appears in the connection. what is the correct way to do it?

browser: ['API', 'chrome', '22.5.0']

**Comment by bentacos** [comment]
this is not a bug. the new version of WhatsApp doesn't show the browser anymore. it will only show the OS name.

**Comment by muhammad9711** [comment]
But I currently use the old version v4.4.0, the browser icon still show what we put on browser options, and even use whatsapp web also show. But not on latest Baileys

**Comment by bentacos** [comment]
v4 is no longer supported. stop searching for what's not possible.

**Comment by Riders004** [comment]
> this is not a bug. the new version of WhatsApp doesn't show the browser anymore. it will only show the OS name.

It's showing browser icon in connected uf you connect thorugh WhatsApp Web not with Baileys but in Baileys it's not showing
