### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by leandrodesign** [WhiskeySockets/Baileys#230]
I'm having trouble replying to a specific message, can someone help me?

is correct?

async replyMessage(phoneNumber, text, quotedMessage) {
        await this.verifyId(this.getWhatsAppId(phoneNumber))
        await this.instance.sock?.presenceSubscribe(phoneNumber);
        const data = await this.instance.sock?.sendMessage(
            this.getWhatsAppId(phoneNumber),
            {
                text: text,
                quoted: quotedMessage
          }
        );
        return data;
    }

**Comment by programadorbob** [comment]
Use this example based on your code.

```
async replyMessage(phoneNumber, text, quotedMessage) {
    await this.verifyId(this.getWhatsAppId(phoneNumber))
    await this.instance.sock?.presenceSubscribe(phoneNumber);
    const data = await this.instance.sock?.sendMessage(this.getWhatsAppId(phoneNumber), {
        text: text
    }, {
        quoted: quotedMessage
    });
    return data;
}
```

**Comment by SheIITear** [comment]
Dont make issues to ask help with your code. Ask in dc or discussions.

**Comment by leandrodesign** [comment]
> Use este exemplo com base no seu código.
> 
> ```
> async replyMessage(phoneNumber, text, quotedMessage) {
>     await this.verifyId(this.getWhatsAppId(phoneNumber))
>     await this.instance.sock?.presenceSubscribe(phoneNumber);
>     const data = await this.instance.sock?.sendMessage(this.getWhatsAppId(phoneNumber), {
>         text: text
>     }, {
>         quoted: quotedMessage
>     });
>     return data;
> }
> ```

thanks

**Comment by leandrodesign** [comment]
> Não faça problemas para pedir ajuda com seu código. Pergunte em dc ou discussões.

Sorry, I even tried to do it the way you say but I couldn't

**Comment by azartheen** [comment]
@LeonardoBein try like this 

 await this.verifyId(this.getWhatsAppId(to))
        const result = await this.instance.sock?.sendMessage(
            this.getWhatsAppId(to),
            {
                text: data.text,
                sections: data.sections,
                buttonText: data.buttonText,
                footer: data.description,
                title: data.title,
                viewOnce: true,
            }
        )
        return result
