### ISSUE TITLE
[BUG] when fetch all groups 

### ISSUE THREAD

**Issue by JunaGanz** [WhiskeySockets/Baileys#238]
When i try to fetch all groups on whatsapp using this function sock.groupFetchAllParticipating()

it not only returns the value to the variable i created but also returns the value to the groups.update event

**Comment by SheIITear** [comment]
what

**Comment by Hendra827** [comment]
#160 this issue?

**Comment by JunaGanz** [comment]
> #160 check my pull request

Thanks!! You saved me!!
