### ISSUE TITLE
Mobile API outdated

### ISSUE THREAD

**Issue by imredfox** [WhiskeySockets/Baileys#241]
Whatsapp mobile version "2.22.24.81" outdated. Giving "{ login: 'xx', reason: 'old_version', status: 'fail' }" error.

Current WhatsApp iOS version is 2.23.13.82.

Need to update src/Defaults/index.ts (MOBILE_TOKEN and MOBILE_USERAGENT)

MOBILE_USERAGENT: "WhatsApp/2.23.13.82 iOS/15.3.1 Device/Apple-iPhone_7"
MOBILE_TOKEN format : "0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM"+md5(app package md5)

But I can not extract md5 sum of the application package. (My phone is not jailbreaked)

Can someone extract the md5 checksum of the app?

**Comment by imredfox** [comment]
My mistake. "0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM"+md5(app version)

So...

export const MOBILE_TOKEN = Buffer.from('0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM3d3683e76445591c0591bc3c034c3bca')
export const MOBILE_USERAGENT = 'WhatsApp/2.23.13.82 iOS/15.3.1 Device/Apple-iPhone_7'

**Comment by Davidaprilio** [comment]
> My mistake. "0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM"+md5(app version)
> 
> So...
> 
> export const MOBILE_TOKEN = Buffer.from('0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM3d3683e76445591c0591bc3c034c3bca') export const MOBILE_USERAGENT = 'WhatsApp/2.23.13.82 iOS/15.3.1 Device/Apple-iPhone_7'

Thanks it's works for me

**Comment by lauriolasw** [comment]
Hello
I tried using:

MOBILE_TOKEN = Buffer.from('0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM3d3683e76445591c0591bc3c034c3bca')
MOBILE_USERAGENT = 'WhatsApp/2.23.13.82 iOS/15.3.1 Device/Apple-iPhone_7'

And had this error:  { reason: '**old_version**', status: 'fail', login: 'nnn' }
 
So, I attempted to update the token using the latest APK, (and using md5sum) directly from the WA download site:

MOBILE_TOKEN = Buffer.from('0a1mLfGUIBVrMKF1RdvLI5lkRBvof6vn0fD2QRSM9bf0dbb9983ac28770ab7c91af6b13f2')
MOBILE_USERAGENT = 'WhatsApp/2.23.23.79 iOS/15.3.1 Device/Apple-iPhone_7'

And now have this error: { reason: '**bad_token**', status: 'fail', login: 'nnn' }

I would appreciate any guidance or suggestions on how to resolve this issue
