### ISSUE TITLE
[BUG] "Cannot derive from empty media key"

### ISSUE THREAD

**Issue by danLDev** [WhiskeySockets/Baileys#242]
**Describe the bug**
When attempting to download a media message, I'm seeing an error 'Cannot derive from empty media key'.

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Received an image message via the `messages.upsert` event
4. Pass image message to lambda via sqs
5. Call the `downloadMediaMessage` method inside the lambda

**Expected behavior**
The media to be downloaded

**Environment (please complete the following information):**
The baileys instance is running on a fargate instance with the following config
```ts
  const socket = makeWASocket({
    version,
    logger: childLogger,
    auth: {
      creds: auth.creds,
      keys: makeCacheableSignalKeyStore(auth.keys, childLogger),
    },
    generateHighQualityLinkPreview: true,
    syncFullHistory: true,
    qrTimeout: 30000,
    markOnlineOnConnect: false,
    browser: Browsers.appropriate('Desktop'),
  });
```
The instance has multiple devices (70+) running on the same IP address, auth credentials are stored in Redis, and the whole system sees around 100000 events/min at peak times.

The lambda where the media is being downloaded does not have access to the socket, and we cannot create a new socket connection without breaking the connected device credentials, and as such cannot pass the `sock.updateMediaMessage` method.

**Comment by PurpShell** [comment]
Are you passing in the media key through to the lambda? That's your error here

**Comment by danLDev** [comment]
Why would you mark this as completed without giving a chance for me to clarify whether the problem is resolved?

Yes we are passing the full media key through to the lambda, exactly as the docs recommend.

Please re-open.

**Comment by PurpShell** [comment]
> Why would you mark this as completed without giving a chance for me to clarify whether the problem is resolved?
> 
> Yes we are passing the full media key through to the lambda, exactly as the docs recommend.
> 
> Please re-open.

still an issue? i suppose the media key was missing in some cases
