### ISSUE TITLE
[BUG] Even placing the correct security_code it does not register

### ISSUE THREAD

**Issue by Guilherme-j10** [WhiskeySockets/Baileys#244]
I tried a few times among them I put the security code in the following ways:

1: xxxxxx
2: xxx-xxx

anyway none worked and always get the log below

Failed to register your phone number. Please try again.
 {
  email_wait: 0,
  guess_wait: 0,
  guesses_left: 15,
  login: 'xxxxxxxxxxxxxx',
  min_poll: 5,
  reason: 'security_code',
  reset_method: 'email',
  server_time: 1689274182,
  status: 'fail',
  wipe_token: '1689274182',
  wipe_type: 'offline',
  wipe_wait: 603828
}

**Comment by gabrielayer** [comment]
k
k
k
k
k
k
k
k
k
k
k
k

**Comment by Auties00** [comment]
see my explanation in the linked issue
