### ISSUE TITLE
[BUG] Buttons doesn't appear

### ISSUE THREAD

**Issue by lintanxai** [WhiskeySockets/Baileys#25]
Buttons message doesn't appear in current whatsapp from google play

**Comment by andresayac** [comment]
you can share more details, if you use business or normal whatsapp, you can share the package.json

**Comment by lintanxai** [comment]
> you can share more details, if you use business or normal whatsapp, you can share the package.json

Thanks sir i'm using baileys from the last official repo the buttons just appear only in old whatsapp app

**Comment by MaznAbdullah** [comment]
> > you can share more details, if you use business or normal whatsapp, you can share the package.json
> 
> Thanks sir i'm using baileys from the last official repo the buttons just appear only in old whatsapp app

buttons not sent if you linked baileys withe "WhatsApp Business"
if you link withe "WhatsApp Personal" it will ok.

**Comment by lintanxai** [comment]
> Add

Thanks i will try to linked in wa messenger

**Comment by exallhost** [comment]
iOS ✅ 
Android ❌
Web ✅ 
Some solution for Android?

**Comment by andresayac** [comment]
The problem is that the message is not being sent. I have been debugging the code and WhatsApp is returning a 405 error. I assume that there might be a missing value or a wrong pointer, but I haven't reached that point yet since I am very new to this.

![image](https://user-images.githubusercontent.com/16548795/235282495-6771fa60-f4ec-4c0f-80b6-5261c26c6bbf.png)

**Comment by ariessetiyawan** [comment]
> Buttons message doesn't appear in current whatsapp from google play

I have try sendmessage button and listmemu successfully, but not for templatebutton (iOS ✅Android ❌Web ✅)

**Comment by lintanxai** [comment]
> > Buttons message doesn't appear in current whatsapp from google play
> 
> I have try sendmessage button and listmemu successfully, but not for templatebutton (iOS ❌ Android ❌ Web ✅)

Thanks sir may i know the baileys version

**Comment by ariessetiyawan** [comment]
> > > Buttons message doesn't appear in current whatsapp from google play
> > 
> > 
> > I have try sendmessage button and listmemu successfully, but not for templatebutton (iOS ❌ Android ❌ Web ✅)
> 
> Thanks sir may i know the baileys version

"version": [2, 2308, 7]

**Comment by cobraprojects** [comment]
same issue

**Comment by Yesenia57** [comment]
a little help, the buttons are not shown in WhatsApp Messenger or WhatsApp Bussines, but in WhatsApps Mods or Immunes if they are shown, is there a solution for that?

**Comment by andresayac** [comment]
> a little help, the buttons are not shown in WhatsApp Messenger or WhatsApp Bussines, but in WhatsApps Mods or Immunes if they are shown, is there a solution for that?

hello please update to the latest version of Baileys, if you use WhatsApp bussines you will not be able to send buttons try with a normal version they work for me

**Comment by iosahil** [comment]
> hello please update to the latest version of Baileys, if you use WhatsApp bussines you will not be able to send buttons try with a normal version they work for me

WhatsApp Android (Personal) : `2.23.10.4 (Beta)` // Latest as of now
Baileys: `[2, 2308, 7]` // Downloaded & compiled from WhiskeySockets/Baileys
WhatsApp for Windows: `2.2314.6.0`

I confirms that:
On Android, `TemplateButtons` aren't visible though `ButtonMessages` are visible.
On PC, Both are visible.

**Comment by satriowicaksn** [comment]
Is there really no solution to this problem ?

**Comment by NjabuloJ** [comment]
Button is error to work on npm install baileys
