### ISSUE TITLE
[BUG] Connection Closed when sending message to groups with many participants

### ISSUE THREAD

**Issue by DavidsonGomes** [WhiskeySockets/Baileys#251]
When trying to send any messages to groups with many participants, the request takes a long time and returns this error. how can i resolve this?

`
Error: Connection Closed
0|api  |     at sendRawMessage (/home/whatsplan-sender/htdocs/sender.whatsplan.com.br/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:56:19)
0|api  |     at sendNode (/home/whatsplan-sender/htdocs/sender.whatsplan.com.br/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:75:16)
0|api  |     at /home/whatsplan-sender/htdocs/sender.whatsplan.com.br/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:436:19
0|api  |     at async Object.transaction (/home/whatsplan-sender/htdocs/sender.whatsplan.com.br/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)
0|api  |     at async relayMessage (/home/whatsplan-sender/htdocs/sender.whatsplan.com.br/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:278:9)
0|api  |     at async Object.sendMessage (/home/whatsplan-sender/htdocs/sender.whatsplan.com.br/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:646:17) {
0|api  |   data: null,
0|api  |   isBoom: true,
0|api  |   isServer: false,
0|api  |   output: {
0|api  |     statusCode: 428,
0|api  |     payload: {
0|api  |       statusCode: 428,
0|api  |       error: 'Precondition Required',
0|api  |       message: 'Connection Closed'
0|api  |     },
0|api  |     headers: {}
0|api  |   }
`

**Comment by programadorbob** [comment]
Use `defaultQueryTimeoutMs: undefined` in main config in makeWASocket

**Comment by DavidsonGomes** [comment]
> Use `defaultQueryTimeoutMs: undefined` in main config in makeWASocket

apartment worked, thank you!

**Comment by luispimenta** [comment]
@DavidsonGomes is it still working? Here it stopped, and I made this adjustment and it's not working.

Can you pass your package.json so I can compare the versions?
