### ISSUE TITLE
presenceSubscribe() allways return undefined

### ISSUE THREAD

**Issue by calix666** [WhiskeySockets/Baileys#254]
ALLWAYS return undefined 

     let presencia= await sock.presenceSubscribe("52562xxx@s.whatsapp.net")

     await sock.sendMessage(msg.from, { text: presencia}, { quoted: msg })

Siempre devuelve undefined

**Comment by SheIITear** [comment]
Not a bug.

**Comment by calix666** [comment]
is bug. even if the user is writing or recording audio, it never returns the value
