### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Teamolduser** [WhiskeySockets/Baileys#259]
const response = await sock.groupAcceptInviteV4("abcd@s.whatsapp.net", groupInviteMessage)
console.log("joined to: " + response)

is not working please fix it or remove it from script and readme file

**Comment by SheIITear** [comment]
Use the issue template.

**Comment by Teamolduser** [comment]
> Use the issue template.

I'm using it same as but it's not working if remove privacy from group then it's added the number else if add privacy then it can't i tried to send invite but I can't
