### ISSUE TITLE
[BUG] - Small Image for Link Preview, Expecting Large Image for Link Preview

### ISSUE THREAD

**Issue by mkhotib20** [WhiskeySockets/Baileys#260]
**Describe the bug**
I compare message containing link that i sent through baileys and whatsapp device (Web, mobile). 

In baileys i sent it with `getUrlInfo` and i got small `og:image` in preview

<img width="639" alt="image" src="https://github.com/WhiskeySockets/Baileys/assets/23493234/29701625-cc10-43ef-9684-0071fc70801c">

But, in whatsapp device, i got large  link preview, like image below
<img width="391" alt="image" src="https://github.com/WhiskeySockets/Baileys/assets/23493234/74839a83-7ab7-4930-86b7-c66136a0a6a5">

**To Reproduce**
1. Created a new connection
2. send text message containing link and send it with `linkPreview` option
3. You'll receive message on destination jid 
4. Compare it with the link that you've sent with your own device

**Expected behavior**
It should sent with large link preview

**Additional context**
here's my `makeWaSocket` options

```
const sock = makeWASocket({
  version,
  logger,
  printQRInTerminal: !usePairingCode,
  mobile: false,
  auth: {
    creds: state.creds,
    keys: makeCacheableSignalKeyStore(state.keys, logger),
  },
  msgRetryCounterCache,
  generateHighQualityLinkPreview: true,
  getMessage: async () => {
    return proto.Message.fromObject({});
  },
});

```

here's my send message code
```
const urlFromText = extractUrlFromText(message);
let linkPreview;

if (urlFromText) {
  try {
    linkPreview = await getUrlInfo(urlFromText, {
      thumbnailWidth: 1200,
      fetchOpts: {
        timeout: 5000,
      },
    });
  } catch (error) {
    console.error(error);
  }
}

sock.sendPresenceUpdate("available", destination);
await sleep(500);
sock.sendPresenceUpdate("composing", destination);
await sleep(Math.max(message.length * 10, 7500));
sock.sendPresenceUpdate("paused", destination);
const result = await sock.sendMessage(destination, {
  text: message,
  linkPreview,
});

```

**Comment by mkhotib20** [comment]
i have been solved by adding this when calling `getUrlInfo`
```
const linkPreview = await getUrlInfo(urlFromText, {
  thumbnailWidth: 1024,
  fetchOpts: {
    timeout: 5000,
  },
  uploadImage: waCon.waUploadToServer,
});

```

**Comment by mkhotib20** [comment]
i have been solve this issue with adding this code when calling getUrlInfo
```
const linkPreview = await getUrlInfo(urlFromText, {
  thumbnailWidth: 1024,
  fetchOpts: {
    timeout: 5000,
  },
  uploadImage: waCon.waUploadToServer,
});

```

**Comment by wduandy** [comment]
@mkhotib20 can you show me the code of the ```getUrlInfo``` function? I have the same issue.

**Comment by mkhotib20** [comment]
here's my code

```

const socket = makeWaSocket() // let's assume this is your socket connection

const linkPreview = await getUrlInfo(urlFromText, {
  thumbnailWidth: 1024,
  fetchOpts: {
    timeout: 5000,
  },
  uploadImage: socket.waUploadToServer,
});


socket.sendMessage(jid, {
   linkPreview,
})

```

**Comment by wduandy** [comment]
@mkhotib20 thanks a lot!

**Comment by wduandy** [comment]
@mkhotib20, strangely, the generated preview link only shows on iOS devices. I can't get it to display on Android devices. Have you faced the same issue?

**Comment by Fonnte** [comment]
> 

Why is this code required? Isn't just install link-preview-js will automatically take care of it?

**Comment by Fonnte** [comment]
> here's my code
> 
> ```
> 
> const socket = makeWaSocket() // let's assume this is your socket connection
> 
> const linkPreview = await getUrlInfo(urlFromText, {
>   thumbnailWidth: 1024,
>   fetchOpts: {
>     timeout: 5000,
>   },
>   uploadImage: socket.waUploadToServer,
> });
> 
> 
> socket.sendMessage(jid, {
>    linkPreview,
> })
> ```

Why is this code required? Isn't just install link-preview-js will automatically take care of it?

**Comment by mkhotib20** [comment]
@Fonnte i've tried to only install `link-preview-js` and still same, the preview is not showing up. so i'm trying to do this and it works

**Comment by mkhotib20** [comment]
@wduandy can you show me the code then you call `sendMessage()`, perhaps i can help you

**Comment by Fonnte** [comment]
> @Fonnte i've tried to only install `link-preview-js` and still same, the preview is not showing up. so i'm trying to do this and it works

Quite weird, i am not doing that but link preview just work out of the blue 😅

**Comment by mkhotib20** [comment]
is your link showing meta preview like this? or just the text become blue?

![image](https://github.com/WhiskeySockets/Baileys/assets/23493234/5260f2cd-2fd3-4c9f-bae3-5e36c8a555e2)

because, on my case, the link turned blue but not showing meta preview like this, eg : og:image, title, description.

**Comment by Fonnte** [comment]
> @Fonnte is your link showing `meta site preview` like this? or just the text become blue?
> 
> because, on my case, the link turned into bluem but not showing `meta site preview` like this, eg : og:image, title, description.
> 
> ![image](https://user-images.githubusercontent.com/23493234/256803221-5260f2cd-2fd3-4c9f-bae3-5e36c8a555e2.png)

Yap, it does. Sorry i am on my phone

![IMG_20230728_181147](https://github.com/WhiskeySockets/Baileys/assets/23734341/555264f5-a0ed-4fcd-a053-d9823c878b78)

**Comment by mkhotib20** [comment]
it's okay, 
this issue supposed to help who can't generate meta preview like me. and if it's already generated by itself it doesn't need to do my step

**Comment by Fonnte** [comment]
> it's okay, this issue supposed to help who can't generate meta preview like me. and if it's already generated by itself it doesn't need to do my step

No worries, you've done great and your code definitely help this community. I just wonder why using geturlinfo is required while baileys doing it under the hood. Sorry, just curious 😅

**Comment by mkhotib20** [comment]
noo, i'm never saying that `getUrlInfo` is required. i'm doing this because i was send a message that contain link and it's not generating link preview. 

as i said before, `if it's already generated by itself it doesn't need to do my step`

> it's okay, this issue supposed to help who can't generate meta preview like me. and if it's already generated by itself it doesn't need to do my step

**Comment by fogolin** [comment]
I can confirm, android is not receiving the preview images. Web and iOS working fine, but on android phones, it's just showing the data, and not loading the images.

**Comment by MiguelRomaniw** [comment]
I have the same problem, I can't generate a large thumbnail, only a small thumbnail

Did anyone manage to solve it?

**Comment by andre-mr** [comment]
> here's my code
> 
> ```
> 
> const socket = makeWaSocket() // let's assume this is your socket connection
> 
> const linkPreview = await getUrlInfo(urlFromText, {
>   thumbnailWidth: 1024,
>   fetchOpts: {
>     timeout: 5000,
>   },
>   uploadImage: socket.waUploadToServer,
> });
> 
> 
> socket.sendMessage(jid, {
>    linkPreview,
> })
> ```

hi. where is this getUrlInfo from? I found a function with this name inside libs, but it seems it's in your logic, are you using a custom function?

**Comment by CodexRaunak** [comment]
> uploadImage: socket.waUploadToServer

Thanks a lot it worked

**Comment by sosofire** [comment]
@mkhotib20 https://docs.langchain4j.dev/ Why does parsing this URL result in a 404 error



AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: ClientRequest, …}
arg1 =
AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: ClientRequest, …}
code =
'ERR_BAD_REQUEST'
config =
{transitional: {…}, adapter: Array(3), transformRequest: Array(1), transformResponse: Array(1), timeout: 5000, …}
message =
'Request failed with status code 404'
name =
'AxiosError'
request =
ClientRequest {_events: {…}, _eventsCount: 7, _maxListeners: undefined, outputData: Array(0), outputSize: 0, …}
response =
{status: 404, statusText: 'Not Found', headers: AxiosHeaders, config: {…}, request: ClientRequest, …}
config =
{transitional: {…}, adapter: Array(3), transformRequest: Array(1), transformResponse: Array(1), timeout: 5000, …}
data =
Unzip {_writeState: Uint32Array(2), _readableState: ReadableState, _events: {…}, _eventsCount: 5, _maxListeners: undefined, …}
headers =
connection: close
content-length: 5142
server: GitHub.com
content-type: text/html; charset=utf-8
etag: W/"683f6c52-239b"
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
x-github-request-id: 3E70:17A3B6:1A0167:1B5BF5:683FEBA7
accept-ranges: bytes
age: 3515
date: Wed, 04 Jun 2025 07:44:35 GMT
via: 1.1 varnish
x-served-by: cache-tyo11925-TYO
x-cache: HIT
x-cache-hits: 0
x-timer: S1749023076.655149,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: 05acb7bb2ef814370e873b9d15c0ffc20be6af17
request =
ClientRequest {_events: {…}, _eventsCount: 7, _maxListeners: undefined, outputData: Array(0), outputSize: 0, …}
status =
404
statusText =
'Not Found'
[[Prototype]] =
Object
status =
404
stack =
'AxiosError: Request failed with status code 404\n    at settle (E:\\my\\baileys\\node_modules\\axios\\dist\\node\\axios.cjs:2031:12)\n    at RedirectableRequest.handleResponse (E:\\my\\baileys\\node_modules\\axios\\dist\\node\\axios.cjs:3096:9)\n    at RedirectableRequest.emit (node:events:529:35)\n    at RedirectableRequest._processResponse (E:\\my\\baileys\\node_modules\\follow-redirects\\index.js:409:10)\n    at RedirectableRequest._onNativeResponse (E:\\my\\baileys\\node_modules\\follow-redirects\\index… prepareWAMessageMedia (E:\\my\\baileys\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\messages.js:113:109)\n    at async getUrlInfo (E:\\my\\baileys\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\link-preview.js:87:42)\n    at async WhatsAppManager.sendMessage (E:\\my\\baileys\\whatsapp-manager.js:1581:35)\n    at async UnifiedMessageConsumer._processWithRetry (E:\\my\\baileys\\mq-consumer.js:95:16)\n    at async UnifiedMessageConsumer._handleMessage (E:\\my\\b...
[[Prototype]] =
Error

**Comment by areumtecnologia** [comment]
Nao precisa mais se preocupar com isso. Usando a versao baileys@7.0.0-rc.3 e so enviar uma mensagem de texto contendo uma url que o baileys ja envia o preview, porem tem que instalar link-preview-js@3.1.0

**Comment by Riders004** [comment]
Can anyone share the code of 

getUrlInfo
