### ISSUE TITLE
[BUG] SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by ArrDev10** [WhiskeySockets/Baileys#262]
When I try to send text to Jid status@broadcast, I receive an error
![Screenshot_20230720-102023~2](https://github.com/WhiskeySockets/Baileys/assets/83260062/e3d30947-0b9e-4083-a2d2-db7aad8078e1)

**Comment by SheIITear** [comment]
Doesnt look like baileys error. If the issue still happens using the documentation make a new issue with proper information.
