### ISSUE TITLE
[BUG] Adding a user not in device contacts to a group 

### ISSUE THREAD

**Issue by francofantini** [WhiskeySockets/Baileys#263]
**Describe the bug**

Whenever I try to create a group (groupCreate) or add a user to a group (groupParticipantsUpdate) Baileys will only add users that have a contact associated on the device. 
How can I get around this and add users that I have never saved on my device? 
So far I've checked with multiple phone numbers, checked that users are able to be added to groups by everyone and have seen a 403 error that I can't seem to find any documentation on.

```json
[
  {
    "status": "403",
    "jid": "XXX@s.whatsapp.net",
    "content": {
      "tag": "participant",
      "attrs": {
        "jid": "XXX@s.whatsapp.net",
        "error": "403"
      },
      "content": [
        {
          "tag": "add_request",
          "attrs": {
            "code": "XXXX",
            "expiration": "1690140989"
          }
        }
      ]
    }
  }
]

```

**To Reproduce**
1. Created a new connection
2. Add a number that you don't have in your phones contact list to a group

**Expected behavior**
I should be able to add any whatsapp number to a group.

**Environment (please complete the following information):**
 - Is this on a server? Local machine
 - What do your `connectOptions` look like? 
 ```
 {
    printQRInTerminal: true,
    auth: state,
}
```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**

**Comment by AliAryanTech** [comment]
+1

**Comment by johnparkerg** [comment]
+1

**Comment by DikaArdnt** [comment]
> **Describe the bug**
> 
> Whenever I try to create a group (groupCreate) or add a user to a group (groupParticipantsUpdate) Baileys will only add users that have a contact associated on the device. How can I get around this and add users that I have never saved on my device? So far I've checked with multiple phone numbers, checked that users are able to be added to groups by everyone and have seen a 403 error that I can't seem to find any documentation on.
> 
> ```json
> [
>   {
>     "status": "403",
>     "jid": "XXX@s.whatsapp.net",
>     "content": {
>       "tag": "participant",
>       "attrs": {
>         "jid": "XXX@s.whatsapp.net",
>         "error": "403"
>       },
>       "content": [
>         {
>           "tag": "add_request",
>           "attrs": {
>             "code": "XXXX",
>             "expiration": "1690140989"
>           }
>         }
>       ]
>     }
>   }
> ]
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Created a new connection
> 2. Add a number that you don't have in your phones contact list to a group
> 
> **Expected behavior** I should be able to add any whatsapp number to a group.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server? Local machine
> * What do your  look like?`connectOptions`
> 
> ```
> {
>    printQRInTerminal: true,
>    auth: state,
> }
> ```
> 
> * Do you have multiple clients on the same IP? No
> * Are you using a proxy? No
> 
> **Additional context** Add any other context about the problem here.

Maybe someone you're trying to add is turning on their privacy. You can give him an invitation message

**Comment by xxirfanx** [comment]
+1

**Comment by johnparkerg** [comment]
> > **Describe the bug**
> > 
> > Whenever I try to create a group (groupCreate) or add a user to a group (groupParticipantsUpdate) Baileys will only add users that have a contact associated on the device. How can I get around this and add users that I have never saved on my device? So far I've checked with multiple phone numbers, checked that users are able to be added to groups by everyone and have seen a 403 error that I can't seem to find any documentation on.
> > 
> > ```json
> > [
> >   {
> >     "status": "403",
> >     "jid": "XXX@s.whatsapp.net",
> >     "content": {
> >       "tag": "participant",
> >       "attrs": {
> >         "jid": "XXX@s.whatsapp.net",
> >         "error": "403"
> >       },
> >       "content": [
> >         {
> >           "tag": "add_request",
> >           "attrs": {
> >             "code": "XXXX",
> >             "expiration": "1690140989"
> >           }
> >         }
> >       ]
> >     }
> >   }
> > ]
> > ```
> > 
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Created a new connection
> > 2. Add a number that you don't have in your phones contact list to a group
> > 
> > **Expected behavior** I should be able to add any whatsapp number to a group.
> > 
> > **Environment (please complete the following information):**
> > 
> > * Is this on a server? Local machine
> > * What do your  look like?`connectOptions`
> > 
> > ```
> > {
> >    printQRInTerminal: true,
> >    auth: state,
> > }
> > ```
> > 
> > * Do you have multiple clients on the same IP? No
> > * Are you using a proxy? No
> > 
> > **Additional context** Add any other context about the problem here.
> 
> Maybe someone you're trying to add is turning on their privacy. You can give him an invitation message

I've personally checked that users are able to be added to groups by everyone and have tried with multiple phone numbers, still the same error.

**Comment by SheIITear** [comment]
Like @Auties00 if it cant be done on web client it most likely cant be done on baileys. 403 means forbidden -> you dont have permission. Its giving you the data to make a request for the user to join. Closing as doesnt seem to be a baileys bug.

**Comment by Pryanishnik** [comment]
Hey guys, I found out that whatsapp web facing the same issue and they have a PR to fix it, so it seems to be possible to add not in contact user to a group.
 https://github.com/pedroslopez/whatsapp-web.js/pull/2344

**Comment by mzayn** [comment]
any solution for this if the contact is not saved (private) - how to send invite with message join group ? any code for that. 

thanks

**Comment by Shubhamrawat5** [comment]
same issue

**Comment by ILHMSR2846** [comment]
same issue
