### ISSUE TITLE
Export Contacts From Chats

### ISSUE THREAD

**Issue by vaccarieli** [WhiskeySockets/Baileys#266]
I would like a feature that allows me to export all the contacts from my individual WhatsApp chats. I want to clarify that I am not looking to export contacts from group chats, but rather from the individual conversations I have on WhatsApp.

**Comment by onurguven** [comment]
If you want to export numbers from all your previous individual conversations, you can do it as follows:

```
wbot.ev.on('messaging-history.set', (data) => {
  const contactData = data.contacts;

  const filteredContacts = contactData.filter((item) =>
    item.id.endsWith("@s.whatsapp.net")
  );

  console.log(filteredContacts);
});
```

If you only want to export all the numbers saved in your address book, you can do it as follows:

```
wbot.ev.on("contacts.upsert", async (contacts) => {
  console.log(contacts);
});
```

**Comment by vaccarieli** [comment]
How do you trigger the event to export all the contacts? @onurguven. Nothing is being logged to the console.

**Comment by onurguven** [comment]
I've recently started using this package, and I don't want to give any wrong information, but as far as I understand, it works like this:

After scanning the QR code and establishing the first connection, 'contacts.upsert' transmits the entire contact list once. 

After that, as long as the connection is open and every time there is a change in the contacts list, it is automatically triggered and only forwards the contact items that have changed (newly added or updated).

There also seems to be a bug with 'contacts.upsert' as mentioned here: #268.

**Comment by SheIITear** [comment]
Dont make issues for such reason. Ask in discussions or discord.

**Comment by ricardojlrufino** [comment]
Tool to export Whatsapp chat history emulating Whatsapp APP, using NodeJS + baileys whatsapp lib.
https://github.com/ricardojlrufino/whatsapp-history-exporter
In case anyone is in need
