### ISSUE TITLE
[BUG] When and in a group of 500 to 900 people, baileys bugs and stops responding how do I solve it sometimes bugs and disconnects

### ISSUE THREAD

**Issue by Inaciooooo** [WhiskeySockets/Baileys#276]
When I add the bot to a group with more than 300 members, it crashes and stops responding to and sometimes disconnects When I add the bot to a group with more than 300 members, it crashes and stops responding to and sometimes disconnects

**Comment by DavidsonGomes** [comment]
add defaultQueryTimeoutMs = undefined in makeWASocket
