### ISSUE TITLE
Delay when sending message to group

### ISSUE THREAD

**Issue by renatoiub** [WhiskeySockets/Baileys#287]
When sending a text message to a group, the response takes about 30 seconds.
Does anyone know what could be causing this? Sometimes it ships quickly but most times it takes a while. Another case is when you send it from time to time while a message appears that is currently unavailable because you are using an old version of Whatsapp.

**Comment by Fonnte** [comment]
> When sending a text message to a group, the response takes about 30 seconds. Does anyone know what could be causing this? Sometimes it ships quickly but most times it takes a while. Another case is when you send it from time to time while a message appears that is currently unavailable because you are using an old version of Whatsapp.

First question : 
1. CPU might at peak
2. Socket connection is losing (not lost yet)

Second question : use store to resend the message. See example.ts

**Comment by renatoiub** [comment]
I believe it is really a BUG. It is intermittent, does not consume CPU and regardless of the connection I use, the problem happens. Not every group text message sends it, many report it as unavailable at the moment and I believe this is the cause.

**Comment by PurpShell** [comment]
if you are sending media, that's the only way you'll ever have a delay. Media messages need to take their time and upload to whatsapp servers before actually sending the message
