### ISSUE TITLE
Monitor private messages only

### ISSUE THREAD

**Issue by renatoiub** [WhiskeySockets/Baileys#289]
Is there any way or configuration that can be done to supervise only private messages and exclude messages from groups? I have an instance with several groups, and I would like Baileyes to monitor only private conversations because I noticed that depending on the moment, it causes slowness in sending messages.

**Comment by is99zsq** [comment]
> Is there any way or configuration that can be done to supervise only private messages and exclude messages from groups? I have an instance with several groups, and I would like Baileyes to monitor only private conversations because I noticed that depending on the moment, it causes slowness in sending messages.

why not quitting from the group?
if you are in the group, you can received the message and you must ack the msg.

**Comment by zennn08** [comment]
try this

```ts
import { isJidUser } from "@whiskeysockets/baileys"

const sock = makeWASocket({
  ...your_config,
  shouldIgnoreJid: jid => !isJidUser(jid)
})
```

**Comment by SheIITear** [comment]
This isnt an issue. Ask such questions in discussions or discord.
