### ISSUE TITLE
Why do messages sometimes only appear on wa mobile, and don't appear on wa web/desktop or vice versa

### ISSUE THREAD

**Issue by 161710089** [WhiskeySockets/Baileys#294]
Why do messages sometimes only appear on wa mobile, and don't appear on wa web/desktop or vice versa

**Comment by joseorlando-nsolucoes** [comment]
Are they audio messages?

**Comment by calix666** [comment]
update whatsapp and delete "baileys_auth_info" close all open sesion and login again

**Comment by renatoiub** [comment]
I am also having the same problem, how do I update whatsapp that is open in baileys?
