### ISSUE TITLE
get all contacts

### ISSUE THREAD

**Issue by sg957** [WhiskeySockets/Baileys#296]
Is there a way to get all the contacts? I don't mean the list of chats but the list of all contacts
Thank you

**Comment by danufirda** [comment]
sudah ada di dokumentasi

**Comment by danufirda** [comment]
sock.ev.on('contacts.upsert', (contact) => {

});

ini hanya muncul pertama setelah baileys terkoneksi dengan whatsapp, dan akan muncul kembali menampilkan kontak jika ada kontak baru. sebaiknya anda menyimpannya di .json atau sql

**Comment by mdev-imagenet** [comment]
I think this could help also (Baileys 'store' Doc): https://github.com/WhiskeySockets/Baileys/blob/ab2b530ac5a088830bea35f4630f6a65d97eadb2/README.md?plain=1#L299

**Comment by renatoiub** [comment]
Também queria saber como fazer.

**Comment by PurpShell** [comment]
Create a store, bind it, periodically save it, and load it from json on start
Then, you can simply access store.contacts
