### ISSUE TITLE
No new message notification on phone if message received in Baileys

### ISSUE THREAD

**Issue by abdulloh10** [WhiskeySockets/Baileys#299]
Hello
For some reason, the notification of the received message does not appear on the phone if the message is also received in Baileys. How can I get notifications for new messages on my phone?

**Comment by zennn08** [comment]
You can set `markOnlineOnConnect` to `false` in your configuration

```ts
const sock = makeWASocket({
  ...config,
  markOnlineOnConnect: false
})
```

**Comment by abdulloh10** [comment]
> You can set `markOnlineOnConnect` to `false` in your configuration
> 
> ```ts
> const sock = makeWASocket({
>   ...config,
>   markOnlineOnConnect: false
> })
> ```

Thank You

**Comment by salomonamiga** [comment]
hi

im using https://github.com/code-chat-br/whatsapp-api
with uses code as an implementation of Baileys,
but im having the same issue, and can't find anywhere how to solve it, I tried to ask on that git repo but have no answer
I tried to implement markOnlineOnConnect: false on the socketConfig but is not working for me
maybe here someone can help me on this ? I need the notifications !
Thank you !

**Comment by abdulloh10** [comment]
> hi
> 
> im using https://github.com/code-chat-br/whatsapp-api with uses code as an implementation of Baileys, but im having the same issue, and can't find anywhere how to solve it, I tried to ask on that git repo but have no answer I tried to implement markOnlineOnConnect: false on the socketConfig but is not working for me maybe here someone can help me on this ? I need the notifications ! Thank you !

const sock = makeWASocket({
   ...config,
   markOnlineOnConnect: false
})
does not completely solve the problem. After scanning to add a new device, there is no notification. After restarting the node, a notification then appears.

**Comment by salomonamiga** [comment]
> > hi
> > im using https://github.com/code-chat-br/whatsapp-api with uses code as an implementation of Baileys, but im having the same issue, and can't find anywhere how to solve it, I tried to ask on that git repo but have no answer I tried to implement markOnlineOnConnect: false on the socketConfig but is not working for me maybe here someone can help me on this ? I need the notifications ! Thank you !
> 
> const sock = makeWASocket({ ...config, markOnlineOnConnect: false }) does not completely solve the problem. After scanning to add a new device, there is no notification. After restarting the node, a notification then appears.

sorry I didnt understand 100% this
"After restarting the node, a notification then appears."
you mean you get WhatsApp notifications ?

is there any solution to my problem or anyhow the markOnlineOnConnect: false works ?

**Comment by abdulloh10** [comment]
> > > hi
> > > im using https://github.com/code-chat-br/whatsapp-api with uses code as an implementation of Baileys, but im having the same issue, and can't find anywhere how to solve it, I tried to ask on that git repo but have no answer I tried to implement markOnlineOnConnect: false on the socketConfig but is not working for me maybe here someone can help me on this ? I need the notifications ! Thank you !
> > 
> > 
> > const sock = makeWASocket({ ...config, markOnlineOnConnect: false }) does not completely solve the problem. After scanning to add a new device, there is no notification. After restarting the node, a notification then appears.
> 
> sorry I didnt understand 100% this "After restarting the node, a notification then appears." you mean you get WhatsApp notifications ?
> 
> is there any solution to my problem or anyhow the markOnlineOnConnect: false works ?

Yes, after applied `markOnlineOnConnect: false' and `pm2 restart whatsapp` a notification in mobile phone appears. But later the notification may disappear again. The solution is to pm2 restart again

**Comment by salomonamiga** [comment]
> > > > hi
> > > > im using https://github.com/code-chat-br/whatsapp-api with uses code as an implementation of Baileys, but im having the same issue, and can't find anywhere how to solve it, I tried to ask on that git repo but have no answer I tried to implement markOnlineOnConnect: false on the socketConfig but is not working for me maybe here someone can help me on this ? I need the notifications ! Thank you !
> > > 
> > > 
> > > const sock = makeWASocket({ ...config, markOnlineOnConnect: false }) does not completely solve the problem. After scanning to add a new device, there is no notification. After restarting the node, a notification then appears.
> > 
> > 
> > sorry I didnt understand 100% this "After restarting the node, a notification then appears." you mean you get WhatsApp notifications ?
> > is there any solution to my problem or anyhow the markOnlineOnConnect: false works ?
> 
> Yes, after applied `markOnlineOnConnect: false` and `pm2 restart whatsapp` a notification in mobile phone appears. But later the notification may disappear again. The solution is to pm2 restart again

thank you for the clarification, is so sad there is no way to fix this, I have seen other APIs can do, but this API has much more features, this is the only one I wish there is a fix anytime soon

**Comment by azudindaem** [comment]
This dirty trick might help

```ts
if(events['messages.upsert']) {
   client.sendPresenceUpdate('unavailable')
```

**Comment by kyraex** [comment]
> This dirty trick might help
> 
> ```ts
> if(events['messages.upsert']) {
>    client.sendPresenceUpdate('unavailable')
> ```

If there are high number of incoming messages, will it cause any issue due to spamming of presence update?

**Comment by diorgenesgrzesiuk** [comment]
Any progress on this problem?

By making the suggestions above, the alerts on the cell phone temporarily work again... then the problem continues...

**Comment by PurpShell** [comment]
> > This dirty trick might help
> > ```ts
> > if(events['messages.upsert']) {
> >    client.sendPresenceUpdate('unavailable')
> > ```
> 
> If there are high number of incoming messages, will it cause any issue due to spamming of presence update?

Yes it will spam, this is not a proper way of doing things. This person should've set a debounce  on it

**Comment by PurpShell** [comment]
For everyone confused here:  client.sendPresenceUpdate('unavailable')

Readme reference: https://github.com/WhiskeySockets/Baileys?tab=readme-ov-file#update-presence

**Comment by moshe1132767** [comment]
anyone? same problem

**Comment by anazmuhdd** [comment]
> anyone? same problem

yes. I do, I have maded the markonlineconnect into false and added every configurations and tested everything, no change.... Anyone who knows it?

**Comment by Isac999** [comment]
same here, when Baileys is connected, my phone still gets the messages but no sound or notification pops up
