### ISSUE TITLE
Polls added in "sending Messages" in the README 

### ISSUE THREAD

**Issue by piLovr** [WhiskeySockets/Baileys#30]
How to send Polls is missing there

**Comment by piLovr** [comment]
And change Group settings according join requests

**Comment by RavensVenix** [comment]
`sock.sendMessage(m.chat,` {
    poll: {
        name: "pollName",
        values: ["option1", "option2", "option3"]
    }
});`

**Comment by sahilashraff** [comment]
> `sock.sendMessage(m.chat, { poll: { name: "pollName", values: ["option1", "option2", "option3"] } });`

It's working but shows only on web not on mobile app is there any way to fix it?

**Comment by Rippanteq7** [comment]
> > `sock.sendMessage(m.chat, { poll: { name: "pollName", values: ["option1", "option2", "option3"] } });`
> 
> It's working but shows only on web not on mobile app is there any way to fix it?

Try this branch #957
