### ISSUE TITLE
[BUG]The thumbnail of the images does not appear

### ISSUE THREAD

**Issue by DavidModzz** [WhiskeySockets/Baileys#301]
When I send an image wearing baileys the thumbnail does not appear, instead a gray image appears!

![Screenshot_20230731-233844_Gallery.jpg](https://github.com/WhiskeySockets/Baileys/assets/86541514/1086d210-feb0-4e64-bd59-9b38ec7d3337)

**Comment by zennn08** [comment]
try

`yarn add jimp` or `yarn add sharp`
