### ISSUE TITLE
[BUG] problem typescript installing with yarn

### ISSUE THREAD

**Issue by mikilanz** [WhiskeySockets/Baileys#305]
i get this following error when installing with yarn.

![image](https://github.com/WhiskeySockets/Baileys/assets/35862932/c4c1d7d0-4a3e-4515-9622-360125acea7b)

im using nestJS typescript and package @whiskeysockets/baileys version 6.3.0. after running nest build. i get the error

**Comment by mi-mazouz** [comment]
same issue ! Did you resolve it ? @mikilanz

**Comment by PurpShell** [comment]
exclude node_modules from tsc compilation
