### ISSUE TITLE
[BUG] "undefined" message is not a mediaMessage

### ISSUE THREAD

**Issue by danLDev** [WhiskeySockets/Baileys#307]
I'm occasionally receiving errors from the `downloadMediaMessage` method when passing a valid message. 

**To Reproduce**
- Receive an image upsert
- Pass to `downloadMediaMessage` as below

Message 
```json
{
"message": { 
     "key": { 
       "fromMe": true
       "id": "3A2586CBDCE7668AB9A1"
       "remoteJid": "120363039697526678@g.us"
     }
     "message": { 
       "imageMessage": {
         "directPath": "/v/t62.7118-24/29992091_250943791012408_2437232673850074823_n.enc?ccb=11-4&oh=01_AdS9WpuExZvFbNebSVmkU_J0y_VOQlosVHaiQAPlNtBv0Q&oe=64D64F05&_nc_hot=1689176553"
         "fileEncSha256": "YzRold8fy8FL/sD6ncXl9wbay5euzjjL+/ekCbLUrww="
         "fileLength": 101742
         "fileSha256": "MHTf3dK79GMU2KH78vvgfaHRtEdLCuIiiyxOR8XudNw="
         "height": 1600
         "mediaKey":"yB+kmNT9A0mCH5XskUkeKWYpZVnk3cXFS3xgVPF4SvY="
         "mediaKeyTimestamp": 1689176048
         "mimetype": "image/jpeg"
         "url": "https://mmg.whatsapp.net/v/t62.7118-24/29992091_250943791012408_2437232673850074823_n.enc?ccb=11-4&oh=01_AdS9WpuExZvFbNebSVmkU_J0y_VOQlosVHaiQAPlNtBv0Q&oe=64D64F05&mms3=true"
         "width": 900
       }
     }
     "messageC2STimestamp": 1689176551
     "messageTimestamp": 1689176549
     "multicast": true
     "originalSelfAuthorUserJidString": "16466343399@s.whatsapp.net"
     "status": "READ"
     "userReceipt": [ ]
   }
```

Call to download
```typescript
    try {
      buffer = (await downloadMediaMessage(
        message,
        'buffer',
        {},
        {
          logger: childLogger,
          reuploadRequest: async (msg) => {
            const newMessage = await this.requestMediaReupload(
              msg,
              phoneNumber,
              txid,
            );
            return newMessage;
          },
        },
      )) as Buffer;
    } catch (e) {
      throw new Error(`Error downloading media from whatsapp ${e}`);
    }
```

**Expected behavior**
The image to download successfully

**Environment (please complete the following information):**
 - Is this on a server? - Yes, running in AWS Lambda
 - What do your `connectOptions` look like?  
 ``` typescript
 const socket = makeWASocket({
    version,
    logger: childLogger,
    auth: {
      creds: auth.creds,
      keys: makeCacheableSignalKeyStore(auth.keys, childLogger),
    },
    generateHighQualityLinkPreview: true,
    syncFullHistory: true,
    qrTimeout: 30000,
    markOnlineOnConnect: false,
    browser: Browsers.appropriate('Desktop'),
  });
  ```
 - Do you have multiple clients on the same IP? - No
 - Are you using a proxy? - No

**Additional context**
Device sockets are running on a server, messages are passed to a queue and consumed asynchronously with a ~10s delay.
We are running around 70 devices on the server, and this only happens occasionally.

**Comment by PurpShell** [comment]
message.message needs to be passed. This is an error on your end

**Comment by danLDev** [comment]
@PurpShell  This isn't the issue, the message being passed here is of type `WAMessage` as per the required args.

This also wouldn't explain why 99% of our messages are being downloaded fine.

Please re-open.

**Comment by PurpShell** [comment]
> @PurpShell This isn't the issue, the message being passed here is of type `WAMessage` as per the required args.
> 
> This also wouldn't explain why 99% of our messages are being downloaded fine.
> 
> Please re-open.

Are you still having this issue? If you are please provide more info

**Comment by danLDev** [comment]
I no longer work for the company implementing this so can't say for sure. But if I remember correctly I resolved it by creating a different `downloadMediaMessage` implementation based on your advice.

Should be okay to close this
