### ISSUE TITLE
[BUG] sendMessage in status broadcast

### ISSUE THREAD

**Issue by siTotes** [WhiskeySockets/Baileys#32]
how can I send or create stories in this baileys module.  in the example on github they changed the function from id to status@broadcast but my try failed and the code was stopped

**Comment by canove** [comment]
afaik it's not possible atm

**Comment by edgardmessias** [comment]
The flow to do this is the same of sending a message to group, but we need define manually the contact list.

**Comment by siTotes** [comment]
> The flow to do this is the same of sending a message to group, but we need define manually the contact list.

Can you provide an example of the code for me. I don't understand a bit

**Comment by edgardmessias** [comment]
There are no code to do it, we need to develop it

**Comment by siTotes** [comment]
> There are no code to do it, we need to develop it

come on, just make it when sending messages or videos and pictures because on all the web nothing explains about this

what I mean is just like the sample code, just an example conn. send Message(status@broadcast, {text: 'halo pren'})

**Comment by edgardmessias** [comment]
@siTotes , what I mean is: There are no code in Baileys to handle messages for status/broadcast, we need to modify the Baileys to do it. I don't have enough time to it.

**Comment by siTotes** [comment]
> @siTotes , what I mean is: There are no code in Baileys to handle messages for status/broadcast, we need to modify the Baileys to do it. I don't have enough time to it.

Ok thanks then

**Comment by Auties00** [comment]
Added support in https://github.com/WhiskeySockets/Baileys/pull/249

**Comment by mr-mr7** [comment]
is it fix?
