### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Teamolduser** [WhiskeySockets/Baileys#33]
The Discord Link Get Expired Please Update it or Any One Have @adiwajshing Discord username or server link please also  update  that in README.md

**Comment by potkek** [comment]
What link do you mean?

**Comment by Teamolduser** [comment]
> What link do you mean?
Link's 🔗 OrInvite Or Invitations

 
For example :- 
https://github.com/
https://discord.gg/WeJM5FP9GG/

**Comment by potkek** [comment]
You put a slash there

https://discord.gg/WeJM5FP9GG/

I just found out the link only works without the slash apparently

https://discord.gg/WeJM5FP9GG

If you click the link directly from the README.md it should work tho :)

**Comment by andresayac** [comment]
Link: https://discord.com/invite/WeJM5FP9GG
![image](https://user-images.githubusercontent.com/16548795/234871679-b0a1aad0-7eea-4df5-9b07-f1d214fea0fd.png)


Close this issue, send these types of requests through the discussions section

**Comment by Teamolduser** [comment]
> You put a slash there
> 
> https://discord.gg/WeJM5FP9GG
> 
> I just found out the link only works without the slash apparently
> 
> https://discord.gg/WeJM5FP9GG
> 
> If you click the link directly from the README.md it should work tho :)

I tried from README.me file but it open discord and nothing else  then copy and paste on WhatsApp then then i tried in discord to join server with link it told expired and there is no slash

**Comment by potkek** [comment]
Can you do a video of that? If I try it jumps into discord
