### ISSUE TITLE
[BUG] Incorrect display of the browser icon and name

### ISSUE THREAD

**Issue by dzagalskii** [WhiskeySockets/Baileys#331]
**Describe the bug**
The browser icon and name is displayed incorrectly in the list of devices when using both standard Baileys and custom browsers.

**To Reproduce**
1. Created a new connection with default browser (Browsers.baileys('Chrome'))
2. In the list of devices, the icon and browser name are displayed incorrectly

**Expected behavior**
The browser name and icon are displayed as described when setting up a connection.

**Comment by afeno** [comment]
I noticed that the only one working is `'browser': Browsers.macOS("Desktop")`
But 'browser': Browsers.ubuntu('Chrome') is not showing the right icon anymore in the last baileys version
