### ISSUE TITLE
Postman Collection/Examples

### ISSUE THREAD

**Issue by fogolin** [WhiskeySockets/Baileys#333]
Hey, what if we had an official Postman documentation for this API, with examples of requests and responses?
I just stumbled on this old one:
https://documenter.getpostman.com/view/18988925/UVeNni36#intro

Any sugestions?

**Comment by AlvaroBrasilia** [comment]
Baileys is not an API, Baileys is a "tool" to create your own API.

If you want to use or create an API based on Baileys I suggest you take a look at https://github.com/salman0ansari/whatsapp-api-nodejs or many others available.
