### ISSUE TITLE
Sessions getting closed by itself.

### ISSUE THREAD

**Issue by aarvee022** [WhiskeySockets/Baileys#343]
Sessions are getting closed by itself. needs to scan again and again. getting this issue for last few days.

Please help

**Comment by neoxr** [comment]
sama issue

**Comment by ChocoPie02** [comment]
Still got same issue, always re connect on next day

**Comment by rayidetriawan** [comment]
sama issue

**Comment by weershft** [comment]
I'm having a problem because the connection only lasts a maximum of about 4 days, and then closes again.

**Comment by otirbnaej** [comment]
Same

**Comment by weershft** [comment]
does any one have a solution for it?
