### ISSUE TITLE
[BUG] message.upsert events stop

### ISSUE THREAD

**Issue by nrbrttth** [WhiskeySockets/Baileys#35]
Hello all!

**Describe the bug**
I'm facing a problem when starting a process, connecting some phone numbers through QR code, everything's working fine, I can send messages, receive upsert events.
But after some time (4-5 hours) the socket stops receiving the upsert events. I can still connect/disconnect, but the message upsert events won't come.

**To Reproduce**
1. Created some new connection
2. Wait for some time (mostly 4-5 hours)
3. Message events won't come, though there are active conversations

**Expected behavior**
The message events shouldn't stop, or if there's any problem with the socket, there should be an error message.

**Environment:**
 - Express.js server running 5-6 socket connections (later we want more)
 - My `connectOptions`:
```
const browser = Browsers.appropriate('Desktop');
const socket = makeWASocket({
  logger: this.logger, // pino logger with level 'error'
  syncFullHistory: false,
  shouldSyncHistoryMessage: () => false,
  auth: { // custom MySQL auth state
    creds: state?.creds,
    keys: state?.keys,
  },
  browser: browser
});
```
 - No proxy used

Any help would be welcome!

**Comment by mrfzvx12** [comment]
same issue

**Comment by Laxeder** [comment]
up +'

**Comment by Laxeder** [comment]
I'm facing the same problem. I also use a custom authentication method (fork of useMultiFileAuthState | redis db).

I'm considering this to be the problem and also the use of poll messages, I use it as a substitute for interactive messages, decrypting each poll message update.

Did you find a solution for this problem?

**Comment by sultanlive** [comment]
Did you find the reason? I have the same problem

**Comment by DeveloperNewton** [comment]
Add this option in makeWASocket:

```
makeWASocket({
   ...,
   defaultQueryTimeoutMs: undefined // add this
})
```

**Comment by Auties00** [comment]
Tracking issue in https://github.com/WhiskeySockets/Baileys/issues/34
