### ISSUE TITLE
[BUG] stream errored out code 503

### ISSUE THREAD

**Issue by frmauro** [WhiskeySockets/Baileys#350]
The application is randomly receiving a stream error with code 503

node: {
   "tag": "stream:error",
   "attrs": {
       "code": "503"
   }
 }

"name": "@whiskeysockets/baileys",
"version": "6.3.1",

**Comment by ORMiK0** [comment]
503 - whatsapp has banned your number for policy violations

**Comment by Riders004** [comment]
> 503 - whatsapp has banned your number for policy violations

I got unbanned it

**Comment by hugoafj** [comment]
> 503 - whatsapp has banned your number for policy violations

this was not true right?

**Comment by bautiliendo** [comment]
Did you guys find a solution? I'm getting this error after being active with the QR for about 30 minutes:


{"tag":"stream:error","attrs":{"code":"503"}},"msg":"stream errored out"}

and  "503 – WhatsApp has banned your number for policy violations."

That is not correct. I can reconnect manually without any problem.
