### ISSUE TITLE
How to....

### ISSUE THREAD

**Issue by JunaGanz** [WhiskeySockets/Baileys#355]
![Screenshot_2023_0828_213535](https://github.com/WhiskeySockets/Baileys/assets/93413322/b46c9cc5-2a0a-4b71-80a4-ae083f8e419e)
 
How? can someone tell me how to send pollMessage with quoted message?

I'll try like this
```
sock.sendMessage(jid, { poll: { name: "this is poll message", values: ["yep!","nope"] }}, { quoted: quotedMessage })
```
But the quoted don't appear!1
Is the code that I used wrong?

And onemore question! How to send quick video message?

**Comment by SheIITear** [comment]
Don't make issues for how to questions.
