### ISSUE TITLE
[BUG] Update Profile Name

### ISSUE THREAD

**Issue by moskoweb** [WhiskeySockets/Baileys#36]
**Describe the bug**
When trying to change the profile name, it returns the following error:
```json
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "myAppStateKey (\"AAAAALVm\") not present"
}
```

**To Reproduce**
1. Created a new connection
2. Use ```instance.socket?.updateProfileName("New Name")```

**Comment by andresayac** [comment]
I have not been able to recreate in two whatsapp accounts each one different business and normal

Whatsapp BUSSINES
![image](https://user-images.githubusercontent.com/16548795/235355696-42c926ba-6d46-4875-91a6-492b1ab21fe1.png)

Whatsapp Not Bussines
![image](https://user-images.githubusercontent.com/16548795/235355708-26f297c1-9233-405b-aa26-18fc8b5c08ea.png)




![image](https://user-images.githubusercontent.com/16548795/235355747-7f504407-181e-41c2-8ef5-76a252fad106.png)

**Comment by w3nder** [comment]
It's working normally here too.

**Comment by edgardmessias** [comment]
Please, reopen if this still happening

**Comment by danilo-pimentel** [comment]
> **Describe the bug** When trying to change the profile name, it returns the following error:
> 
> ```json
> {
>     "statusCode": 404,
>     "error": "Not Found",
>     "message": "myAppStateKey (\"AAAAALVm\") not present"
> }
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Created a new connection
> 2. Use `instance.socket?.updateProfileName("New Name")`

Same issue for me:

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": [
            "Error updating profile name",
            "Error: myAppStateKey (\"AAAAAKNl\") not present"
        ]
    }
}

**Comment by DRIMOL** [comment]
Acontece comigo tambem 

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": [
            "Error updating profile name",
            "Error: myAppStateKey (\"AAAAADoC\") not present"
        ]
    }
}

**Comment by stactus** [comment]
I had problems here too, apparently it's **only on WhatsApp Business**, on Messenger it updates normally.

See the return below:

```
{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": [
            "Error updating profile name",
            "Error: myAppStateKey (\"AAAAAGdq\") not present"
        ]
    }
}
```
