### ISSUE TITLE
[BUG]It doesn't work when entering the pairing code on WhatsApp 

### ISSUE THREAD

**Issue by ArrDev10** [WhiskeySockets/Baileys#361]
Has the code for connecting to WhatsApp using the pairing code changed? Because I created this code when the new pairing code was released, please let me know, friend.
![Screenshot_20230901-162123](https://github.com/WhiskeySockets/Baileys/assets/83260062/45fdbecf-2149-4dfc-857e-ccbb33e3df86)
![Screenshot_20230901-160047](https://github.com/WhiskeySockets/Baileys/assets/83260062/f519d6ba-7df4-4319-bc2c-03667d0e0e46)

**Comment by Fokusdotid** [comment]
Gw work" aja tuh

**Comment by Nexov25** [comment]
> Has the code for connecting to WhatsApp using the pairing code changed? Because I created this code when the new pairing code was released, please let me know, friend. ![Screenshot_20230901-162123](https://user-images.githubusercontent.com/83260062/264973207-45fdbecf-2149-4dfc-857e-ccbb33e3df86.png) ![Screenshot_20230901-160047](https://user-images.githubusercontent.com/83260062/264973234-f519d6ba-7df4-4319-bc2c-03667d0e0e46.png)

coba pake config ini Coy : browser: ['Chrome (Linux)', '', ''],

**Comment by Nexov25** [comment]
> Gw work" aja tuh

Ada yang ngaco paling di kodingan nya

**Comment by ArrDev10** [comment]
> Gw kerja" aja tuh

Gak kan kemaren bisa tapi setelah update 6.41 gak bisa, apakah codingan nya berubah?

**Comment by ArrDev10** [comment]
> > Apakah kode untuk menghubungkan ke WhatsApp menggunakan kode penyandingan telah berubah? Karena kode ini saya buat ketika kode pairing baru dirilis, mohon infonya ya sob.![Tangkapan Layar_20230901-162123](https://user-images.githubusercontent.com/83260062/264973207-45fdbecf-2149-4dfc-857e-ccbb33e3df86.png) ![Tangkapan Layar_20230901-160047](https://user-images.githubusercontent.com/83260062/264973234-f519d6ba-7df4-4319-bc2c-03667d0e0e46.png)
> 
> coba pake config ini Coy : browser: ['Chrome (Linux)', '', ''],

Ntar tak coba dh

**Comment by ArrDev10** [comment]
> coba pake config ini Coy : browser: ['Chrome (Linux)', '', ''],

Oke masalah ini sudah terselesaikan,, penyebab nya ada di confirm browser

**Comment by Nexov25** [comment]
> > coba pake config ini Coy : browser: ['Chrome (Linux)', '', ''],
> 
> Oke masalah ini sudah terselesaikan,, penyebab nya ada di confirm browser

Ciee, Seneng masalah nya udah kelar

**Comment by abclimadasar** [comment]
Bang bagi sc bang

**Comment by rangga-teresa** [comment]
@abclimadasar https://whatsapp.com/channel/0029VaRylBH9mrGlQNm8iN0U
