### ISSUE TITLE
[BUG] (node:42215) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit 

### ISSUE THREAD

**Issue by olalonde** [WhiskeySockets/Baileys#365]
**Describe the bug**

Seeing this in console after calling `makeWASocket()`
```
(node:42215) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at TLSSocket.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:904:35)
    at TLSSocket._wrapHandle (node:_tls_wrap:674:8)
    at TLSSocket.reinitializeHandle (node:_tls_wrap:683:22)
    at internalConnectMultiple (node:net:1123:30)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by Guilherme-j10** [comment]
this error is from nodejs possibly your code has some while, setInterval or even a setTimeOut or some recursive function is not a Baileys problem directly. It would be better if you published the code along with the issue to make it easier to help

**Comment by olalonde** [comment]
It's a problem with Baileys library. I'm just running the example code from the repo. Baileys needs to `. setMaxListeners` on the websocket to avoid this warning.

**Comment by SheIITear** [comment]
Youre creating too many listeners
