### ISSUE TITLE
Support chatModify setting "Admin needs to approve new participants"

### ISSUE THREAD

**Issue by olalonde** [WhiskeySockets/Baileys#370]
An API to toggle this option.

<img width="441" alt="Screenshot 2023-09-05 at 11 30 21 PM" src="https://github.com/WhiskeySockets/Baileys/assets/416585/54386bc2-d1b9-4b72-bbaf-6e77fcacbd17">

**Comment by Riders004** [comment]
> An API to toggle this option.
> 
> <img alt="Screenshot 2023-09-05 at 11 30 21 PM" width="441" src="https://user-images.githubusercontent.com/416585/265750415-54386bc2-d1b9-4b72-bbaf-6e77fcacbd17.png">

Check the readme file ita there

**Comment by olalonde** [comment]
If you mean `sock.groupRequestParticipantsUpdate`, that's not what I am looking for. This is for a group that is to approve new participants as far as I know where as I'm looking for the API to change a group setting to "approve new participants" = "on".

**Comment by Riders004** [comment]
const response = await sock.groupRequestParticipantsUpdate(
    "abcd-xyz@g.us", // id group,
    ["abcd@s.whatsapp.net", "efgh@s.whatsapp.net"],
    "approve" // replace this parameter with "reject" 
)
console.log(response)







Try this

**Comment by olalonde** [comment]
Isn't this to approve new participants?

**Comment by Riders004** [comment]
> Isn't this to approve new participants?

Yes but bot need admin

**Comment by olalonde** [comment]
Ok but that's not what I'm trying to do. I'm trying to change a group setting.

**Comment by Riders004** [comment]
> Ok but that's not what I'm trying to do. I'm trying to change a group setting.

Change it
