### ISSUE TITLE
[BUG] getLastMessageInChat is not defined

### ISSUE THREAD

**Issue by RavensVenix** [WhiskeySockets/Baileys#373]
I took this code in README.md
and tried it then got an error:

getLastMessageInChat is not defined

const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
await sock.chatModify({
  delete: true,
  lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
},
'123456@s.whatsapp.net')

**Comment by SheIITear** [comment]
Its not supposed to exist. Not a bug.
