### ISSUE TITLE
[BUG] socket.groupParticipantsUpdate fails silently

### ISSUE THREAD

**Issue by olalonde** [WhiskeySockets/Baileys#375]
**Describe the bug**
When you try to add a participant to a group that the participant has left recently, it's not possible to add back the participant.

<img width="577" alt="Screenshot 2023-09-09 at 2 19 07 PM" src="https://github.com/WhiskeySockets/Baileys/assets/416585/dceea931-c1cd-489a-a285-810b9cb9484a">

When this happens, the call to `socket.groupParticipantsUpdate` appears to succeed when it does not. It would be better if an error was thrown.

**To Reproduce**
1. Created a group and add Alice
2. Alice leaves group
3. Try adding Alice back to group

**Expected behavior**
An error should be thrown.

**Comment by aliazhar-id** [comment]
![image](https://github.com/WhiskeySockets/Baileys/assets/58647884/dcffcafd-79c7-4e0d-a48f-1c981f69a527)

mine works;

P.S: "Oops!, @Ali Azhar | Me has left this group recently !" the translate

**Comment by olalonde** [comment]
@aliazhar-id You used an "invite link" which is not affected by this limitation. See https://faq.whatsapp.com/420332980275753

**Comment by olalonde** [comment]
Ah, did you mean that your call to `socket.groupParticipantsUpdate` is throwing an error?

**Comment by olalonde** [comment]
Ah I see, it returns a result object instead of throwing. https://github.com/WhiskeySockets/Baileys/blob/cd8542ff7c072b5e58d2d3de2396983a5304e5e1/src/Socket/groups.ts#L195

**Comment by aliazhar-id** [comment]
> @aliazhar-id You used an "invite link" which is not affected by this limitation. See https://faq.whatsapp.com/420332980275753

Ahh, I shouldn't have capture that last one.

when using a bot it cannot be added and returns an error. "left recently"
the last one I joined manually using the invite link

**Comment by aliazhar-id** [comment]
> Ah, did you mean that your call to `socket.groupParticipantsUpdate` is throwing an error?

yes
