### ISSUE TITLE
how to know what user voted in pollMessage 

### ISSUE THREAD

**Issue by JunaGanz** [WhiskeySockets/Baileys#38]
How? Anyone explain this to me pls!?

**Comment by andresayac** [comment]
I use this, the important thing is how it is in the example, having the getMessage function defined
Then from the message.update event set your logic

https://github.com/WhiskeySockets/Baileys/blob/master/Example/example.ts
![image](https://user-images.githubusercontent.com/16548795/235354604-10dafa76-3953-453a-9c21-dfab626ba313.png)

**Comment by JunaGanz** [comment]
Thanks

> I use this, the important thing is how it is in the example, having the getMessage function defined Then from the message.update event set your logic
> 
> https://github.com/WhiskeySockets/Baileys/blob/master/Example/example.ts ![image](https://user-images.githubusercontent.com/16548795/235354604-10dafa76-3953-453a-9c21-dfab626ba313.png)

Thanks
