### ISSUE TITLE
how to make Baileys return  when there are bots in our group, then bots other than our bot don't wor

### ISSUE THREAD

**Issue by ArrDev10** [WhiskeySockets/Baileys#382]
![Uploading Screenshot_20230914-151240~2.png…]()

**Comment by FERDIZ-afk** [comment]
There is no image data that you uploaded

**Comment by ArrDev10** [comment]
> There is no image data that you uploaded

![Screenshot_20230914-151240~2](https://github.com/WhiskeySockets/Baileys/assets/83260062/b439a5e8-6d9f-46a3-ae77-8a4c12d7a1c0)
