### ISSUE TITLE
[BUG] failed to sync state from version

### ISSUE THREAD

**Issue by HeaveNsHzj** [WhiskeySockets/Baileys#383]
**Describe the bug**
When delete message for me in "web.whatsapp.com"

**To Reproduce**
1. yarn example
2. scan qrcode in terminal to login
3. "control + c" to kill the process and restart by "yarn example"
2. open "web.whatsapp.com" in browser,  and action "delete message for me"
3. error show in terminal  

**Expected behavior**
no error and receive an "messages.delete" event

**Error Log**
{"level":30,"time":"2023-09-14T09:29:19.543Z","pid":15428,"hostname":"BIH-L-4934.local","name":"regular_high","error":"Error: failed to find key \"AAAAADQw\" to decode mutation\n    at getKey (/Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:192:19)\n    at async decodeSyncdMutations (/Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:161:21)\n    at async decodeSyncdPatch (/Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:212:20)\n    at async decodePatches (/Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:320:30)\n    at async /Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:394:70\n    at async Object.transaction (/Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)\n    at async /Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:330:9\n    at async /Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:105:36\n    at async processNotification (/Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/messages-recv.js:265:21)\n    at async /Users/huangzhongjian/whatsapp/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/messages-recv.js:511:29","msg":"failed to sync state from version"}

**Comment by HeaveNsHzj** [comment]
node version: v18.12.1

**Comment by Auties00** [comment]
This error usually happens when your connection is already dead, please make sure that your local environment is configured correctly. If the issue persists, open another one providing your full code
