### ISSUE TITLE
[REQUEST] Intractive message

### ISSUE THREAD

**Issue by ArrDev10** [WhiskeySockets/Baileys#389]
in baileys can make a intractive message using WhatsApp business like this
![Screenshot_20230918-121859](https://github.com/WhiskeySockets/Baileys/assets/83260062/08982bf2-d0a4-484c-9c4f-8452310970a5)

**Comment by salykingleb** [comment]
What do you mean?

**Comment by xirf** [comment]
This feature already requested at #384 yet, it's still no follow up.

**Comment by ArrDev10** [comment]
Then
