### ISSUE TITLE
[BUG] Connection Closed when sending message to groups 

### ISSUE THREAD

**Issue by luispimenta** [WhiskeySockets/Baileys#394]
When trying to send any messages to groups, the request takes a long time and returns this error. how can i resolve this?

`"err":{"type":"Error","message":"Connection Closed","stack":"Error: Connection Closed\n    at sendRawMessage (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19)\n    at sendNode (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16)\n    at query (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:137:15)\n    at groupQuery (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:12:55)\n    at Object.groupMetadata (/var/app/current/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:30)\n    at jidExists (/var/app/current/dist/wa.js:251:41)\n    at send (/var/app/current/dist/controllers/message.js:37:49)\n    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/app/current/node_modules/express/lib/router/route.js:144:13)\n    at validate (/var/app/current/dist/middlewares/session-validator.js:7:5)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Closed"},"headers":{}}},"msg":"An error occured during message send Error: Connection Closed"}`

I have tried `defaultQueryTimeoutMs: undefined` and `defaultQueryTimeoutMs: 0`

but nothing worked

everything was ok since yesterday, and it stopped without any updates or any adjustments

my makeWASocket

```
const socket = makeWASocket({
    printQRInTerminal: true,
    browser: Browsers.ubuntu('Chrome'),
    generateHighQualityLinkPreview: true,
    ...socketConfig,
    auth: {
      creds: state.creds,
      keys: makeCacheableSignalKeyStore(state.keys, logger),
    },
    logger,
    defaultQueryTimeoutMs: 0,
    shouldIgnoreJid: (jid) => isJidBroadcast(jid),
    getMessage: async (key) => {
      const data = await prisma.message.findFirst({
        where: { remoteJid: key.remoteJid!, id: key.id!, sessionId },
      });
      return (data?.message || undefined) as proto.IMessage | undefined;
    },
  });

```

**Comment by Guru322** [comment]
`defaultQueryTimeoutMs: 0` solved it for me

**Comment by luispimenta** [comment]
@Guru322 What's your version of Baileys?

How is your makeWASocket?

can you help me?

**Comment by Guru322** [comment]
> @Guru322 What's your version of Baileys?
> 
> How is your makeWASocket?
> 
> can you help me?
  
Using the latest version of Baileys

 ```SH
const connectionOptions = {
    printQRInTerminal: !pairingCode, 
    mobile: useMobile,
    msgRetryCounterMap,
    logger: Pino({
        level: 'fatal'
    }),
    auth: {
        creds: authState.state.creds,
        keys: makeCacheableSignalKeyStore(authState.state.keys, Pino().child({
            level: 'fatal',
            stream: 'store'
        })),
    },
    browser: ['Chrome (Linux)', '', ''],
    version,
    getMessage: async (key) => {
        let jid = jidNormalizedUser(key.remoteJid)
        let msg = await store.loadMessage(jid, key.id)
        return msg?.message || ""
    },
    msgRetryCounterCache,
    connectTimeoutMs: 60000,
    defaultQueryTimeoutMs: 0,
    keepAliveIntervalMs: 10000,
    emitOwnEvents: true,
    fireInitQueries: true,
    generateHighQualityLinkPreview: true,
    syncFullHistory: true,
    markOnlineOnConnect: true
};
global.conn = makeWASocket(connectionOptions);
 ```

**Comment by luispimenta** [comment]
@Guru322 thanks, but it still didn't work, very strange

Does not send messages in small groups, nor in large ones

It's strange that locally it works, but online in an AWS instance it doesn't work, could this be related?

**Comment by Guru322** [comment]
> @Guru322 thanks, but it still didn't work, very strange
> 
> Does not send messages in small groups, nor in large ones
> 
> It's strange that locally it works, but online in an AWS instance it doesn't work, could this be related?

ya boss it works fine in local but gives issue in cloud, i tried on heroku it's giving the same error

**Comment by luispimenta** [comment]
Any idea what it could be?

Or do you know of any cloud that is ok?

**Comment by Guru322** [comment]
> @Guru322
> 
> Any idea what it could be?
> 
> Or do you know of any cloud that is ok?

Boss checkout this docs:-
[Useful Docs](https://github.com/ArrDev10/WaBot-With-PairingCode)
I referred to this and it worked,
I observed it on replit for 2 hours, not giving the error
Will update this comment after trying on heroku

**Comment by Guru322** [comment]
> > @Guru322
> > Any idea what it could be?
> > Or do you know of any cloud that is ok?
> 
> Boss checkout this docs:- [Useful Docs](https://github.com/ArrDev10/WaBot-With-PairingCode) I referred to this and it worked, I observed it on replit for 2 hours, not giving the error Edit: Tested on Heroku all fine>,<

![Screenshot_2023-09-23-11-22-02-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/WhiskeySockets/Baileys/assets/106463398/59d66c0c-b416-46e0-b29e-5f67503e7e94)

Working smooth

**Comment by luispimenta** [comment]
@Guru322 Thank you very much, I will test this, thanks for the support

**Comment by Guru322** [comment]
> @Guru322 Thank you very much, I will test this, thanks for the support

Welcome

**Comment by weershft** [comment]
@luispimenta esta a funcionar bem com a alteração?

**Comment by luispimenta** [comment]
> @luispimenta esta a funcionar bem com a alteração?

Sim, uma coisa que também estava prejudicando, eu chamava sempre o sendpresenceupdate enviando composing antes de enviar a mensagem, para mostrar que o usuario estava digitando, removi isso e nunca mais deu problema

**Comment by CodexRaunak** [comment]
> `defaultQueryTimeoutMs: 0` solved it for me

Thanks it worked for me tooo!.
