### ISSUE TITLE
[BUG] failed in yarn install inside a docker container

### ISSUE THREAD

**Issue by mikilanz** [WhiskeySockets/Baileys#396]
![image](https://github.com/WhiskeySockets/Baileys/assets/35862932/839cc285-4383-4db2-bc7e-97f4dc6afc29)

[dependencies 2/6] RUN yarn install --production:
0.907 yarn install v1.22.19
1.056 [1/4] Resolving packages...
1.772 [2/4] Fetching packages...
9.201 error Command failed.
9.201 Exit code: 128
9.201 Arguments: ls-remote --tags --heads ssh://git@github.com/adiwajshing/libsignal-node.git
9.201 Directory: /usr/src/app
9.201 Output:
9.201 Host key verification failed.
9.201 fatal: Could not read from remote repository.
9.201
9.201 Please make sure you have the correct access rights
9.201 and the repository exists.
9.201 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

for information I'm using image from node:alpine3.18 & in package json 
 "@whiskeysockets/baileys": "6.4.0"

**Comment by Riders004** [comment]
> ![image](https://user-images.githubusercontent.com/35862932/269824135-839cc285-4383-4db2-bc7e-97f4dc6afc29.png)
> 
> [dependencies 2/6] RUN yarn install --production: 0.907 yarn install v1.22.19 1.056 [1/4] Resolving packages... 1.772 [2/4] Fetching packages... 9.201 error Command failed. 9.201 Exit code: 128 9.201 Arguments: ls-remote --tags --heads ssh://[git@github.com](mailto:git@github.com)/adiwajshing/libsignal-node.git 9.201 Directory: /usr/src/app 9.201 Output: 9.201 Host key verification failed. 9.201 fatal: Could not read from remote repository. 9.201 9.201 Please make sure you have the correct access rights 9.201 and the repository exists. 9.201 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> for information I'm using image from node:alpine3.18 & in package json "@whiskeysockets/baileys": "6.4.0"

Can you share me your docker image File ?

**Comment by mikilanz** [comment]
already solve it. this is my dockerfile

```
FROM node:alpine3.18 AS base

WORKDIR /usr/src/app
COPY [ "nest-cli.json", "package.json", "tsconfig.build.json", "tsconfig.json", "yarn.lock", "./"]
COPY ./src ./src
RUN apk add --no-cache git openssh

#==== Dependencies ====
FROM base AS dependencies

# RUN apk add --no-cache git openssh-keygen
# RUN yarn install --production
# RUN yarn add @nestjs/cli@9.0.0
# RUN yarn add @nestjs/schematics@9.0.0
# RUN yarn build

RUN npm install --legacy-peer-deps --only=production
RUN npm install --legacy-peer-deps @nestjs/cli@9.0.0
RUN npm install --legacy-peer-deps @nestjs/schematics@9.0.0
RUN npm run build
RUN cp -R node_modules prod_node_modules


#==== Release ====
FROM base AS release

COPY --from=dependencies ./usr/src/app/prod_node_modules ./node_modules
COPY --from=dependencies ./usr/src/app/dist ./dist
ENV TZ="Asia/Jakarta"

EXPOSE 80

CMD ["node", "dist/main.js"]
```

**Comment by Riders004** [comment]
Ok then

**Comment by Zain-ul-din** [comment]
not working for me any idea how to fix it?

```Dockerfile
FROM node:20-alpine

RUN apk add --no-cache git openssh openssh-keygen 

RUN mkdir -p /root/.ssh
RUN ssh-keyscan -H github.com >> ~/.ssh/known_hosts

WORKDIR /usr/src/app

COPY package*.json ./
COPY yarn.lock ./
COPY tsconfig.json ./

RUN yarn install --production

COPY src ./
COPY static ./

EXPOSE 3000

CMD ["npx", "yarn", "dev"]
```
