### ISSUE TITLE
Interactive message work?

### ISSUE THREAD

**Issue by ArrDev10** [WhiskeySockets/Baileys#398]
I found this in my groups, does it work at Baileys, I asked the person, it's not the official WA Api 
![Screenshot_20230923-184021](https://github.com/WhiskeySockets/Baileys/assets/83260062/c4e29acb-e8b9-4a0c-a37a-a007b3678b0b)

**Comment by Riders004** [comment]
Buttons working?

**Comment by ArrDev10** [comment]
> Buttons working?

I don't know what WA API library he uses

**Comment by abclimadasar** [comment]
Lies

**Comment by Riders004** [comment]
> Lies

Who

**Comment by Riders004** [comment]
> > Buttons working?
> 
> I don't know what WA API library he uses

Ok thanks sir

**Comment by Guru322** [comment]
This is intresting

**Comment by ArrDev10** [comment]
> This is interesting

(Rumor) after I asked the bot owner, it turns out he uses baileys, but in a different repository, https://github.com/RullDev/BailysV2

**Comment by ArrDev10** [comment]
> Lies

I don't know, but I could try

**Comment by Guru322** [comment]
> > This is interesting
> 
> (Rumor) after I asked the bot owner, it turns out he uses baileys, but in a different repository, https://github.com/RullDev/BailysV2

le me try>.<

**Comment by Riders004** [comment]
> > This is interesting
> 
> (Rumor) after I asked the bot owner, it turns out he uses baileys, but in a different repository, https://github.com/RullDev/BailysV2

In that Baileys there no option for Pairing code system

**Comment by Riders004** [comment]
> > > This is interesting
> > 
> > 
> > (Rumor) after I asked the bot owner, it turns out he uses baileys, but in a different repository, https://github.com/RullDev/BailysV2
> 
> In that Baileys there no option for Pairing code system

@Guru322

**Comment by Guru322** [comment]
> > Lies
> 
> I don't know, but I could try

tried it not working🤐

**Comment by ArrDev10** [comment]
> > > Lies
> > 
> > 
> > I don't know, but I could try
> 
> tried it not working🤐

🥲

**Comment by SheIITear** [comment]
No.

**Comment by Kasanstore7** [comment]
hoaks

**Comment by YanzBotz** [comment]
is that real

**Comment by handoko19** [comment]
xD

**Comment by JLENF** [comment]
buttons is working in https://github.com/WhiskeySockets/Baileys
im tested with https://github.com/salman0ansari/whatsapp-api-nodejs

**Comment by Riders004** [comment]
> buttons is working in https://github.com/WhiskeySockets/Baileys im tested with https://github.com/salman0ansari/whatsapp-api-nodejs

I Think You have Beta Version of WhatsApp of Business Or Messenger

**Comment by Riders004** [comment]
> buttons is working in https://github.com/WhiskeySockets/Baileys im tested with https://github.com/salman0ansari/whatsapp-api-nodejs

Can you share me your buttons code

**Comment by JLENF** [comment]
Hi,

[root@whatsbot-gpt]# curl --location 'localhost:3333/message/button?key=ea75f8af-2d46-494d-9e83-ca9ae6603db5' --header                                                   'Content-Type: application/json' --data '{
    "id": "5547xxxxxxxx",
    "btndata": {
        "text": "Confirm",
        "buttons": [
            {
                "type": "replyButton",
                "title": "Confirm"
            }
        ],
        "footerText": "Please confirm."
    }
}'

**Comment by ArrDev10** [comment]
> buttons is working in https://github.com/WhiskeySockets/Baileys im tested with https://github.com/salman0ansari/whatsapp-api-nodejs

Where does proof button work?

**Comment by JLENF** [comment]
> Where does proof button work?

<img width="1415" alt="Captura de Tela 2023-09-26 às 14 35 08" src="https://github.com/WhiskeySockets/Baileys/assets/3689234/32ceb728-ece1-443e-a968-c30ad589f6ba">

<img width="1418" alt="Captura de Tela 2023-09-26 às 14 34 51" src="https://github.com/WhiskeySockets/Baileys/assets/3689234/f3b48d7d-8a14-4eef-8b02-be35d45a3af9">

![IMG_5762](https://github.com/WhiskeySockets/Baileys/assets/3689234/72b41cb7-ac04-4ef7-abdf-4ffd1f4ef676)

**Comment by JLENF** [comment]
![WhatsApp Image 2023-09-26 at 14 50 18](https://github.com/WhiskeySockets/Baileys/assets/3689234/98b68cbb-3d6d-4b68-b75a-9e2e9e4c8384)

**Comment by Guru322** [comment]
waku waku

**Comment by Riders004** [comment]
> > Where does proof button work?
> 
> <img alt="Captura de Tela 2023-09-26 às 14 35 08" width="1415" src="https://user-images.githubusercontent.com/3689234/270747127-32ceb728-ece1-443e-a968-c30ad589f6ba.png"> <img alt="Captura de Tela 2023-09-26 às 14 34 51" width="1418" src="https://user-images.githubusercontent.com/3689234/270747436-f3b48d7d-8a14-4eef-8b02-be35d45a3af9.png">
> ![IMG_5762](https://user-images.githubusercontent.com/3689234/270747599-72b41cb7-ac04-4ef7-abdf-4ffd1f4ef676.jpg)

Share your buttons code

**Comment by JLENF** [comment]
> Compartilhe o código dos seus botões

Now I understand that there is a difference between button and reply message.
Iam using reply buttons.

**Comment by Ghost7798** [comment]
> > Where does proof button work?
> 
> <img alt="Captura de Tela 2023-09-26 às 14 35 08" width="1415" src="https://user-images.githubusercontent.com/3689234/270747127-32ceb728-ece1-443e-a968-c30ad589f6ba.png"> <img alt="Captura de Tela 2023-09-26 às 14 34 51" width="1418" src="https://user-images.githubusercontent.com/3689234/270747436-f3b48d7d-8a14-4eef-8b02-be35d45a3af9.png">
> ![IMG_5762](https://user-images.githubusercontent.com/3689234/270747599-72b41cb7-ac04-4ef7-abdf-4ffd1f4ef676.jpg)

Can I get bot script

**Comment by ahmadkeren** [comment]
> > This is interesting
> 
> (Rumor) after I asked the bot owner, it turns out he uses baileys, but in a different repository, https://github.com/RullDev/BailysV2

already try but not working.. (udah dicoba tapi gak bisa)

**Comment by IgorDePaula** [comment]
Remove button from docs, please.
