### ISSUE TITLE
Calls support

### ISSUE THREAD

**Issue by billantony** [WhiskeySockets/Baileys#40]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

I am interested in handling incoming voice calls on WhatsApp programmatically.

Receive incoming WhatsApp calls
Answer the call
Receive streaming data and send data back simultaneously in a bidirectional connection
End the call

**Comment by erickythierry** [comment]
up

**Comment by Guilherme-j10** [comment]
up

**Comment by Auties00** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> I am interested in handling incoming voice calls on WhatsApp programmatically.
> 
> Receive incoming WhatsApp calls Answer the call Receive streaming data and send data back simultaneously in a bidirectional connection End the call

you can't do that currently, we are working on it

**Comment by Auties00** [comment]
> I have  noticed that sending voice call is possible to implement. But what to do next i do not understand
> 
> `{
>   "tag": "call",
>   "attrs": {
>     "to": {
>       "_jid": { "type": 1, "user": "1234567890", "device": 0, "domainType": 0 }
>     },
>     "id": "5223.12338-39"
>   },
>   "content": [
>     {
>       "tag": "relaylatency",
>       "attrs": {
>         "call-id": "0DDBB7F053B6361A9A0A9F5369F6D5D7",
>         "call-creator": {
>           "_jid": {
>             "type": 1,
>             "user": "1234567890123",
>             "device": 9,
>             "domainType": 0
>           }
>         }
>       },
>       "content": [
>         {
>           "tag": "te",
>           "attrs": { "latency": "33554930" },
>           "content": {
>             "0": 157,
>             "1": 240,
>             "2": 205,
>             "3": 62,
>             "4": 13,
>             "5": 150
>           }
>         },
>         {
>           "tag": "destination",
>           "attrs": {},
>           "content": [
>             {
>               "tag": "to",
>               "attrs": {
>                 "jid": {
>                   "_jid": {
>                     "type": 1,
>                     "user": "1234567890",
>                     "device": 0,
>                     "domainType": 0
>                   }
>                 }
>               },
>               "content": null
>             },
>             {
>               "tag": "to",
>               "attrs": {
>                 "jid": {
>                   "_jid": {
>                     "type": 1,
>                     "user": "1234567890",
>                     "device": 29,
>                     "domainType": 0
>                   }
>                 }
>               },
>               "content": null
>             }
>           ]
>         }
>       ]
>     }
>   ]
> }`
> 

as i said it's possible, but it still needs to be implemented as it's a very complex issue

**Comment by edgardmessias** [comment]
There are two parts to work with calls: the websocket commands and the WebRTC connection.

I am able to understand how to offer or accept a call, but the WebRTC connection is the problem.

They use a full customized version of [pjsip](https://www.pjsip.org/).


The code that I did to offer a call, without connecting: https://github.com/wppconnect-team/wa-js/blob/00abf6bfe42424a3dc126b06bd11e8ba50e1888b/src/call/functions/offer.ts#L70

**Comment by edgardmessias** [comment]
The steps:

* **Socket**: Send a offer call
    * Response: `{rte: <some ip:port>, key: <base64>, relay: {te2:<ip:port>, token}[]}`
* **Nodejs**: Process the response and get the ice/stun servers and token
* **WebRTC**: Send a customized STUN request to make a NAT connection
    * **Custom attribute 0x4000**: Maybe part of token
    * **XOR-RELAYED-ADDRESS**: ip of server
    * **MESSAGE-INTEGRITY**: HMAC-SHA1 of message
* **WebRTC**: Send a customized STUN request to PING
    * **Custom attribute**: 0x4002 or 0x4003
* **Nodejs**: Get the timming of response for each server
* **Socket**: Send a relaylatency with the timming of ping
* **...** to find out yet

**Comment by ripreal** [comment]
@edgardmessias cool. But i did not find in example https://github.com/wppconnect-team/wa-js/blob/00abf6bfe42424a3dc126b06bd11e8ba50e1888b/src/call/functions/offer.ts#L70 proto like this. Are you using it?
        /** Properties of a Call. */
        interface ICall {

            /** Call callKey */
            callKey?: (Uint8Array|null);

            /** Call conversionSource */
            conversionSource?: (string|null);

            /** Call conversionData */
            conversionData?: (Uint8Array|null);

            /** Call conversionDelaySeconds */
            conversionDelaySeconds?: (number|null);
        }

**Comment by clairton** [comment]
+1

**Comment by badereddineqodia** [comment]
+2

**Comment by WeberIT** [comment]
+3

atm i have absolutely no time but ill be in the boat if i can get some free time

**Comment by Pulij** [comment]
> https://github.com/bhavya32/WA-Calls

don't work:(

**Comment by Keito-Klein** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> I am interested in handling incoming voice calls on WhatsApp programmatically.
> 
> Receive incoming WhatsApp calls
> Answer the call
> Receive streaming data and send data back simultaneously in a bidirectional connection
> End the call
> 

I interested too, but i want reject that call when receive incoming Whatsapp call. I've tried various methods but still can't find the function.

**Comment by gamersindo1223** [comment]
is there any update?

**Comment by ahmedRSA** [comment]
any update on this?

**Comment by irux** [comment]
Any new findings on this?

**Comment by erickythierry** [comment]
> Any new findings on this?

There probably won't be anything else coming out about this (at least not here)
since those mainly responsible for this adaptation ended up leaving the project due to legal notice from Meta

**Comment by Pulij** [comment]
> What's new? Any updates on this issue?

No:(

**Comment by erickythierry** [comment]
> What's new? Any updates on this issue?

There is a Brazilian company that managed to make it work (with the help of the current main maintainer of Baileys)
**wavoip**

analyzing part of the public codes of this service, apparently they were based on this repo:

https://github.com/bhavya32/WA-Calls

but they clearly managed to make it work, they saw that it was something highly profitable and preferred to close the code.

and recently the main maintainer of baileys said he will not share this function

So, it's unlikely to see this feature here in the official repo.

**Comment by erickythierry** [comment]
> What's new? Any updates on this issue?

There is a Brazilian company that managed to make it work (with the help of the current main maintainer of Baileys)
**wavoip**

**Comment by billantony** [comment]
You can explore this library
https://github.com/rs-company-project/wavoip-api

**Comment by billantony** [comment]
You can integrate it into Baileys, it works well

**Comment by gamersindo1223** [comment]
> You can integrate it into Baileys, it works well

But looks like it's a service.

**Comment by Guilherme-j10** [comment]
> > You can integrate it into Baileys, it works well
> 
> But looks like it's a service.

yep its a service, and u need pay to use

**Comment by kabaweb** [comment]
Regarding this information, is it possible to replicate it and then leave it in an open project? From what I understand, communication is a point with socket.io to then communicate with asterix?

**Comment by davisvkz** [comment]
i was interessed about this repository: https://github.com/bhavya32/WA-Calls could be an start point

**Comment by erickythierry** [comment]
> i was interessed about that repository: https://github.com/bhavya32/WA-Calls could be an start point

the wavoip-api service came from there.
but they decided not to proceed in an open source way due to commercial interests.

**Comment by Dakauann** [comment]
theres so many people gate keeping this feature, it makes me think about the future of open source...

**Comment by Auties00** [comment]
> theres so many people gate keeping this feature, it makes me think about the future of open source...

It’s just something that will be used 100% to spam people, even if one person does it the whole library could be taken down as a result(you couldn’t even blame Meta at that point). It’s not gatekeeping, it’s keeping up what is already available, mind you for free. If you find someone who has developed it themselves and wants to share it with you, be it for free or for a price, obviously that’s fine, but we won’t publish anything like that.

**Comment by Pulij** [comment]
> okay after some rethinking i have decided to share the implementation with only 2 people
> 
> if you are interested hit me up with an email **note** you have to give me a detailed explanation how will you use the calls for your business
> 
> and of course this will be paid.

I just wanted to make a music bot and sell this feature :(
But I doubt you'd give away such functionality for cheap, especially since I'm from Russia.

**Comment by SheIITear** [comment]
> listen music on internet, usage should be useful for people

There could be legitimate uses, but the cons outweigh the pros. Imagine if it is made public and you wake up every night to automated AI bot trying to scam you.

**Comment by Dakauann** [comment]
well, whatsapp already has a really strict policy about spam messages, i think they would do the same to whatsapp calls

**Comment by Pulij** [comment]
> > > > > listen music on internet, usage should be useful for people
> > > > 
> > > > 
> > > > There could be legitimate uses, but the cons outweigh the pros. Imagine if it is made public and you wake up every night to automated AI bot trying to scam you.
> > > 
> > > 
> > > exactly this type of concern stops me from releasing it to public and i had conversation with my coworkers and they all suggested not to do this because you might or will get a C&D letter from meta and i might destroy my carrier for nothing.
> > 
> > 
> > The Zuck is busy with AI, you’ll just get a cease and desist, nothing more, still I wouldn’t want people to be called at 2AM by a robocall. I think messages are enough
> 
> whatsapp is working on calls anyway for business api if some are really desperate for calls they will wait and opt for official solution, no need to give to spammers.

It's not available in Russia, and it's paid anyway :(
Even a service like https://app.wavoip.com/ is pointless here since there's no way to buy a subscription. I have some peaceful ideas with Wavoip, but I just can't interact with it in any way...

**Comment by AstroX11** [comment]
WOW

**Comment by Dakauann** [comment]
> > > > > > listen music on internet, usage should be useful for people
> > > > > 
> > > > > 
> > > > > There could be legitimate uses, but the cons outweigh the pros. Imagine if it is made public and you wake up every night to automated AI bot trying to scam you.
> > > > 
> > > > 
> > > > exactly this type of concern stops me from releasing it to public and i had conversation with my coworkers and they all suggested not to do this because you might or will get a C&D letter from meta and i might destroy my carrier for nothing.
> > > 
> > > 
> > > The Zuck is busy with AI, you’ll just get a cease and desist, nothing more, still I wouldn’t want people to be called at 2AM by a robocall. I think messages are enough
> > 
> > 
> > whatsapp is working on calls anyway for business api if some are really desperate for calls they will wait and opt for official solution, no need to give to spammers.
> 
> It's not available in Russia, and it's paid anyway :( Even a service like https://app.wavoip.com/ is pointless here since there's no way to buy a subscription. I have some peaceful ideas with Wavoip, but I just can't interact with it in any way...

i have a direct connection with wavoip developers, i could talk to them to help you, contact me if you need something

**Comment by Pulij** [comment]
> > > > > > > listen music on internet, usage should be useful for people
> > > > > > 
> > > > > > 
> > > > > > There could be legitimate uses, but the cons outweigh the pros. Imagine if it is made public and you wake up every night to automated AI bot trying to scam you.
> > > > > 
> > > > > 
> > > > > exactly this type of concern stops me from releasing it to public and i had conversation with my coworkers and they all suggested not to do this because you might or will get a C&D letter from meta and i might destroy my carrier for nothing.
> > > > 
> > > > 
> > > > The Zuck is busy with AI, you’ll just get a cease and desist, nothing more, still I wouldn’t want people to be called at 2AM by a robocall. I think messages are enough
> > > 
> > > 
> > > whatsapp is working on calls anyway for business api if some are really desperate for calls they will wait and opt for official solution, no need to give to spammers.
> > 
> > 
> > It's not available in Russia, and it's paid anyway :( Even a service like https://app.wavoip.com/ is pointless here since there's no way to buy a subscription. I have some peaceful ideas with Wavoip, but I just can't interact with it in any way...
> 
> i have a direct connection with wavoip developers, i could talk to them to help you, contact me if you need something

How can I get in touch with you? (I'm probably one of the only people in Russia working on something like this. I'm 16 years old, and I want to create a service similar to wavoip.com, but specifically for Russia and a few other countries. I also plan to develop a music-focused WhatsApp bot that users can connect to their account with a single command. Right now, I’m working on an API that will enable scalable projects in the future, and I’m looking for people who would be interested in building something like this with me. All my ideas are for peaceful purposes—I don’t want this to be used for spam calls.)

P.s I don’t have the money or the means to purchase the open-source version of your solution, so unfortunately, if you offer something like that, it won’t work for me. :(

However, if you could help me out, I’d be really grateful.

**Comment by Dakauann** [comment]
> > > > > > > > listen music on internet, usage should be useful for people
> > > > > > > 
> > > > > > > 
> > > > > > > There could be legitimate uses, but the cons outweigh the pros. Imagine if it is made public and you wake up every night to automated AI bot trying to scam you.
> > > > > > 
> > > > > > 
> > > > > > exactly this type of concern stops me from releasing it to public and i had conversation with my coworkers and they all suggested not to do this because you might or will get a C&D letter from meta and i might destroy my carrier for nothing.
> > > > > 
> > > > > 
> > > > > The Zuck is busy with AI, you’ll just get a cease and desist, nothing more, still I wouldn’t want people to be called at 2AM by a robocall. I think messages are enough
> > > > 
> > > > 
> > > > whatsapp is working on calls anyway for business api if some are really desperate for calls they will wait and opt for official solution, no need to give to spammers.
> > > 
> > > 
> > > It's not available in Russia, and it's paid anyway :( Even a service like https://app.wavoip.com/ is pointless here since there's no way to buy a subscription. I have some peaceful ideas with Wavoip, but I just can't interact with it in any way...
> > 
> > 
> > i have a direct connection with wavoip developers, i could talk to them to help you, contact me if you need something
> 
> How can I get in touch with you? (I'm probably one of the only people in Russia working on something like this. I'm 16 years old, and I want to create a service similar to wavoip.com, but specifically for Russia and a few other countries. I also plan to develop a music-focused WhatsApp bot that users can connect to their account with a single command. Right now, I’m working on an API that will enable scalable projects in the future, and I’m looking for people who would be interested in building something like this with me. All my ideas are for peaceful purposes—I don’t want this to be used for spam calls.)
> 
> P.s I don’t have the money or the means to purchase the open-source version of your solution, so unfortunately, if you offer something like that, it won’t work for me. :(
> 
> However, if you could help me out, I’d be really grateful.

You can contact me via whatsapp, i will get you in touch with the developer of wavoip, but the service is paid so, you will need to talk to him, there will be charges on their service

**Comment by top-master** [comment]
Seems [Auties00/Cobalt](https://github.com/Auties00/Cobalt) supports starting calls and stopping calls, however, audio and video capture or playback is a task left to anyone interested.

I know that project is for Java, yet knowing how WhatsApp's calls-API works is everything, and a rewrite for Node-JS should be possible.

**Comment by dannywynn** [comment]
> Seems [Auties00/Cobalt](https://github.com/Auties00/Cobalt) supports starting calls and stopping calls, however, audio and video capture or playback is a task left to anyone interested.
> 
> I know that project is for Java, yet knowing how WhatsApp's calls-API works is everything, and a rewrite for Node-JS should be possible.

even baileys and whatsmeow can start calls, the hard part is to transfer audio data

**Comment by ahmedRSA** [comment]
> Seems [Auties00/Cobalt](https://github.com/Auties00/Cobalt) supports starting calls and stopping calls, however, audio and video capture or playback is a task left to anyone interested.
> 
> I know that project is for Java, yet knowing how WhatsApp's calls-API works is everything, and a rewrite for Node-JS should be possible.

it says it only works with mobile api with six parts code can you make call with qr scan ?

**Comment by billantony** [comment]
Has anyone managed to implement the calls? I see libraries that can do it, but I can't see the method they use.
https://github.com/green-api/whatsapp-api-calls-client-js

**Comment by dannywynn** [comment]
> Has anyone managed to implement the calls? I see libraries that can do it, but I can't see the method they use. https://github.com/green-api/whatsapp-api-calls-client-js

the actuall call happen on their relay server, without relay server this package is useless.

**Comment by softov** [comment]
Hi... do you have updates on the topic? 

Now Business support it in api/webrtc... maybe something changed in the current workflow too?

https://developers.facebook.com/documentation/business-messaging/whatsapp/calling/

**Comment by billantony** [comment]
https://github.com/WhiskeySockets/wacrg

**Comment by billantony** [comment]
# WhatsApp Calling for Baileys

Hi everyone!

I've been working on an experimental implementation that adds WhatsApp calling support on top of Baileys.

Repository:
[[call-WhiskeySockets](https://github.com/billantony/call-WhiskeySockets?utm_source=chatgpt.com)](https://github.com/billantony/call-WhiskeySockets)

The goal of this project is to make voice calls easier to integrate with the WhiskeySockets ecosystem.

bug reports, and ideas are all welcome. Thanks for helping improve WhatsApp calling support for the community!   
## 🎯 Complete Example

```javascript
import express from 'express'
import { makeWASocket } from '@whiskeysockets/baileys'
import { WhatsAppCalls } from 'whatsapp-calls-module'

const app = express()
app.use(express.json())
app.use(express.raw({ type: 'application/octet-stream', limit: '50mb' }))

// Create Baileys socket
const sock = makeWASocket({
    printQRInTerminal: true,
    browser: ['Chrome', 'Linux', '3.0']
})

// Wait for connection
sock.ev.on('connection.update', (update) => {
    if (update.connection === 'open') {
        // Initialize calls module
        const calls = new WhatsAppCalls()
        await calls.initialize(sock, app)
        
        // Make available globally
        global.whatsappCalls = calls
    }
})

// Endpoint to start call
app.post('/call/start', async (req, res) => {
    const { phoneNumber, audioSource, durationMs } = req.body
    const callId = await global.whatsappCalls.startCall(phoneNumber, audioSource, durationMs)
    res.json({ error: false, callId })
})

// Endpoint to end call
app.post('/call/end', async (req, res) => {
    const { callId } = req.body
    await global.whatsappCalls.endCall(callId)
    res.json({ error: false, message: 'Call ended' })
})

// Endpoint for microphone audio
app.post('/call/audio/:callId', async (req, res) => {
    global.whatsappCalls.processAudioChunk(req.params.callId, req.body)
    res.json({ error: false, message: 'Audio chunk received' })
})

app.listen(8080)
```
