### ISSUE TITLE
[BUG] connection error when scanning qr code with whiskesocket/baileys type my bot esm module plugins bot

### ISSUE THREAD

**Issue by Aal-oss** [WhiskeySockets/Baileys#405]

**Comment by Aal-oss** [comment]
Here is my code snippet
global.authFolder = storeSys.fixFileName(`${opts._[0] || ''}sessions`)
    let { state, saveCreds } = await useMultiFileAuthState(path.resolve('./sessions'))
    let { version, isLatest } = await fetchLatestBaileysVersion()
    console.log(`using WA v${version.join('.')}, isLatest: ${isLatest}`)
const connectionOptions = {
version,
printQRInTerminal: true,
syncFullHistory: true,
auth: state,
browser: ['AKAZA - MD', 'Safari', '3.1.0'], 
logger: pino({ level: 'silent' }),
patchMessageBeforeSending: (message) => {
const requiresPatch = !!(
message.buttonsMessage 
|| message.templateMessage
|| message.listMessage
);
if (requiresPatch) {
message = {
viewOnceMessage: {
message: {
messageContextInfo: {
deviceListMetadataVersion: 2,
deviceListMetadata: {},
},
...message,
},
},
};
}
return message;
},
}
global.conn = makeWASocket(connectionOptions)
conn.isInit = false


async function connectionUpdate(update) {
  const { connection, lastDisconnect, isNewLogin } = update
   if (connection == 'connecting') console.log(chalk.yellowBright('Tunggu Sebentar...'))
   if (connection == 'open') {
      console.log(chalk.green('Tersambung'))
      conn.sendMessage(`${global.nomorown}@s.whatsapp.net`, {text: `Bot Online!\n\nVersion: 2.23.9.76, WhatsApp, isLatest: true\n\nServer:\nIndonesia\n\nKode:\n62` }) // Connection Update
  }
  if (connection == 'close') console.log(chalk.red('Koneksi Terputus!'))
  if (isNewLogin) conn.isInit = true
  if (lastDisconnect && lastDisconnect.error && lastDisconnect.error.output && lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut && conn.ws.readyState !== WebSocket.CONNECTING) {
    console.log(reloadHandler(true))
    timestamp.connect = new Date
  }
  if (db.data == null) await loadDatabase()
  console.log(JSON.stringify(update, null, 4))
  if (update.receivedPendingNotifications) conn.sendMessage(`${global.nomorown}@s.whatsapp.net`, {text: 'Akazabotz md berhasil tersambung dengan baik' }) //Akazamd
}

process.on('uncaughtException', console.error)
// let strQuot = /(["'])(?:(?=(\\?))\2.)*?\1/

**Comment by FERDIZ-afk** [comment]
Browser nya coba ganti

browser: ["Chrome (Linux)", "", ""]

**Comment by Aal-oss** [comment]
Anjay ternyata orang indo kukira pada orang kuar semua

**Comment by Aal-oss** [comment]
> Browser nya coba ganti
> 
> browser: ["Chrome (Linux)", "", ""]

Nanti gw cona bang
