### ISSUE TITLE
[BUG] When I try to send Message to Group starts with 12xxx ID

### ISSUE THREAD

**Issue by JunaGanz** [WhiskeySockets/Baileys#409]
I used pairing code for register account, when registering it's perfectly normal.

But when I try to send Message in Group, Group ID starts with "123xxx@g.us" it's not sending and causing connetion closed. In another Group, Group ID not starts with "123xxx@g.us" it's perfectly normal when I try the same thing.

I suspect it was because I used the pairing code method

*Note:* I'm really sorry if my grammar is Soo bad. Hope you understand what I said

**Comment by JunaGanz** [comment]
Edit: After I investigated again, it turned out that the group ID was not one of the causes

The problem comes sometimes when sending messages to several groups.

**Comment by Radit10** [comment]
Use scan QR still cannot send message in group

**Comment by JunaGanz** [comment]
> Use scan QR still cannot send message in group

You're right. That's why I closed this issue


But how can we fix this issue?

**Comment by Radit10** [comment]
> > Use scan QR still cannot send message in group
> 
> You're right. That's why I closed this issue
> 
> But how can we fix this issue? Shall I reopen this issue?

Yeah reopen this issue, because this bug so annoying, but you still can send message in grup if the participant group is below 500
