### ISSUE TITLE
[BUG] Bug in the Profile Picture update section

### ISSUE THREAD

**Issue by FERDIZ-afk** [WhiskeySockets/Baileys#418]
![Screenshot_2023-10-05-00-39-51-48](https://github.com/WhiskeySockets/Baileys/assets/69185890/24be5fb3-08b2-4890-b874-e5282cd0fc6a)

There was a bug when I wanted to set the profile via buffer,

 ***fdz.updateProfilePicture(jid, buffer From download)***

Please anyone help me, how to solve an error like this.

**Comment by FERDIZ-afk** [comment]
Why is it closed? I haven't gotten any instructions on how to resolve this error.

**Comment by SheIITear** [comment]
Issues aren't for resolving bugs on code written by yourself.

**Comment by FERDIZ-afk** [comment]
Media download code in the message that I use

const {
  jidNormalizedUser,
  jidDecode,
  proto,
  areJidsSameUser,
  extractMessageContent,
  generateWAMessageFromContent,
  generateForwardMessageContent,
  downloadContentFromMessage,
  toBuffer,
  getDevice,
  prepareWAMessageMedia
} = require('@adiwajshing/baileys');

fdz.downloadMediaMessage = async (message) => {
    let mime = {
      imageMessage: "image",
      videoMessage: "video",
      stickerMessage: "sticker",
      documentMessage: "document",
      audioMessage: "audio",
      ptvMessage: "video"
    }[message.type]

    if ('thumbnailDirectPath' in message.msg && !('url' in message.msg)) {
      message = {
        directPath: message.msg.thumbnailDirectPath,
        mediaKey: message.msg.mediaKey
      };
      mime = 'thumbnail-link'
    } else {
      message = message.msg
    }
    return await toBuffer(await downloadContentFromMessage(message, mime))
  }


So what's wrong with this code?

I copied the code from this repository 

https://github.com/Hisoka-Morrou/hisoka-baileys/blob/3e7583931dec1bb9834f01f2a055010d5e8ed0c8/lib/serialize.js#L100

**Comment by tyagolp** [comment]
+1
