### ISSUE TITLE
[BUG] is it possible to download PT message? I was try it but I got this 

### ISSUE THREAD

**Issue by JunaGanz** [WhiskeySockets/Baileys#420]
**Describe the bug**
Got errored when I try to download ptvMessage
```
Error: error:1C800064:Provider routines::bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:199:29)
    at Transform.final [as _final] (/home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:498:31)
    at callFinal (node:internal/streams/writable:700:12)
    at prefinish (node:internal/streams/writable:712:7)
    at finishMaybe (node:internal/streams/writable:722:5)
    at Writable.end (node:internal/streams/writable:634:5)
    at IncomingMessage.onend (node:internal/streams/readable:705:10)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12) {
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}
```

Is it possible to download ptvMessage on baileys?
can someone make it possible?!

**Comment by Prodigy90** [comment]
Did you get this fixed??

I'm getting the same error but I'm trying to download a normal media file also with a viewonce media

**Comment by cristiano-linvix** [comment]
@Prodigy90, did you fixed this?

**Comment by cristiano-linvix** [comment]
I got it, the problem occurs if you pass document type different from:
```typescript
const MEDIA_KEYS: ("ppic" | "product" | "image" | "video" | "sticker" | "audio" | "gif" | "ptt" | "thumbnail-document" | "thumbnail-image" | "thumbnail-link" | "thumbnail-video" | "md-app-state" | "md-msg-hist" | "document" | "product-catalog-image" | "payment-bg-image")[]
```

**Comment by Prodigy90** [comment]
> I got it, the problem occurs if you pass document type different from:
> 
> ```ts
> const MEDIA_KEYS: ("ppic" | "product" | "image" | "video" | "sticker" | "audio" | "gif" | "ptt" | "thumbnail-document" | "thumbnail-image" | "thumbnail-link" | "thumbnail-video" | "md-app-state" | "md-msg-hist" | "document" | "product-catalog-image" | "payment-bg-image")[]
> ```

Oh, hehe.

Didn't get this problem. Nice it's working for you now man!

**Comment by cristiano-linvix** [comment]
The function expects the media type of the file to be downloaded, how did you obtain the type of the file to be downloaded to pass to the function?
```typescript
export declare const downloadContentFromMessage: ({ mediaKey, directPath, url }: DownloadableMessage, type: MediaType, opts?: MediaDownloadOptions) => Promise<Transform>;
```

**Comment by Prodigy90** [comment]
Since it's an already existing message I input it manually, but you could create a function for it too.

If you want to download it as it comes in, just use this to get the filepath and save it automatically.

```                    const type = isViewOnceMessage.message?.imageMessage || isViewOnceMessage.message?.videoMessage;
                    const mimetype = type.mimetype
                    const parts = mimetype.split('/');
                    const lastPart = parts[parts.length - 1].split(';')[0].trim();
                    const buffer = await downloadMediaMessage(
                        msg,
                        'buffer',
                        {},
                        {
                            logger,
                            reuploadRequest: client.updateMediaMessage
                        }
                    )
                    // save to file
                    const path = `filename.${lastPart}`
                    await writeFile(path, buffer)```

**Comment by cristiano-linvix** [comment]
I was doing it exactly like this, but this way, it will break.

Why does the type need to be in the array I mentioned.

Test sending TXT files, XML was where the problem occurred for me.
