### ISSUE TITLE
[BUG] Problems with API QR Code

### ISSUE THREAD

**Issue by renatoiub** [WhiskeySockets/Baileys#423]
Yesterday there was a problem with the server and it had to be shut down. After starting again, when trying to connect the API QR Code it says "Unable to connect the device, try again later" and it no longer connects. Has anyone ever experienced this?

**Comment by Auties00** [comment]
This usually happens if your device's date is wrong

**Comment by renatoiub** [comment]
I've already checked the Data and the problem still persists.

**Comment by programadorbob** [comment]
It's not a baileys bug, close this issue
