### ISSUE TITLE
[BUG] JID not exists on 10 digit Indonesian numbers 

### ISSUE THREAD

**Issue by dyheng** [WhiskeySockets/Baileys#424]
**Describe the bug**
When sending msg to Indonesian WA Number with total 10 digits eg: 6281160XXXX (total 10 characters).
It responds JID not exists. 
above 10 digits works fine.

**Expected behavior**
Expected to be able to send to the 10 digits number, because it is on Whatsapp and is daily used on phone without any problem.

**Comment by azudindaem** [comment]
Baileys does not restrict or impose a minimum digit rule on phone numbers. The issue may be related to other factors such as using middleware for phone number checks/validation.

**Comment by dyheng** [comment]
The problem only occurs in 10 digit indonesian phone number , reponse 'JID not exists' but when i tried malaysia 10 digit phone number eg 6012678XXXX , it sent succesfully.

**Comment by azudindaem** [comment]
> The problem only occurs in 10 digit indonesian phone number , reponse 'JID not exists' but when i tried malaysia 10 digit phone number eg 6012678XXXX , it sent succesfully.

there must be some validation rule on your library that cause the issue.. when sending message to any number either valid or no, there is no such error JID not exists return. please check your middleware/source code again

here is response from the server when sending 10 diigts Indonesian number (not valid number)

```json
{
	"key": {
		"remoteJid": "6234567890@s.whatsapp.net",
		"fromMe": true,
		"id": "xxxxxxxxx"
	},
	"message": {
		"extendedTextMessage": {
			"text": "Test From Baileys"
		},
		"messageContextInfo": null
	},
	"messageTimestamp": "1696727513",
	"status": "PENDING"
}
```

**Comment by Riders004** [comment]
> The problem only occurs in 10 digit indonesian phone number , reponse 'JID not exists' but when i tried malaysia 10 digit phone number eg 6012678XXXX , it sent succesfully.

Use + then country code then mobile ( phone  )number 
For ex :- +12581473690
+1 is country code and 2581473690 is phone number from
