### ISSUE TITLE
phone hidden from ads ctwa

### ISSUE THREAD

**Issue by detho** [WhiskeySockets/Baileys#427]
![image](https://github.com/WhiskeySockets/Baileys/assets/7983284/da386c0e-acc3-4a96-9253-ac54b65cdedb)

not trigger in messages.upsert 

https://faq.whatsapp.com/626403979060997/?cms_platform=android&locale=in_ID

**Comment by azudindaem** [comment]
try this PR let us know if this working

https://github.com/WhiskeySockets/Baileys/pull/408

**Comment by detho** [comment]
> try this PR let us know if this working
> 
> #408

not working

**Comment by azudindaem** [comment]
From what I've observed, some users report that it can be triggered as usual, while others report that it doesn't trigger. We need more feedback on this matter

**Comment by PurpShell** [comment]
LID stuff.
