### ISSUE TITLE
Call menu

### ISSUE THREAD

**Issue by Aal-oss** [WhiskeySockets/Baileys#429]
How to make a menu display like call history
My friend can do it but I'm still confused about how to do it

**Comment by Riders004** [comment]
> How to make a menu display like call history My friend can do it but I'm still confused about how to do it

Ask your friend

**Comment by Aal-oss** [comment]
I was able to use console.log(m) to capture data, apparently using relayMessage

**Comment by Riders004** [comment]
> I was able to use console.log(m) to capture data, apparently using relayMessage

Define m
