### ISSUE TITLE
Always online

### ISSUE THREAD

**Issue by Elalitareq** [WhiskeySockets/Baileys#431]
When I login to Whatsapp through baileys I stop receiving notifications on phone and stopped even receiving calls and always appear online can you add an option to keep the presence offline

**Comment by kyraex** [comment]
Just add `markOnlineOnConnect: false` in your auth configuration.

```
const WA = makeWASocket({
      auth: state,
      ...,
      markOnlineOnConnect: false,
      });
```

**Comment by Elalitareq** [comment]
> Just add `markOnlineOnConnect: false` in your auth configuration.
> 
> ```
> const WA = makeWASocket({
>       auth: state,
>       ...,
>       markOnlineOnConnect: false,
>       });
> ```

its already there
    const socket = makeWASocket({
      auth: authState?.state,
      browser: ["TestApi", "Desktop", "10.0"],
      logger: Logger({ level: "debug" }),
      syncFullHistory: false,
      markOnlineOnConnect: false,
      printQRInTerminal: true,
      getMessage: async (key) => {
        return await store.operation.messages.get({ "key.id": key.id });
      },
    });

**Comment by ChargerMc** [comment]
sock.sendPresenceUpdate('unavailable') after every message send or any logic you want

**Comment by kyraex** [comment]
> > Just add `markOnlineOnConnect: false` in your auth configuration.
> > ```
> > const WA = makeWASocket({
> >       auth: state,
> >       ...,
> >       markOnlineOnConnect: false,
> >       });
> > ```
> 
> its already there const socket = makeWASocket({ auth: authState?.state, browser: ["TestApi", "Desktop", "10.0"], logger: Logger({ level: "debug" }), syncFullHistory: false, markOnlineOnConnect: false, printQRInTerminal: true, getMessage: async (key) => { return await store.operation.messages.get({ "key.id": key.id }); }, });

If you use any presence update, you should consider https://github.com/WhiskeySockets/Baileys/issues/431#issuecomment-1758057135

**Comment by renerlemes** [comment]
> sock.sendPresenceUpdate('unavailable') after every message send or any logic you want

For me, this work!

**Comment by jbaladao** [comment]
> > sock.sendPresenceUpdate('unavailable') after every message send or any logic you want
> 
> For me, this work!

How do you fix your code? Here not working after define sock.sendPresenceUpdate('unavailable')...

**Comment by Elalitareq** [comment]
> > > sock.sendPresenceUpdate('unavailable') after every message send or any logic you want
> > 
> > 
> > For me, this work!
> 
> How do you fix your code? Here not working after define sock.sendPresenceUpdate('unavailable')...

In my case i set timeout to send presenceupdate and tracked that timeout so that when i send a message it will update status after 1 minutes unless they send another message which will clear timeout of the previous one and sets it again

I also added a set interval to send presence update every 10 minutes (in my case it worked not sure if this is the correct approach or not)

**Comment by cafi** [comment]
> Just add `markOnlineOnConnect: false` in your auth configuration.
> 
> ```
> const WA = makeWASocket({
>       auth: state,
>       ...,
>       markOnlineOnConnect: false,
>       });
> ```

Where do I insert this? Whee do I find auth configuration?

**Comment by ojuolokun86** [comment]
Pls I have issues 
When my bot is connected to WhatsApp, after sometimes it will show active in link side but won't respond to msg or command anymore or even listen to msg
