### ISSUE TITLE
[BUG] send a buttons message not working and not shown in mobile apps

### ISSUE THREAD

**Issue by wahyukodar** [WhiskeySockets/Baileys#443]
**Describe the bug**
send a buttons message not working and not shown in mobile apps.

**To Reproduce**
```
// send a buttons message!
const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
  {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
]

const buttonMessage = {
    text: "Hi it's button message",
    footer: 'Hello World',
    buttons: buttons,
    headerType: 1
}

const sendMsg = await sock.sendMessage(id, buttonMessage)
```

**Expected behavior**
Button 1, Button 2, and Button 3 should be showed in mobile apps

**Comment by programadorbob** [comment]
There are no bugs regarding the buttons, they are discontinued, close this issue now, if you had read the functions correctly, you would be aware that WhatsApp has discontinued the buttons outside the official API

**Comment by renatoiub** [comment]
I tested the buttons and the list again, they worked again on IOS.

**Comment by IgorDePaula** [comment]
Remove button from docs, please.

**Comment by renatoiub** [comment]
Algumas apis já estão usando listas e botões.

**Comment by IgorDePaula** [comment]
@renatoiub quais?

**Comment by renatoiub** [comment]
Evolutivos já está, pelo menos lista eu já testei e funciona.

**Comment by renatoiub** [comment]
https://github.com/EvolutionAPI/evolution-api/pull/322

**Comment by IgorDePaula** [comment]
Lista tem o wppconnect, que eh a que eu uso hoje. Mas vou dar uma olhada
nessa também.

Em qui., 28 de dez. de 2023 08:33, renatoiub ***@***.***>
escreveu:

**Comment by renatoiub** [comment]
O pessoal está usando e atualizando. Eu consegui usar no meu projeto mas tive que mexer nos arquivos da baileys.

**Comment by IgorDePaula** [comment]
Vamos trocar uma ideia depois

Em qui., 28 de dez. de 2023 às 08:42, renatoiub ***@***.***>
escreveu:

**Comment by renatoiub** [comment]
Se quiser fazer um teste, nos meus repositórios está uma versão que funciona lista. Porém após instalar vc tem que alterar uma linha em um arquivo da baileys pra funcionar.

**Comment by radhesolution** [comment]
Hi,

In our software, you can send different types of WhatsApp messages, including btn messages.

To ensure everything is working correctly, please follow the steps below to test various message types. Send your test messages to +917878222906:

> Poll Message > Type .poll to test a poll message.

> BTN Message > Type .btn to test a standard reply btn.

> Call to Action BTN > Type .cta to test a call-to-action btn (call & URL).

> BTN with Media Message > Type .btnmedia to test the btn integrated with media content.

> Menu Message > Type .menu to test the menu btn.

By following these steps, you can ensure that all the different types of WhatsApp messages function as expected.

Digi Bulk Marketing

**Comment by IgorDePaula** [comment]
How to make This?

Em sex., 15 de nov. de 2024, 09:11, radhesolution ***@***.***>
escreveu:
