### ISSUE TITLE
WAConnection is not a constructor

### ISSUE THREAD

**Issue by JohnTaco93** [WhiskeySockets/Baileys#449]
This is my code:
// Import Baileys library
const { WAConnection } = require('@adiwajshing/baileys')

// Create a new connection
const conn = new WAConnection()

// Set the QR code callback
conn.on('qr', qr => {
    // Display the QR code in the terminal 3000
    console.log('Scan this QR code in terminal 3000:\n', qr)
})

// Set the open callback
conn.on('open', () => {
    // Show a success message
    console.log('Connected to WhatsApp')
})

// Set the chat update callback
conn.on('chat-update', async chat => {
    // Check if the update is a new message
    if (chat.messages && chat.count) {
        // Get the message
        const message = chat.messages.all()[0]
        // Check if the message is from a random user
        if (message.key.fromMe === false) {
            // Get the sender's number
            const sender = message.key.remoteJid
            // Reply with 'hola'
            await conn.sendMessage(sender, 'hola', 'conversation')
        }
    }
})

// Connect to WhatsApp
conn.connect()

// I am getting this error (it happens with either @adiwajshing/baileys or @whiskeysockets/baileys)
const conn = new WAConnection()
             ^

TypeError: WAConnection is not a constructor
    at Object.<anonymous> (C:\Users\M S I\Desktop\baileys_johntaco_bots\try6\index.js:5:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.1

**Comment by bobdevfull** [comment]
Firstly, you didn't update your code and mainly you don't pay attention, look at the code example before opening an issue
