### ISSUE TITLE
[BUG] Couldn't read/get group message from webhook

### ISSUE THREAD

**Issue by jcteh92** [WhiskeySockets/Baileys#45]
**Describe the bug**
Couldn't read/get group message from webhook (incoming message),  message was missing in return JSON during group message

**To Reproduce**
1. Login client
2. message in any whatsapp group

![Screenshot 2023-05-05 at 9 58 37 PM](https://user-images.githubusercontent.com/103173545/236480027-a39c246d-5a2f-4a02-8036-675724718dbe.png)

**Environment (please complete the following information):**
 - Is this on a server? - Docker (localhost)
 - Do you have multiple clients on the same IP?  - 1 client only
 - Are you using a proxy? - No

**Comment by dewnan98** [comment]
any progress on this?
