### ISSUE TITLE
Method for listing groups

### ISSUE THREAD

**Issue by lucasdzuc** [WhiskeySockets/Baileys#479]
Feature suggestion:

method to list groups of the contact that is logged in.

If you already have an implementation, please send me the link for evaluation.

**Comment by Auties00** [comment]
Please use the discord to ask for help 
This isn't a bug report or a feature request

**Comment by Vanortton** [comment]
A única forma que encontrei é recebendo o histórico de sincronização com `syncFullHistory: true` e usando o evento `messaging-history.set`. Vem um campo contacts, os objetos com a propriedade name preenchida geralmente são grupos, mas o mesmo pode ser feito apenas checando o jid: `.endsWith('@g.us')`.
