### ISSUE TITLE
[BUG] sendMessage not sending image attached

### ISSUE THREAD

**Issue by Lucas-Gardini** [WhiskeySockets/Baileys#480]
**Describe the bug**
When passing a buffer from a base64 image string, the image does not go with the message

**To Reproduce**
1. Create a buffer from a base64 string
2. Send it with image property

**Expected behavior**
The image is sent within the message

Code:
```ts
public async sendMessage(number: string, message: string, base64: string) {
    const a = await this.client.sendMessage(`${number}@s.whatsapp.net`, {
        text: message,
        image: Buffer.from(base64, "base64"),
    });
}
```

**Comment by Rippanteq7** [comment]
> **Describe the bug** When passing a buffer from a base64 image string, the image does not go with the message
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a buffer from a base64 string
> 2. Send it with image property
> 
> **Expected behavior** The image is sent within the message
> 
> Code:
> 
> ```ts
> public async sendMessage(number: string, message: string, base64: string) {
>     const a = await this.client.sendMessage(`${number}@s.whatsapp.net`, {
>         text: message,
>         image: Buffer.from(base64, "base64"),
>     });
> }
> ```

For [media messages](https://github.com/WhiskeySockets/Baileys#media-messages) use caption instead of text

```js
const a = await this.client.sendMessage(`${number}@s.whatsapp.net`, {
    image: Buffer.from(base64, "base64"),
    caption: "your caption"
});
```
