### ISSUE TITLE
Can please provide update of this library. last 2month not get any update after updating WhatsApp

### ISSUE THREAD

**Issue by marutikarad** [WhiskeySockets/Baileys#487]
Can please provide update of this library. last 2month not get any update after updating WhatsApp

**Comment by PurpShell** [comment]
Hi! We are working

**Comment by ChargerMc** [comment]
How we can help? Any guide?

**Comment by marutikarad** [comment]
Not getting group list after scan

**Comment by renatoiub** [comment]
There is already an API that uses Baileys using lists and buttons. They are certainly more advanced than here
