### ISSUE TITLE
 Multiple socks

### ISSUE THREAD

**Issue by DenisAlvesDias** [WhiskeySockets/Baileys#489]
Goodnight. First of all, I'm sorry if I opened the topic in the wrong place. But I've been trying for a few days without success. With the API, is it possible to control multiple socks at the same time? I tried to create a map, but when I connect the second WhatsApp, it keeps trying to connect over and over again. There would be some way to do this. Sorry for the English.

**Comment by weershft** [comment]
Olá Alves, não entendi sua pergunta, poderia explicar mais detalhadamente por favor?

Se for BR, pode escrever em português...
tmj

**Comment by DenisAlvesDias** [comment]
Boa tarde. Claro. Minha vontade é o seguinte:
Exemplo:
Tenho 5 clientes que vão utilizar o produto. 
Existe uma forma de trabalhar que eu vou ter multiplos socks com numeros de whatsapp diferente? 
Por exemplo: 
Crio a sessão do primeiro, crio a pasta dele com o numero de telefone, e a api responde normalmente.
Ae chega o segundo, cria outra sessão, outro sock e vai responder normalmente em paralelo com o primeiro.

Na minha cabeça a forma de fazer isso seria ter codigo para cada cliente, porém, se der para fazer tudo num codigo so, ter N clientes com numeros de whatsapp diferente trabalhando no mesmo código em paralelo.
