### ISSUE TITLE
pinInChatMessage

### ISSUE THREAD

**Issue by HACKERESOBERANO** [WhiskeySockets/Baileys#495]
Is the pin message function already available?

**Comment by gusta4321** [comment]
let templategenerate= await generateWAMessageFromContent(from, proto.Message.fromObject({pinInChatMessage: {
key: message.key,
type: 1,
senderTimestampMs: new Date().getTime() / 1000
}}), {})

let templatenew = {
messageContextInfo: { messageAddOnDurationInSecs: 604800 },
...templategenerate.message
}

await conn.relayMessage(from, templatenew, { messageId: templategenerate.key.id })

It only works on WhatsApp Web.
