### ISSUE TITLE
 Can't send audio messages

### ISSUE THREAD

**Issue by ecatugy** [WhiskeySockets/Baileys#501]
**Describe the bug**
 Can't send audio messages; the message comes through, but the player stays paused. I've tried a bunch of audio mimetypes like audio/mp4, audio/mp3, and audio/mpeg, but none of 'em work. Here's my submission example:

Does anyone have any usage examples?

```javascript
/**
   * Sends a message to the specified receiver.
   *
   * @param receiver The receiver's phone number
   * @param sessionId The session ID
   * @param messages The list of messages to send
   * @return The message sending results
   */
  private async sendMessageAsync(receiver: string, sessionId: string, message: Message): Promise<SendMessageResult> {

    const session = getSession(sessionId) as any

    if (!session) {
      throw new Error(`Session not found: ${sessionId}`)
    }
    const sendMessage =     { audio: { url: "https://dl.espressif.com/dl/audio/ff-16b-1c-44100hz.mp3" }, mimetype: 'audio/mp4' }
    const formattedReceiver = formatPhone(receiver)
    const result: SendMessageResult = await session.sendMessage(formattedReceiver, sendMessage, { ephemeralExpiration: 100000000 })

    return result
  }

**Comment by reinaldocoelho** [comment]
I have a same problem, when sent an audio message (with ppt: true), I receive an status OK from API, but the audio message never appear on mobile either sent to customer.
If on same machine I connect the Whatsapp Web and run the library to send audio message, the message comes to Whatsapp Web, not appear on mobile and on the whatsapp web not confirm the sent notification.

When I can found more details about the problem?

**Comment by Edufgs** [comment]
I have the same problem. Any news?

**Comment by MichaellDev1** [comment]
I have the same problem 😢

**Comment by codespearhead** [comment]
@reinaldocoelho Are you sending a file that's already in your file system?

@MichaellDev1 Is this still reproducible if instead of a remote file such as `"https://dl.espressif.com/dl/audio/ff-16b-1c-44100hz.mp3"` you send a file that's already in your file system?

Because from what I understand, getting the file from a remote source, handling eventual authentication and handling potential errors that might arise from downloading it or saving it is your file system out of the scope of the project, because it's best you do it yourself.

**Comment by reinaldocoelho** [comment]
Hi @codespearhead ,  my file was downloaded from an whatsapp to make a test when sent.
In my case, if I send the file with type "audio/ogg; codecs=opus", the audio is sent with success.

The important part is that the process worked with codec opus, not only the ogg format.

**Comment by codespearhead** [comment]
What version are you using? Because I'm pretty sure that's the default:

https://github.com/WhiskeySockets/Baileys/blob/79c33e53b4124735f019c48e8075c9cde807b7e7/src/Utils/messages.ts#L52
