### ISSUE TITLE
Stream Errored Out Status code 440[BUG]

### ISSUE THREAD

**Issue by aayush-farmart** [WhiskeySockets/Baileys#502]
**Describe the bug**

I am getting a stream errored out connection update repeatedly with a status code of 440(Login timeout). I am handling the connection update by calling the startSock() function again in order to re-establish the connection, but the error just keeps coming up again and again, resulting in an infinite loop (sort of). 
Is there any clear solution to this? I am using the latest versions of Whatsapp Business and of Baileys(6.5.0)

**To Reproduce**
I am using the example file provided in the repository. 

**Expected behavior**
The connection should not be reset every 5 seconds with the stream errored out error.

**Environment (please complete the following information):**
 - Is this on a server? **I'm getting this server on both the server as well as my local machine.**
 - What do your `connectOptions` look like? 
   My connectOptions are as follows:
   ```
    {
      version,
      logger: P({ level: "fatal" }),
      printQRInTerminal: !usePairingCode,
      mobile: useMobile,
      browser: ["chrome (linux)", "", ""],
      auth: {
        creds: state.creds,
        /** caching makes the store faster to send/recv messages */
        //keys: makeCacheableSignalKeyStore(state.keys, logger),
        keys: state.keys,
      },
      msgRetryCounterCache,
      generateHighQualityLinkPreview: true,
      // ignore all broadcast messages -- to receive the same
      // comment the line below out
      shouldIgnoreJid: (jid) => isJidBroadcast(jid),
      // implement to handle retries
      getMessage: async (key) => {
        /* if (store) {
          const msg = await store.loadMessage(key.remoteJid!, key.id!);
          return msg?.message || undefined;
        } */
  
        // only if store is present
        return {
          conversation: "hello",
        };
      },
    }
   ```
 - Do you have multiple clients on the same IP? `No.`
 - Are you using a proxy? `No.`

**Additional context**
I have referred to similar issues #141 , #130 and #107 and have tried the temporary workarounds mentioned there, but to no avail. Find below the error object I'm receiving:

![image](https://github.com/WhiskeySockets/Baileys/assets/134056353/bfc0c4f1-7fe8-4b34-ba84-fde870ce1d53)

**Comment by masbilal** [comment]
same problem

**Comment by TechDan09** [comment]
Same problem, any update on this?

**Comment by llermaly** [comment]
+1

**Comment by guiqis** [comment]
+1

**Comment by Frederico03** [comment]
+1

**Comment by taksrules** [comment]
did anyone find a fix to the problem

**Comment by amunim** [comment]
bump

**Comment by wilisandi** [comment]
any solution?

**Comment by flozender** [comment]
Adding a delay of around `30000ms` upon encountering `statusCode: 440` before retrying a connection fixed it for me.

**Comment by nagi1** [comment]
We still have this problem even with waiting for a full minute. 

Do you have any idea why this happening?

cc: @flozender

**Comment by RaphaelMalth** [comment]
+1  I'm using "mongo-baileys": "1.0.1",

**Comment by lucaspereirasouzat** [comment]
same problem on latest version "baileys": "^6.7.17",

**Comment by rodrigogs** [comment]
I'm having the same problem with 6.7.17

**Comment by User-425** [comment]
same problem with @whiskeysockets/baileys: "^6.4.0" , but apparently for me, it only show when we reused last authentication session, it won't error if we freshly start a new one by re-scanning (by deleted the auth_info_baileys first). Hope this can help

**Comment by n-qber** [comment]
You have to restart the connection as the error implies, from [https://www.npmjs.com/package/@adiwajshing/baileys](https://www.npmjs.com/package/@adiwajshing/baileys) we can see that:

```typescript {.line-numbers}
import { Boom } from '@hapi/boom'

async function connectToWhatsApp () {
    const sock = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true
    })
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
    sock.ev.on('messages.upsert', m => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        await sock.sendMessage(m.messages[0].key.remoteJid!, { text: 'Hello there!' })
    })
}
// run in main file
connectToWhatsApp()
```


I did the same thing (reconnect in this specific error scenario) and my code worked fine
