### ISSUE TITLE
[BUG] Cannot find module cache-manager/dist/index.js

### ISSUE THREAD

**Issue by jrCleber** [WhiskeySockets/Baileys#505]
> Library version: 6.5.0

**Describe the bug**
A clear and concise description of what the bug is: Upon attempting to use a module in a project, an error occurs stating that the module 'cache-manager' cannot be found in the 'node_modules' directory. Specifically, the 'dist/index.js' file is missing. This suggests a problem with the module's installation or the 'package.json' file.

**Error**
```sh
Error: Cannot find module '/home/root/Projects/wa/node_modules/cache-manager/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:415:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:665:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/root/Projects/wa/node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
```

**To Reproduce**
1. Set up the project environment.
2. Run the project which requires the 'cache-manager' module.
3. Encounter the error indicating the missing 'dist/index.js' file in the 'cache-manager' module.

**Expected behavior**
A clear and concise description of what you expected to happen: The project should have properly located and utilized the 'cache-manager' module without any errors, allowing the project to run as intended.

**Environment (please complete the following information):**
- Is this on a server? [Yes/No, if yes, provide server details]
- What do your `connectOptions` look like? [Provide details of the connection options set in the project]
- Do you have multiple clients on the same IP? No
- Are you using a proxy? No

**Additional context**
This problem may be related to an incomplete or corrupt installation of the 'cache-manager' module. It's also possible that the 'package.json' file does not have a valid "main" entry for this module, or that the module version is incompatible with the current project setup. Checking the module installation and 'package.json' configuration is recommended.

**Comment by lukasportal** [comment]
looks like the package cache-manager published an empty repo or something

install an older version like 5.2.2

**Comment by jrCleber** [comment]
That didn't work.

**Comment by lukasportal** [comment]
it worked here
make sure you:
`rm -rf node_modules package-lock.json`
`npm install cache-manager@5.2.2`
`npm install`

**Comment by jrCleber** [comment]
Thanks for the help, but it still doesn't work.

**Comment by chocolaid** [comment]
What worked for me was version 4.0.1

**Comment by gamersindo1223** [comment]
use the github release
npm i --save github:node-cache-manager/node-cache-manager
@chocolaid

**Comment by chocolaid** [comment]
@gamersindo1223 The 4.0.1 worked well so no need

**Comment by gamersindo1223** [comment]
Oh okay!
But if someone else can't download the old npm package just use my answer

**Comment by Guru322** [comment]
> add this in package.json
> 
> "overrides":{ "cache-manager":"5.2.2" }
> 
> install it like this
> 
> { "dependencies": { //your modul }, "overrides": { "cache-manager": "5.2.2" }

Thanks , it worked

**Comment by Guru322** [comment]
> it worked here make sure you: `rm -rf node_modules package-lock.json` `npm install cache-manager@5.2.2` `npm install`

Thanks

**Comment by SheIITear** [comment]
https://github.com/node-cache-manager/node-cache-manager/issues/611

**Comment by jrCleber** [comment]
> add this in package.json
> 
> "overrides":{ "cache-manager":"5.2.2" }
> 
> install it like this
> 
> { "dependencies": { //your modul }, "overrides": { "cache-manager": "5.2.2" } }

This adjustment did the trick. Thanks.
