### ISSUE TITLE
EBUSY: resource busy or locked when sending message using buffer image

### ISSUE THREAD

**Issue by arpitgoyall** [WhiskeySockets/Baileys#518]
**Describe the bug**
When we try to send a message containing an image buffer then it gives the error shown below:
```
{
  "level": 50,
  "time": "2023-11-28T14:18:32.266Z",
  "pid": 10392,
  "hostname": "ZERO_BOOK_13",
  "err": {
    "type": "Error",
    "message": "EBUSY: resource busy or locked, unlink 'C:\\Users\\arpit\\AppData\\Local\\Temp\\imageBAE5545C74E3D4DB'",
    "stack": "Error: EBUSY: resource busy or locked, unlink 'C:\\Users\\arpit\\AppData\\Local\\Temp\\imageBAE5545C74E3D4DB'",
    "errno": -4082,
    "code": "EBUSY",
    "syscall": "unlink",
    "path": "C:\\Users\\arpit\\AppData\\Local\\Temp\\imageBAE5545C74E3D4DB"
  },
  "msg": "An error occured during message send"
}
```

**To Reproduce**

Send message that contains an image buffer

```
await socket.sendMessage(jid,
    {
      image: Buffer.from(imageBase64, 'base64'),
      caption: "This is caption",
    }
);
```

**Expected behavior**
The message should be delivered without any errors.

**Additional context**
I also tried saving the file into the disk and passing the path of it like `{ image: { url : "path/to/file"} }` but the same problem is coming when we try to delete that file, obviously we don't want to store those images forever.

**Comment by CSFelix** [comment]
Same problem here. It happens when I try to send images on `webp` format like two compacted images below:

[Backgrounds.zip](https://github.com/WhiskeySockets/Baileys/files/13492459/Backgrounds.zip)

**Comment by CSFelix** [comment]
I have good (or bad) news!!

In my case, the problem happen when I let the `jpegThumbnail` for images be automatically generated by `jimp` package. When I manually set the property as an empty string for instance, the problem does not happen:

```typescript
options = {
        image: fs.readFileSync(media.path),
        caption: body,
        jpegThumbnail: ""
};
```

But, the images are sent without a thumbnail (expected, since I set the thumbnail as an empty string):

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/919b042a-0f39-47bf-a418-d7f520dcb116)

---

Then, I would guess the issue is in Jimp package when it tries to automatically generate the thumbnail.

**Comment by CSFelix** [comment]
I was able to solve the problem temporally using this workaround:

```typescript
options = {
  image: fs.readFileSync(media.path),
  caption: formatBody(body as string, ticket.contact)
};

let sentMessage;
try {
  sentMessage = await wbot.sendMessage(number, { ...options });
} catch (err) {
  options = {
    image: fs.readFileSync(media.path),
    caption: formatBody(body as string, ticket.contact),
    jpegThumbnail: ""
  };
  sentMessage = await wbot.sendMessage(number, { ...options });
}
```
Now, I'm searching how to completely solve it (send webp images with automatically generated thumbnails)

**Comment by raseldev18** [comment]
> **Describe the bug** When we try to send a message containing an image buffer then it gives the error shown below:
> 
> ```
> {
>   "level": 50,
>   "time": "2023-11-28T14:18:32.266Z",
>   "pid": 10392,
>   "hostname": "ZERO_BOOK_13",
>   "err": {
>     "type": "Error",
>     "message": "EBUSY: resource busy or locked, unlink 'C:\\Users\\arpit\\AppData\\Local\\Temp\\imageBAE5545C74E3D4DB'",
>     "stack": "Error: EBUSY: resource busy or locked, unlink 'C:\\Users\\arpit\\AppData\\Local\\Temp\\imageBAE5545C74E3D4DB'",
>     "errno": -4082,
>     "code": "EBUSY",
>     "syscall": "unlink",
>     "path": "C:\\Users\\arpit\\AppData\\Local\\Temp\\imageBAE5545C74E3D4DB"
>   },
>   "msg": "An error occured during message send"
> }
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> Send message that contains an image buffer
> 
> ```
> await socket.sendMessage(jid,
>     {
>       image: Buffer.from(imageBase64, 'base64'),
>       caption: "This is caption",
>     }
> );
> ```
> 
> **Expected behavior** The message should be delivered without any errors.
> 
> **Additional context** I also tried saving the file into the disk and passing the path of it like `{ image: { url : "path/to/file"} }` but the same problem is coming when we try to delete that file, obviously we don't want to store those images forever.

maybe this solves your problem: https://github.com/BochilGaming/games-wabot-md/blob/e6d5e830bc438a26437f303e2f1aeadc86c05c85/lib/clearTmp.js#L28

**Comment by CSFelix** [comment]
Any updates on this bug?

**Comment by arpitgoyall** [comment]
Issue was resolved when I used this code

```
await socket.sendMessage(jid,
    {
      image: Buffer.from(imageBase64, 'base64'),
      caption: "This is caption",
      jpegThumbnail: '',
    }
);
```

`jpegThumbnail` parameter makes the difference
