### ISSUE TITLE
NPM Package 

### ISSUE THREAD

**Issue by ahmedRSA** [WhiskeySockets/Baileys#52]
It's a Javascript library and without NPM what's the point of this library?

I understand devs work on this in their free time but it literally take 5-6mins to setup everything and make a NPM package.

**Comment by ahmedRSA** [comment]
It's been 5 days since this comment
https://github.com/WhiskeySockets/Baileys/issues/37#issuecomment-153401479.

**Comment by choopchik** [comment]
https://github.com/WhiskeySockets/Baileys/issues/43#issuecomment-1535550135

**Comment by hbinduni** [comment]
they already add this package, `https://www.npmjs.com/package/@whiskeysockets/baileys`
you can install using: `yarn add @whiskeysockets/baileys`
