### ISSUE TITLE
[BUG] Stickers not Rendering on WhatsApp Mobile

### ISSUE THREAD

**Issue by CSFelix** [WhiskeySockets/Baileys#521]
**Describe the bug**

When sending stickers, they are sent normally to WhatsApp Web (image 1), but they do not render on WhatsApp Mobile App (image 2)

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/a3896817-99c0-4255-9c9a-c848322c5b2c)

<br />

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/74b97944-8728-42d4-b2b8-2977867968f8)

---

**To Reproduce**

1. Create a new connection;
2. Send an image as a sticker, regardless of whether it is in buffer or stream format, the problem happens in both situations.

> Code to Send Image as Sticker (Buffer Method)

```typescript
let options: AnyMessageContent;
options = {
  sticker: fs.readFileSync(media.path),
  isAnimated: false
};

await client.sendMessage(
  <JID>,
  { ...options }
);
```

> Code to Send Image as Sticker (Stream Method)

```typescript
let options: AnyMessageContent;
options = {
  sticker: { stream: fs.createReadStream(media.path) },
  isAnimated: false
};

await client.sendMessage(
  <JID>,
  { ...options }
);
```

---

**Expected behavior**

The stickers should have been normally rendered on both platforms: Web and Mobile App.

---

**Environment (please complete the following information):**

 - Is this on a server?

```txt
It is running on localhost (Windows 11);
```

 - What do your `connectOptions` look like? 

```typescript
const { version, isLatest } = await fetchLatestBaileysVersion();

client = makeWASocket({
  version,
  logger: loggerBaileys,
  printQRInTerminal: false,
  auth: state as AuthenticationState,
  generateHighQualityLinkPreview: false,
  shouldIgnoreJid: jid => isJidBroadcast(jid),
  browser: ["BestZap", "Chrome", "10.15.7"],
  syncFullHistory: true,
  patchMessageBeforeSending: message => {
     const requiresPatch = !!(
       message.buttonsMessage || message.listMessage
     );
     if (requiresPatch) {
       message = {
         viewOnceMessage: {
           message: {
             messageContextInfo: {
               deviceListMetadataVersion: 2,
               deviceListMetadata: {}
             },
             ...message
           }
         }
       };
     }
     return message;
   }
});
```

 - Do you have multiple clients on the same IP?

```txt
No, only my personal WhatsApp is connected on Baileys
``` 

 - Are you using a proxy?

```txt
No proxy
```

**Comment by CSFelix** [comment]
> i face this issue too, is there a way to fix it?

I'm afraid but I did not get to work around this yet 😞

**Comment by fauzanfebrian** [comment]
> > i face this issue too, is there a way to fix it?
> 
> I'm afraid but I did not get to work around this yet 😞

i fix it with this npm package `wa-sticker-formatter`
because whatsapp need its metadata so that package will attach the metadata to the buffer

**Comment by CSFelix** [comment]
> > > i face this issue too, is there a way to fix it?
> > 
> > 
> > I'm afraid but I did not get to work around this yet 😞
> 
> i fix it with this npm package `wa-sticker-formatter` because whatsapp need its metadata so that package will attach the metadata to the buffer

I did not work for me 😞. The stickers look ok on WhatsApp Web, but the problem remains on WhatsApp App for Mobiles.

Did you just installed the package or made modifications in the code?

**Comment by fauzanfebrian** [comment]
> > > > i face this issue too, is there a way to fix it?
> > > 
> > > 
> > > I'm afraid but I did not get to work around this yet 😞
> > 
> > i fix it with this npm package `wa-sticker-formatter` because whatsapp need its metadata so that package will attach the metadata to the buffer
> 
> I did not work for me 😞. The stickers look ok on WhatsApp Web, but the problem remains on WhatsApp App for Mobiles.
> 
> Did you just installed the package or made modifications in the code?

you should convert the buffer with that package, did you?

if you want to look how do i implement it just go to my repo, [https://github.com/fauzanfebrian/whatsapp-service](repo) you can find it in file media.ts

**Comment by CSFelix** [comment]
> > > > > i face this issue too, is there a way to fix it?
> > > > 
> > > > 
> > > > I'm afraid but I did not get to work around this yet 😞
> > > 
> > > 
> > > i fix it with this npm package `wa-sticker-formatter` because whatsapp need its metadata so that package will attach the metadata to the buffer
> > 
> > 
> > I did not work for me 😞. The stickers look ok on WhatsApp Web, but the problem remains on WhatsApp App for Mobiles.
> > Did you just installed the package or made modifications in the code?
> 
> you should convert the buffer with that package, did you?
> 
> if you want to look how do i implement it just go to my [repo](https://github.com/fauzanfebrian/whatsapp-service/blob/master/src/whatsapp/bases/media.ts).

It worked, thank you very much!!!!!!!!!!

**Comment by CSFelix** [comment]
For the readers, this is the version of my code that works

```ts
import Sticker, { StickerTypes } from "wa-sticker-formatter";

const stickerFile = fs.readFileSync(media.path); // media is an Express.Multer.File
const stickerBuffer = Buffer.from(stickerFile);

const sticker = new Sticker(stickerBuffer, {
  quality: 50,
  type: StickerTypes.CROPPED,
  author: "",
  pack: ""
});

const stickerMedia = await sticker.toBuffer();

options = {
  sticker: stickerMedia,
  fileName: media.originalname,
  isAnimated: false
};

const sentMessage = await wbot.sendMessage(
 <JID>,
 { ...options }
);
```
