### ISSUE TITLE
[Feature Request] Add Option to Star and Unstar Messages

### ISSUE THREAD

**Issue by CSFelix** [WhiskeySockets/Baileys#524]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. ✔️ Search through the repo's previous issues
2. ✔️ Read through the readme at least once
3. ✔️ Search the docs for the feature you're looking for

Nowadays, it is possible to detect if a message has been starred or unstarred by  `messages.update` event, but there is no function to mark messages as starred/unstarred with Baileys. The three images below ilustrates the functionality on WhatsApp Web:

> **Star Function**

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/f19db0ef-d5ef-4446-9776-019f424497e6)

<br />

> **Starred Messages has a Star Icon**

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/20169b9a-610d-4ec3-9ec6-6f36b9218eca)

<br />

> **Unstar Function**

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/df52a710-6b77-4cc0-b6fb-d45107e79696)

**Comment by azudindaem** [comment]
The function is already available.. if it is not yet implemented, I will create a pull request promptly

 I believe it is already there, or perhaps not fully implemented.

**Comment by azudindaem** [comment]
Please try and review the pull request I have submitted. https://github.com/WhiskeySockets/Baileys/pull/525

**Comment by CSFelix** [comment]
> Please try and review the pull request I have submitted. #525

It worked!! I only needed to change a line of your code. I will comment on the pull request to change later!!

**Comment by CSFelix** [comment]
Can I close this issue or let it open for a while?
