### ISSUE TITLE
Waiting For Message

### ISSUE THREAD

**Issue by Riders004** [WhiskeySockets/Baileys#528]
![IMG-20231204-WA0007](https://github.com/WhiskeySockets/Baileys/assets/120787636/c152923b-a98c-4dc7-a9a9-6108f9472e38)

How to fix that waiting for message issue

**Comment by Riders004** [comment]
Showing waiting for message i already implemented that function

**Comment by kyraex** [comment]
That function is useless if you don't setup a working store. Make sure you implement a store to store messages and that function or anything similar will pull message from that store. This also won't work for old messages that was send from baileys and not stored previously

Correct me if im wrong. Good luck!

**Comment by Riders004** [comment]
> That function is useless if you don't setup a working store. Make sure you implement a store to store messages and that function or anything similar will pull message from that store. This also won't work for old messages that was send from baileys and not stored previously
> 
> Correct me if im wrong. Good luck!

Do you have any example to setups a working store

**Comment by PurpShell** [comment]
Just check the official example.

**Comment by Riders004** [comment]
> Just check the official example.

Got it
