### ISSUE TITLE
[Feature Request] Add Option to Vote on Polls

### ISSUE THREAD

**Issue by CSFelix** [WhiskeySockets/Baileys#548]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. ✔️ Search through the repo's previous issues
2. ✔️ Read through the readme at least once
3. ✔️ Search the docs for the feature you're looking for

Nowadays, it is possible to detect poll votes when:
- contact votes on polls;
- I vote on polls using WhatsApp Web and WhatsApp Mobile App.

However, there is no function to vote on polls directly with Baileys.

**Comment by SheIITear** [comment]
Voting on polls is similar to finding out the voted option.

Do this in reverse: https://gist.github.com/PurpShell/44433d21631ff0aefbea57f7b5e31139 and you should get the value you can use to vote on polls.

**Comment by CSFelix** [comment]
> Voting on polls is similar to finding out the voted option.
> 
> Do this in reverse: https://gist.github.com/PurpShell/44433d21631ff0aefbea57f7b5e31139 and you should get the value you can use to vote on polls.

Gotcha, I will try to implement it and I will share the code here if I got any results. Thanks!!
