### ISSUE TITLE
[BUG] statusCode: 404

### ISSUE THREAD

**Issue by officialdittaz** [WhiskeySockets/Baileys#552]
can somebody help me to fix this error

/home/runner/VIOLET/node_modules/baileys/lib/Utils/chat-utils.js:105
        throw new boom_1.Boom(`myAppStateKey ("${myAppStateKeyId}") not present`, { statusCode: 404 });
              ^

Error: myAppStateKey ("AAAAABiD") not present
    at encodeSyncdPatch (/home/runner/VIOLET/node_modules/baileys/lib/Utils/chat-utils.js:105:15)
    at async /home/runner/VIOLET/node_modules/baileys/lib/Socket/chats.js:555:32
    at async Object.transaction (/home/runner/VIOLET/node_modules/baileys/lib/Utils/auth-utils.js:136:26)
    at async /home/runner/VIOLET/node_modules/baileys/lib/Socket/chats.js:550:13
    at async /home/runner/VIOLET/node_modules/baileys/lib/Utils/make-mutex.js:18:36
    at async appPatch (/home/runner/VIOLET/node_modules/baileys/lib/Socket/chats.js:549:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 404,
    payload: {
      statusCode: 404,
      error: 'Not Found',
      message: 'myAppStateKey ("AAAAABiD") not present'
    },
    headers: {}
  }
}

**Comment by Guilherme-j10** [comment]
up

**Comment by mdev-imagenet** [comment]
Look at the answer here: #588

**Comment by PurpShell** [comment]
lets follow on the original issue
