### ISSUE TITLE
[BUG] The pairing code in the connection is not working

### ISSUE THREAD

**Issue by DavidsonGomes** [WhiskeySockets/Baileys#556]
The pairing code in the connection is not working, it generates the code, but the request does not arrive on WhatsApp, I tested it using Baileys' own example code

<img width="563" alt="Screenshot 2023-12-18 at 14 18 47" src="https://github.com/WhiskeySockets/Baileys/assets/24706726/f3e72aca-570d-4e11-aaf5-c1384dd1d2d4">

**Comment by Rippanteq7** [comment]
> The pairing code in the connection is not working, it generates the code, but the request does not arrive on WhatsApp, I tested it using Baileys' own example code
> 
> <img alt="Screenshot 2023-12-18 at 14 18 47" width="563" src="https://private-user-images.githubusercontent.com/24706726/291360293-f3e72aca-570d-4e11-aaf5-c1384dd1d2d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjM2NDUsIm5iZiI6MTcwMjkyMzM0NSwicGF0aCI6Ii8yNDcwNjcyNi8yOTEzNjAyOTMtZjNlNzJhY2EtNTcwZC00ZTExLWFhZjUtYzEzODRkZDFkMmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzFmMWUyMzdlNDFiZmNiYWY3YTVlYzIwNGE1M2UzODFhMTRkNmNhM2Y0M2I2M2E3MDVkZjMyZWJmOGM2YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VFqdEWyCNOa5sIOJY7Evt4WlWu1NfocE30VXv7_tWFA">

Check this #328

**Comment by DavidsonGomes** [comment]
> > The pairing code in the connection is not working, it generates the code, but the request does not arrive on WhatsApp, I tested it using Baileys' own example code
> > <img alt="Screenshot 2023-12-18 at 14 18 47" width="563" src="https://private-user-images.githubusercontent.com/24706726/291360293-f3e72aca-570d-4e11-aaf5-c1384dd1d2d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjM2NDUsIm5iZiI6MTcwMjkyMzM0NSwicGF0aCI6Ii8yNDcwNjcyNi8yOTEzNjAyOTMtZjNlNzJhY2EtNTcwZC00ZTExLWFhZjUtYzEzODRkZDFkMmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzFmMWUyMzdlNDFiZmNiYWY3YTVlYzIwNGE1M2UzODFhMTRkNmNhM2Y0M2I2M2E3MDVkZjMyZWJmOGM2YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VFqdEWyCNOa5sIOJY7Evt4WlWu1NfocE30VXv7_tWFA">
> 
> Check this #328

thanks
