### ISSUE TITLE
[BUG] Waiting for this message. This may take a while

### ISSUE THREAD

**Issue by EduardoBradial** [WhiskeySockets/Baileys#557]
When sending a message, the receptor receive a warning saying that the message is not available and that he has to wait for it, and this link too: [https://faq.whatsapp.com/3398056720476987?cms_id=3398056720476987&draft=false]

![image](https://github.com/WhiskeySockets/Baileys/assets/114176595/cfbfd7b8-bf76-4e07-8eee-44f1ff7f041e)

Unfortunately, i don't have the right path to reproduce this scenario, but it happens usually when sending messages to groups but also when sending to normal contacts sporadically.

**Expected behavior**
Send a message and the receptor receive it normally.

**My environment:**
 - Linux 20.04 server
 - There's multiple clients on the same IP

**Comment by lomeliDev** [comment]
How many clients do you have on the same IP?

**Comment by EduardoBradial** [comment]
> How many clients do you have on the same IP?

Arround 10 clients per server

**Comment by EduardoBradial** [comment]
> Send the code you are using in getMessage in the connection configuration

The problem is happening when I send the message, whoever, this is part of the code I believe is responsible to config the Baileys socket

 `const wsocket: Session = makeWASocket({
          logger: loggerBaileys,
          printQRInTerminal: false,
          auth: state,
          version,
          shouldIgnoreJid: jid => isJidBroadcast(jid),
          patchMessageBeforeSending: message => {
            const requiresPatch = !!(
              message.buttonsMessage ||
              message.templateMessage ||
              message.listMessage
            );
            if (requiresPatch) {
              message = {
                viewOnceMessageV2: {
                  message: {
                    messageContextInfo: {
                      deviceListMetadataVersion: 2,
                      deviceListMetadata: {}
                    },
                    ...message
                  }
                }
              };
            }

            return message;
          }
});`

**Comment by EduardoBradial** [comment]
> You need to configure it correctly and also include the getMessage function. You define as a bug what is not a bug, but rather a bad configuration, it is better to close this issue...

Thanks for the advise, I found this getMessage function now and will implement that on my use case.

**Comment by anshaneja5** [comment]
@EduardoBradial Can you help me? I am having the same problem in sending message. It mostly occurs in groups and that too when members are very large. How to tackle this and what is this getMessage function. Please help.

**Comment by gelpiu-developers** [comment]
I have this configuration and the issue is still happening? Do I need to ad something more?

```typescript
const { version, isLatest } = await fetchLatestBaileysVersion();
    const logger = P().child({ level: envConfig.logLevel });

    // external map to store retry counts of messages when decryption/encryption fails
    // keep this out of the socket itself, so as to prevent a message decryption/encryption loop across socket restarts
    const msgRetryCounterCache = new NodeCache();

    logger.info(
      `[Socket] Using WA v${version.join('.')}, isLatest: ${isLatest}`
    );

    this.socket = makeWASocket({
      version,
      logger,
      printQRInTerminal: true,
      auth: {
        creds: this.state.creds,
        keys: makeCacheableSignalKeyStore(this.state.keys, logger)
      },
      browser: Browsers.macOS('Desktop'),
      syncFullHistory: true,
      generateHighQualityLinkPreview: true,
      msgRetryCounterCache,
      // ignore all broadcast messages -- to receive the same
      // comment the line below out
      shouldIgnoreJid: (jid) => isJidBroadcast(jid),
      getMessage: async (key) => {
        if (this.store) {
          const msg = await this.store.loadMessage(key.remoteJid!, key.id!);
          return msg?.message || undefined;
        }

        // Only if store is present
        return proto.Message.fromObject({});
      },
      patchMessageBeforeSending: (message) => {
        const requiresPatch = !!(
          message.buttonsMessage ||
          message.templateMessage ||
          message.listMessage
        );
        if (requiresPatch) {
          message = {
            viewOnceMessage: {
              message: {
                messageContextInfo: {
                  deviceListMetadataVersion: 2,
                  deviceListMetadata: {}
                },
                ...message
              }
            }
          };
        }

        return message;
      }
    });
```

**Comment by EduardoBradial** [comment]
> [@EduardoBradial](https://github.com/EduardoBradial) Can you help me? I am having the same problem in sending message. It mostly occurs in groups and that too when members are very large. How to tackle this and what is this getMessage function. Please help.

So, basically you need to implement a function to recover that message. Baileys have a prebuilt option for you to configure in the makeWASocket function. This function should return the message from your store.

**IMPORTANT OBS:** In our case, we're working with multiple WhatsApp connections, so the messageId from group message should not be stored in the message.id, as it could lead into duplicated registers, so, in my case, the messages from a group has a whatsappId field, and i'm searching for it in the getMessage function.

The makeWASocket should look like this:

```
const wsocket: Session = makeWASocket({
          logger: loggerBaileys,
          printQRInTerminal: false,
          auth: state,
          version,
          getMessage,
          shouldIgnoreJid: jid => isJidBroadcast(jid),
          patchMessageBeforeSending: message => {
            const requiresPatch = !!(
              message.buttonsMessage ||
              message.templateMessage ||
              message.listMessage
            );
            if (requiresPatch) {
              message = {
                viewOnceMessageV2: {
                  message: {
                    messageContextInfo: {
                      deviceListMetadataVersion: 2,
                      deviceListMetadata: {}
                    },
                    ...message
                  }
                }
              };
            }

            return message;
          }
        }); 
```

The getMessage function:

```
const getMessage = async (
          key: proto.IMessageKey
        ): Promise<proto.IMessage | undefined> => {
          let messageToBeRetried = await Message.findByPk(key.id!);

          if (!messageToBeRetried) {
            const groupMessagesToBeRetried = await FindGroupMessagesService({
              idFromWhatsApp: key.id!
            });
            messageToBeRetried = groupMessagesToBeRetried ? groupMessagesToBeRetried[0] : null;
          }

          const dataJson = messageToBeRetried?.dataJson
            ? JSON.parse(messageToBeRetried.dataJson)
            : undefined;

          logInfo(
            "WASocket",
            "getMessage",
            `Key of the message to be retried: ${JSON.stringify(
              key,
              undefined,
              2
            )}`
          );

          return dataJson?.message;
        };
```
