### ISSUE TITLE
[BUG] Status Code 408

### ISSUE THREAD

**Issue by Jakquellyn** [WhiskeySockets/Baileys#573]
Error: Timed Out
    at /root/calestial/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:136:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/root/calestial/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:131:19)\n' +
      '    at waitForMessage (/root/calestial/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:114:53)\n' +
      '    at query (/root/calestial/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:136:22)\n' +
      '    at getUSyncDevices (/root/calestial/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:166:30)\n' +
      '    at /root/calestial/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:305:53\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Object.transaction (/root/calestial/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)\n' +
      '    at async Object.relayMessage (/root/calestial/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:278:9)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by Jakquellyn** [comment]
plise help me

**Comment by Jakquellyn** [comment]
> Send your connectOptions
const sock = makeWASocket({
        version,
        defaultQueryTimeoutMs: undefined,
        logger: Pino({ level: "silent" }),
        printQRInTerminal: true,
        shouldIgnoreJid: jid => isJidBroadcast(jid),
        browser: ['Calestial MD', 'Safari', '9.4.5'],
        auth: {
            creds: state.creds,
            /** caching makes the store faster to send/recv messages */
            keys: makeCacheableSignalKeyStore(state.keys, logger),
        },
        patchMessageBeforeSending: (message) => {
            const requiresPatch = !!(
                message.buttonsMessage ||
                // || message.templateMessage
                message.listMessage
            );
            if (requiresPatch) {
                message = {
                    viewOnceMessage: {
                        message: {
                            messageContextInfo: {
                                deviceListMetadataVersion: 2,
                                deviceListMetadata: {},
                            },
                            ...message,
                        },
                    },
                };
            }

            return message;
        },
        // implement to handle retries
        getMessage: async key => {
            if (store) {
                // if (alert.length < 4) alert.push(1)
                const msg = await store.loadMessage(key.remoteJid, key.id)
                return msg?.message || undefined
            }

            // only if store is present
            return {
                conversation: 'Failed to provide message'
            }
        }
    })

**Comment by Guilherme-j10** [comment]
up

**Comment by roysG** [comment]
up

**Comment by Lakshay-bit-png** [comment]
@Jakquellyn How did u Fixed it please tell....

**Comment by Jakquellyn** [comment]
> @Jakquellyn How did u Fixed it please tell....

idk bro

**Comment by RiyanRIS** [comment]
+1
