### ISSUE TITLE
[BUG] Error in \@whiskeysockets\baileys\lib\Utils\generics.js   Status Code 408

### ISSUE THREAD

**Issue by lucas-linvix** [WhiskeySockets/Baileys#579]
Hello everyone, I have a problem in my project, currently it is showing this error:

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/6c815d32-1ada-44f4-9a4c-da3c9a15dc2a)

I tried restarting my server but it had no effect. At the moment, my application is showing a lot of instability when sending messages and files, this was the only error I found in this regard. Could anyone help me with this?

**Comment by SheIITear** [comment]
Duplicate
