### ISSUE TITLE
[BUG] `__importStar` is defined multiple times

### ISSUE THREAD

**Issue by s43** [WhiskeySockets/Baileys#586]
**Describe the bug**
I am tying to implement baileys within my app ( typed with typescript ), but once I import the lib & initialize the socket I get this error, checked the file **messages-media.js** and found that there's a var declaration at the line 18.

`
./node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js
Error: 
  × the name `__importStar` is defined multiple times
 `

**To Reproduce**
1. Installed, and Imported the way mentioned on the docs.

**Expected behavior**

`
./node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js
Error: 
  × the name `__importStar` is defined multiple times
 `

<img width="683" alt="image" src="https://github.com/WhiskeySockets/Baileys/assets/4326571/23fa1bb5-7712-4837-8c7d-22881b8f2b3c">

**Environment (please complete the following information):**
- Nextjs App, dev mode

**Comment by s43** [comment]
Not sure why this being closed ?

**Comment by SheIITear** [comment]
Baileys does not offer support for bun, nextjs etc. Hence this is not a baileys bug. Feel free to join our discord server if you want to ask help with other topics.
