### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DenzzCompany** [WhiskeySockets/Baileys#59]
(node:23359) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fromMe' of undefined
1|index  |     at generateWAMessageFromContent (/root/xinzuov3.0.2/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:405:40)
1|index  |     at generateWAMessage (/root/xinzuov3.0.2/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:463:53)
1|index  |     at runMicrotasks (<anonymous>)
1|index  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1|index  |     at async Object.Socket.client.generateMessage (/root/xinzuov3.0.2/system/extra.js:59:22)
1|index  | (node:23359) UnhandledPromiseRejectionWarning: Unhandled promise rejection.

**Comment by guiireal** [comment]
The bug you are showing is without context, as the name itself suggests:

``´TypeError: Cannot read property 'fromMe' of undefined```

And it also indicates the file:

```root/xinzuov3.0.2/system/extra.js:59:22```

This is by no means an error of Baileys, please check your code, specifically the file extra.js, line 59.

**Comment by guiireal** [comment]
The bug you are showing is without context, as the name itself suggests:

```TypeError: Cannot read property 'fromMe' of undefined```

And it also indicates the file:

```root/xinzuov3.0.2/system/extra.js:59:22```

This is by no means an error of Baileys, please check your code, specifically the file extra.js, line 59.
