### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zetsubococaebom** [WhiskeySockets/Baileys#597]
Error in Pairing Code

The Latest Version of Baileys has just been released, not even 1 hour.  Since its launch, I have encountered an error that occurs when we request a code and enter it into WhatsApp.  The system responds "wrong code" after requesting the code.  I have tested this on Baileys version 6.5.0 and everything works fine, unlike this latest version.

Please fix it immediately.

**Comment by bolaxd** [comment]
I have the same problem

**Comment by zetsubococaebom** [comment]
> I have the same problem

Xixixixixixi

**Comment by T3uZ** [comment]
No problems here, I created what is doing something wrong

**Comment by zetsubococaebom** [comment]
> No problem here, I believe you are doing something wrong

do you use pairing code?

**Comment by Pokoke-01** [comment]
Change your browser description
```
browser: [ "Ubuntu", "Chrome", "20.0.04" ]
```

**Comment by bolaxd** [comment]
> Change your browser description
> 
> ```
> browser: [ "Ubuntu", "Chrome", "20.0.04" ]
> ```

Thanks for suggest

**Comment by zetsubococaebom** [comment]
> Change your browser description
> ```
> browser: [ "Ubuntu", "Chrome", "20.0.04" ]
> ```

thanks, it works

**Comment by JER-OFC** [comment]
> > Ubah deskripsi browser Anda
> > ```
> > browser: [ "Ubuntu", "Chrome", "20.0.04" ]
> > ```
> 
> terima kasih, itu berhasil

**Comment by Riders004** [comment]
> Change your browser description
> 
> ```
> browser: [ "Ubuntu", "Chrome", "20.0.04" ]
> ```

Can I use another is instead of Ubuntu ? And another browser instead of chrome ?
