### ISSUE TITLE
How to edit a message sent on whatsapp using bailyes.

### ISSUE THREAD

**Issue by vihangayt0** [WhiskeySockets/Baileys#60]
How to edit a message sent on whatsapp using bailyes.

**Comment by andresayac** [comment]
Edit message 

```
await sock.relayMessage(jid, {
  protocolMessage: {
    key: msg.key,
    type: 14,
    editedMessage: {
      conversation: "new text"
    }
  }
}, {})
```

**Comment by filipeloose** [comment]
@andresayac send the discord link

**Comment by andresayac** [comment]
> @andresayac send the discord link
> 
> 

 **Join the Discord [here](https://discord.gg/WeJM5FP9GG)**

**Comment by andresayac** [comment]
> How to edit a message sent on whatsapp using bailyes.

Closed this the issue please

**Comment by vihangayt0** [comment]
Thanks for help ❤️

**Comment by MuhammadRestu999** [comment]
> Thanks to ![image](https://user-images.githubusercontent.com/16548795/237989130-2de638e9-ad0b-4258-9746-2180f8275fe7.png)

that's me :v

**Comment by aidulcandra** [comment]
Is editing messages available now in all version of whatsapp?
