### ISSUE TITLE
[BUG] cannot process image with extension HEIC/HEIF

### ISSUE THREAD

**Issue by dimaslanjaka** [WhiskeySockets/Baileys#606]
**Describe the bug**
throw when sending image with HEIC/HEIF extension
![image](https://github.com/WhiskeySockets/Baileys/assets/12471057/87a7c9da-78c6-4314-a1f0-736856b83b4b)

**To Reproduce**
- send message with file image extension `HEIC` or `HEIF`

you can download the sample photos https://drive.google.com/drive/folders/10_81O4E_amy1cKpyX-vP56EjHtLxmTif?usp=sharing

**Expected behavior**
successful send reply message with png, jpg, webp, heif, heic extension.

**Environment (please complete the following information):**
 - Is this on a server? 
localhost OS windows

 - What do your `connectOptions` look like? 
```ts
this.sock = baileys.makeWASocket({
  version,
  logger: this.logger,
  printQRInTerminal: true,
  mobile: false,
  auth: {
    creds: state.creds,
    /** caching makes the store faster to send/recv messages */
    keys: baileys.makeCacheableSignalKeyStore(state.keys, this.logger)
  },
  msgRetryCounterCache: this.msgRetryCounterCache,
  generateHighQualityLinkPreview: true,
  // ignore all broadcast messages -- to receive the same
  // comment the line below out
  // shouldIgnoreJid: jid => isJidBroadcast(jid),
  // implement to handle retries & poll updates
  getMessage: this.getMessage
});
```

 - Do you have multiple clients on the same IP?
no

 - Are you using a proxy?
no

**Additional context**
-

**Comment by tb-sumberjaya** [comment]
Basically WhatsApp doesn't support that codec. Even if you successfully send it, the client will not be able to display it because the codec is not supported.
There are several alternatives:
1. Send that file as document instead of as image
2. Re-encode that file to another supported codec like jpeg, png, etc.
