### ISSUE TITLE
Id

### ISSUE THREAD

**Issue by Riders004** [WhiskeySockets/Baileys#609]
How can I find message I'd if user's message using Baileys

**Comment by SuhailTechInfo** [comment]
> How can I find message I'd if user's message using Baileys

*Check inside the message key :*
```
{
  key: {
    remoteJid: '923184474176@s.whatsapp.net',
    fromMe: true,
    id: 'BAE509E1CE501D26'  // this is message id
  }
}
```

## If message sent by baileys :
- Then message id must start with `BAE5`, like below ID.
```
   id: 'BAE509E1CE501D26'   // baileys message id
```

**Comment by Riders004** [comment]
> > How can I find message I'd if user's message using Baileys
> 
> _Check inside the message key :_
> 
> ```
> {
>   key: {
>     remoteJid: '923184474176@s.whatsapp.net',
>     fromMe: true,
>     id: 'BAE509E1CE501D26'  // this is message id
>   }
> }
> ```
> 
> ## If message sent by baileys :
> * Then message id must start with `BAE5`, like below ID.
> 
> ```
>    id: 'BAE509E1CE501D26'   // baileys message id
> ```

How can I check jt
