### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DGXeon** [WhiskeySockets/Baileys#612]
incorrect paircode in v6.6.0?🤔

**Comment by DGXeon** [comment]
Now its working, after i changed browser to browser: [ "Ubuntu", "Chrome", "20.0.04" ]

**Comment by Riders004** [comment]
It's not working now 

![Screenshot_2024-02-06-20-13-02-159_com gbwhatsapp](https://github.com/WhiskeySockets/Baileys/assets/120787636/ab6cc3c3-c5df-47cb-8e52-cc5fae53657e)


It's giving this issue 😔
