### ISSUE TITLE
[BUG] It doesn't work when entering the pairing code on WhatsApp

### ISSUE THREAD

**Issue by OvExeR** [WhiskeySockets/Baileys#613]
![screenshot-1706449280023](https://github.com/WhiskeySockets/Baileys/assets/44639216/29213851-63d5-4755-8215-7488c5ee2520)
![photo_2024-01-28_20-42-02](https://github.com/WhiskeySockets/Baileys/assets/44639216/d605ad30-adfc-4e97-859b-7598208cb27d)

Pairing Code tidak mau konek kenapa ya?

**Comment by Guru322** [comment]
> ![screenshot-1706449280023](https://private-user-images.githubusercontent.com/44639216/300266664-29213851-63d5-4755-8215-7488c5ee2520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTE1MzMsIm5iZiI6MTcwNjQ1MTIzMywicGF0aCI6Ii80NDYzOTIxNi8zMDAyNjY2NjQtMjkyMTM4NTEtNjNkNS00NzU1LTgyMTUtNzQ4OGM1ZWUyNTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE0MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYWRkY2ZkODUwZGZlMTJkMTExMDNiNTg0YTQxNjY2NDQxODhjMjAxYTE4ZmZjODE3OGMwZDkxZDUyMjRmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vd54Bss0PygIoFxj6zm05mErfAhNl7VR645ZIGOSjTs) ![photo_2024-01-28_20-42-02](https://private-user-images.githubusercontent.com/44639216/300266747-d605ad30-adfc-4e97-859b-7598208cb27d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTE1MzMsIm5iZiI6MTcwNjQ1MTIzMywicGF0aCI6Ii80NDYzOTIxNi8zMDAyNjY3NDctZDYwNWFkMzAtYWRmYy00ZTk3LTg1OWItNzU5ODIwOGNiMjdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE0MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMGVmYWZkYTM2ZWUwODkxMzlhNzY5MTRjNzBjZWEyOWQ1NWQzNTBkOTUyZjUyYjY1NjUxYmMxMGJkYzAxMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBuApSjJUyfP27vAE_YsyEAWitLjfdQ9ujbx1shAXPw)
> 
> Pairing Code tidak mau konek kenapa ya?

#597

**Comment by OvExeR** [comment]
> > ![screenshot-1706449280023](https://private-user-images.githubusercontent.com/44639216/300266664-29213851-63d5-4755-8215-7488c5ee2520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTE1MzMsIm5iZiI6MTcwNjQ1MTIzMywicGF0aCI6Ii80NDYzOTIxNi8zMDAyNjY2NjQtMjkyMTM4NTEtNjNkNS00NzU1LTgyMTUtNzQ4OGM1ZWUyNTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE0MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYWRkY2ZkODUwZGZlMTJkMTExMDNiNTg0YTQxNjY2NDQxODhjMjAxYTE4ZmZjODE3OGMwZDkxZDUyMjRmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vd54Bss0PygIoFxj6zm05mErfAhNl7VR645ZIGOSjTs) ![photo_2024-01-28_20-42-02](https://private-user-images.githubusercontent.com/44639216/300266747-d605ad30-adfc-4e97-859b-7598208cb27d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTE1MzMsIm5iZiI6MTcwNjQ1MTIzMywicGF0aCI6Ii80NDYzOTIxNi8zMDAyNjY3NDctZDYwNWFkMzAtYWRmYy00ZTk3LTg1OWItNzU5ODIwOGNiMjdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE0MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMGVmYWZkYTM2ZWUwODkxMzlhNzY5MTRjNzBjZWEyOWQ1NWQzNTBkOTUyZjUyYjY1NjUxYmMxMGJkYzAxMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBuApSjJUyfP27vAE_YsyEAWitLjfdQ9ujbx1shAXPw)
> > Pairing Code tidak mau konek kenapa ya?
> 
> #597

Thanks, work bang

**Comment by jeffersonveloso** [comment]
The problem persists with version 6.6.0.
