### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JER-OFC** [WhiskeySockets/Baileys#615]
alpha.sendMessage(m.chat, { document: { url: result.video.noWatermark, caption: ``}}, { quoted: m })

I am currently having difficulty creating a document in the form of a video. If I use this code, it will send a PDF, please help, thank you

**Comment by Rippanteq7** [comment]
Just add the mimetype, ex:

```javascript
alpha.sendMessage(m.chat, {
    document: { url: result.video.noWatermark },
    caption: '',
    mimetype: 'video/mp4', // mimetype goes here
}, { quoted: m })
```

**Comment by JER-OFC** [comment]
> Just add the mimetype, ex:
> 
> ```js
> alpha.sendMessage(m.chat, {
>     document: { url: result.video.noWatermark },
>     caption: '',
>     mimetype: 'video/mp4', // mimetype goes here
> }, { quoted: m })
> ```

Thank you bro, this method works

**Comment by JER-OFC** [comment]
Thank you bro, this method works
