### ISSUE TITLE
[BUG] erro de compatibilidade com sharp

### ISSUE THREAD

**Issue by Kaally** [WhiskeySockets/Baileys#616]
![Captura de tela de 2024-01-29 22-57-15](https://github.com/WhiskeySockets/Baileys/assets/119092658/11e499cb-d3ef-4171-a89f-1604a04c1579)

**A versão mais recente do Baileys está entrando em conflito com a última versão do sharp.**

**Comment by ImYanXiao** [comment]
> ![Captura de tela de 2024-01-29 22-57-15](https://private-user-images.githubusercontent.com/119092658/300665608-11e499cb-d3ef-4171-a89f-1604a04c1579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTQ4NDMsIm5iZiI6MTcwNjU5NDU0MywicGF0aCI6Ii8xMTkwOTI2NTgvMzAwNjY1NjA4LTExZTQ5OWNiLWQzZWYtNDE3MS1hODlmLTE2MDRhMDRjMTU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwNjAyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDRmY2U1YjJhMmJiNWFlOGVjMTlmYmYwY2FiNzVmNjM3NTc2NzNjZjY3NTQ5NmIwMzdkZTJkODI0MWIxYTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0QAbpX5M-YGmCR084BqBbjMtkKtUy1XE0ijNj8f4GO8)
> 
> **erro de compatibilidade com sharp**

A versão do pacote sharp do seu projeto entra em conflito com a versão do pacote sharp de Baileys
