### ISSUE TITLE
[BUG] Button SendMessage

### ISSUE THREAD

**Issue by ilhamn2405** [WhiskeySockets/Baileys#62]
![1683923992-picsay](https://github.com/WhiskeySockets/Baileys/assets/43334234/3f0fa4bb-9a25-478d-9b8b-7791eefd271a)
Saya menambahkan button di fitur isCmd, pesan di terima, tetapi tidak ada respon apapun (⁠╯⁠︵⁠╰⁠,⁠)

**Comment by andresayac** [comment]
this is already duplicated refer to
https://github.com/WhiskeySockets/Baileys/issues/56

**Comment by ilhamn2405** [comment]
> ini sudah digandakan merujuk ke #56

Means for now there is no solution?

**Comment by andresayac** [comment]
no friend for now, separators have recommended not to depend on this solution

**Comment by edgardmessias** [comment]
Duplicate of #56

**Comment by ryugenxd** [comment]
> > ini sudah digandakan merujuk ke #56
> 
> Means for now there is no solution?

>meng kadang", w asah ni parang  ```git pull```

**Comment by WatanabeThiago** [comment]
I'm waiting for this feature.
