### ISSUE TITLE
how i send xls file using api and show XLS file logo in whatsapp on android phone

### ISSUE THREAD

**Issue by spacesoft321** [WhiskeySockets/Baileys#627]
Hello Team 

we are using this api in waziper 

when i send a xls file using waziper api , its show pdf logo on WhatsApp in my phone

i share some screen shot and api 

![image](https://github.com/WhiskeySockets/Baileys/assets/6949772/16eee87c-7d49-43c6-aae0-b99daf9f3da1)

what i do for update icon in waziper api 

https://rcon.fastwsapi.com/api/send?number=84933313xxx&type=media&message=test+message&media_url=https%3A%2F%2Fi.pravatar.cc&filename=file_test.jpg&instance_id=609ACF283XXXX&access_token=652019f28f548

example : 

**https://rcon.fastwsapi.com/api/send?number=918878596325&type=media&message=test+message&media_url=https://sample-videos.com/xls/Sample-Spreadsheet-10-rows.xls&instance_id=65BCBCB272C5C&access_token=652019f28f548**

    public function send()
    {
        $json = file_get_contents('php://input');

        if (!empty($json)) {
            $json = json_decode($json);
        }

        $team_id = "";
        $instance_id = "";
        $access_token = "";
        $type = post("type");
        $message = post("message");
        $filename = post("filename");
        $media_url = post("media_url");
        $number = post("number");

        if (!empty($json) && isset($json->media_url)) $media_url = $json->media_url;
        if (!empty($json) && isset($json->filename)) $filename = $json->filename;
        if (!empty($json) && isset($json->message)) $message = $json->message;
        if (!empty($json) && isset($json->type)) $type = $json->type;
        if (!empty($json) && isset($json->instance_id)) $instance_id = $json->instance_id;
        if (!empty($json) && isset($json->access_token)) $access_token = $json->access_token;
        if (!empty($json) && isset($json->number)) $number = $json->number;

        $team = self::get_team($access_token);
        $team_id = $team->id;
        $access_token = $team->ids;
        $instance_id = self::get_instance_id($instance_id);

        $session = db_get("*", TB_WHATSAPP_SESSIONS, ["team_id" => $team_id, "instance_id" => $instance_id]);

        if (!$session) {
            return $this->respond(["status" => "error", "message" => __("Instance ID Invalidated")]);
        }

        if ($session->status == 0) {
            return $this->respond(["status" => "error", "message" => __("This instance ID has not been activated yet")]);
        }

        $account = db_get("*", TB_ACCOUNTS, ["team_id" => $team_id, "token" => $instance_id]);

        if (!$account) {
            return $this->respond(["status" => "error", "message" => __("Account does not exist")]);
        }

        if ($account->status == 0) {
            return $this->respond(["status" => "error", "message" => "This WhatsApp account relogin required"]);
        }

        if ($number == "" || !is_numeric($number)) {
            return $this->respond(["status" => "error", "message" => __("Phone number is required")]);
        }

        if ($media_url == "" && $message == "") {
            return $this->respond(["status" => "error", "message" => __("Please enter media url or message")]);
        }

        $response = wa_post_curl("send_message", [
            "instance_id" => $instance_id,
            "access_token" => $access_token
        ], [
            "media_url" => $media_url,
            "chat_id" => $number . "@s.whatsapp.net",
            "caption" => $message,
            "filename" => $filename
        ]);

        return $this->respond((array)$response);
    }

Please update code for file type format

**Comment by SuhailTechInfo** [comment]
> when i send a xls file using waziper api , its show pdf logo on WhatsApp in my phone

**Dude try to use `mimetype` for `xls` files**
###  i found following mimetype for `xls` file
```
 "mimetype" : "application/vnd.ms-excel", 
```
- Try to use above mimetype,
- If not works then google it `(about what's xls mimetype)`



<br><br>
### Implement According to your code like below : 
```
[
        "media_url" => $media_url,
        "chat_id" => $number . "@s.whatsapp.net",
        "caption" => $message,
        "mimetype" => "application/vnd.ms-excel", // Set it According to your code
        "filename" => $filename
]
```

***Hope it'll helpFull !***

**Comment by spacesoft321** [comment]
i know about         "mimetype" => "application/vnd.ms-excel", // Set it According to your code

but how i set file format in api , where we set file format

my.fastwsapi.com
