### ISSUE TITLE
Send Status is Working But One Problem...

### ISSUE THREAD

**Issue by RavensVenix** [WhiskeySockets/Baileys#629]
OK, so the story is that I was making a harsh words filter then tried it and yes it worked but I forgot to put the word c** and it was sent to status, on my WhatsApp the status has been deleted but others can still see it.

AND MORE STUPIDLY I TRIED IT ON THE MAIN ACCOUNT WHICH CONTAINS PERSONAL CONTACTS LIKE TEACHER, MOM, DAD

THE QUESTION IS HOW DO I REMOVE IT? I JUST REALIZED WHEN A FRIEND TOLD ME THAT MY STATUS WASN'T DELETED

(Sorry if I open issues on Github, I don't have Discord)

**Comment by Riders004** [comment]
Can you share send status code ?

**Comment by RavensVenix** [comment]
To All Contacts?

> Can you share send status code ?
