### ISSUE TITLE
COMO SABER QUAL OPÇÃO O USUARIO VOTOU NA ENQUETE

### ISSUE THREAD

**Issue by Inaciooooo** [WhiskeySockets/Baileys#63]
Tipo quero usar enquete como botão aí preciso saber como o baileys sabe qual opçao da enquete o usuário votou me ajudem por favor

**Comment by kodmanyagha** [comment]
+1

**Comment by andresayac** [comment]
https://github.com/WhiskeySockets/Baileys/issues/38

**Comment by Rony-S** [comment]
> #38

Mas está dae não está funcionando comigo

**Comment by Laxeder** [comment]
Speak in English please!! (Fale em ingles por favor!!).

```ts
import { decryptPollVote } from "@whiskeysockets/baileys";

```

**Comment by Laxeder** [comment]
Speak in English please!! (Fale em ingles por favor!!).

```ts
import { decryptPollVote } from "@whiskeysockets/baileys";
import digestSync from "crypto-digest-sync";

const pollCreation: proto.IWebMessageInfo;
const pollUpdate: proto.IWebMessageInfo;
const voterJid = pollUpdate.key.fromMe ? client.id : pollUpdate.key.participant || pollUpdate.key.remoteJid;
const savedVotes: { [id: string]: string[] } = {};

const poll = decryptPollVote(pollUpdate.message.pollUpdateMessage.vote, {
  pollCreatorJid: pollCreation.key.fromMe ? client.id : pollCreation.key.participant || pollCreation.key.remoteJid,
  pollMsgId: pollUpdate.message.pollUpdateMessage.pollCreationMessageKey.id,
  pollEncKey: pollCreation.message.messageContextInfo.messageSecret,
  voterJid,
});

const votesAlias: { [name: string]: string } = {};
const hashVotes: string[] = poll.selectedOptions.map((opt) => Buffer.from(opt).toString("hex").toUpperCase()).sort();
const oldVotes: string[] = savedVotes[voterJid].sort();
const nowVotes: string[] = [];

// Get hash votes values
for (const opt of pollCreation.message.pollCreationMessage.options) {
  const hash = Buffer.from(digestSync("SHA-256", new TextEncoder().encode(Buffer.from(opt.optionName).toString())))
    .toString("hex")
    .toUpperCase();

  votesAlias[opt.optionName] = opt.optionName;

  if (hashVotes.includes(hash)) {
    nowVotes.push(opt.optionName);
  }
}

let vote: string | null = null;
let action: "add" | "remove" = "add";

const avaibleVotes = Object.keys(votesAlias);

for (const name of avaibleVotes) {
  if (nowVotes.length > oldVotes.length) {
    if (oldVotes.includes(name) || !nowVotes.includes(name)) continue;

    action = "add";
    vote = votesAlias[name];

    break;
  } else {
    if (nowVotes.includes(name) || !oldVotes.includes(name)) continue;

    action = "remove";
    vote = votesAlias[name];

    break;
  }
}
```

You need to save the votes you cast to check which vote was added or removed. Each pollUpdate returns only the votes of the user who voted.

The system I made to get the votes. If anyone works with cryptography and knows how to decrypt it, I'm open to suggestions to solve the hash votes.

The *pollMessage* can be retrieved from the return of *sendMessage*

I used "crypto-digest-sync" to solve some problems with crypto;

```
npm i crypto-digest-sync
```

**Comment by andresayac** [comment]
english please 


https://github.com/WhiskeySockets/Baileys/issues/38

> Mas está dae não está funcionando comigo
how are you trying that's right

**Comment by Rony-S** [comment]
> 

This function doesn't work for me, I use nodejs

**Comment by andresayac** [comment]
> > 
> 
> This function doesn't work for me, I use nodejs



I don't understand, the two options are valid for javascript and typescript with some changes

**Comment by Rony-S** [comment]
> > > 
> > 
> > 
> > Esta função não funciona para mim, eu uso nodejs
> 
> Não entendi, as duas opções são válidas para javascript e typescript com algumas alterações

I couldn't apply it in javascript can you show me an example on insta?

**Comment by andresayac** [comment]
This is not the final script, it was very improvised to create a bot, but the important thing is that I understand how it works and I try to emit events to read them later. I use a very good library to generate bots called .

https://github.com/andresayac/poll_example_bot_baileys
