### ISSUE TITLE
[BUG] Cannot find name 'Store'. Did you mean 'Storage'?

### ISSUE THREAD

**Issue by Santy1422** [WhiskeySockets/Baileys#633]
**Describe the bug**
66.99 node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.d.ts(2,50): error TS2552: Cannot find name 'Store'. Did you mean 'Storage'?

**To Reproduce**
deploy in railway

**Environment (please complete the following information):**

    "@types/socket.io-client": "^3.0.0",
    "@whiskeysockets/baileys": "6.6.0",
  "overrides": { 
    "cache-manager": "5.2.2"
  },
**Additional context**

**Comment by Rippanteq7** [comment]
> **Describe the bug** 66.99 node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.d.ts(2,50): error TS2552: Cannot find name 'Store'. Did you mean 'Storage'?
> 
> **To Reproduce** deploy in railway
> 
> **Environment (please complete the following information):**
> 
> ```
> "@types/socket.io-client": "^3.0.0",
> "@whiskeysockets/baileys": "6.6.0",
> ```
> 
> "overrides": { "cache-manager": "5.2.2" }, **Additional context** Add any other context about the problem here.

#611

**Comment by PurpShell** [comment]
fixed
