### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JER-OFC** [WhiskeySockets/Baileys#634]
![Screenshot_2024-02-06-16-13-31-57_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/WhiskeySockets/Baileys/assets/138082354/4757a5dc-a12d-4eb3-9b1e-f2c4e553195e)

Please help, I can't enter the code and it always fails, I've also used it

browser: [ "Ubuntu", "Chrome", "20.0.04" ],

**Comment by Riders004** [comment]
Use delay option

**Comment by Riders004** [comment]
Same error I'm getting

**Comment by ImYanXiao** [comment]
> ![Screenshot_2024-02-06-16-13-31-57_6012fa4d4ddec268fc5c7112cbb265e7](https://private-user-images.githubusercontent.com/138082354/302566474-4757a5dc-a12d-4eb3-9b1e-f2c4e553195e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzM1NjEsIm5iZiI6MTcwNzI3MzI2MSwicGF0aCI6Ii8xMzgwODIzNTQvMzAyNTY2NDc0LTQ3NTdhNWRjLWExMmQtNGViMy05YjFlLWYyYzRlNTUzMTk1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjM0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjE1ZGIyYTZlZDk3YmJhZmNkYTQ0ODM1MzYxOThhZWI0MDQ1NjA4MjMyY2QyYmIwMmNhZGEyY2Y0NTQ4NmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XpZ0qj0_yNZja6tOrhhKfqLMAzInGZoXFSxXlpnwHJ8)
> 
> Please help, I can't enter the code and it always fails, I've also used it
> 
> browser: [ "Ubuntu", "Chrome", "20.0.04" ],

https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326

**Comment by ImYanXiao** [comment]
> ![Screenshot_2024-02-06-16-13-31-57_6012fa4d4ddec268fc5c7112cbb265e7](https://private-user-images.githubusercontent.com/138082354/302566474-4757a5dc-a12d-4eb3-9b1e-f2c4e553195e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzM3MTgsIm5iZiI6MTcwNzI3MzQxOCwicGF0aCI6Ii8xMzgwODIzNTQvMzAyNTY2NDc0LTQ3NTdhNWRjLWExMmQtNGViMy05YjFlLWYyYzRlNTUzMTk1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmM5OWIzMWUxYTU0MzFkMTcwZGE2MWM3YjAyNTI5OWM3MTY0MGE4ODJmNjY1NDcwMDQ4M2RjOTQ3M2RiYzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5WUcG_7ktl6DJn9iIaLJu-94rDKYyGc0v96c87Hvoks)
> 
> Please help, I can't enter the code and it always fails, I've also used it
> 
> browser: [ "Ubuntu", "Chrome", "20.0.04" ],

Try this, ['Mac OS', 'safari', '5.1.10']

**Comment by Riders004** [comment]
> > ![Screenshot_2024-02-06-16-13-31-57_6012fa4d4ddec268fc5c7112cbb265e7](https://private-user-images.githubusercontent.com/138082354/302566474-4757a5dc-a12d-4eb3-9b1e-f2c4e553195e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzM3MTgsIm5iZiI6MTcwNzI3MzQxOCwicGF0aCI6Ii8xMzgwODIzNTQvMzAyNTY2NDc0LTQ3NTdhNWRjLWExMmQtNGViMy05YjFlLWYyYzRlNTUzMTk1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmM5OWIzMWUxYTU0MzFkMTcwZGE2MWM3YjAyNTI5OWM3MTY0MGE4ODJmNjY1NDcwMDQ4M2RjOTQ3M2RiYzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5WUcG_7ktl6DJn9iIaLJu-94rDKYyGc0v96c87Hvoks)
> > Please help, I can't enter the code and it always fails, I've also used it
> > browser: [ "Ubuntu", "Chrome", "20.0.04" ],
> 
> Try this, ['Mac OS', 'safari', '5.1.10']

I'm using [ "Windows", "Firefox", "10.0.22621" ]
Still same problem
B

**Comment by Guru322** [comment]
> 
> Please help, I can't enter the code and it always fails, I've also used it
> 
> browser: [ "Ubuntu", "Chrome", "20.0.04" ],

![image](https://github.com/WhiskeySockets/Baileys/assets/106463398/20778fa1-5a4b-4fb3-80a2-c8ec39d7e07f)

**Comment by Riders004** [comment]
> > Please help, I can't enter the code and it always fails, I've also used it
> > browser: [ "Ubuntu", "Chrome", "20.0.04" ],
> 
> ![image](https://private-user-images.githubusercontent.com/106463398/302863916-20778fa1-5a4b-4fb3-80a2-c8ec39d7e07f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODIyNjIsIm5iZiI6MTcwNzI4MTk2MiwicGF0aCI6Ii8xMDY0NjMzOTgvMzAyODYzOTE2LTIwNzc4ZmExLTVhNGItNGZiMy04MGEyLWM4ZWMzOWQ3ZTA3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNDU5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmI4YTY0NDNmOTg4ZmIwN2JmNmYxODZiOGNkZTA1OGNjZDBjYmQzMjExYTBhNGNiZTVmMWEzY2M4NzBkNDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BGmx-IeFTAYhvAONQ7yZYwWl_D03CqELdoZf6T_bYR0)

But pehle to sahi tha Mera me to Firefox use kar rh hu ?

**Comment by Guru322** [comment]
> But pehle to sahi tha Mera me to Firefox use kar rh hu ?
[Adopt to changes](https://www.britannica.com/science/survival-of-the-fittest)

**Comment by Riders004** [comment]
> > But pehle to sahi tha Mera me to Firefox use kar rh hu ?
> > [Adopt to changes](https://www.britannica.com/science/survival-of-the-fittest)

Ye konsi link di di apne 🙁

**Comment by Guru322** [comment]
> Ye konsi link di di apne 🙁
Padhle usse

**Comment by Riders004** [comment]
> > Ye konsi link di di apne 🙁
> 
> Padhle usse

Me iz not science student 😂

**Comment by Guru322** [comment]
> > > Ye konsi link di di apne 🙁
> > 
> > 
> > Padhle usse
> 
> Me iz not science student 😂

Galat field mai aa gye Aap
Science lena chaiye tha aapko

**Comment by Riders004** [comment]
> > Science bhag jati hai mujhe dekh kar to kese leta me Science or math dono bhag jate mujhe dekh kar 😂
> 
> Ye bhi accha hai

Ha to ab dm aao bot number pe
