### ISSUE TITLE
[BUG] Pairing Code Not work

### ISSUE THREAD

**Issue by charlesslim** [WhiskeySockets/Baileys#636]
Pairing code error bro

**Comment by danitechnology** [comment]
> > Pairing code error bro
> 
> browser: ['Mac OS', 'chrome', '121.0.6167.159']

This is very helpful, thank you

**Comment by Lursy** [comment]
> > Erro de código de emparelhamento, mano
> 
> navegador: ['Mac OS', 'cromo', '121.0.6167.159']

the code is returned **but does not work**

**Comment by Riders004** [comment]
> > Pairing code error bro
> 
> browser: ['Mac OS', 'chrome', '121.0.6167.159']

Bro

**Comment by Riders004** [comment]
> @Riders004 If it still doesn't work, use this browser code: `browser: ['Windows', 'Firefox', '123.0']`

Bro I'm getting ban

**Comment by NekoSenpai69** [comment]
> Pairing code error bro

Use 6.5.0v and keep printInTerminal: true/false
And browser:["Chrome (Linux)","",""] in config

**Comment by Riders004** [comment]
> > Pairing code error bro
> 
> Use 6.5.0v and keep printInTerminal: true/false And browser:["Chrome (Linux)","",""] in config

Can't connecting to WhatsApp

**Comment by jacruz** [comment]
It works for me: https://github.com/WhiskeySockets/Baileys/issues/636#issuecomment-1960760279
