### ISSUE TITLE
SyntaxError: Cannot declare a var variable that shadows a let/const/class variable: '__importStar'.

### ISSUE THREAD

**Issue by jDiegoMartinez** [WhiskeySockets/Baileys#637]
![Selección_197](https://github.com/WhiskeySockets/Baileys/assets/49005854/30732e0e-909f-4ac7-b077-9820c22725a3)

**Comment by jDiegoMartinez** [comment]
Can you help me, what can I do?

**Comment by SheIITear** [comment]
Looks like you are trying to use bun or something similar which is not supported.

**Comment by Araxeus** [comment]
https://github.com/oven-sh/bun/issues/5732
