### ISSUE TITLE
Continue WhatsApp Web Session

### ISSUE THREAD

**Issue by sebastian-heinz** [WhiskeySockets/Baileys#645]
Would there be a way to transfer an existing WhatsApp web session or continue it via this project?
I can imagine a new credentials provider that takes the IndexDB path as input for example, would something like this be possible?
I'd also volunteer to work on this, but I am not quite sure about the mapping and minimal required information to fill out in the `AuthenticationCreds` properties.

Any thoughts?
Thanks!

**Comment by dsgremmy** [comment]
Hi, I am interested in this

I have a WA Web session (local or on the server) and I would like to know if with Baileys I can connect to it.

Or the only way to use Baileys is to create a new session (QR).
