### ISSUE TITLE
[BUG] Slow Media Decryption Performance Under High Message Traffic via WhatsApp API

### ISSUE THREAD

**Issue by lucasdoctype** [WhiskeySockets/Baileys#647]
When there's a high volume of messages being processed by the WhatsApp API, the response time for decrypting media files (such as images, videos, audios) received in messages significantly increases, leading to notable delays in retrieving these files. This issue seems to occur during periods of intense message traffic.

**Comment by azudindaem** [comment]
This is not a bug. You need to handle traffic from the API side, depending on the number of sessions in your node.

**Comment by lucasdoctype** [comment]
I've already addressed the issue of request queuing by implementing multi-threading on the node, allowing for concurrent processing. The API on my end is functioning smoothly. However, the problem persists with the downloadContentFromMessage function, which takes a considerable amount of time to return the decrypted file even when handling high volumes of messages. This delay occurs specifically during the decryption process, indicating that the bottleneck is not with the handling of the message traffic on my side but with the time it takes for the API function to process and decrypt media files. Here's an outline of the implementation for downloading content, showing retries and backoff strategy in case of failures:


while (contDownload < 10 && !stream) {
  try {
    stream = await downloadContentFromMessage(
      msg.message.audioMessage ||
        msg.message.videoMessage ||
        msg.message.documentMessage ||
        msg.message.imageMessage ||
        msg.message.stickerMessage ||
        msg.message.extendedTextMessage?.contextInfo.quotedMessage.imageMessage ||
        msg.message?.buttonsMessage?.imageMessage ||
        msg.message?.templateMessage?.fourRowTemplate?.imageMessage ||
        msg.message?.templateMessage?.hydratedTemplate?.imageMessage ||
        msg.message?.templateMessage?.hydratedFourRowTemplate?.imageMessage ||
        msg.message?.interactiveMessage?.header?.imageMessage,
      messageType
    );
  } catch (error) {
    contDownload++;
    await new Promise(resolve =>
      setTimeout(resolve, 1000 * contDownload * 2)
    );
    logger.warn(`>>>> erro ${contDownload} de baixar o arquivo ${msg?.key.id}`);
  }
}
This code effectively manages retries and increases wait time exponentially, suggesting that the issue lies with the API's media decryption process during high traffic periods, not with our traffic handling or session management.

**Comment by vitortoigo** [comment]
Can do this with a background queue to dont impact requests performance

**Comment by PurpShell** [comment]
I suggest you offload your media decryption. To some other process or if you have a frontend that you display this media on, you can decrypt there
