### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Riders004** [WhiskeySockets/Baileys#657]
const startSock = async() => {
	const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')
	// fetch latest version of WA Web
	const { version, isLatest } = await fetchLatestBaileysVersion()
	console.log(`using WA v${version.join('.')}, isLatest: ${isLatest}`)

	const sock = makeWASocket({
		version,
		logger,
		printQRInTerminal: !usePairingCode,
		mobile: useMobile,
		auth: state
	})

	store?.bind(sock.ev)

Can I use upoer connection method to connect to WhatsApp instead of below one 

const startSock = async() => {
	const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')
	// fetch latest version of WA Web
	const { version, isLatest } = await fetchLatestBaileysVersion()
	console.log(`using WA v${version.join('.')}, isLatest: ${isLatest}`)

	const sock = makeWASocket({
		version,
		logger,
		printQRInTerminal: !usePairingCode,
		mobile: useMobile,
		auth: {
			creds: state.creds,
			/** caching makes the store faster to send/recv messages */
			keys: makeCacheableSignalKeyStore(state.keys, logger),
		},
		msgRetryCounterCache,
		generateHighQualityLinkPreview: true,
		// ignore all broadcast messages -- to receive the same
		// comment the line below out
		// shouldIgnoreJid: jid => isJidBroadcast(jid),
		// implement to handle retries & poll updates
		getMessage,
	})

	store?.bind(sock.ev)

**Comment by SuhailTechInfo** [comment]
> Can I use upoer connection method to connect to WhatsApp instead of below one

***Yes You can use Above method too!***



## My Connection Config
```
    const { state, saveCreds } = await useMultiFileAuthState(__dirname + baileys)
    let sock = SuhailMDConnect({
      logger: Pino({ level: "silent"||"debug"||"fatal" }).child({ level: "silent" }), 
      browser: [ 'Suhail',  'chrome', '121.0.6167.159'],
      generateHighQualityLinkPreview: true, // For Larger link Preview
      auth : state,
      getMessage,
    })
    store.bind(sock.ev)
```
