### ISSUE TITLE
[feat] adjust baileys to run in BUN

### ISSUE THREAD

**Issue by LucasSaud** [WhiskeySockets/Baileys#660]
it`s possible to adjust baileys code to run in bun?

**Comment by SheIITear** [comment]
No, bun does not support some websocket features and is missing some crypto stuff as well.

**Comment by jlucaso1** [comment]
@LucasSaud @SheIITear with this adjustments will be possible to run:
https://github.com/WhiskeySockets/libsignal-node/pull/6

**Comment by jgoyvaerts** [comment]
@SheIITear  any chance we can get this PR merged? it would solve the issue of not being able to run on Bun, everything else works fine (even though Bun has some limited websocket support, everything seems to work as expected)

**Comment by SheIITear** [comment]
Oh sorry, these comments have somehow went under my notifications. I'll check them asap after I finish with my school project tonight.

**Comment by SheIITear** [comment]
I did some quick test and seems to work, merged.
