### ISSUE TITLE
[BUG] bug send media video/audio slow

### ISSUE THREAD

**Issue by AKAZAMD** [WhiskeySockets/Baileys#663]
case "play": {
  if (!isReg) return reply(global.info.reg);

  try {
    if (!text) return zareply(`Gunakan contoh ${command} Dj dalinda`);

    const yts = require('yt-search');
    let results = await yts(text);
    let url = results.videos[0].url;
    let api = await ytal(url);

    const caption = `
╭─────〔 A L M D  P L A Y 〕─────╮
⭐ Judul: ${api.title}
🔗 Link: ${url}
🔗 URL Video: ${url}
╰─────────────────────╯`;

    reply(`tes ${url}\nthumb ${api.thumbnail}\nlagu ${api.audio}`)

    let response = await axios.get(api.audio, { responseType: 'arraybuffer' });
    let buffer = Buffer.from(response.data);

    let pathnya = `./${api.title}` + `.mp3`;
    await fs.writeFileSync(pathnya, buffer);

    conn.sendMessage(m.chat, { audio: fs.readFileSync(pathnya), mimetype: 'audio/mp4', ptt: false }, { quoted: m });
  } catch (error) {
    console.error(error);
    reply(`Terjadi kesalahan: ${error}`);
  }
}
break;
very very slow to send media and not play

**Comment by AKAZAMD** [comment]
![Screenshot_20240229-190414_WhatsApp�Business](https://github.com/WhiskeySockets/Baileys/assets/138199422/38401b6c-31e4-4b1d-809e-272f53e683ee)
not played

**Comment by bolaxd** [comment]
apa result url dari api? Coba infokan log ny

**Comment by AKAZAMD** [comment]
> apa result url dari api? Coba infokan log ny
ya api ytal scraper yang sayabuat tapi url muncul saat ku coba write bisa tapi pas saya kirim sangat sangat lama dan sekarang dapat di putar untuk audio denga menyatuhkan case dan scraper
case "play": {
  if (!isReg) return reply(global.info.reg);
try{
      if (!text) {
      return conn.reply(m.chat, `Gunakan contoh ${usedPrefix}${command} Dj dalinda`, m);
    }
let user = global.db.data.users[m.sender]
if (user.limit < 10) return reply('limitlu kurang minimal 10limit untuk pake ni fitur')
if (user.money < 2000) return reply('uang mu kurang minimal 2000 untuk pake ni fitur')
    // Kurangi limit dan money pengguna
    global.db.data.users[m.sender].limit -= 10;
    global.db.data.users[m.sender].money -= 2000;

    // Cari video di YouTube
    let search = await yts(text)
    let anu = search.videos[Math.floor(Math.random() * search.videos.length)]


    const caption = `
╭─────〔 AL MD  P L A Y 〕─────╮
Title : ${anu.title}
Ext : Search
ID : ${anu.videoId}
Duration : ${anu.timestamp}
Viewers : ${anu.views}
Upload At : ${anu.ago}
Author : ${anu.author.name}
Channel : ${anu.author.url}
Description : ${anu.description}
Url : ${anu.url}
╰─────────────────────╯
`;

const response = await axios.get(`https://api.revanced.net/get-video?url=${anu.url}`);
      const data = response.data;
const vid = {};
const aud = {};
      data.files.forEach(file => {
        if (file.type === 'audio' && file.fileExtension === '.webm') {
          aud[file.quality] = file.downloadUrl;
        } 
      });
data.files.forEach(file => {
        if (file.type === 'muxed', 'video' && file.fileExtension === '.mp4') {
          vid[file.quality] = file.url;
        } 
      });
      console.log(aud)
    conn.sendText(m.chat, caption, m, {
      contextInfo: {
        externalAdReply: {
          showAdAttribution: true,
          mediaType: 2,
          body: "ALmd", 
          sourceUrl: anu.url,
        },
      },
    });
    const doc = {
      audio: {
        url: aud["null"],
      },
      mimetype: 'audio/mp4',
      fileName: `${anu.title}.mp4`,
    };
 
   return conn.sendMessage(m.chat, doc, { quoted: m });
  } catch (error) {
    console.error(error);
    reply('Terjadi kesalahan. Silakan coba lagi nanti...');
  }
};
break;

kode diatas mampu untuk mengirim sangat lama sekalih
