### ISSUE TITLE
SendMessage as Poll

### ISSUE THREAD

**Issue by hardknockdays** [WhiskeySockets/Baileys#664]
with BOT that can send a message as a Poll we can collect data for survey more easier, just like what our audience looking for in our bot.![Screenshot_20240301-031505184 (1).jpg](https://github.com/WhiskeySockets/Baileys/assets/46776762/92a718f1-62bc-4934-8a05-59a392382971)

**Comment by daniel672-boo** [comment]
> with BOT that can send a message as a Poll we can collect data for survey more easier, just like what our audience looking for in our bot.![Screenshot_20240301-031505184 (1).jpg](https://private-user-images.githubusercontent.com/46776762/309061997-92a718f1-62bc-4934-8a05-59a392382971.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTE5NTcsIm5iZiI6MTcwOTU5MTY1NywicGF0aCI6Ii80Njc3Njc2Mi8zMDkwNjE5OTctOTJhNzE4ZjEtNjJiYy00OTM0LThhMDUtNTlhMzkyMzgyOTcxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDIyMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMzI0NmU3NWNmYjQ3MzQ4ZmU0ZjdlYWQ4MWIxMjViZjA5NDk4MmM2YjA0NzY3MzU1YTJlZDQ5OGFmN2ZlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sxeAluJE_vemikBw-xAuVJbFusf9ZxNJeAfPAeaLRhM)

sock.sendMessage(id, { poll: { name: "ph", value: ["1", "2"] } })

**Comment by hardknockdays** [comment]
How about turn off Allow multiple answer?
