### ISSUE TITLE
[BUG] Losing some Messages in Baileys WhatsApp API

### ISSUE THREAD

**Issue by lucasdoctype** [WhiskeySockets/Baileys#668]
Hello,

I am currently developing a WhatsApp application using the Baileys WhatsApp API, and I've encountered an issue where some messages are getting lost or not being captured by my event listeners. I have set up listeners for "messages.upsert" and "messages.update" events to handle incoming and updated messages respectively. Here is a simplified version of my setup:

wsocket = makeWASocket({
  logger: loggerBaileys,
  printQRInTerminal: false,
  auth: state as AuthenticationState,
  version,
  msgRetryCounterCache,
  getMessage: async key => {
    if (store) {
      const msg = await store.loadMessage(key.remoteJid!, key.id!);
      return msg?.message || undefined;
    }
  }
});

Handling messages.upsert Event:

wbot.ev.on("messages.upsert", async (messageUpsert) => {
  logger.info(`RECEIVED FROM BAILEYS -> ${JSON.stringify(messageUpsert?.messages[0])}`);
  const messages = messageUpsert.messages.filter(filterMessages).map(msg => msg);
  if (messages == null || messages.length === 0 || messages === undefined ) return;
  messagesArray.push({msg: messages[0], wbot});
});

wbot.ev.on("messages.update", (messageUpdate) => {
  logger.info(`RECEIVED FROM BAILEYS MESSAGES_UPDATE -> ${JSON.stringify(messageUpdate)}`);
  if (messageUpdate.length === 0) return;
  messageUpdate.forEach(async (message) => {
    handleMsgAck(message, message.update.status);
  });
});

Despite this setup, I'm noticing that some messages are either not being captured by the event listeners or are being lost before they can be handled. This issue is causing significant gaps in the message flow, and I'm concerned about the reliability of message capture for my application's functionality.

Could you provide any insights or recommendations on how to ensure that all messages are reliably captured and no messages are lost? Are there any additional events or error handling mechanisms that I should implement to address this issue?

Thank you for your assistance.

**Comment by lucasdoctype** [comment]
unfortunately :(

**Comment by Riders004** [comment]
Waiting for message issue ?
