### ISSUE TITLE
[BUG] Lost conection when send message to ~ 900 devices in same group

### ISSUE THREAD

**Issue by vinikjkkj** [WhiskeySockets/Baileys#669]
**Describe the bug**
it's in title

**To Reproduce**
1. Try to send message to a big group

**Expected behavior**
Send message with no problem

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**
I tried to use proxy, but didn't got success 

***SOCKET***

makeWASocket({
  browser: ['Chrome (Linux)', '', ''],
  printQRInTerminal: false,
  auth: state,
  syncFullHistory: false,
  msgRetryCounterCache: retryMessageCache
})

***LOGS***

`{"level":20,"time":1709747233945,"pid":32448,"hostname":"srv432719","jid":"GROUPID@g.us","msg":"adding device identity"}
{"level":20,"time":1709747233945,"pid":32448,"hostname":"srv432719","msgId":"BAE5EAEF778BF30F","msg":"sending message to 949 devices"}`

***ERROR***

`{"statusCode":408,"payload":{"statusCode":408,"error":"Request Time-out","message":"Connection was lost"},"headers":{}}`

**Comment by vinikjkkj** [comment]
I found the error, the encodeBinaryNode function that is called in the sendNode function was taking up 100% of my cpu and stoping my code, closing the session with WhatsApp, I hope this helps someone

**Comment by Fonnte** [comment]
are you closing this because you've found with solution? if yes, do you mind sharing?

**Comment by vinikjkkj** [comment]
> are you closing this because you've found with solution? if yes, do you mind sharing?

As I said before, this was occurring because my CPU got 100% workload to process message, stoping the connection.

If is occurring for you, change the bot machine to more powerful one

**Comment by vinikjkkj** [comment]
> > I found the error, the encodeBinaryNode function that is called in the sendNode function was taking up 100% of my cpu and stoping my code, closing the session with WhatsApp, I hope this helps someone
> 
> How did you arrive at this conclusion?

tests

**Comment by Shubhamrawat5** [comment]
Facing same problem

**Comment by AlvaroBrasilia** [comment]
> > > I found the error, the encodeBinaryNode function that is called in the sendNode function was taking up 100% of my cpu and stoping my code, closing the session with WhatsApp, I hope this helps someone
> > 
> > 
> > How did you arrive at this conclusion?
> 
> tests

Could you tell me what the specifications of the previous machine are and what the new one is?

I'm getting this error only in groups with more than ~600 members, but observing the behavior of the machine, it doesn't even come close to consuming 100% of the CPU or memory resources.

Current machine: AWS t4g.xlarge (4x cpu + 16gb ram)
