### ISSUE TITLE
[BUG] Some Text Messages are Sent with Empty Content

### ISSUE THREAD

**Issue by CSFelix** [WhiskeySockets/Baileys#676]
# Bug

Even though the text messages having contents, Baileys sends them without content sometimes. The image below is from a contact that received our message with empty content.

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/24093c40-7f11-4dee-9f08-c0bdd7a3712d)

---

# How to Reproduce

There is no a guarantee way to reproduce this issue. It happens randomly during a conversation.

---

# Expected Behavior

The messages should be sent with their respective contents.

---

# Environment

 - Is this on a server?
    Yes, it's running on a Linux Server.

 - What do your `connectOptions` look like? 
```ts
wsocket = makeWASocket({
  logger: loggerBaileys,
  printQRInTerminal: false,
  auth: state as AuthenticationState,
  generateHighQualityLinkPreview: false,
  browser: ["Baileys", "Chrome", "10.15.7"],
  syncFullHistory: true,
  markOnlineOnConnect: true,
  patchMessageBeforeSending: message => {
    const requiresPatch = !!(
      message.buttonsMessage || message.listMessage
    );
    if (requiresPatch) {
      message = {
        viewOnceMessage: {
          message: {
            messageContextInfo: {
              deviceListMetadataVersion: 2,
              deviceListMetadata: {}
            },
            ...message
          }
        }
      };
    }
    return message;
  },
  getMessage
});
``` 

 - Do you have multiple clients on the same IP?
     Yes, around seven connections, but the issue only happened to one so far.

 - Are you using a proxy?
     Nope, no proxies.

**Comment by lcssanches** [comment]
I've been experiencing this with and without proxies.

**Comment by CSFelix** [comment]
> I've been experiencing this with and without proxies.

I've talked to @PurpShell on the Discord Server. He said we have to wait for a Pull Request.

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/95f92c97-16f2-4378-9760-af2b415c3ed0)

**Comment by tiagomatrixd** [comment]
I believe this is happening because of your getMessage() function.

**Comment by CSFelix** [comment]
> I believe this is happening because of your getMessage() function.

Hmm, got it, but even on WhatsApp Mobile App the message appears empty

**Comment by PurpShell** [comment]
Looks like a getMessage issue
