### ISSUE TITLE
[BUG] Reactions are not shown on WhatsApp Web

### ISSUE THREAD

**Issue by CSFelix** [WhiskeySockets/Baileys#685]
# Bug

Reactions sent by Baileys appears on WhatsApp Mobile App (image 1), but don't on WhatsApp Web (image 2).

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/c3182cf4-df97-48f7-a751-dacc89df1361)

![image](https://github.com/WhiskeySockets/Baileys/assets/57205604/4e77eb76-775b-47a2-af66-e23abf8b20c3)

---

# How to Reproduce

1. React to a message using Baileys
2. The reaction will appear on WhatsApp Mobile App
3. But it will not appear on WhatsApp Web

---

# Expected behavior

The reaction should appear on WhatsApp Web too.

---

# Environment

 - Is this on a server?
Yes, it's running on a Linux Server. I also tested on Windows localhost.

 - What do your `connectOptions` look like? 

```ts
wsocket = makeWASocket({
  logger: loggerBaileys,
  printQRInTerminal: false,
  auth: state as AuthenticationState,
  generateHighQualityLinkPreview: false,
  browser: ["Baileys", "Chrome", "10.15.7"],
  syncFullHistory: true,
  markOnlineOnConnect: true,
  patchMessageBeforeSending: message => {
    const requiresPatch = !!(
      message.buttonsMessage || message.listMessage
    );
    if (requiresPatch) {
      message = {
        viewOnceMessage: {
          message: {
            messageContextInfo: {
              deviceListMetadataVersion: 2,
              deviceListMetadata: {}
            },
            ...message
          }
        }
      };
    }
    return message;
  },
  getMessage
});
```

 - Do you have multiple clients on the same IP?
On Linux, yes. I have around seven connections.
On Windows not. I have only one connection.

 - Are you using a proxy?
Nope, no proxies.

---

# Adicional Context

This is a sample of my code to send reactions:

```ts
await socket.sendMessage(
    jid,
    {
        react: {
            text: '❤️',
            key: {
                remoteJid: '<jid>',
                fromMe: true,
                id: '<messageId>'
            }
        }
    }
);
```

**Comment by initech-vmc** [comment]
try `fromMe: False`

**Comment by CSFelix** [comment]
> try `fromMe: False`

It worked, thank you so much bro!!
