### ISSUE TITLE
Send Group Mentions Message

### ISSUE THREAD

**Issue by hardknockdays** [WhiskeySockets/Baileys#687]
Any idea please for send Group Mentions Message with Baileys?
![Screenshot_20240321-030504725 (1).jpg](https://github.com/WhiskeySockets/Baileys/assets/46776762/d4ea3fcc-4f31-4c58-a56b-62192790f34a)

**Comment by DavidModzz** [comment]
```
sock.sendMessage(from, {text: `your text Góes here @{sender.split("@")[0]}`, mentions: [id's to mention]} )
```

**Comment by nazuninha** [comment]
client.sendMessage(from,
{ 
 text: `@${GroupID}`,
contextInfo: {
 groupMentions: [
{
 groupJid: GroupID,
 groupSubject: 'GroupName'
}
]
}});
