### ISSUE TITLE
session instability

### ISSUE THREAD

**Issue by lucas-linvix** [WhiskeySockets/Baileys#705]
**Describe the bug**
 Hello everyone,  I am using baileys to receive messages and files from numerous contacts who forward messages to my phone number, however, for some time now I have noticed that the connection with the api began to show a lot of instability, every 2 hours or 4 hours, the connection drops and returns automatically after 1 or 5 minutes, but this is directly impacting other parts of the application as well.

**To Reproduce**

1. Created a new connection or already have an active connection
2. Run the code and perform all basic operations of receiving messages, forwarding files, etc... For a period of 2 to 4 hours

**Expected behavior**

the session connection will drop abruptly and will be inactive for 1 to 5 minutes, after which it will return

**Environment (please complete the following information):**

 - Is this on a server?
 
 Response: Yes, the code its run in Digitalocean 
 - What do your `connectOptions` look like? 

 Response: its like this:
     opts: {
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 1000000,
      transports: [Array],
      allowUpgrades: true,
      httpCompression: [Object],
      cors: [Object],
      allowEIO3: false,
      path: '/socket.io'
    }

 - Do you have multiple clients on the same IP?
  
   Response:  Yes

 - Are you using a proxy?
 
   Response: No

**Additional context**
 My code is running in a Digitalocean environment, furthermore, I am using it as a postgresql database with sequelize to do all the saving, changing and deleting data operations.

I used sentry to identify some errors I found in the code, during the period with session connection instability:

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/c64ff28b-2620-4f0a-a65b-fc3e0e876f64)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/ef6bac9f-d86b-4d8c-94c0-cbfad1c6114a)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/0e94bbbd-78ab-4dcb-8232-60f5d2150c3e)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/c449bb0a-14b9-411e-8bae-f59c6267ff6f)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/2f575a80-d7f5-4958-b4ad-04c03ed19c17)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/56a95deb-6fe6-42ef-b81a-c2a3aef1e406)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/4005fd5d-178a-462a-9a40-1fa077102990)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/a096f664-ba38-4946-80c9-16be5c2fe3af)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/d0d2d775-f240-42c2-8cd4-718b85204b7e)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/8b82fd84-b93e-400d-ae85-ca5109a8d57d)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/582bf08a-1783-43bb-aa29-43274c2bec56)

![image](https://github.com/WhiskeySockets/Baileys/assets/146751746/11f8113e-b6fc-4ea7-a089-e981f239e018)

I don't have 100%, but I believe that the problem may be when receiving messages, some error is occurring and this is causing instability to continue the rest of the process or the WebSocket connection itself may have some configuration or logical failure .
At the current time, I am dealing with a large amount of sending and receiving information

 I would just like to stabilize the session connection or establish a period of time to keep it active, maybe only for 8 hours.

**Comment by morris-choga** [comment]
Even on whatsapp.js sessions are also unstable. Its so draining now 😭

**Comment by lucas-linvix** [comment]
@morris-choga, in the community I found that other developers are having the same problem, I don't know if it's related to my problem, but it's still strange.

**Comment by CJRMedeiros123** [comment]
I have this problem!
