### ISSUE TITLE
Get poll voters

### ISSUE THREAD

**Issue by Rcccclaks** [WhiskeySockets/Baileys#71]
Like, I want to use a poll as a button, so I need to know how Baileys knows which poll option the user voted for, please help me

**Comment by satriowicaksn** [comment]
up, also need help for this

**Comment by andresayac** [comment]
I don't see it as complex, the truth is, you just have to listen to the update of the message


> satriowicaksn

**Comment by andresayac** [comment]
I am going to generate an example

**Comment by satriowicaksn** [comment]
thanks @andresayac I will try it!

**Comment by Rcccclaks** [comment]
> I don't see it as complex, the truth is, you just have to listen to the update of the message
> 
> #38
> 
> > satriowicaksn


My system does not recognize the update, when I select an option, it activates messages.upsert and not chat-update

**Comment by andresayac** [comment]
> 
> 
> > I don't see it as complex, the truth is, you just have to listen to the update of the message
> > 
> > #38
> > 
> > > satriowicaksn
> 
> 
> My system does not recognize the update, when I select an option, it activates messages.upsert and not chat-update
> 
> 

hello is messages.update not chat.update, I am working on an example but before that I am waiting for validation of a request pull

https://github.com/WhiskeySockets/Baileys/pull/74

**Comment by Rcccclaks** [comment]
> hello it's messages.update it's also possible from messages.upsert but it ignores the chats.update, I'm working on an example but before I'm waiting for validation of a pull request,
> 
> #74

When you get it can you let me know?

**Comment by andresayac** [comment]
I share this idea, it is not the super script, it was very improvised to make a bot, the important thing is that I understand how it works and I try to emit events to read them later, it should be noted that I have not generated a bot that is how I currently use it

https://github.com/andresayac/poll_example_bot_baileys

![image](https://github.com/WhiskeySockets/Baileys/assets/16548795/4292978c-b7d3-45d7-85eb-6f0f0c9f1d7d)
![image](https://github.com/WhiskeySockets/Baileys/assets/16548795/fce81d73-7fcc-459d-b7be-db5aa19d8938)

**Comment by kodmanyagha** [comment]
Poll messages doesn't come from `messages.update` event. They're coming from `messages.upsert` and format is like that:

```
{
      "key": {
        "remoteJid": "905374937766@s.whatsapp.net",
        "fromMe": true,
        "id": "3AD3XXXXXXXX9BC75F"
      },
      "messageTimestamp": 1684309796,
      "pushName": "Emir Bugra",
      "broadcast": false,
      "status": 2,
      "message": {
        "pollUpdateMessage": {
          "pollCreationMessageKey": {
            "remoteJid": "905374937766@s.whatsapp.net",
            "fromMe": true,
            "id": "XXXXXXXXXXXXX"
          },
          "vote": {
            "encPayload": "tEjjdA1JcwINxxxxEXQGhO+Bkm7xxxxxxJLlPCbuYImKpJsxxxxxxxrok380EA=",
            "encIv": "XEYzxxxxsND92Ru"
          },
          "senderTimestampMs": "1684309795533"
        }
      }
    }
```

We must decrypt `encPayload` but I don't know how to do that.

**Comment by andresayac** [comment]
> Poll messages doesn't come from `messages.update` event. They're coming from `messages.upsert` and format is like that:
> 
> ```
> {
>       "key": {
>         "remoteJid": "905374937766@s.whatsapp.net",
>         "fromMe": true,
>         "id": "3AD3XXXXXXXX9BC75F"
>       },
>       "messageTimestamp": 1684309796,
>       "pushName": "Emir Bugra",
>       "broadcast": false,
>       "status": 2,
>       "message": {
>         "pollUpdateMessage": {
>           "pollCreationMessageKey": {
>             "remoteJid": "905374937766@s.whatsapp.net",
>             "fromMe": true,
>             "id": "XXXXXXXXXXXXX"
>           },
>           "vote": {
>             "encPayload": "tEjjdA1JcwINxxxxEXQGhO+Bkm7xxxxxxJLlPCbuYImKpJsxxxxxxxrok380EA=",
>             "encIv": "XEYzxxxxsND92Ru"
>           },
>           "senderTimestampMs": "1684309795533"
>         }
>       }
>     }
> ```
> 
> We must decrypt `encPayload` but I don't know how to do that.
> 

Have you tried the script, it seems that I do not recommend that you document it and do so by leaving several examples above.

**Comment by kodmanyagha** [comment]
> > Poll messages doesn't come from `messages.update` event. They're coming from `messages.upsert` and format is like that:
> > ```
> > {
> >       "key": {
> >         "remoteJid": "905374937766@s.whatsapp.net",
> >         "fromMe": true,
> >         "id": "3AD3XXXXXXXX9BC75F"
> >       },
> >       "messageTimestamp": 1684309796,
> >       "pushName": "Emir Bugra",
> >       "broadcast": false,
> >       "status": 2,
> >       "message": {
> >         "pollUpdateMessage": {
> >           "pollCreationMessageKey": {
> >             "remoteJid": "905374937766@s.whatsapp.net",
> >             "fromMe": true,
> >             "id": "XXXXXXXXXXXXX"
> >           },
> >           "vote": {
> >             "encPayload": "tEjjdA1JcwINxxxxEXQGhO+Bkm7xxxxxxJLlPCbuYImKpJsxxxxxxxrok380EA=",
> >             "encIv": "XEYzxxxxsND92Ru"
> >           },
> >           "senderTimestampMs": "1684309795533"
> >         }
> >       }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We must decrypt `encPayload` but I don't know how to do that.
> 
> Have you tried the script, it seems that I do not recommend that you document it and do so by leaving several examples above.
> 
> I read this it seems not?
> 
> https://github.com/WhiskeySockets/Baileys/blob/master/Example/example.ts
> 
> Example
> 
> git clone https://github.com/andresayac/poll_example_bot_baileys.git
> 
> cd poll_example_bot_baileys npm I npm run start Scan qr Send poll this for device Select opción and view terminal

Yep it worked, probably I'm making something wrong in my own project. Thanks you so much.

**Comment by Rcccclaks** [comment]
> 

ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' imported from /storage/emulated/0/poll_example_bot_baileys/baileys.js
    at new NodeError (node:internal/errors:399:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:202:9)
    at packageResolve (node:internal/modules/esm/resolve:781:14)
    at moduleResolve (node:internal/modules/esm/resolve:843:20)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:309:30)
    at ESMLoader.resolve (node:internal/modules/esm/loader:312:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v19.9.0

**Comment by andresayac** [comment]
you can clone and try again friend
https://github.com/andresayac/bot_baileys

> > 
> 
> ErrorCaptureStackTrace(err); ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' imported from /storage/emulated/0/poll_example_bot_baileys/baileys.js at new NodeError (node:internal/errors:399:5) at legacyMainResolve (node:internal/modules/esm/resolve:202:9) at packageResolve (node:internal/modules/esm/resolve:781:14) at moduleResolve (node:internal/modules/esm/resolve:843:20) at defaultResolve (node:internal/modules/esm/resolve:1058:11) at nextResolve (node:internal/modules/esm/hooks:654:28) at Hooks.resolve (node:internal/modules/esm/hooks:309:30) at ESMLoader.resolve (node:internal/modules/esm/loader:312:26) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38) at ModuleWrap. (node:internal/modules/esm/module_job:76:40) { code: 'ERR_MODULE_NOT_FOUND' }
> 
> Node.js v19.9.0

**Comment by Rcccclaks** [comment]
> você pode clonar e tentar novamente amigo https://github.com/andresayac/bot_baileys
> 
> > > 
> > 
> > 
> > ErrorCaptureStackTrace(err); ^
> > Erro [ERR_MODULE_NOT_FOUND]: Não é possível encontrar o pacote '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' importado de /storage/emulated/0/poll_example_bot_baileys/baileys.js no novo NodeError (node:internal /errors: 399:5) em legacyMainResolve (node:internal/modules/esm/resolve:202:9) em packageResolve (node:internal/modules/esm/resolve:781:14) em moduleResolve (node:internal/modules/ esm/resolve :843:20) em defaultResolve (node:internal/modules/esm/resolve:1058:11) em nextResolve (node:internal/modules/esm/hooks:654:28) em Hooks.resolve (node:internal /modules/esm/hooks:309:30) em ESMLoader.resolve (node:internal/modules/esm/loader:312:26) em ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38) em ModuleWrap.(node:internal/modules/esm/module_job:76:40) { código: 'ERR_MODULE_NOT_FOUND' }
> > Node.js v19.9.0

Mesmo erro

**Comment by Rcccclaks** [comment]
> você pode clonar e tentar novamente amigo https://github.com/andresayac/bot_baileys
> 
> > > 
> > 
> > 
> > ErrorCaptureStackTrace(err); ^
> > Erro [ERR_MODULE_NOT_FOUND]: Não é possível encontrar o pacote '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' importado de /storage/emulated/0/poll_example_bot_baileys/baileys.js no novo NodeError (node:internal /errors: 399:5) em legacyMainResolve (node:internal/modules/esm/resolve:202:9) em packageResolve (node:internal/modules/esm/resolve:781:14) em moduleResolve (node:internal/modules/ esm/resolve :843:20) em defaultResolve (node:internal/modules/esm/resolve:1058:11) em nextResolve (node:internal/modules/esm/hooks:654:28) em Hooks.resolve (node:internal /modules/esm/hooks:309:30) em ESMLoader.resolve (node:internal/modules/esm/loader:312:26) em ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38) em ModuleWrap.(node:internal/modules/esm/module_job:76:40) { código: 'ERR_MODULE_NOT_FOUND' }
> > Node.js v19.9.0

Same error in terminal

**Comment by Rcccclaks** [comment]
> you can clone and try again friend https://github.com/andresayac/bot_baileys
> 
> > > 
> > 
> > 
> > ErrorCaptureStackTrace(err); ^
> > Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' imported from /storage/emulated/0/poll_example_bot_baileys/baileys.js at new NodeError (node:internal/errors:399:5) at legacyMainResolve (node:internal/modules/esm/resolve:202:9) at packageResolve (node:internal/modules/esm/resolve:781:14) at moduleResolve (node:internal/modules/esm/resolve:843:20) at defaultResolve (node:internal/modules/esm/resolve:1058:11) at nextResolve (node:internal/modules/esm/hooks:654:28) at Hooks.resolve (node:internal/modules/esm/hooks:309:30) at ESMLoader.resolve (node:internal/modules/esm/loader:312:26) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38) at ModuleWrap. (node:internal/modules/esm/module_job:76:40) { code: 'ERR_MODULE_NOT_FOUND' }
> > Node.js v19.9.0

Can you modify this one and send it to me with it working?
https://github.com/Rcccclaks/BotBaileys

**Comment by andresayac** [comment]
> > puedes clonar y volver a intentar amigo https://github.com/andresayac/bot_baileys
> > > > 
> > > 
> > > 
> > > ErrorCaptureStackTrace(err); ^
> > > Error [ERR_MODULE_NOT_FOUND]: No se puede encontrar el paquete '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' importado de /storage/emulated/0/poll_example_bot_baileys/baileys.js en el nuevo NodeError (node:internal/errors: 399:5) en legacyMainResolve (node:internal/modules/esm/resolve:202:9) en packageResolve (node:internal/modules/esm/resolve:781:14) en moduleResolve (node:internal/modules/esm/resolve :843:20) en defaultResolve (nodo:interno/módulos/esm/resolve:1058:11) en nextResolve (nodo:interno/módulos/esm/hooks:654:28) en Hooks.resolve (nodo:interno/módulos/ esm/hooks:309:30) en ESMLoader.resolve (nodo:internal/modules/esm/loader:312:26) en ESMLoader.getModuleJob (nodo:internal/modules/esm/loader:172:38) en ModuleWrap. (nodo: interno/módulos/esm/module_job: 76:40) { código: 'ERR_MODULE_NOT_FOUND' }
> > > Node.js v19.9.0
> 
> ¿Puedes modificar este y enviármelo con él funcionando? https://github.com/Rcccclaks/BotBaileys

yes

**Comment by Rcccclaks** [comment]
> > > você pode clonar e voltar a tentar amigo https://github.com/andresayac/bot_baileys
> > > > > 
> > > > 
> > > > 
> > > > ErrorCaptureStackTrace(err); ^
> > > > Erro [ERR_MODULE_NOT_FOUND]: Não foi possível encontrar o pacote '/storage/emulated/0/poll_example_bot_baileys/node_modules/@whiskeysockets/baileys/' importado de /storage/emulated/0/poll_example_bot_baileys/baileys.js no novo NodeError (node: internal/errors: 399:5) en legacyMainResolve (node:internal/modules/esm/resolve:202:9) en packageResolve (node:internal/modules/esm/resolve:781:14) en moduleResolve (node:internal/modules /esm/resolve :843:20) en defaultResolve (nodo:interno/módulos/esm/resolve:1058:11) en nextResolve (nodo:interno/módulos/esm/hooks:654:28) en Hooks.resolve (nodo: interno/módulos/esm/hooks:309:30) em ESMLoader.resolve (nodo:internal/modules/esm/loader:312:26) em ESMLoader.getModuleJob (nodo:internal/modules/esm/loader:172:38) pt ModuleWrap. (nodo: interno/módulos/esm/module_job: 76:40) { código: '
> > > > Node.js v19.9.0
> > 
> > 
> > Você pode modificar este e enviá-lo com ele funcionando? https://github.com/Rcccclaks/BotBaileys
> 
> embora haja muito trabalho como você tem

I was wanting a lot you know

**Comment by andresayac** [comment]
That's why I designed a much more scalable idea as I have it in my repository to play with events and globalize to messages, sometimes it's recommended to use baileys as updates or reactions so I've taken an idea to globalize in an event called messages

git clone https://github.com/andresayac/bot_baileys.git
cd bot_baileys
npm i
npm run start

**Comment by Rcccclaks** [comment]
> É por isso que desenvolvi uma ideia muito mais escalável como tenho em meu repositório para brincar com eventos e globalizar para mensagens, às vezes é recomendável usar baileys como atualizações ou reações, então tenho uma ideia para globalizar em um evento chamado mensagens
> 
> git clone https://github.com/andresayac/bot_baileys.git cd bot_baileys npm i npm run start



> That's why I designed a much more scalable idea as I have it in my repository to play with events and globalize to messages, sometimes it's recommended to use baileys as updates or reactions so I've taken an idea to globalize in an event called messages
> 
> git clone https://github.com/andresayac/bot_baileys.git cd bot_baileys npm i npm run start

It's just that this one doesn't work neither in Ubuntu nor in termux

**Comment by andresayac** [comment]
> It's just that this one doesn't work neither in Ubuntu nor in termux

I am going to validate on linux

**Comment by andresayac** [comment]
> cd bot_baileys
> npm i
> npm run start

![image](https://github.com/WhiskeySockets/Baileys/assets/16548795/8a279801-23e0-4b1a-b02a-b922fba15891)
![image](https://github.com/WhiskeySockets/Baileys/assets/16548795/2a1f2a69-cdaf-4262-8c4b-6674d93db124)

**Comment by Rcccclaks** [comment]
> > cd bot_baileys
> > npm i
> > npm run start
> 
> ![image](https://user-images.githubusercontent.com/16548795/242108546-8a279801-23e0-4b1a-b02a-b922fba15891.png) ![image](https://user-images.githubusercontent.com/16548795/242108570-2a1f2a69-cdaf-4262-8c4b-6674d93db124.png)

It worked but can you do it on the base I sent you? I'll pay you 10 reais

**Comment by andresayac** [comment]
> It worked but can you do it on the base I sent you? I'll pay you 10 reais

believe me it is much easier as you raise it, just scan the qr and everything you get to the message event, and from there you can use the different methods or native oppciones to modify to your liking, the issue is that it depends on the event messages.update and has no logic in the code that you pass me would have to return to condition 

![image](https://github.com/WhiskeySockets/Baileys/assets/16548795/16742a91-22e7-4e8f-92cc-f37f4c0f0baf)

**Comment by Rcccclaks** [comment]
> > Funcionou mas dá pra fazer na base que te mandei? te pago 10 reais
> 
> acredite em mim é muito mais fácil conforme você aumenta, basta digitalizar o qr e tudo o que você recebe no evento de mensagem, e a partir daí você pode usar os diferentes métodos ou oppciones nativos para modificar ao seu gosto, a questão é que depende do event message.update e não tem logica no codigo que me passar teria que retornar a condição
> 
> ![imagem](https://user-images.githubusercontent.com/16548795/242117015-16742a91-22e7-4e8f-92cc-f37f4c0f0baf.png)

Can you pass me some of your means of communication?

**Comment by andresayac** [comment]
> > > Funcionou mas dá pra fazer na base que te mandei? te pago 10 reais
> > 
> > 
> > acredite em mim é muito mais fácil conforme você aumenta, basta digitalizar o qr e tudo o que você recebe no evento de mensagem, e a partir daí você pode usar os diferentes métodos ou oppciones nativos para modificar ao seu gosto, a questão é que depende do event message.update e não tem logica no codigo que me passar teria que retornar a condição
> > ![imagem](https://user-images.githubusercontent.com/16548795/242117015-16742a91-22e7-4e8f-92cc-f37f4c0f0baf.png)
> 
> Can you pass me some of your means of communication?

discord andresaya#9842

**Comment by wallycoding** [comment]
Adding the getMessage function worked for me, the "messages.update" event started to notify on votes

```ts
const sock = makeWASocket({
    ..., // your config
    getMessage,
  });
```
Store
```ts
const store = makeInMemoryStore({ logger })
```
function getMessage
```ts
async function getMessage(key: WAMessageKey): Promise<WAMessageContent | undefined> {
	if(store) {
		const msg = await store.loadMessage(key.remoteJid!, key.id!)
		return msg?.message || undefined
	}

	// only if store is present
	return proto.Message.fromObject({})
}
```

The getMessage method is called in processMessage:
https://github.com/WhiskeySockets/Baileys/blob/e24947e55ad6e3370de867b258bb33bb9e828c56/src/Utils/process-message.ts#L340

**Comment by acorreane** [comment]
maybe enhacement by @PurpShell
https://gist.github.com/PurpShell/44433d21631ff0aefbea57f7b5e31139
