### ISSUE TITLE
Closing stale open session for new outgoing prekey bundle ERROR

### ISSUE THREAD

**Issue by mikelx99** [WhiskeySockets/Baileys#710]
**Describe the bug**
I keep encountering this error in a loop when I run my bot on an Ubuntu server. 

I only experience this error when I run the bot using my sudo user account. However, I do not encounter this error when using the root user or when running the bot on Windows.

![Screenshot 2024-04-01 071727](https://github.com/WhiskeySockets/Baileys/assets/124032862/3dd5e1c9-0eee-4d09-b169-9869d6260392)

**Environment**
Ubuntu Server 22.04 - NodeJS 20

**Tried Solutions**

```
chmod -R a+x node_module
chown -R myuser:myuser /botfolder
chown -R 755 /botfolder
chown -R 775 /botfolder

find /botfolder -type f -exec chmod u+rw {} \
find /botfolder -type f -exec chmod u+rw {} \ 

```

But nothing seems working keep getting that error how do i fix this error ?

Thank you

**Comment by MarkBone** [comment]
Me too

**Comment by iamrony777** [comment]
Try running in docker environment 
image: debian (bookworm)

**Comment by UmamDev** [comment]
I have the same problem

**Comment by hiagodeoliveiratv** [comment]
Any solution?

**Comment by hiagodeoliveiratv** [comment]
> **Describe the bug** I keep encountering this error in a loop when I run my bot on an Ubuntu server.
> 
> I only experience this error when I run the bot using my sudo user account. However, I do not encounter this error when using the root user or when running the bot on Windows.
> 
> ![Screenshot 2024-04-01 071727](https://private-user-images.githubusercontent.com/124032862/318318078-3dd5e1c9-0eee-4d09-b169-9869d6260392.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MzQ0NTIsIm5iZiI6MTcxNDUzNDE1MiwicGF0aCI6Ii8xMjQwMzI4NjIvMzE4MzE4MDc4LTNkZDVlMWM5LTBlZWUtNGQwOS1iMTY5LTk4NjlkNjI2MDM5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQwMzI5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGNmZDM4NGY1ZWI3YTJmYTk4YTA3OTA0OGQ3YzlmMTE4NDJkMmI2M2VjNTZkNDFlYWQ3ODkzOTBjZTczNTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YTGj3wgb3dCWggTntN3oSh-5lpXs8yyxdVXrhaZSFfg)
> 
> **Environment** Ubuntu Server 22.04 - NodeJS 20
> 
> **Tried Solutions**
> 
> ```
> chmod -R a+x node_module
> chown -R myuser:myuser /botfolder
> chown -R 755 /botfolder
> chown -R 775 /botfolder
> 
> find /botfolder -type f -exec chmod u+rw {} \
> find /botfolder -type f -exec chmod u+rw {} \ 
> ```
> 
> But nothing seems working keep getting that error how do i fix this error ?
> 
> Thank you

You did it ?

**Comment by PurpShell** [comment]
Not a problem. This is just a libsignal message

**Comment by FlavioCoutinhoGO** [comment]
> Not a problem. This is just a libsignal message

How do I hide this message?

**Comment by mrfzvx12** [comment]
> Not a problem. This is just a libsignal message

when that message appears, baileys stops receiving whatsapp messages, it's like stuck

**Comment by AnderRedna** [comment]
> > Not a problem. This is just a libsignal message
> 
> when that message appears, baileys stops receiving whatsapp messages, it's like stuck

Did you solve that?

**Comment by mrfzvx12** [comment]
> > > Not a problem. This is just a libsignal message
> > 
> > 
> > when that message appears, baileys stops receiving whatsapp messages, it's like stuck
> 
> Did you solve that?

nope, I still often get this problem, it makes like the system stops for several hours.
