### ISSUE TITLE
[BUG] Pairing Code

### ISSUE THREAD

**Issue by revandadityajw** [WhiskeySockets/Baileys#713]
![Screenshot_20240403_230030](https://github.com/WhiskeySockets/Baileys/assets/107557794/dcc118b4-3f81-4489-9763-e64c397ad40f)
When I use the pairing code, when I enter the linked device it always takes a long time to load and cannot link the device

**Comment by manfe** [comment]
3 hours ago, there was whatsapp outage, probably is related to this?

**Comment by revandadityajw** [comment]
> 3 hours ago, there was whatsapp outage, probably is related to this?

Is there perhaps an error here?
let connectionOptions = {
		version,
		keepAliveIntervalMs: 30_000,
		printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true,
		auth: opts.authState?.state,
		browser: ['Chrome', 'Safari', '3.1.0'],
		...opt

**Comment by Riders004** [comment]
> > 3 hours ago, there was whatsapp outage, probably is related to this?
> 
> Is there perhaps an error here? let connectionOptions = { version, keepAliveIntervalMs: 30_000, printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true, auth: opts.authState?.state, browser: ['Chrome', 'Safari', '3.1.0'], ...opts }

Use u Ubuntu instead of chrome

**Comment by Riders004** [comment]
> > > > > 3 hours ago, there was whatsapp outage, probably is related to this?
> > > > 
> > > > 
> > > > Is there perhaps an error here? let connectionOptions = { version, keepAliveIntervalMs: 30_000, printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true, auth: opts.authState?.state, browser: ['Chrome', 'Safari', '3.1.0'], ...opts }
> > > 
> > > 
> > > Use u Ubuntu instead of chrome
> > 
> > 
> > whats is default? has some indication?
> 
> This bug is occurred because of WhatsApp update. They change something 💀 And baileys still not updated :(

Baileys got fixed check the [issue 702](https://github.com/WhiskeySockets/Baileys/issues/702)

**Comment by shizothetechie** [comment]
> > > > > > 3 hours ago, there was whatsapp outage, probably is related to this?
> > > > > 
> > > > > 
> > > > > Is there perhaps an error here? let connectionOptions = { version, keepAliveIntervalMs: 30_000, printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true, auth: opts.authState?.state, browser: ['Chrome', 'Safari', '3.1.0'], ...opts }
> > > > 
> > > > 
> > > > Use u Ubuntu instead of chrome
> > > 
> > > 
> > > whats is default? has some indication?
> > 
> > 
> > This bug is occurred because of WhatsApp update. They change something 💀 And baileys still not updated :(
> 
> Baileys got fixed check the [issue 702](https://github.com/WhiskeySockets/Baileys/issues/702)

Aye chomu usne wo bug bataya h 💀😂.

They just report issue as bug that is not a fix patch update dude 💀 check properly

**Comment by APdev93** [comment]
> > 3 hours ago, there was whatsapp outage, probably is related to this?
> 
> Is there perhaps an error here? let connectionOptions = { version, keepAliveIntervalMs: 30_000, printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true, auth: opts.authState?.state, browser: ['Chrome', 'Safari', '3.1.0'], ...opts }

L

> > 3 hours ago, there was whatsapp outage, probably is related to this?
> 
> Is there perhaps an error here? let connectionOptions = { version, keepAliveIntervalMs: 30_000, printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true, auth: opts.authState?.state, browser: ['Chrome', 'Safari', '3.1.0'], ...opts }

```javascript
connectionOptions = {
		...Other,
		printQRInTerminal: false,
		browser: Browsers.ubuntu("Chrome"),
		auth: {
			creds: state.creds,
			keys: makeCacheableSignalKeyStore(state.keys, P),
		}
}
```

#Try this, The method you are using is the `old method`

**Comment by Riders004** [comment]
> > > > > > > 3 hours ago, there was whatsapp outage, probably is related to this?
> > > > > > 
> > > > > > 
> > > > > > Is there perhaps an error here? let connectionOptions = { version, keepAliveIntervalMs: 30_000, printQRInTerminal: opts.isChild ? false : opts.pairingCode ? false : true, auth: opts.authState?.state, browser: ['Chrome', 'Safari', '3.1.0'], ...opts }
> > > > > 
> > > > > 
> > > > > Use u Ubuntu instead of chrome
> > > > 
> > > > 
> > > > whats is default? has some indication?
> > > 
> > > 
> > > This bug is occurred because of WhatsApp update. They change something 💀 And baileys still not updated :(
> > 
> > 
> > Baileys got fixed check the [issue 702](https://github.com/WhiskeySockets/Baileys/issues/702)
> 
> Aye chomu usne wo bug bataya h 💀😂.
> 
> They just report issue as bug that is not a fix patch update dude 💀 check properly

Are chomu k bhaiya uska connection dekho jara chrome safari hai 💀
