### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'creds')

### ISSUE THREAD

**Issue by rssdevoloper** [WhiskeySockets/Baileys#719]
hello, I found a problem updating useSingleFileAuthState to useMultiFileAuthState

following is my code

const {
   default: makeWASocket,
   useMultiFileAuthState,
   DisconnectReason,
   generateForwardMessageContent,
   prepareWAMessageMedia,
   generateWAMessageFromContent,
   generateMessageID,
   downloadContentFromMessage,
   makeInMemoryStore,
   jidDecode,
   PHONENUMBER_MCC,
   fetchLatestBaileysVersion,
   proto
} = require('@adiwajshing/baileys');
........

const {
       states,
       saveCreds
     } = useMultiFileAuthState(authFile);
........
const optionmakewa = {
     printQRInTerminal: !isPairingCode,
     syncFullHistory: true,
     markOnlineOnConnect: true,
     connectTimeoutMs: 60000,
     defaultQueryTimeoutMs: 0,
     keepAliveIntervalMs: 10000,
     generateHighQualityLinkPreview: true,
     patchMessageBeforeSending: (message) => {
       const requiresPatch = !!(
         message.buttonsMessage ||
         message.templateMessage ||
         message.listMessage
       )
       returns (
         requiresPatch &&
           (message = {
             viewOnceMessage: {
               message: {
                 messageContextInfo: {
                   deviceListMetadataVersion: 2,
                   deviceListMetadata: {},
                 },
                 ...messages,
               },
             },
           }),
         message
       )
     },
     browser: ['Ubuntu', 'Chrome', '20.0.04'],
     logger: pino({ level: 'silent' }),
     version: version,
     auth: {
             creds: state.creds,
             keys: makeCacheableSignalKeyStore(state.keys, pino().child({
                 level: 'silent',
                 stream: 'store'
             })),
         },
}

global.conn = simple.makeWASocket(optionmakewa )
conn.ev.on('creds.update', saveCreds)

it encountered an error
             creds: state.creds,
                          ^

TypeError: Cannot read properties of undefined (reading 'creds')
     at Object.<anonymous> (R:\RTXZY-MD-pro\main.js:133:26)
     at Module._compile (node:internal/modules/cjs/loader:1356:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
     at Module.load (node:internal/modules/cjs/loader:1197:32)
     at Module._load (node:internal/modules/cjs/loader:1013:12)
     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
     at node:internal/main/run_main_module:28:49

Node.js v18.19.1

when I tried it on my other script, it was normal. When I updated the old sc to the new one, it gave an error

"dependencies": {
         "@adiwajshing/baileys": "npm:@whiskeysockets/baileys", // version 6.6.0
........

**Comment by APdev93** [comment]
It's a typo errors 

In variable u type it `states` and u call it `state` So creds is `undefined`. Change `states` into `state`

```javascript
const { state } = useMultiFileAuthState("session name")

const optionsMakeWa = {
...other
Auth: state.creds
...other
}
```

**Comment by APdev93** [comment]
> @APdev93 It was just a typing error when creating the issue. The error is still the same even though there are no errors in my code.
> 
> how to solve this bug?
![Screenshot_20240407-224502~3](https://github.com/WhiskeySockets/Baileys/assets/83260062/f79128d2-1d9d-4cf7-bcce-107cf68ef70b)

This `states` There is no object named `states` in `useMultiFileAuthState()`


Change it to `state`

**Comment by rssdevoloper** [comment]
![image](https://github.com/WhiskeySockets/Baileys/assets/65481692/2b55068f-8055-4e8f-acc1-5a24e2c64513)
![image](https://github.com/WhiskeySockets/Baileys/assets/65481692/5c75ba2e-4cf9-49fa-8aed-5b177994d17b)

just the same

**Comment by rssdevoloper** [comment]
require('./config')
const {
  default: makeWASocket,
  useMultiFileAuthState,
  DisconnectReason,
  generateForwardMessageContent,
  prepareWAMessageMedia,
  generateWAMessageFromContent,
  generateMessageID,
  downloadContentFromMessage,
  makeInMemoryStore,
  jidDecode,
  PHONENUMBER_MCC,
  fetchLatestBaileysVersion,
  proto
} = require('@whiskeysockets/baileys');

const pino = require('pino');
const WebSocket = require('ws');
const path = require('path');
const fs = require('fs');
const yargs = require('yargs/yargs');
const cp = require('child_process');
const _ = require('lodash');
const syntaxerror = require('syntax-error');
const os = require('os');
const fetch = require('node-fetch');
const chalk = require('chalk');

let simple = require('./lib/simple')

......


const authFile = '' + (opts['_'][0] || 'sessions')
global.isInit = !fs.existsSync(authFile)

const {
      state,
      saveCreds
    } = useMultiFileAuthState(authFile);
const { version, isLatest } =fetchLatestBaileysVersion();
console.log(chalk.magenta('-- using WA v' + version + ', isLatest: ' + isLatest + ' --'));




const optionmakewa = {
    printQRInTerminal: !isPairingCode,
    syncFullHistory: true,
    markOnlineOnConnect: true,
    connectTimeoutMs: 60000,
    defaultQueryTimeoutMs: 0,
    keepAliveIntervalMs: 10000,
    generateHighQualityLinkPreview: true,
    patchMessageBeforeSending: (message) => {
      const requiresPatch = !!(
        message.buttonsMessage ||
        message.templateMessage ||
        message.listMessage
      )
      return (
        requiresPatch &&
          (message = {
            viewOnceMessage: {
              message: {
                messageContextInfo: {
                  deviceListMetadataVersion: 2,
                  deviceListMetadata: {},
                },
                ...message,
              },
            },
          }),
        message
      )
    },
    browser: ['Ubuntu', 'Chrome', '20.0.04'],
    logger: pino({ level: 'silent' }),
    version: version,
    auth: {
      creds: state.creds
    }
}

global.conn = simple.makeWASocket(makeWASocket)
conn.ev.on('creds.update', saveCreds)

...............

**Comment by APdev93** [comment]
> @APdev93 ![image](https://private-user-images.githubusercontent.com/65481692/320292797-2b55068f-8055-4e8f-acc1-5a24e2c64513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDg3MzgsIm5iZiI6MTcxMjUwODQzOCwicGF0aCI6Ii82NTQ4MTY5Mi8zMjAyOTI3OTctMmI1NTA2OGYtODA1NS00ZThmLWFjYzEtNWEyNGUyYzY0NTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE2NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjN2JiNzUzZDU4MDZlZWJmODA2NWY2MzQ4ZTg2OWI5Y2I5NTE1OGU5MzA4NDRmMzE2M2QyYTkxMTVkNDM5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fFGSkaQM2A7bUHhKFN1YE2KmH8ScReU9OfZOvaPT9qA) ![image](https://private-user-images.githubusercontent.com/65481692/320292824-5c75ba2e-4cf9-49fa-8aed-5b177994d17b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDg3MzgsIm5iZiI6MTcxMjUwODQzOCwicGF0aCI6Ii82NTQ4MTY5Mi8zMjAyOTI4MjQtNWM3NWJhMmUtNGNmOS00OWZhLThhZWQtNWIxNzc5OTRkMTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE2NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNDE2MzljMDg4ZmFhN2Y0NjQ0NTk2ZWZjYTI5OWQwYzFmMWE3NmJjOTdkMmVjOTlkMWUyOTYxODgyNmZmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ofsIrtSoxer6fkfAnjJr2jIIVMHCNVBCuxwR7F3CiE)
> 
> just the same

Umphhh, try to trouble shooting.

**Comment by APdev93** [comment]
> > @APdev93 ![image](https://private-user-images.githubusercontent.com/65481692/320292797-2b55068f-8055-4e8f-acc1-5a24e2c64513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDg3MzgsIm5iZiI6MTcxMjUwODQzOCwicGF0aCI6Ii82NTQ4MTY5Mi8zMjAyOTI3OTctMmI1NTA2OGYtODA1NS00ZThmLWFjYzEtNWEyNGUyYzY0NTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE2NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjN2JiNzUzZDU4MDZlZWJmODA2NWY2MzQ4ZTg2OWI5Y2I5NTE1OGU5MzA4NDRmMzE2M2QyYTkxMTVkNDM5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fFGSkaQM2A7bUHhKFN1YE2KmH8ScReU9OfZOvaPT9qA) ![image](https://private-user-images.githubusercontent.com/65481692/320292824-5c75ba2e-4cf9-49fa-8aed-5b177994d17b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDg3MzgsIm5iZiI6MTcxMjUwODQzOCwicGF0aCI6Ii82NTQ4MTY5Mi8zMjAyOTI4MjQtNWM3NWJhMmUtNGNmOS00OWZhLThhZWQtNWIxNzc5OTRkMTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE2NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNDE2MzljMDg4ZmFhN2Y0NjQ0NTk2ZWZjYTI5OWQwYzFmMWE3NmJjOTdkMmVjOTlkMWUyOTYxODgyNmZmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ofsIrtSoxer6fkfAnjJr2jIIVMHCNVBCuxwR7F3CiE)
> > just the same
> 
> Umphhh, try to trouble shooting.

In my code that's work

**Comment by SheIITear** [comment]
Rescan qr.

**Comment by rssdevoloper** [comment]
@SheIITear This is not a session problem, I haven't authenticated yet

**Comment by rssdevoloper** [comment]
@APdev93 can you help me with my script
