### ISSUE TITLE
[Question] how to make message with footer

### ISSUE THREAD

**Issue by Rizz-OFC** [WhiskeySockets/Baileys#720]
How do I make a message on WhatsApp have a footer like the photo I provided 
![Screenshot_2024-04-07-12-14-33-04](https://github.com/WhiskeySockets/Baileys/assets/161809385/f62f093d-f4e7-4d00-b505-fb25eceeb4b0)

**Comment by APdev93** [comment]
Uo

**Comment by DwiRizqiH** [comment]
use [interactiveMessage](https://whiskeysockets.github.io/Baileys/interfaces/proto.Message.IInteractiveMessage.html)

**Comment by SatganzDevs** [comment]
> use [interactiveMessage](https://whiskeysockets.github.io/Baileys/interfaces/proto.Message.IInteractiveMessage.html)

example please
