### ISSUE TITLE
[BUG] request registration code in Mobile mode, old_version error

### ISSUE THREAD

**Issue by DavidsonGomes** [WhiskeySockets/Baileys#721]
I get the old_version error when I try to request activation via voice or sms

<img width="728" alt="Screenshot 2024-04-08 at 16 27 14" src="https://github.com/WhiskeySockets/Baileys/assets/24706726/dd875dae-e9f0-42dc-8c5f-05cb806addd8">

**Comment by DavidsonGomes** [comment]
> Edit the application version to be more up to date
> 
> https://github.com/WhiskeySockets/Baileys/blob/f5a5eb991a6b14a6efdf48bcfed039966abaec8d/src/Defaults/index.ts#L23

I understood, but now this error appears here. What can it be?

 { reason: 'format_wrong', status: 'fail', login: '553131577388' }

**Comment by DavidsonGomes** [comment]
Ok, thanks

**Comment by Ghostyn18** [comment]
> I get the old_version error when I try to request activation via voice or sms
> 
> <img alt="Screenshot 2024-04-08 at 16 27 14" width="728" src="https://private-user-images.githubusercontent.com/24706726/320625583-dd875dae-e9f0-42dc-8c5f-05cb806addd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzY2NTQsIm5iZiI6MTcxMzgzNjM1NCwicGF0aCI6Ii8yNDcwNjcyNi8zMjA2MjU1ODMtZGQ4NzVkYWUtZTlmMC00MmRjLThjNWYtMDVjYjgwNmFkZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAxMzkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2E0MzMxNmNlZmI5YzM4MGZmNGJmNjEwMWQ5NmQzNjQ4YWNmN2MyOTkwNjgyMDg3Y2IyZGMyMTVjYTIxMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvmER5AdXmVffk0LY-eBxcELbpRPXfVMgvQ6QJOrUwI">

Send me code pls
