### ISSUE TITLE
[BUG] Cannot log in by scanning the QR code in version v6.6.0.

### ISSUE THREAD

**Issue by mission-sun** [WhiskeySockets/Baileys#724]
Today, I just upgraded the npm version to v6.6.0. When scanning the code to log in to the node terminal, an error occurs as described below. However, there is no issue when using v6.4.1. Has anyone encountered a similar problem?

unhandledRejection TypeError: $util.Long.fromValue is not a function
    at Function.fromObject (/node_modules/@whiskeysockets/baileys/WAProto/index.js:98968:60)
    at fromJSON (/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.js:313:60)
    at Object.readFromFile (/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.js:433:17)

**Comment by rameshbackendDev** [comment]
I am also encountering same issue.

**Comment by himanshuja** [comment]
Refer this, probably this may help. Recently due some changes at whatsapp's end most people encountered issue while logging in.  Please refer this issue #700 here is the branch with fix https://github.com/WhiskeySockets/Baileys/tree/fix-516 

Hopefully this may solve your issue.

**Comment by rameshbackendDev** [comment]
@himanshuja I have checked #700 there is no solution mentioned. It was just closed, no fix or solution suggested. Also the branch you suggested in an old branch from late 2023. Please elaborate if you know the solution.

**Comment by rameshbackendDev** [comment]
@mission-sun hey, pls let me know if you have found any work around. Thanks.

**Comment by Riders004** [comment]
https://github.com/WhiskeySockets/Baileys/issues/702#issuecomment-2032967692


Try that
