### ISSUE TITLE
Send massage seen list

### ISSUE THREAD

**Issue by ravindudil5han** [WhiskeySockets/Baileys#726]
When you post a message to a bot group via WhiskeySockets/Baileys, it would be valuable if you could get a list of group members who have seen that message.

**Comment by SuhailTechInfo** [comment]
> When you post a message to a bot group via WhiskeySockets/Baileys, it would be valuable if you could get a list of group members who have seen that message.

***YOU CAN GET RECEIPT INFO BY GETTING MESSAGE FROM STORE!***

### MUST TRY BELOW CODE

```js
let data = await store.loadMessage(message.jid, message.reply_message.id)
console.dir(data.userReceipt)
```

### OUTPUT
- result contains an array, of users with thier timeStamps
```js
[
    {
      userJid: '923xxxxxxxxxx@s.whatsapp.net',
      receiptTimestamp: 1713089726    
    }
]
```


***HOPE IT'll HELP YOU!***

**Comment by ravindudil5han** [comment]
> > When you post a message to a bot group via WhiskeySockets/Baileys, it would be valuable if you could get a list of group members who have seen that message.
> 
> _**YOU CAN GET RECEIPT INFO BY GETTING MESSAGE FROM STORE!**_
> 
> ### MUST TRY BELOW CODE
> ```js
> let data = await store.loadMessage(message.jid, message.reply_message.id)
> console.dir(data.userReceipt)
> ```
> 
> ### OUTPUT
> * result contains an array, of users with thier timeStamps
> 
> ```js
> [
>     {
>       userJid: '923xxxxxxxxxx@s.whatsapp.net',
>       receiptTimestamp: 1713089726    
>     }
> ]
> ```
> 
> _**HOPE IT'll HELP YOU!**_

Can you give me a loadmassage script. I haven't any idea what you tell. Is there any function in WhiskeySockets/Baileys
