### ISSUE TITLE
Emoji Reaction

### ISSUE THREAD

**Issue by nandoweb** [WhiskeySockets/Baileys#729]
Hello, the stickers do not appear when users use them in a message, the emoji comes out as if it were a separate message.

In other words, if 30 people Like a message, there will be 30 messages that whaticker will receive.

Any Solution?

Thanks
![image](https://github.com/WhiskeySockets/Baileys/assets/7269301/1ea1f8d7-3e28-42d7-a4f3-bec746645305)

**Comment by CAIOZIn1** [comment]
There is a property in baileys that returns whether it was a reaction to a message or something else

```following example in terminal:```

![image](https://github.com/WhiskeySockets/Baileys/assets/100611416/35f7a81d-3f69-4aba-a60b-cd7e86009f6d)

```Endpoint:```

![image](https://github.com/WhiskeySockets/Baileys/assets/100611416/592ba11e-52d8-4e65-a53b-7b4928b4d011)

NOTE: If it is not a reaction, the value null is returned.

I hope I helped, enjoy.

**Comment by nandoweb** [comment]
> There is a property in baileys that returns whether it was a reaction to a message or something else
> 
> `following example in terminal:`
> 
> ![image](https://private-user-images.githubusercontent.com/100611416/325347246-35f7a81d-3f69-4aba-a60b-cd7e86009f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5OTQwNDAsIm5iZiI6MTcxMzk5Mzc0MCwicGF0aCI6Ii8xMDA2MTE0MTYvMzI1MzQ3MjQ2LTM1ZjdhODFkLTNmNjktNGFiYS1hNjBiLWNkN2U4NjAwOWY2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQyMTIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQxZWJkMGU3Y2E5NWZjMjk1NWI3N2YxZDgxNWZmZTJiMjQ3YWIyYTkzZjJjZDJjNGUzODA5NDE1OTIzYTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Qqt67ly9vy92u0G6F1q__9qSjC9L-eMz7aqvwrAjVs)
> 
> `Endpoint:`
> 
> ![image](https://private-user-images.githubusercontent.com/100611416/325347482-592ba11e-52d8-4e65-a53b-7b4928b4d011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5OTQwNDAsIm5iZiI6MTcxMzk5Mzc0MCwicGF0aCI6Ii8xMDA2MTE0MTYvMzI1MzQ3NDgyLTU5MmJhMTFlLTUyZDgtNGU2NS1hNTNiLTdiNDkyOGI0ZDAxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQyMTIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDc0OWI2NmE4NTZjZmIwM2U4MTZlMjNkZTZhN2QxNzg4NzMwOWRhOGNlMmQwYTkwOTUyOTBiYTY5Yzk2Mzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p1VIW7eNQOyXL_kj180-aT_lzXKtpeFnjgJLG2RVRlg)
> 
> NOTE: If it is not a reaction, the value null is returned.
> 
> I hope I helped, enjoy.

How Solve in this code?

**Comment by PurpShell** [comment]
This looks like a whaticket-community issue, not a baileys one
