### ISSUE TITLE
[BUG] How fix Connection Terminate?

### ISSUE THREAD

**Issue by Laminhdatau** [WhiskeySockets/Baileys#731]
{"level":30,"time":"2024-04-16T02:19:58.982Z","pid":8720,"hostname":"klikdigitaldev","class":"baileys","trace":"Error: Connection Terminated\n    at WebSocketClient.<anonymous> (/home/klikdigitaldev/KLIKDIGITAL/JOB/csai_backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:439:30)\n    at WebSocketClient.emit (node:events:518:28)\n    at WebSocketClient.emit (node:domain:488:12)\n    at WebSocket.<anonymous> (/home/klikdigitaldev/KLIKDIGITAL/JOB/csai_backend/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:518:28)\n    at WebSocket.emit (node:domain:488:12)\n    at WebSocket.emitClose (/home/klikdigitaldev/KLIKDIGITAL/JOB/csai_backend/node_modules/ws/lib/websocket.js:260:10)\n    at TLSSocket.socketOnClose (/home/klikdigitaldev/KLIKDIGITAL/JOB/csai_backend/node_modules/ws/lib/websocket.js:1272:15)\n    at TLSSocket.emit (node:events:530:35)\n    at TLSSocket.emit (node:domain:488:12)","msg":"connection errored"}
DISCONNECT REASEON: 401

**Comment by Riders004** [comment]
Update your Baileys into latest

**Comment by loxeed1990** [comment]
my Baileys is already latest, but this error still occured, why is that?
