### ISSUE TITLE
[BUG] unable to get message.update event from poll vote

### ISSUE THREAD

**Issue by PwccaCode** [WhiskeySockets/Baileys#740]
**Describe the bug**
When voting on a poll the expected behavior is for an event to trigger on messages.update, but an event triggers on message.upsert
this event is of type notify(as expected)

{
  messages: [
    {
      key: [Object],
      messageTimestamp: 1713684493,
      pushName: 'EXAMPLE',
      broadcast: false,
      message: [Message]
    }
  ],
  type: 'notify'
}

but this cannot be used to decrypt the poll vote since its missing messagecreationKey

Create a connection send a poll, vote on it

**Expected behavior**

event messages.update triggers

**Environment (please complete the following information):**
 - Is this on a server? no local machine
 - Do you have multiple clients on the same IP?  no
 - Are you using a proxy? no 

**Additional context**
Its possible that im not fully understanding the necessary setup for a pollvote to be registered. please help

**Comment by SheIITear** [comment]
Poll update message DOES not contain the keys for decrypting the votes. You have to save the keys yourself.
