### ISSUE TITLE
Request Adding Charge Buyer for WhatsApp Bussiness

### ISSUE THREAD

**Issue by XanderID** [WhiskeySockets/Baileys#760]
Since there is a new feature on WhatsApp Business called Charge Buyer, can it be added to Baileys?

<h1>Charge Buyer</h1>

![Charge Buyer Image](https://github.com/WhiskeySockets/Baileys/assets/55838823/533420c3-468b-4d4d-89d6-a392851a6793)

<h1>Status of Charge Buyer</h1>

![Status of Charge Buyer](https://github.com/WhiskeySockets/Baileys/assets/55838823/5e5262d5-3970-472a-9978-768ebf8e112f)

<h1>Change Status of Charge Buyer</h1>

![Change Status Charge Buyer](https://github.com/WhiskeySockets/Baileys/assets/55838823/1923f5c7-da40-4604-b5d2-aefe209bebd2)

<h1>Charge Buyer Detail</h1>

![Detail Charge Buyer](https://github.com/WhiskeySockets/Baileys/assets/55838823/06f9398e-069e-4cbc-9e73-e1ab7ebebf79)

**Comment by PurpShell** [comment]
not possible, if possible via whatsapp web reopen
