### ISSUE TITLE
[BUG] Error playing audio on iOS/WA (Windows) devices

### ISSUE THREAD

**Issue by juniorkrz** [WhiskeySockets/Baileys#768]
There is an issue I noticed regarding audio/PTT messages, they are sent normally, but some devices cannot play the message.

Devices that don't work: iOS, WhatsApp (Windows)
Devices that work: Android, WhatsApp Web

**My code:**
```
client.sendMessage(
  message.key.remoteJid,
  { audio: { url: path }, ptt: true, mimetype: 'audio/mp4' },
  { quoted: message, ephemeralExpiration: WA_DEFAULT_EPHEMERAL }
)
```

![issue](https://github.com/WhiskeySockets/Baileys/assets/53500803/39d9b5d8-1328-4a54-b6f8-2849d537fe72)

**Comment by Alien-Alfa** [comment]
use mimetype: 'audio/mpeg' it will work both in iOS and android

**Comment by codespearhead** [comment]
@juniorkrz Did the above suggestion work? If so, can you close this issue?

**Comment by juniorkrz** [comment]
> use mimetype: 'audio/mpeg' it will work both in iOS and android

@Alien-Alfa Thanks for the suggestion, but this didn't work for me.

> @juniorkrz Did the above suggestion work? If so, can you close this issue?

@codespearhead The problem persists on iOS/Windows devices, only works on Android/WhatsApp Web

**Windows:**

![windows](https://github.com/WhiskeySockets/Baileys/assets/53500803/522202ec-76e9-44de-ba37-b6c7afacb644)

**iOS:**

![iOS](https://github.com/WhiskeySockets/Baileys/assets/53500803/48059b50-b24e-4034-acf9-0adc4011600e)

**Comment by codespearhead** [comment]
Try `audio/ogg; codecs=opus`.

Possibly related: #501

**Comment by juniorkrz** [comment]
> Try `audio/ogg; codecs=opus`:
> 
> https://github.com/WhiskeySockets/Baileys/blob/79c33e53b4124735f019c48e8075c9cde807b7e7/src/Utils/messages.ts#L52
> 
> Possibly related: #501

@codespearhead This way it didn't work on Android or iOS

**Comment by juniorkrz** [comment]
Thanks to everyone for the help.

What worked for me was converting the audio to `aac` using `fluent-ffmpeg` and sending it with the mimetype `audio/aac`.
