### ISSUE TITLE
[BUG] Message is not sent to broadcast lists

### ISSUE THREAD

**Issue by allanlisboa** [WhiskeySockets/Baileys#781]
As you can see, I am sending the message to a broadcast. However, the message arrives at a number instead of being sent in transmission...

**Comment by allanlisboa** [comment]
As you can see, I am sending the message to a broadcast. However, the message arrives at a number instead of being sent in transmission...

![Captura de Tela 2024-05-14 às 09 02 24](https://github.com/WhiskeySockets/Baileys/assets/37181884/0fa6d894-8e6f-43f8-90cb-a0dda709d693)

![WhatsApp Image 2024-05-14 at 09 05 12](https://github.com/WhiskeySockets/Baileys/assets/37181884/c494db02-c501-49cb-afb4-ff7a5343f938)


![Captura de Tela 2024-05-14 às 09 08 04](https://github.com/WhiskeySockets/Baileys/assets/37181884/bd3a2b3c-9b34-47de-9387-1ea5abb3634b)

![Captura de Tela 2024-05-14 às 09 08 27](https://github.com/WhiskeySockets/Baileys/assets/37181884/1df1b31e-e194-4827-ad9a-694d741cea39)

**Comment by Rippanteq7** [comment]
> As you can see, I am sending the message to a broadcast. However, the message arrives at a number instead of being sent in transmission...
> 
> Message fired from the api: ![Captura de Tela 2024-05-14 às 09 02 24](https://private-user-images.githubusercontent.com/37181884/330415656-0fa6d894-8e6f-43f8-90cb-a0dda709d693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MTU2NTYtMGZhNmQ4OTQtOGU2Zi00M2Y4LTkwY2ItYTBkZGE3MDlkNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTEyZDc0YzY0ZDQ2MWYxMDRiYTczZDUzOWViZjY3MGEzMDIwOGEyY2MzMjUxNGY5ZGZkYmYyNTAwMWY5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ToDeYNXj26EblPMzfBTTvIQL1NoGeOOxHepWQ-yJsDU)
> 
> On WhatsApp the message is sent to a WhatsApp number: ![WhatsApp Image 2024-05-14 at 09 10 04](https://private-user-images.githubusercontent.com/37181884/330418618-50473a0c-92c9-4337-afc9-023ec1146b51.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MTg2MTgtNTA0NzNhMGMtOTJjOS00MzM3LWFmYzktMDIzZWMxMTQ2YjUxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGY0MjNjYTI4OWEzY2NiZTlhOGM2N2JlMTM1NjBhZDFlMTNmMTc2ZmUxYTEwMDA3NDI5NDJjMWEwODZlN2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rsRBa-1K9szuh-WmjGWwtbXAwaD2l6VCsIe6709NziU)
> 
> API version: ![Captura de Tela 2024-05-14 às 09 08 27](https://private-user-images.githubusercontent.com/37181884/330417788-1df1b31e-e194-4827-ad9a-694d741cea39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MTc3ODgtMWRmMWIzMWUtZTE5NC00ODI3LWFkOWEtNjk0ZDc0MWNlYTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODk0OTY3MTk5ZTJhZmIyNGM0Y2JmY2M0OTJjY2FkNmFmOWJjOTBmYmJmYmYxNGM5NWQ4ZmU4OGJmODk3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OmKozzpwsnKI-npJpp2hoc66hVLaROWnfR5zzkJIZmY)
> 
> ![Captura de Tela 2024-05-14 às 09 14 19](https://private-user-images.githubusercontent.com/37181884/330420053-f75745d6-c25e-4d63-8669-f0d98df1df5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MjAwNTMtZjc1NzQ1ZDYtYzI1ZS00ZDYzLTg2NjktZjBkOThkZjFkZjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2Y2YzA0NjM0OTllZDZhMGZjYmE1NTQ4MWU2NzY0ZGE5ZTY4MjhhNzQxYjVmMmUxNzhmYmRhZmY5Nzc2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1L91HroWtwZzFa3dRypAXRvs0OiUqUIECZl2DmGbtw)

Check [#249](https://github.com/WhiskeySockets/Baileys/pull/249#issue-1806303548)

**Comment by allanlisboa** [comment]
> > As you can see, I am sending the message to a broadcast. However, the message arrives at a number instead of being sent in transmission...
> > Message fired from the api: ![Captura de Tela 2024-05-14 às 09 02 24](https://private-user-images.githubusercontent.com/37181884/330415656-0fa6d894-8e6f-43f8-90cb-a0dda709d693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MTU2NTYtMGZhNmQ4OTQtOGU2Zi00M2Y4LTkwY2ItYTBkZGE3MDlkNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTEyZDc0YzY0ZDQ2MWYxMDRiYTczZDUzOWViZjY3MGEzMDIwOGEyY2MzMjUxNGY5ZGZkYmYyNTAwMWY5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ToDeYNXj26EblPMzfBTTvIQL1NoGeOOxHepWQ-yJsDU)
> > On WhatsApp the message is sent to a WhatsApp number: ![WhatsApp Image 2024-05-14 at 09 10 04](https://private-user-images.githubusercontent.com/37181884/330418618-50473a0c-92c9-4337-afc9-023ec1146b51.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MTg2MTgtNTA0NzNhMGMtOTJjOS00MzM3LWFmYzktMDIzZWMxMTQ2YjUxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNTU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGY0MjNjYTI4OWEzY2NiZTlhOGM2N2JlMTM1NjBhZDFlMTNmMTc2ZmUxYTEwMDA3NDI5NDJjMWEwODZlN2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rsRBa-1K9szuh-WmjGWwtbXAwaD2l6VCsIe6709NziU)
> > API version: ![Captura de Tela 2024-05-14 às 09 08 27](https://private-user-images.githubusercontent.com/37181884/330417788-1df1b31e-e194-4827-ad9a-694d741cea39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MTc3ODgtMWRmMWIzMWUtZTE5NC00ODI3LWFkOWEtNjk0ZDc0MWNlYTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODk0OTY3MTk5ZTJhZmIyNGM0Y2JmY2M0OTJjY2FkNmFmOWJjOTBmYmJmYmYxNGM5NWQ4ZmU4OGJmODk3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OmKozzpwsnKI-npJpp2hoc66hVLaROWnfR5zzkJIZmY)
> > ![Captura de Tela 2024-05-14 às 09 14 19](https://private-user-images.githubusercontent.com/37181884/330420053-f75745d6-c25e-4d63-8669-f0d98df1df5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI0NDIsIm5iZiI6MTcxNTcwMjE0MiwicGF0aCI6Ii8zNzE4MTg4NC8zMzA0MjAwNTMtZjc1NzQ1ZDYtYzI1ZS00ZDYzLTg2NjktZjBkOThkZjFkZjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2Y2YzA0NjM0OTllZDZhMGZjYmE1NTQ4MWU2NzY0ZGE5ZTY4MjhhNzQxYjVmMmUxNzhmYmRhZmY5Nzc2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1L91HroWtwZzFa3dRypAXRvs0OiUqUIECZl2DmGbtw)
> 
> Check [#249](https://github.com/WhiskeySockets/Baileys/pull/249#issue-1806303548)


In my case, Satatus works perfectly. But I want to send a message to a specific broadcast list and it is not working as above

**Comment by Francuchin** [comment]
Same Error... D:

**Comment by PurpShell** [comment]
sending from broadcast list will not work on web, wontfix

**Comment by mr-mr7** [comment]
how find jid of broadcast list ???
