### ISSUE TITLE
[BUG] Error: Connection Failure , statusCode 405

### ISSUE THREAD

**Issue by fauziiram** [WhiskeySockets/Baileys#807]
WebSocket.emit (node:events:513:28)","msg":"connection errored"}
connection closed due to  Error: Connection Failure
    at WebSocket.emit (node:events:513:28) {
  data: { reason: '405', location: 'vll' },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: {
      statusCode: 405,
      error: 'Method Not Allowed',
      message: 'Connection Failure'
    },
    headers: {}
  }
} , reconnecting  true

**Comment by Keito-Klein** [comment]
I got the same error before, then i reinstall the modules and i enter new pairing code got error code 428 : Precondition required. Any solution?

**Comment by sudhansupujari** [comment]
{
  "connection": "close",
  "lastDisconnect": {
    "error": {
      "data": {
        "reason": "405",
        "location": "frc"
      },
      "isBoom": true,
      "isServer": false,
      "output": {
        "statusCode": 405,
        "payload": {
          "statusCode": 405,
          "error": "Method Not Allowed",
          "message": "Connection Failure"
        },
        "headers": {}
      }
    },
    "date": "2024-05-21T01:35:26.275Z"
  }
}

**Comment by pedroota** [comment]
I'm handling about 20 sessions on my db and I'm having this exact same problem, on the console.log just appear error 405

**Comment by athilasb** [comment]
I'm running with 24 machines, all of them crashed, I can't generate the QR Code either

**Comment by pedroota** [comment]
> I'm running with 24 machines, all of them stopped, and I can't generate the QR Code

I'm having this exact problem right now. @PurpShell could you take a look?

**Comment by pedroota** [comment]
🎉 TEMPORARY SOLUTION 🎉

Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.

Here’s what you can do:

Uninstall the current version:

`npm uninstall @whiskeysockets/baileys`

Install the specific version:

`npm install @whiskeysockets/baileys@6.6.0`

But if the manteiners solve this on the latest version, It's even better @PurpShell (I think it's some to implement some Unit Tests)

**Comment by IrfanMaulana00** [comment]
> 🎉 TEMPORARY SOLUTION 🎉
> 
> Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.
> 
> Here’s what you can do:
> 
> Uninstall the current version:
> 
> `npm uninstall @whiskeysockets/baileys`
> 
> Install the specific version:
> 
> `npm install @whiskeysockets/baileys@6.6.0`
> 
> But if the manteiners solve this on the latest version, It's even better @PurpShell (I think it's time to implement some Unit Tests)

not working for me

**Comment by athilasb** [comment]
> 6.6.0

Good, it worked, thank you very much🎉

**Comment by athilasb** [comment]
![image](https://github.com/WhiskeySockets/Baileys/assets/75426305/6f3d0494-fb94-447c-81d2-820c73b1eb96)

**Comment by nimius-debug** [comment]
amazing, thanks it worked @pedroota

**Comment by AkashSaikia** [comment]
Thanks @pedroota 
Works!

Help @PurpShell @SheIITear much appreciated here.

**Comment by gatothp** [comment]
Great, it's working. Thanks

**Comment by mikelx99** [comment]
> The latest version is already fixed. Update baileys and close this issue!

How do I update to the latest version? npm package ( version 6.7.2 ) still has the same issue.

**Comment by dihak** [comment]
> The latest version is already fixed. Update baileys and close this issue!

Still error on latest edge version.

**Comment by nimius-debug** [comment]
sock = makeWASocket({
    version: [2, 2413, 1],
    
   directly pass the version [2, 2413, 1],
   it will fix the problem

**Comment by rakumairu** [comment]
> @dihak @mikelx99 temp solution that work for me sock = makeWASocket({ version: [2, 2413, 1],
> 
> directly pass the version [2, 2413, 1], it will fix the problem

I tried this, but getting an error right after I started the app

```
.../node_modules/baileys/lib/Socket/socket.js:28
    ws.connect();
       ^

TypeError: ws.connect is not a function
    at makeSocket (.../node_modules/baileys/lib/Socket/socket.js:28:8)
    at makeChatsSocket (.../node_modules/baileys/lib/Socket/chats.js:19:42)
    at makeGroupsSocket (.../node_modules/baileys/lib/Socket/groups.js:10:46)
    at makeMessagesSocket (.../node_modules/baileys/lib/Socket/messages-send.js:18:48)
    at makeMessagesRecvSocket (.../node_modules/baileys/lib/Socket/messages-recv.js:21:57)
    at makeBusinessSocket (.../node_modules/baileys/lib/Socket/business.js:9:61)
    at makeRegistrationSocket (.../node_modules/baileys/lib/Socket/registration.js:20:52)
    at makeWASocket (.../node_modules/baileys/lib/Socket/index.js:6:77)
    at connectToWhatsApp (.../build/baileys/waSocket.js:59:40)
```

**Comment by derispewss** [comment]
> 🎉 TEMPORARY SOLUTION 🎉
> 
> Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.
> 
> Here’s what you can do:
> 
> Uninstall the current version:
> 
> `npm uninstall @whiskeysockets/baileys`
> 
> Install the specific version:
> 
> `npm install @whiskeysockets/baileys@6.6.0`
> 
> But if the manteiners solve this on the latest version, It's even better @PurpShell (I think it's time to implement some Unit Tests)

Thanksss, worked!

**Comment by mdmaruf782** [comment]
> @dihak @mikelx99 temp solution that work for me sock = makeWASocket({ version: [2, 2413, 1],
> 
> directly pass the version [2, 2413, 1], it will fix the problem

its work... thank you

**Comment by sairmali** [comment]
which directory can i change this code ?

**Comment by sairmali** [comment]
?

**Comment by meetshamee** [comment]
> 🎉 TEMPORARY SOLUTION 🎉
> 
> Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.
> 
> Here’s what you can do:
> 
> Uninstall the current version:
> 
> `npm uninstall @whiskeysockets/baileys`
> 
> Install the specific version:
> 
> `npm install @whiskeysockets/baileys@6.6.0`
> 
> But if the manteiners solve this on the latest version, It's even better @PurpShell (I think it's time to implement some Unit Tests)

Working

**Comment by sairmali** [comment]
> > 🎉 TEMPORARY SOLUTION 🎉
> > Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.
> > Here’s what you can
> > Uninstall the current version:
> > `npm uninstall @whiskeysockets/baileys`
> > Install the specific version:
> > `npm install @whiskeysockets/baileys@6.6.0`
> > But if the manteiners solve this on the latest version, It's even better @PurpShell (I think it's time to implement some Unit Tests)
> 
> Working

I am using old libraries  https://www.npmjs.com/package/@adiwajshing/baileys so how can add this ?

**Comment by sairmali** [comment]
?

**Comment by Xrazik1** [comment]
> @dihak @mikelx99 temp solution that work for me sock = makeWASocket({ version: [2, 2413, 1],
> 
> directly pass the version [2, 2413, 1], it will fix the problem

Which baileys version is it, according to releases list?

**Comment by Guilherme-j10** [comment]
> @dihak @mikelx99 solução temporária que funciona para mim sock = makeWASocket({ version: [2, 2413, 1],
> 
> passe diretamente a versão [2, 2413, 1], isso resolverá o problema

where did you get this information

**Comment by Amr006** [comment]
@sairmali 
i am using "@adiwajshing/baileys": "^4.2.0",
and this works for me 

const waConfig = {
        auth: state,
        printQRInTerminal: true,  // This should work if not overridden
        logger,
        browser: deviceOSBrowser,
        syncFullHistory: userBySession.syncFullHistory ?? false,
        version: [2, 2413, 1],
        defaultQueryTimeoutMs: undefined,
    };
or
 you can just change version: [2, 2413, 1],

**Comment by wandrey7** [comment]
> 🎉 TEMPORARY SOLUTION 🎉
> 
> Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.
> 
> Here’s what you can do:
> 
> Uninstall the current version:
> 
> `npm uninstall @whiskeysockets/baileys`
> 
> Install the specific version:
> 
> `npm install @whiskeysockets/baileys@6.6.0`
> 
> But if the manteiners solve this on the latest version, It's even better @PurpShell (I think it's time to implement some Unit Tests)

it's working, thanks

**Comment by aledc7** [comment]
> 🎉 TEMPORARY SOLUTION 🎉
> 
> Hey everyone, I found a temporary solution for the issue we've been experiencing. I was initially using the latest version of the library (6.7.2), but after downgrading to version 6.6.0, everything is now working fine.
> 
> Here’s what you can do:
> 
> Uninstall the current version:
> 
> `npm uninstall @whiskeysockets/baileys`
> 
> Install the specific version:
> 
> `npm install @whiskeysockets/baileys@6.6.0`
> 
> But if the manteiners solve this on the latest version, It's even better [@purpshell](https://github.com/purpshell) (I think it's time to implement some Unit Tests)



Thanks, it solved the problem. The latest version still has the same issue. These things highlight the need for an alternative to Baileys. Any suggestions?
