### ISSUE TITLE
[BUG] error status code 405

### ISSUE THREAD

**Issue by RidwanzAnphelibelll** [WhiskeySockets/Baileys#808]
eror status code 405

**Comment by rezahaesbe5** [comment]
why method not allowed (405) ?

**Comment by nimius-debug** [comment]
temp solution that work for me
sock = makeWASocket({
version: [2, 2413, 1],

directly pass the version [2, 2413, 1],
it will fix the problem

**Comment by bi16m06** [comment]
> temp solution that work for me sock = makeWASocket({ version: [2, 2413, 1],
> 
> directly pass the version [2, 2413, 1], it will fix the problem

can you screenshot ur code for example?

**Comment by itsmeichwan** [comment]
> temp solution that work for me sock = makeWASocket({ version: [2, 2413, 1],
> 
> directly pass the version [2, 2413, 1], it will fix the problem

Cool, It works on me  too

**Comment by itsmeichwan** [comment]
> > temp solution that work for me sock = makeWASocket({ version: [2, 2413, 1],
> > directly pass the version [2, 2413, 1], it will fix the problem
> 
> can you screenshot ur code for example?

![image](https://github.com/WhiskeySockets/Baileys/assets/68050501/51acd8e2-f5e1-4e9f-8d4d-9415eb0fc555)
> Put ur code like this

**Comment by eckoSantoso** [comment]
nice temporary solution, its work.
