### ISSUE TITLE
[BUG] Property 'call' does not exist on type 'void'.

### ISSUE THREAD

**Issue by moskoweb** [WhiskeySockets/Baileys#81]
**Describe the bug**
When installing the package locally to update, the error below appears regarding WebSocket. I corrected the error, removing the `sendPromise` variable, and calling `ws.send`, inside the `sendRawMessage` function, so as not to have more errors.

Error:
<img width="1710" alt="Captura de Tela 2023-05-19 às 15 45 31" src="https://github.com/WhiskeySockets/Baileys/assets/6052272/ed0c697a-ed62-4f34-aa3d-e5ac50129d41">

Solution:
<img width="781" alt="Captura de Tela 2023-05-19 às 15 47 22" src="https://github.com/WhiskeySockets/Baileys/assets/6052272/bc7ab05e-6a34-4429-a188-e483e2078264">

**To Reproduce**
1. Git clone
2. Yarn install

**Comment by barkerpedro** [comment]
try changing the line:
``` typescript
const sendPromise = promisify<void>(ws.send)
```
to:
``` typescript
const sendPromise = promisify<ArrayBufferLike>(ws.send)
```
