### ISSUE TITLE
[BUG] Can't link devices

### ISSUE THREAD

**Issue by AKAZAMD** [WhiskeySockets/Baileys#812]
I can't link the device. I've tried using the pairing code and qrcode method, it still doesn't work
...when I use the pairing code
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^
Error: Connection Closed
    at sendRawMessage (/home/container/node_modules/baileys/lib/Socket/socket.js:54:19)
    at sendNode (/home/container/node_modules/baileys/lib/Socket/socket.js:73:16)
    at Object.requestPairingCode (/home/container/node_modules/baileys/lib/Socket/socket.js:370:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/container/index.js:70:22) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,

I think it's like that in the panel it's hard to copy everything
...when using qrcode
Unknown DisconnectReason: 405|close

So that's what the error looks like, I have tried several versions of Baileys, from the new to the old, it's the same

**Comment by G-rillei** [comment]
Same error here

**Comment by defrindr** [comment]
same with me

**Comment by VampXDH** [comment]
I'm the same way too

**Comment by barkerpedro** [comment]
Unknown disconnection reason: 405
this error means the WA version is out of date, check the commit https://github.com/WhiskeySockets/Baileys/pull/805

**Comment by harvansh265** [comment]
after updated version now i am getting status 516 after qr scan

 | Error: Stream Errored (unknown)
  |     at WebSocketClient.<anonymous> (@whiskeysockets/baileys/lib/So                                                                    cket/socket.js:501:13)
  |     at WebSocketClient.emit (node:events:512:28)
  |     at WebSocketClient.emit (node:domain:489:12)
  |     at @whiskeysockets/baileys/lib/Socket/socket.js:236:35
  |     at Object.decodeFrame (@whiskeysockets/baileys/lib/Utils/noise                                                                    -handler.js:136:17)
  |     at WebSocketClient.onMessageRecieved (@whiskeysockets/baileys/                                                                    lib/Socket/socket.js:212:15)
  |     at WebSocketClient.emit (node:events:512:28)
  |     at WebSocketClient.emit (node:domain:489:12)
  |     at WebSocket.<anonymous> (@whiskeysockets/baileys/lib/Socket/C                                                                    lient/web-socket-client.js:46:100)
  |     at WebSocket.emit (node:events:512:28)
  |     at WebSocket.emit (node:domain:489:12)
  |     at Receiver.receiverOnMessage (ws/lib/websocket.js:1184:20)
  |     at Receiver.emit (node:events:512:28)
  |     at Receiver.emit (node:domain:489:12)
  |     at Receiver.dataMessage (ws/lib/receiver.js:526:14)
  |     at Receiver.getData (ws/lib/receiver.js:459:17)
  |     at Receiver.startLoop (ws/lib/receiver.js:158:22)
  |     at Receiver._write (ws/lib/receiver.js:84:10)
  |     at writeOrBuffer (node:internal/streams/writable:399:12)
  |     at _write (node:internal/streams/writable:340:10)
  |     at Writable.write (node:internal/streams/writable:344:10)
  |     at TLSSocket.socketOnData (ws/lib/websocket.js:1278:35) {
  |   data: { tag: 'stream:error', attrs: { code: '516' }, content: undefined },
  |   isBoom: true,
  |   isServer: true,
  |   output: {
  |     statusCode: 516,
  |     payload: {
  |       statusCode: 516,
  |       error: 'Unknown',
  |       message: 'Stream Errored (unknown)'
  |     },
  |     headers: {}
  |   }
  | }

**Comment by mayankagar360** [comment]
Any Update

**Comment by Alien-Alfa** [comment]
check issue #710

**Comment by Alien-Alfa** [comment]
duplicate issue check #783

**Comment by Loki-Xer** [comment]
Same error i think baileys team have to give a proper update for this issue 🫢

**Comment by jadielsousa** [comment]
I managed to solve it by generating the prototype again by following the following step:

cd proto-extract
npm i or yarn 
npm run start or yarn start

https://github.com/WhiskeySockets/Baileys/tree/master/proto-extract

The script will update ../WAProto/WAProto.proto (except if something is broken)

**Comment by harvansh265** [comment]
> I managed to solve it by generating the prototype again by following the following step:
> 
> cd proto-extract npm i or yarn npm run start or yarn start
> 
> https://github.com/WhiskeySockets/Baileys/tree/master/proto-extract
> 
> The script will update ../WAProto/WAProto.proto (except if something is broken)

Not working ,  get same 516 error

**Comment by AKAZAMD** [comment]
after I updated the version it turned out it worked so what should I close this but if I close it then other people don't know how
version: [2, 2413, 1]

**Comment by harvansh265** [comment]
> > > I managed to solve it by generating the prototype again by following the following step:
> > > cd proto-extract npm i or yarn npm run start or yarn start
> > > https://github.com/WhiskeySockets/Baileys/tree/master/proto-extract
> > > The script will update ../WAProto/WAProto.proto (except if something is broken)
> > 
> > 
> > Not working , get same 516 error
> 
> Copy the new WAProto folder to node_modules/@whiskeysockets/baileys in your project.


copied and updated all things as you said like npm install and npm start but not worked

**Comment by marsescobin** [comment]
This is unfortunately still an issue: 

- Tried with multiple devices 
- It seems WA may be flagging the connection as suspicious and disconnecting right away?

`{"level":30,"time":"2025-04-10T00:05:25.305Z","pid":27269,"hostname":"Mariannes-MacBook-Air.local","class":"baileys","me":{"id":"15092005582:4@s.whatsapp.net","name":"Rover AI [test]"},"platform":"smbi","msg":"pairing configured successfully, expect to restart the connection..."}
{"level":50,"time":"2025-04-10T00:05:25.689Z","pid":27269,"hostname":"Mariannes-MacBook-Air.local","class":"baileys","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
🔌 Connection closed — possibly logged out or session expired.
{"level":30,"time":"2025-04-10T00:05:25.690Z","pid":27269,"hostname":"Mariannes-MacBook-Air.local","class":"baileys","trace":"Error: Stream Errored (restart required)\n    at WebSocketClient.<anonymous> (/Users/marsescobin/coding projects/rover-ai-bot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:519:13)\n    at WebSocketClient.emit (node:events:514:28)\n    at /Users/marsescobin/coding projects/rover-ai-bot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35\n    at Object.decodeFrame (/Users/marsescobin/coding projects/rover-ai-bot/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:144:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"connection errored"}`
