### ISSUE TITLE
How to edit message 

### ISSUE THREAD

**Issue by music-sir** [WhiskeySockets/Baileys#82]
# How to edit message

**Comment by andresayac** [comment]
here it is

https://github.com/WhiskeySockets/Baileys/issues/60

**Comment by Adhaaz** [comment]
> here it is
> 
> #60

How about creating a poll in a group, sir?

**Comment by andresayac** [comment]
@edgardmessias closed this please

**Comment by hbinduni** [comment]
this is how i edit msg, but currently only support in mobile app, has no effect to desktop client:
```
const {key} = await sock.sendMessage(jid, {text: 'Hello there!'});
await waitFor(1000 * 2); // put delay 2secs
await sock.sendMessage(jid, {text: 'Hello there edited!', edit: key});
```
