### ISSUE TITLE
Pair Account from Mobile to Web

### ISSUE THREAD

**Issue by imredfox** [WhiskeySockets/Baileys#838]
Hello.

I want to pair our accounts created with Baileys from Whatsapp mobile to Whatsapp Web with pair code.

I also accept paid solutions. People who can produce paid solutions can write whatsapp or telegram information.

(Paid solutions continue through upwork.com)

Thank you.

**Comment by Riders004** [comment]
It's simple see docs

**Comment by imredfox** [comment]
> It's simple see docs

I need pairing from mobile api (baileys) to whatsapp web (web.whatsapp.com), not pairing from mobile device to baileys.

**Comment by Riders004** [comment]
> > It's simple see docs
> 
> I need pairing from mobile api (baileys) to whatsapp web (web.whatsapp.com), not pairing from mobile device to baileys.

Show me the error
