### ISSUE TITLE
When I use bailyes to send an image to a whatsapp channel, this is how the preview is shown before the image is downloaded. How to fix this?

### ISSUE THREAD

**Issue by vihangaashin** [WhiskeySockets/Baileys#844]
When I use bailyes to send an image to a whatsapp channel, this is how the preview is shown before the image is downloaded. How to fix this?
![Screenshot_20240605-144611_WhatsApp](https://github.com/WhiskeySockets/Baileys/assets/170451546/db456547-093b-4fcb-8c83-bd0e67c3d667)

**Comment by spacesoft321** [comment]
you can test it in FastWSapi.com

there all type solution and **customize as per user or developer**

**Comment by Riders004** [comment]
> When I use bailyes to send an image to a whatsapp channel, this is how the preview is shown before the image is downloaded. How to fix this? ![Screenshot_20240605-144611_WhatsApp](https://private-user-images.githubusercontent.com/170451546/336773873-db456547-093b-4fcb-8c83-bd0e67c3d667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MzI4MzcsIm5iZiI6MTcxOTUzMjUzNywicGF0aCI6Ii8xNzA0NTE1NDYvMzM2NzczODczLWRiNDU2NTQ3LTA5M2ItNGZjYi04YzgzLWJkMGU2N2MzZDY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QyMzU1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjA1ZWZmNDc2MmE5MDc5MTY2YmYyOWYzMjNjM2JkNThhNzI5ZTE3MzVjODM0ZDhiNmMyMjM2MjM4ZjFhOTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v8iGpMs80zNRmq22xohUbZxbnFZ-zQNvo59DZcINHEk)

Try close the WhatsApp and re-open

**Comment by klauskkj10** [comment]
> When I use bailyes to send an image to a whatsapp channel, this is how the preview is shown before the image is downloaded. How to fix this?
> ![Screenshot_20240605-144611_WhatsApp](https://github.com/WhiskeySockets/Baileys/assets/170451546/db456547-093b-4fcb-8c83-bd0e67c3d667)
> 

For a preview to appear, you depend on the ffmpeg dependency. You must install ffmpeg using "pkg install ffmpeg"
