### ISSUE TITLE
sending document with caption is not received

### ISSUE THREAD

**Issue by tibitfone** [WhiskeySockets/Baileys#865]
Hello everyone, using a whaticket with baileys version v6.7.4.
When I receive a document with subtitles, the error occurs.

Didn't find type 152: documentWithCaptionMessage
As a result, I cannot receive documents with captions.
examples:
![image](https://github.com/WhiskeySockets/Baileys/assets/146264344/7eae2724-0220-4609-88e1-8f108d786b9d)

![image](https://github.com/WhiskeySockets/Baileys/assets/146264344/704618bb-d928-4a7a-9acd-edb9c291022a)

Bayles doesn't receive documents with captions?
Or is there any way to solve this?

**Comment by SheIITear** [comment]
Test with baileys itself and if the issue persists share your code and open a new one.
