### ISSUE TITLE
[BUG] EPERM: operation not permitted in unlink temp file

### ISSUE THREAD

**Issue by AndresGnu** [WhiskeySockets/Baileys#867]
**Describe the bug**
EPERM: operation not permitted in unlink temp file in Windows
![image](https://github.com/WhiskeySockets/Baileys/assets/8808619/e06e6d3e-ac13-4477-8843-abec688b48ac)

**To Reproduce**

Run the library on Windows and try to send the image

**Expected behavior**

I hope the error does not stop the entire shipping process.

**Environment (please complete the following information):**
 - Windows 10
 - Node 20.14

**Additional context**
![image](https://github.com/WhiskeySockets/Baileys/assets/8808619/3f3f1c8a-d3d2-4984-b58b-36bc6204eb06)

**Comment by vermaysha** [comment]
Its error because your own source code, not on baileys lib

**Comment by bobslavtriev** [comment]
your code, not baileys, close this issue

**Comment by SheIITear** [comment]
You have something wrong with your permissions. Temp folder should be accessible by programs. This does not directly seem to be baileys issue hence closing for now.
