### ISSUE TITLE
[BUG] Contact Sending name bugs should send "N" instead of "FN"

### ISSUE THREAD

**Issue by jmedellinc** [WhiskeySockets/Baileys#87]
**Describe the bug**
1) When sending a contact, one must send "N" instead of "FN" as part of the name, or the contact received doesn't include the name.
2) displayName stopped working at some momment.  It's shown only as "Contact". Tried name without luck..

**To Reproduce**
Follow the exact guidelines in 
https://whiskeysockets.github.io/docs/tutorial-basics/sending-messages#non-media-messages
const vcard =
  "BEGIN:VCARD\n" + // metadata of the contact card
  "VERSION:3.0\n" +
  "FN:Jeff Singh\n" + // full name
  "ORG:Ashoka Uni;\n" + // the organization of the contact
  "TEL;type=CELL;type=VOICE;waid=911234567890:+91 12345 67890\n" + // WhatsApp ID + phone number
  "END:VCARD";
const sentMsg = await sock.sendMessage(id, {
  contacts: {
    displayName: "Jeff",
    contacts: [{ vcard }],
  },
});

**Expected behavior**
The contact should be received, including the name of the contact, which doesn't happen..
What's received  is a generic "Contact" contact
<img src="https://github.com/WhiskeySockets/Baileys/assets/105754419/e7d2c115-f2b1-43c0-bf29-24777c702802" width="300"/>
And when you open it, the name doesn't show up:
<img src="https://github.com/WhiskeySockets/Baileys/assets/105754419/9134406a-6e1d-4ecf-af23-2685be3aa607" width="300"/>

If you replace "FN" with "N" (and add semi-colons), the name appears in the contact.
const vcard =
  "BEGIN:VCARD\n" + // metadata of the contact card
  "VERSION:3.0\n" +
  "N:Jeff;Singh\n" + // full name
  "ORG:Ashoka Uni;\n" + // the organization of the contact
  "TEL;type=CELL;type=VOICE;waid=911234567890:+91 12345 67890\n" + // WhatsApp ID + phone number
  "END:VCARD";
<img src="https://github.com/WhiskeySockets/Baileys/assets/105754419/0364f63b-5462-4137-982a-e218603a7047" width="300"/>

I couldn't "fix" the JSON keyname for the name to be shown on the messagelist

Updating the guide would be enough for (1) but for (2) I suppose whatsapp server made changes..

Thanks!

**Comment by PurpShell** [comment]
Send contacts via the dedicated message type for them
