### ISSUE TITLE
[BUG] Closing open session in favor of incoming prekey bundle / Closing session: SessionEntry

### ISSUE THREAD

**Issue by oscarguindzberg** [WhiskeySockets/Baileys#887]
**Describe the bug**
I have a server with 15 connected whatsapp users.
I find this on the log from time to time:

```
Closing open session in favor of incoming prekey bundle
Closing session: SessionEntry {
  _chains: {
    'xxx': { chainKey: [Object], chainType: 2, messageKeys: {} },
    'xxx': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 2031812068,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer xx xx xx ...>,
      privKey: <Buffer xx xx xx ...>
    },
    lastRemoteEphemeralKey: <Buffer xx xx xx ...>,
    previousCounter: 0,
    rootKey: <Buffer xx xx xx ...>
  },
  indexInfo: {
    baseKey: <Buffer xx xx xx ...>,
    baseKeyType: 2,
    closed: -1,
    used: 1718654391536,
    created: 1718654391536,
    remoteIdentityKey: <Buffer xx xx xx ...>
  }
}
```

I know this is printed by libsignal, I guess these lines are the culprits:
- https://github.com/adiwajshing/libsignal-node/blob/11dbd962ea108187c79a7c46fe4d6f790e23da97/src/session_builder.js#L74
- https://github.com/adiwajshing/libsignal-node/blob/11dbd962ea108187c79a7c46fe4d6f790e23da97/src/session_record.js#L273

**To Reproduce**
Don't know how to reproduce, it happens from time to time on a server with 15 connected whatsapp users.

**Expected behavior**
No errors on the log

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? 
```
const { version, isLatest } = await fetchLatestBaileysVersion()
const { state, saveCreds } = await useMultiFileAuthState('myPath')
const msgRetryCounterCache = new NodeCache()

        async function getMessage(key)  {
            if(store) {
                const msg = await store.loadMessage(key.remoteJid, key.id)
                return msg?.message || undefined
            }
            // only if store is present
            return proto.Message.fromObject({})
        }

 makeWASocket({
            version,
            logger,
            printQRInTerminal: false,
            mobile: false,
            auth: {
                creds: state.creds,
                keys: makeCacheableSignalKeyStore(state.keys, logger),
            },
            msgRetryCounterCache,
            generateHighQualityLinkPreview: true,
            // ignore broadcast and newsletter messages
            shouldIgnoreJid: jid => !jid || isJidBroadcast(jid) || isJidNewsletter(jid),
            // implement to handle retries & poll updates
            getMessage,
            shouldSyncHistoryMessage: () => true,
            markOnlineOnConnect: false
        })
```
 - Do you have multiple clients on the same IP? yes, 15 clients
 - Are you using a proxy? no

**Additional context**
Using baileys v6.7.5

**Comment by oscarguindzberg** [comment]
These bugs may be related
https://github.com/WhiskeySockets/Baileys/issues/885
https://github.com/WhiskeySockets/Baileys/issues/886
https://github.com/WhiskeySockets/Baileys/issues/887
https://github.com/WhiskeySockets/Baileys/issues/888

**Comment by oscarguindzberg** [comment]
I don't understand why was the issue closed.

**Comment by lgarciaLTM1209** [comment]
I'm experimenting the same issue, someone know how to solve it?

**Comment by bxssdxrk** [comment]
Same with me

**Comment by loic-hamdi** [comment]
> [SheIITear](https://github.com/SheIITear) closed this as [not planned](https://github.com/WhiskeySockets/Baileys/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) [on Jun 22](https://github.com/WhiskeySockets/Baileys/issues/887#event-13250272012)

@SheIITear can you please elaborate, as this issue is still happening?

**Comment by dcpenteado** [comment]
Same

**Comment by pxawtyy** [comment]
still.

**Comment by Pani-Kaz** [comment]
still happens

**Comment by leperdomor** [comment]
Any solution or update?

**Comment by rafwell** [comment]
+1

**Comment by leperdomor** [comment]
After reading the documentation I found the following optimization that has worked for me so far.

Periodic cleanup
Use the timeRelease option or scheduled restarts to clear accumulated data. This helps keep the storage file size under control.

const adapterProvider = createProvider(Provider, { 
    experimentalStore: true,
    timeRelease: 10800000, // 3 hours in milliseconds
})

in addition to this configuration I recommend a reboot every 12 or 24 hours depending on how active your bot is.

Possible Solution
When using the free providers we will need to restart the bot to avoid accumulating temporary data that may affect its performance. In that case an easy solution to implement is to schedule restarts, these restarts will not need to scan the QR again.

Docker and Pm2 One way to do it if you are using docker could be to implement in your docker image Pm2 and with pm2-runtime start your container with a cron pattern.

**Comment by pxawtyy** [comment]
for now, the workaround is to simply **comment out** the lines that log this

path: 

> /yourproject/node_modules/libsignal/src/session_builder.js

search for **"console"** and comment out the **2 occurrences**

there are other annoying logs, like _"decrypted message with closed session"_ and _"failed to decrypt message with any known session"._ for these, same path, but **session_cipher.js**

search for **"console"** and comment out **all occurrences**

there are also others (opening session, closing session...), same path, but **session_record.js**

search for **"console.warn"** and **"console.info"** and you can comment out **all occurrences**

the downside is that you'll have to repeat this process **every time** the library is updated or reinstalled.

**EDIT: probably the issue was closed because it's not a Baileys bug, just logging info of a dep library**

**Comment by herikaniugu** [comment]
try require("util").inspect.defaultOptions.depth = 0

or
console.log = () => {}
console.warn = () => {}
console.error = () => {}

or
console.debug = () => {}
console.trace = () => {}
