### ISSUE TITLE
How to decline a call

### ISSUE THREAD

**Issue by banndicoot-king** [WhiskeySockets/Baileys#890]
How to decline a wp call

**Comment by bobslavtriev** [comment]
https://github.com/WhiskeySockets/Baileys/blob/f25f83656a7cadbcdaf66b7fea72b9d4b3a72aa0/src/Socket/messages-recv.ts#L115

**Comment by CSFelix** [comment]
Try something like this:

```ts
sock.ev.on("call", async (callsList: WACallEvent[]) => {
    for (const call of callsList) {
        await sock.rejectCall(call.id, call.from);
    }
});
```

**Comment by CSFelix** [comment]
> any code to accept the call and take the call event

I guess that this functionality doesn't exist up to now. There's a whole Text Channel destined to only calls on Baileys' Server on Discord.

Here is the invite: https://discord.gg/VNf5PCeq
