### ISSUE TITLE
[BUG] reason: Error: bad-request client.profilePictureUrl()

### ISSUE THREAD

**Issue by Its-me-nishmal** [WhiskeySockets/Baileys#900]
Unhandled Rejection at: Promise {
  <rejected> Error: bad-request
      at assertNodeErrorFree (/home/user/rail-way-bot/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
      at query (/home/user/rail-way-bot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:48)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.profilePictureUrl (/home/user/rail-way-bot/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:442:24)
      at async EventEmitter.<anonymous> (/home/user/rail-way-bot/index.js:426:22) {
    data: 400,
    isBoom: true,
    isServer: true,
    output: { statusCode: 500, payload: [Object], headers: {} }
  }
}

**Comment by 4relial** [comment]
+1

**Comment by dephea** [comment]
+1

**Comment by rayss868** [comment]
+1

**Comment by leandrodesign** [comment]
+1

**Comment by yepelinux** [comment]
+1

**Comment by Its-me-nishmal** [comment]
fix #901 nice , working well

**Comment by dimasmpp130** [comment]
Now now you don't need to update your baileys version to the latest version example $ npm install @whiskeysockets/baileys@zennn08/Baileys#profile-picture-url

You can take or access profile photos without it saying "BAD REQUEST". There is one way to retrieve or access a profile photo without it not saying "BAD REQUEST"

The first step :
You go to your own bot script folder then look for the folder node_modules > @whiskeysockets > baileys > lib > Socket > chats.js

Second step:
After finding the folder above that I told you about above, then you look for a function or code in the form of "profilePictureUrl" then replace the previous code with the new code below 👇👇

const profilePictureUrl = async (jid, type = 'preview', timeoutMs) => {
        var _a;
        jid = (0, WABinary_1.jidNormalizedUser)(jid);
        const result = await query({
            tag: 'iq',
            attrs: {
                target: jid,
                to: WABinary_1.S_WHATSAPP_NET,
                type: 'get',
                xmlns: 'w:profile:picture'
            },
            content: [
                { tag: 'picture', attrs: { type, query: 'url' } }
            ]
        }, timeoutMs);
        const child = (0, WABinary_1.getBinaryNodeChild)(result, 'picture');
        return (_a = child === null || child === void 0 ? void 0 : child.attrs) === null || _a === void 0 ? void 0 : _a.url;
    };

After you change it, just save the previous edits and try to see the results, good luck :)

Note:
The code or function above can be installed on any Baileys version, whether it's 6.5.0 / 6.6.0 or also 6.4.0 and previous versions, so there's no need to update to the Baileys version like I said above, maybe this might work for you, thank you!!!
