### ISSUE TITLE
[BUG] error bad-request when I try to get the profilePicture with profilePictureUrl("xyz@g.us")

### ISSUE THREAD

**Issue by Yago-Tavares** [WhiskeySockets/Baileys#904]
**Describe the bug**
I'm trying to get the contact profile picture who send me message, but I receive the follow error:
```
Error: bad-request
    at assertNodeErrorFree (C:\Users\devs\Documents\xama\backend\node_modules\@whiskeysockets\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (C:\Users\devs\Documents\xama\backend\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:145:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.profilePictureUrl (C:\Users\devs\Documents\xama\backend\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:442:24)
    at async verifyContact (C:\Users\devs\Documents\xama\backend\dist\services\WbotServices\wbotMessageListener.js:439:25)
    at async handleMessage (C:\Users\devs\Documents\xama\backend\dist\services\WbotServices\wbotMessageListener.js:1441:25)
    at async EventEmitter.<anonymous> (C:\Users\devs\Documents\xama\backend\dist\services\WbotServices\wbotMessageListener.js:1849:21) {
  data: 400,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```

The message contact id is valid

**To Reproduce**
1. Created a new connection
2. Receive a new message
3. Try get the profile picture with the message ID

**Expected behavior**
Return the url picture

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? 
```
let wsocket: Session = null;
      const store = makeInMemoryStore({
        logger: loggerBaileys
      });

      const {state, saveState} = await authState(whatsapp);

      const msgRetryCounterCache = new NodeCache();

      wsocket = makeWASocket({
        logger: loggerBaileys,
        printQRInTerminal: false,
        browser: Browsers.appropriate("Desktop"),
        auth: {
          creds: state.creds,
          keys: makeCacheableSignalKeyStore(state.keys, logger),
        },
        version,
        msgRetryCounterCache,
        shouldIgnoreJid: jid => isJidBroadcast(jid),
        defaultQueryTimeoutMs: undefined,
      });

```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? Yes

**Additional context**
-

**Comment by thiagoorodrigues** [comment]
@Yago-Tavares check this #901

**Comment by Yago-Tavares** [comment]
Thank you

**Comment by dimasmpp130** [comment]
Now now you don't need to update your baileys version to the latest version example $ npm install @whiskeysockets/baileys@zennn08/Baileys#profile-picture-url

You can take or access profile photos without it saying "BAD REQUEST". There is one way to retrieve or access a profile photo without it not saying "BAD REQUEST"

The first step :
You go to your own bot script folder then look for the folder node_modules > @whiskeysockets > baileys > lib > Socket > chats.js

Second step:
After finding the folder above that I told you about above, then you look for a function or code in the form of "profilePictureUrl" then replace the previous code with the new code below 👇👇

const profilePictureUrl = async (jid, type = 'preview', timeoutMs) => {
        var _a;
        jid = (0, WABinary_1.jidNormalizedUser)(jid);
        const result = await query({
            tag: 'iq',
            attrs: {
                target: jid,
                to: WABinary_1.S_WHATSAPP_NET,
                type: 'get',
                xmlns: 'w:profile:picture'
            },
            content: [
                { tag: 'picture', attrs: { type, query: 'url' } }
            ]
        }, timeoutMs);
        const child = (0, WABinary_1.getBinaryNodeChild)(result, 'picture');
        return (_a = child === null || child === void 0 ? void 0 : child.attrs) === null || _a === void 0 ? void 0 : _a.url;
    };

After you change it, just save the previous edits and try to see the results, good luck :)

Note:
The code or function above can be installed on any Baileys version, whether it's 6.5.0 / 6.6.0 or also 6.4.0 and previous versions, so there's no need to update to the Baileys version like I said above, maybe this might work for you, thank you!!!
