### ISSUE TITLE
[BUG]  "waiting for message" resend issue.

### ISSUE THREAD

**Issue by keef3ar** [WhiskeySockets/Baileys#905]
Here’s the detailed bug report based on the provided information:

Describe the bug
When resending a message in a personal chat, the sendToAll variable is incorrectly set to true, preventing the message from being resent. Changing the value to false resolves the issue.

To Reproduce

	1.	Create a new connection.
	2.	Make keys of partipiciant invalid(i changed 1 letter in baseKey) to cause resend message
	3.	Send a message in a personal chat.
	4.	See "waiting for message"

Expected behavior
The message should be resent correctly in the personal chat when sendToAll is set to false.

[Link to the problematic line](https://github.com/WhiskeySockets/Baileys/blob/d396a03e65449cb1f4fbab317f6127e66fad6c98/src/Socket/messages-recv.ts#L548).

<img width="578" alt="image" src="https://github.com/WhiskeySockets/Baileys/assets/35760257/bb018c4f-a528-47b0-878b-2d87e50e32f5">

**Comment by keef3ar** [comment]
<img width="641" alt="image" src="https://github.com/WhiskeySockets/Baileys/assets/35760257/799d51f1-5b4c-4f0b-b4c9-059c7c5ef953">
removing this "else" heps for me. Tested in chat with user having 2 web sessions.

**Comment by azudindaem** [comment]
> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/35760257/345938188-799d51f1-5b4c-4f0b-b4c9-059c7c5ef953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzIyMjIsIm5iZiI6MTcyMDEzMTkyMiwicGF0aCI6Ii8zNTc2MDI1Ny8zNDU5MzgxODgtNzk5ZDUxZjEtNWI0Yy00ZjBiLWI0YzktMDU5YzdjNWVmOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDIyMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMGQ2MjlmNjk0MmI5YzEzZjJkN2ZjMGUwYmZmOWIwNWYwN2NmOWI4YTkyM2E0MjJmNzBjMjlhZDU1MmY2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCFTmzd8_r6rhfWXE1AFhbNO8e_2J0ErQoxGI4Dh4wM">
> removing this "else" heps for me. Tested in chat with user having 2 web sessions.

Just because your code works with a few changes, it doesn't mean your code is correct.
