### ISSUE TITLE
[BUG] Get profile picture url is broken

### ISSUE THREAD

**Issue by AidanFrencken** [WhiskeySockets/Baileys#917]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. activated profilePictureUrl function

**Expected behavior**
should return profile picture url or valid error

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like? 
 printQRInTerminal: true,
        auth: state,
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**

`const { DisconnectReason, useMultiFileAuthState } = require("@whiskeysockets/baileys");
const makeWASocket = require("@whiskeysockets/baileys").default;

async function connectionLogic() {
    const { state, saveCreds } = await useMultiFileAuthState("auth_info_baileys");
    console.log("Starting connection...");

    const sock = makeWASocket({
        printQRInTerminal: true,
        auth: state,
    });

    sock.ev.on("connection.update", async (update) => {
        const { connection, lastDisconnect, qr } = update || {};

        if (qr) {
            console.log(qr);
        }

        if (connection === "close") {
            const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
            console.log('Connection closed due to', lastDisconnect?.error, ', reconnecting', shouldReconnect);
            if (shouldReconnect) {
                connectionLogic();
            }
        } else if (connection === "open") {
            console.log('Connection opened');
            // Fetch and log the profile picture URL here
            const ppUrl = await sock.profilePictureUrl("31641581432@s.whatsapp.net");
            console.log(ppUrl);
        }
    });

    sock.ev.on("messages.upsert", (messageInfo) => {
        console.log(messageInfo);
    });

    sock.ev.on("creds.update", saveCreds);
}

connectionLogic();
`

ppUrl throws error 500

**Comment by SethuXD** [comment]
+1

**Comment by Rippanteq7** [comment]
#901

**Comment by bobslavtriev** [comment]
UPDATE WITH NPM/YARN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by raphaelvserafim** [comment]
+1

**Comment by NeKosmico** [comment]
F

**Comment by dimasmpp130** [comment]
Now now you don't need to update your baileys version to the latest version example $ npm install @whiskeysockets/baileys@zennn08/Baileys#profile-picture-url

You can take or access profile photos without it saying "BAD REQUEST". There is one way to retrieve or access a profile photo without it not saying "BAD REQUEST"

The first step :
You go to your own bot script folder then look for the folder node_modules > @whiskeysockets > baileys > lib > Socket > chats.js

Second step:
After finding the folder above that I told you about above, then you look for a function or code in the form of "profilePictureUrl" then replace the previous code with the new code below 👇👇

const profilePictureUrl = async (jid, type = 'preview', timeoutMs) => {
        var _a;
        jid = (0, WABinary_1.jidNormalizedUser)(jid);
        const result = await query({
            tag: 'iq',
            attrs: {
                target: jid,
                to: WABinary_1.S_WHATSAPP_NET,
                type: 'get',
                xmlns: 'w:profile:picture'
            },
            content: [
                { tag: 'picture', attrs: { type, query: 'url' } }
            ]
        }, timeoutMs);
        const child = (0, WABinary_1.getBinaryNodeChild)(result, 'picture');
        return (_a = child === null || child === void 0 ? void 0 : child.attrs) === null || _a === void 0 ? void 0 : _a.url;
    };

After you change it, just save the previous edits and try to see the results, good luck :)

Note:
The code or function above can be installed on any Baileys version, whether it's 6.5.0 / 6.6.0 or also 6.4.0 and previous versions, so there's no need to update to the Baileys version like I said above, maybe this might work for you, thank you!!!

**Comment by AidanFrencken** [comment]
> Now now you don't need to update your baileys version to the latest version example $ npm install @whiskeysockets/baileys@zennn08/Baileys#profile-picture-url
> 
> You can take or access profile photos without it saying "BAD REQUEST". There is one way to retrieve or access a profile photo without it not saying "BAD REQUEST"
> 
> The first step : You go to your own bot script folder then look for the folder node_modules > @WhiskeySockets > baileys > lib > Socket > chats.js
> 
> Second step: After finding the folder above that I told you about above, then you look for a function or code in the form of "profilePictureUrl" then replace the previous code with the new code below 👇👇
> 
> const profilePictureUrl = async (jid, type = 'preview', timeoutMs) => { var _a; jid = (0, WABinary_1.jidNormalizedUser)(jid); const result = await query({ tag: 'iq', attrs: { target: jid, to: WABinary_1.S_WHATSAPP_NET, type: 'get', xmlns: 'w:profile:picture' }, content: [ { tag: 'picture', attrs: { type, query: 'url' } } ] }, timeoutMs); const child = (0, WABinary_1.getBinaryNodeChild)(result, 'picture'); return (_a = child === null || child === void 0 ? void 0 : child.attrs) === null || _a === void 0 ? void 0 : _a.url; };
> 
> After you change it, just save the previous edits and try to see the results, good luck :)
> 
> Note: The code or function above can be installed on any Baileys version, whether it's 6.5.0 / 6.6.0 or also 6.4.0 and previous versions, so there's no need to update to the Baileys version like I said above, maybe this might work for you, thank you!!!

this fixes the issue, thanks

**Comment by gabresende** [comment]
Will it ever be fixed?
