### ISSUE TITLE
[BUG] commentMessage is not supported in the community 

### ISSUE THREAD

**Issue by faxxcoders** [WhiskeySockets/Baileys#920]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by bobslavtriev** [comment]
What is the bug? Which error? Why did you mark it as [BUG]?

**Comment by faxxcoders** [comment]
> Apa bug-nya? Kesalahan apa? Mengapa Anda menandainya sebagai [BUG]?

proto expected

**Comment by faxxcoders** [comment]
Jjj

**Comment by Rippanteq7** [comment]
Huh??

**Comment by faxxcoders** [comment]
> Huh??

Bang sepuh lewat

**Comment by faxxcoders** [comment]
> Huh??

Gimana bang cara send commentMessage
