### ISSUE TITLE
node?.attrs?.jid ???   but not found jid

### ISSUE THREAD

**Issue by jianhuihi** [WhiskeySockets/Baileys#931]
https://github.com/WhiskeySockets/Baileys/blob/5bdfc631058fdb0f7a83b6865339b134a3f62453/src/Socket/messages-recv.ts#L397C1-L398C1

Baileys/src/Socket/messages-recv.ts

node value
 {
  tag: 'notification',
  attrs: {
    from: 'xxxx@s.whatsapp.net',
    type: 'picture',
    id: 'xxx',
    notify: 'xxx',
    t: '1721294595'
  },
  content: [ { tag: 'set', attrs: [Object], content: undefined } ]
}

```case 'picture':
			const setPicture = getBinaryNodeChild(node, 'set')
			const delPicture = getBinaryNodeChild(node, 'delete')
			ev.emit('contacts.update', [{
				id: jidNormalizedUser(node?.attrs?.jid) || ((setPicture || delPicture)?.attrs?.hash) || '',
				imgUrl: setPicture ? 'changed' : 'removed'
			}])
			```
			
			
id: jidNormalizedUser(node?.attrs?.jid) || ((setPicture || delPicture)?.attrs?.hash) || '',    

 result is ''

**Comment by jianhuihi** [comment]
id: jidNormalizedUser(node?.attrs?.jid)   >> 

id: jidNormalizedUser(node?.attrs?.from)

**Comment by bobslavtriev** [comment]
https://github.com/WhiskeySockets/Baileys/pull/906
