### ISSUE TITLE
[BUG]  getLastMessageInChat() archive Chat

### ISSUE THREAD

**Issue by leandroeldj** [WhiskeySockets/Baileys#940]
I want to archive the chats but when doing so I get an error because getLastMessageInChat is not defined.

Or would there be another way to archive a chat?

I would be very grateful for the help

const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net')
await sock.chatModify({ archive: true, lastMessages: [lastMsgInChat] }, '123456@s.whatsapp.net')

**Comment by bobslavtriev** [comment]
Haven't you learned to read? Or do you just not know how to program?

Still declared it as [BUG], really clueless...

**Comment by SheIITear** [comment]
As the documentation says, you will have to implement it on your own side.
