### ISSUE TITLE
Debunk WebSocket Messages

### ISSUE THREAD

**Issue by kaykyr** [WhiskeySockets/Baileys#943]
Hey guys! Long time ago, I remember the original Baileys repo had a script to debunk WebSocket Messages from WhatsAppWeb by passing a .har file (exported on Chrome Dev Tools, for example). Is this still working? How can I do that? Sometimes I want to contribute but I don't have a way to debunk the WS Binary Messages.

**Comment by hacxk** [comment]
```js

if(!window.encodeBack){
  window.encodeBack = require("WAWebSendMsgCommonApi").encodeAndPad;
}

require("WAWebSendMsgCommonApi").encodeAndPad = (a) => {
  let result = window.encodeBack(a);

  console.log(a);
  return result
}
``` 

**When u paste this on your browser console you can see messages (Only Yours)**
