### ISSUE TITLE
[BUG] Error: WebSocket Error (connect ECONNREFUSED 157.240.13.54:443)

### ISSUE THREAD

**Issue by rizkijn123** [WhiskeySockets/Baileys#944]
anyone have same problem with Error: WebSocket Error (connect ECONNREFUSED 157.240.13.54:443)? 
![image](https://github.com/user-attachments/assets/384a3579-b6c2-4721-b4e1-b406feb157fb)

**Comment by PurpShell** [comment]
connection refused, this is a problem with your internet connection, not baileys
