### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hyodu** [WhiskeySockets/Baileys#954]
Hello, I want to report a problem facing **(ios) iPhone and desktop users**, The bot messages **don't show** for this users, Can you please resolve this issue?

**Comment by hacxk** [comment]
what messages not showing? text or media or template messages?

**Comment by Hyodu** [comment]
> what messages not showing? text or media or template messages?

Message with buttons like lists...

**Comment by hacxk** [comment]
> > what messages not showing? text or media or template messages?
> 
> Message with buttons like lists...

That is template messages it can't shown in web whatsapp and IOS and Some androids also template messages sending option is closing from next baileys update

**Comment by Hyodu** [comment]
> > > what messages not showing? text or media or template messages?
> > 
> > 
> > Message with buttons like lists...
> 
> That is template messages it can't shown in web whatsapp and IOS and Some androids also template messages sending option is closing from next baileys update

That's mean that the **button system** will be abolished in general?

**Comment by hacxk** [comment]
> > > > what messages not showing? text or media or template messages?
> > > 
> > > 
> > > Message with buttons like lists...
> > 
> > 
> > That is template messages it can't shown in web whatsapp and IOS and Some androids also template messages sending option is closing from next baileys update
> 
> That's mean that the **button system** will be abolished in general?

yeah button and list will deprecated next update
