### ISSUE TITLE
[BUG] Stream Errored (conflict)

### ISSUE THREAD

**Issue by vinicius-lailla** [WhiskeySockets/Baileys#963]
Description:
I am encountering an error when trying to establish a connection using the Baileys library. The error displayed is Stream Errored (conflict) and occurs after creating and closing a connection, when we try to use the saved credentials to reconnect.

`{"level":30,"time":"2024-07-29T16:36:07.371Z","pid":53,"hostname":"ip-10-0-1-96.ec2.internal","class":"baileys","trace":"Error: Stream Errored (conflict)\n at WebSocketClient.<anonymous> (/home/node/app/node_modules/baileys/lib/Socket/socket.js:524:13)\n at WebSocketClient.emit (node:events:518:28)\n at /home/node/app/node_modules/baileys/lib/Socket/socket.js:241:35\n at Object.decodeFrame (/home/node/app/node_modules/baileys/lib/Utils/noise-handler.js:149:17)\n at WebSocketClient.onMessageReceived (/home/node/app/node_modules/baileys/lib/Socket/socket.js:217:15)\n at WebSocketClient.emit (node:events:518:28)\n at WebSocket.<anonymous> (/home/node/app/node_modules/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n at WebSocket.emit (node:events:518:28)\n at Receiver.receiverOnMessage (/home/node/app/node_modules/ws/lib/websocket.js:1209:20)\n at Receiver.emit (node:events:518:28)","msg":"connection errored"}
`

**Comment by DineshValor** [comment]
Did you able to solve it?
