### ISSUE TITLE
Simultaneous clients don't receive messages in messages.upsert at the same time.

### ISSUE THREAD

**Issue by ecatugy** [WhiskeySockets/Baileys#965]
Whenever I have multiple clients, specifically more than four, receiving messages simultaneously, at least two of them don't trigger the messages.upsert handler. However, if I send messages to each client individually with at least a 5-second interval, the handler triggers properly. Has anyone else experienced this behavior?

**Comment by qwezxcvb** [comment]
**I'm having the same problem, did you find an answer or a workaround?**
@ecatugy
