### ISSUE TITLE
 Cannot destructure property 'user'

### ISSUE THREAD

**Issue by xyzencode** [WhiskeySockets/Baileys#968]
TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.

**Comment by ahmedB7r** [comment]
i got this when react to message

**Comment by dimasmpp130** [comment]
You can install this problem with npm install @whiskeysockets/baileys@bobslavtriev/Baileys#af atau yarn add @whiskeysockets/baileys@bobslavtriev/Baileys#af 

But you need to remind yourself that this version cannot display user profile photos, so if you want to use npm above, whenever you want to display a profile photo, you have to change or edit it in your node_modules folder, follow the method below:

The first step :
You go to your own bot script folder then look for the folder node_modules > @whiskeysockets > baileys > lib > Socket > chats.js

Second step:
After finding the folder above that I told you about above, then you look for a function or code in the form of "profilePictureUrl" then replace the previous code with the new code below 👇👇

const profilePictureUrl = async (jid, type = 'preview', timeoutMs) => {
        var _a;
        jid = (0, WABinary_1.jidNormalizedUser)(jid);
        const result = await query({
            tag: 'iq',
            attrs: {
                target: jid,
                to: WABinary_1.S_WHATSAPP_NET,
                type: 'get',
                xmlns: 'w:profile:picture'
            },
            content: [
                { tag: 'picture', attrs: { type, query: 'url' } }
            ]
        }, timeoutMs);
        const child = (0, WABinary_1.getBinaryNodeChild)(result, 'picture');
        return (_a = child === null || child === void 0 ? void 0 : child.attrs) === null || _a === void 0 ? void 0 : _a.url;
    };

**Comment by Rippanteq7** [comment]
What's this? what do you want to do? we need more information like your code.
Please don't ask by just putting an error message.
