### ISSUE TITLE
Is there a possibility to add labels to contacts as well as WhatsApp Business?

### ISSUE THREAD

**Issue by JuniorRibas** [WhiskeySockets/Baileys#97]
I noticed that there was a merge about event support for labels

But I would like to know if it is possible to add a label to a contact using Baileys

**Comment by marcospaulo-4** [comment]
I would also like to know, is there any example of how this can be done?

**Comment by hmassareli** [comment]
Same question here, I would like to know if I could get a list of chats filtered by labels, or maybe include the label prop on the event where you get the history of chats

**Comment by Auties00** [comment]
https://github.com/WhiskeySockets/Baileys/pull/69
