### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OyakXD** [WhiskeySockets/Baileys#971]
**Describe the bug**
Send message in group with many people

**To Reproduce**
1.  I sent any message in a group with many users, about 1,000 people

**Expected behavior**
Faster shipping, such as privately or in small groups of less than 10 people

**Additional context**
I briefly analyzed the code for sending a message, and apparently it executes a for between the users in the group, and with each message sent it freezes the for until the message is sent. I imagine that's the problem.

**Comment by SheIITear** [comment]
Dup of #970
