### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wesleysnp013** [WhiskeySockets/Baileys#974]
Hello, I'm doing an npm install and I'm getting the following error:

error An unexpected error occurred: "https://codeload.github.com/WhiskeySockets/Baileys/tar.gz/07742e651e14ae481cc192051fa59b9c50c42bbb: Hostname/IP does not match certificate's altnames: Host: codeload.github.com. is not in the cert's altnames: DNS:dns.google, DNS:dns.google.com, DNS:*.dns.google.com, DNS:8888.google, DNS:dns64.dns.google, IP Address:8.8.8.8, IP Address:8.8.4.4, IP Address:2001:4860:4860:0:0:0:0:8888, IP Address:2001:4860:4860:0:0:0:0:8844, IP Address:2001:4860:4860:0:0:0:0:6464, IP Address:2001:4860:4860:0:0:0:0:64".

Can anyone help me?

**Comment by bobslavtriev** [comment]
BUG?????????????????????????????????????????????????????????

**Comment by wesleysnp013** [comment]
Yes!
