### ISSUE TITLE
Is there a way to retrieve all past WhatsApp messages?

### ISSUE THREAD

**Issue by BoboiAzumi** [WhiskeySockets/Baileys#98]
I want to ask this,
Is there a way to retrieve all past WhatsApp messages ?

**Comment by Auties00** [comment]
There's a hard limit at around 100k messages coming from a single chat

**Comment by alsak0de** [comment]
How could that be done in a running client? is there a socket function to retrieve all messages and contacts from the network? is it necessary to logout and read the qr again??

**Comment by luiscuriel** [comment]
Yes, you need to read the qr again, I have not found a method to query all chats and/or messages once you have already logged in and not stored or received everything correctly.

**Comment by lomeliDev** [comment]
> Yes, you need to read the qr again, I have not found a method to query all chats and/or messages once you have already logged in and not stored or received everything correctly.

what is the method ?

**Comment by apprendii7** [comment]
Have some way to reload connection and get messaging-history event again? without read a new QRCode? Because some messages do not arrive.

**Comment by TiagoGouvea** [comment]
I'm looking for this solution.. a way to get all messages from a chat, even before its first connection.

@BoboiAzumi (or anyone else) did you find out how to do it?

**Comment by kuarora** [comment]
Hi, did you find any solution?

**Comment by abhijit360** [comment]
I noticed that this thread didn't clearly answer it. I thought I'd chime in. 
You can set the syncFullHistory boolean value to true as such. 

```
 sock = makeWASocket({
    ...,
    syncFullHistory: true,
  });
```

you must then handle the whatsapp history event as such
```
 sock.ev.on("messaging-history.set", ({ chats: syncedChats, contacts: syncedContact
          +s, messages: syncedMessages, isLatest }) => {
....
)
```
