### ISSUE TITLE
Please support the new version of Link with phone number instead function, thank you!

### ISSUE THREAD

**Issue by xiaohuwei** [WhiskeySockets/Baileys#982]
Today, when I was using the web version of whatApp, I found that I could get a string of 8-digit codes. I think Baileys should support this feature.

**Comment by xiaohuwei** [comment]
https://h5.go-share.cc/static/img/3.39d0fdfc.jpg

**Comment by xiaohuwei** [comment]
https://h5.go-share.cc/static/img/4.ddca7c21.jpg

**Comment by Fonnte** [comment]
It's already exist. Please take your time to do some research before opening an issue. It's even exist in the example.ts using pairingCode : https://github.com/WhiskeySockets/Baileys/blob/master/Example/example.ts

**Comment by pruthvik91** [comment]
This currently requires initial authentication with a QR code. However, I’m building an app to send WhatsApp messages, and if the QR code appears on the same device, it becomes impossible to scan it. That’s why I need the pairing code feature, similar to WhatsApp, which allows authentication without scanning a QR code.
