### ISSUE TITLE
[BUG] Timed Out error whenever I'm trying to send a broadcast message

### ISSUE THREAD

**Issue by aderibigbeganiu** [WhiskeySockets/Baileys#985]
it works perfectly well for private message but get error on broadcast
Error sending message Error: Timed Out
    at /Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:145:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:140:19)\n' +
      '    at waitForMessage (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:119:53)\n' +
      '    at query (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:141:22)\n' +
      '    at groupQuery (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:12:55)\n' +
      '    at groupMetadata (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:30)\n' +
      '    at /Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:323:47\n' +
      '    at /Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:326:23\n' +
      '    at Object.transaction (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' +
      '    at relayMessage (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:306:30)\n' +
      '    at Object.sendMessage (/Users/ganiuadelekeaderibigbe/Desktop/projects/Personal/bwb/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:664:23)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

Here is my implementation: 
try {
                                await sendMessageWTyping(
                                    { text: "Hello there!" },
                                    msg.key.remoteJid!
                                );
                                await sock.sendMessage(
                                    msg.key.remoteJid!,
                                    {
                                        image: {
                                            url: "src/assets/IMG_3184.jpeg",
                                        },
                                        caption: `Hello ${msg.pushName}\nCheck this out! :D`,
                                    },
                                    {
                                        quoted: msg,
                                    }
                                );
                                await sock.sendMessage(
                                    jid,
                                    {
                                        image: {
                                            url: "src/assets/IMG_3184.jpeg",
                                        },
                                        caption: `Hello ${msg.pushName}`,
                                    },
                                    {
                                        statusJidList,
                                        broadcast: true,
                                    }
                                );
                                console.log("Story message sent");
                            } catch (err) {
                                console.error("Error sending message", err);
                            }
the first to sendMessage functions work perfectly but the third one doesn't, it was working before I don't know why it stopped working

**Comment by trxsistemas** [comment]
I also have the same error.

**Comment by devlikepro** [comment]
try this fix https://github.com/WhiskeySockets/Baileys/pull/986

**Comment by aderibigbeganiu** [comment]
Thank you @devlikepro i'll try this now
