### ISSUE TITLE
[BUG] Not show FLOW button

### ISSUE THREAD

**Issue by EnchyID** [WhiskeySockets/Baileys#990]
```javascript
let template = generateWAMessageFromContent(jid, {
		viewOnceMessage: {
			message: {
				messageContextInfo: {
					deviceListMetadata: {},
					deviceListMetadataVersion: 2
				},
				interactiveMessage: {
					header: { type: "text", text: "Test" },
					body: { text: "Body" },
					footer: { text: "Footer" },
					nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.create({
					    nativeFlowButton: proto.Message.InteractiveMessage.NativeFlowMessage.NativeFlowButton.create({
    			            flow_message_version: "3",
    			            flow_id: "1",
    	     	            flow_cta: "Hmm",
    					    flow_action: "navigate",
    	     	            flow_action_payload: {
					            screens: [{
						            name: "screen_pukfuf",
				                    title: "testing",
						            data: {},
				                    terminal: true,
						            layout: JSON.stringify({
						                type: "SingleColumnLayout",
						                children: [{
					                        type: "Form",
						                    name: "flow_path",
						                    children: [{
						                        "type": "TextInput",
						                        "name": "TextInput_48949d",
						                        "label": "label",
						                        "required": true,
						                        "input-type": "text"
						                    }, {
						                        "type": "Dropdown",
						                        "label": "Please select",
						                        "required": true,
						                        "name": "Dropdown_b67c26",
						                        "data-source": [{
						                            "id": "0_Option_1",
						                            "title": "Option 1"
						                        }]
						                    }, {
						                        "type": "Footer",
						                        "label": "Cek",
						                        "on-click-action": {
						                            "name": "complete",
						                            "payload": {
						                                "screen_0_TextInput_0": "${form.TextInput_48949d}",
						                                "screen_0_Dropdown_1": "${form.Dropdown_b67c26"
						                            }
						                        }
						                    }]
						                }]
						            })
					            }]
					        }
					    })
					})
				}
			}
		}
	}, {userJid: msg.sender, quoted: msg})
```

Anyone can you help me?

**Comment by SashaMaz** [comment]
There are no bugs regarding the buttons, they are discontinued, close this issue now, if you had read the functions correctly, you would be aware that WhatsApp has discontinued the buttons outside the official API

**Comment by EnchyID** [comment]
No, the buttons and list can still be used until now, but I was confused after trying WhatsApp Flow

**Comment by EnchyID** [comment]
> There are no bugs regarding the buttons, they are discontinued, close this issue now, if you had read the functions correctly, you would be aware that WhatsApp has discontinued the buttons outside the official API.
> 
> duplicate: #956

![Uploading Screenshot_20240821-210720_WhatsApp.png…]()

**Comment by EnchyID** [comment]
> There are no bugs regarding the buttons, they are discontinued, close this issue now, if you had read the functions correctly, you would be aware that WhatsApp has discontinued the buttons outside the official API.
> 
> duplicate: #956

![Screenshot_20240821-211412_WhatsApp](https://github.com/user-attachments/assets/19860ac6-17e5-40d3-abb8-417759a48029)

This is catalog message

**Comment by EnchyID** [comment]
In fact, these buttons are not limited, there can be many buttons, no longer limited to just 3, but many

![Screenshot_20240821-212456_WhatsApp](https://github.com/user-attachments/assets/89d950b6-17eb-445c-8958-c63dba0bea97)

**Comment by Rippanteq7** [comment]
Bruh

**Comment by mohamed-2010** [comment]
What's version you are used?

**Comment by SashaMaz** [comment]
> 
> Here, list and button work

What is your EnchyBot number?

**Comment by EnchyID** [comment]
> > Here, list and button work
> 
> What is your EnchyBot number?

what u want?

**Comment by EnchyID** [comment]
> What's version you are used?

6.7.6

**Comment by SashaMaz** [comment]
mobile number, I want to receive a message with buttons on my phone

**Comment by EnchyID** [comment]
> > what u want?
> 
> mobile number, I want to receive a message with buttons on my phone

![20240820_122704](https://github.com/user-attachments/assets/79e44ffe-6ab5-4c82-8fc5-8a938a0710e9)

Scan to chat mybot contact, send "Menu" or /start to start chat

**Comment by yaelahsas** [comment]
its work?

**Comment by SashaMaz** [comment]
> its work?

Buttons? yes.

**Comment by a5r0n** [comment]
@EnchyID how do you send list of buttons and sections?
(also, i see you added a little badge "Games" and "Popular")

**Comment by harvansh265** [comment]
> jid, options, msg

can you please share the sample of jid, options, msg ?

**Comment by EnchyID** [comment]
> @EnchyID how do you send list of buttons and sections? (also, i see you added a little badge "Games" and "Popular")

maybe you try added "highlight_label" at beetween of title and sections

**Comment by EnchyID** [comment]
> @EnchyID how do you send list of buttons and sections? (also, i see you added a little badge "Games" and "Popular")

```javascript
function sendListMessage(from, message, buttonText, list, msg){    
    let template = generateContentMessage(from, {
        viewOnceMessage: {
            message: {
                messageContextInfo: {
                    deviceListMetadata: {},
                    deviceListMetadataVersion: 2
                },
                interactiveMessage: {
                    header: {
                       type: "text",
                       text: message
                    },
                    body: { text: message },
                    footer: { text: "@EnchyBot" },
                    nativeFlowMessage: {
                        buttons: [{
                            name: "single_select",
                            buttonParamsJson: JSON.stringify({
                                title: buttonText,
                                sections: list
                            })
                        }]
                    }
                }
            }
        }                      
    }, {userJid: msg.sender, quoted: wa})
    
    sock.relayMessage(from, template.message, { messageId: msg.key.id });
}
```

**Comment by harvansh265** [comment]
> > jid, options, msg
> 
> can you please share the sample of jid, options, msg ?

???

**Comment by EnchyID** [comment]
> > > jid, options, msg
> > 
> > 
> > can you please share the sample of jid, options, msg ?
> 
> ???


Here this is of code
```javascript
    sendButtons(jid, [{
          buttonType: "reply",
          buttonText: {display_text: "Press Me"},
          buttonIndex: "Your id of button"
}, {
         buttonType: "url",
         buttonText: {display_text: "Visit"},
         buttonIndex: "https://your-url"
}], msg);
```

**Comment by harvansh265** [comment]
> > > > jid, options, msg
> > > 
> > > 
> > > can you please share the sample of jid, options, msg ?
> > 
> > 
> > ???
> 
> Here this is of code
> 
> ```js
> sendButtons(jid, [{
>     buttonType: "reply",
>     buttonText: {display_text: "Press Me"},
>     buttonIndex: "Your id of button"
> }, {
>     buttonType: "url",
>     buttonText: {display_text: "Visit"},
>     buttonIndex: "https://your-url"
> }], msg);
> ```

got the options data but what about jid and msg ?? or we can only use buttons as reply on any received message ?

**Comment by EnchyID** [comment]
> > > > > jid, options, msg
> > > > 
> > > > 
> > > > can you please share the sample of jid, options, msg ?
> > > 
> > > 
> > > ???
> > 
> > 
> > Here this is of code
> > ```js
> > sendButtons(jid, [{
> >     buttonType: "reply",
> >     buttonText: {display_text: "Press Me"},
> >     buttonIndex: "Your id of button"
> > }, {
> >     buttonType: "url",
> >     buttonText: {display_text: "Visit"},
> >     buttonIndex: "https://your-url"
> > }], msg);
> > ```
> 
> got the options data but what about jid and msg ?? or we can only use buttons as reply on any received message ?

You can call this function on 
sock.on("message_upsert", chat => {
    let msg = chat.messages[0];
    let jid = msg.key.remoteJid;
    //call the function
    sendButtons(jid, ....., msg);
})
