### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RidwanzAnphelibelll** [WhiskeySockets/Baileys#991]
Unknown reason discount | 405 close

**Comment by tonykx** [comment]
Também estou com erro @

**Comment by jsuceir** [comment]
me too

**Comment by aylonmelos1** [comment]
same here

**Comment by adrielCarmo** [comment]
me too

**Comment by adrielCarmo** [comment]
same here

**Comment by JonhnyDev** [comment]
up

**Comment by AliAryanTech** [comment]
Damn same

**Comment by jonhy751** [comment]
update for new version [2, 2417, 1]

**Comment by acorreane** [comment]
change in /baileys/lib/Defaults/baileys-version.json

**Comment by jpazevedo09** [comment]
Even after changing the version, it is not working, it is only showing a connection error.

**Comment by G4br1e3l** [comment]
> change in /baileys/lib/Defaults/baileys-version.json { "version": [2, 2423, 1] }

After change for this, you need to reinstall the repo. Here Worked.

**Comment by jonhy751** [comment]
update version lib, new realease

**Comment by IqbalzzX** [comment]
> change in /baileys/lib/Defaults/baileys-version.json { "version": [2, 2423, 1] }

Thanks

**Comment by PurpShell** [comment]
USE VERSION 6.7.7
