### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cexzas** [WhiskeySockets/Baileys#992]
BUG CONNECTION

**Comment by Cexzas** [comment]
BUG CONNECT

**Comment by adrielCarmo** [comment]
BUG CONNECT

**Comment by jonhy751** [comment]
update for new version [2, 2417, 1]

**Comment by jpazevedo09** [comment]
Even after changing the version, it is not working, it is only showing a connection error.

**Comment by jonhy751** [comment]
update lib
new realease

**Comment by allanlisboa** [comment]
updating the lib here also didn't solve the problem! the qrcode is not generated

**Comment by RynC1999** [comment]
Still same issue. got this error 

Error: Connection Failure\n    at WebSocketClient.<anonymous> (/root/wabot-brosispku/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:529:13)\n    at WebSocketClient.emit (node:events:518:28)\n    at /root/wabot-brosispku/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:241:35\n    at Object.decodeFrame (/root/wabot-brosispku/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:149:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 
 
 already updated to version 6.7.7
 
![image](https://github.com/user-attachments/assets/b034a7b3-4967-4d26-b2b0-7a05fa1d3fc1)
