### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anonphoenix007** [WhiskeySockets/Baileys#995]
![Screenshot_20240822-234932](https://github.com/user-attachments/assets/356df18a-e795-4ac7-a2cf-a564465bac72)

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds

Pairing with baileys gave this error,it has always been working until few hours ago,I rechecked my code but see nothing wrong with it before I decided to create an issue.

**Comment by lugata** [comment]
I'm encountering the same issue today.

**Comment by PurpShell** [comment]
hmmm

**Comment by anonphoenix007** [comment]
> just updated the library using npm update, and it fixed the issue.

I'll try to update and give feedback then,thanks.

**Comment by yuvalwarsh** [comment]
happens to me either, im using 6.7.7

**Comment by keef3ar** [comment]
me to 6.7.7

**Comment by yuvalwarsh** [comment]
im on 6.7.7, i noticed im getting it only for messages in length of 40 chars and above (below that it works fine) 
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds

**Comment by keef3ar** [comment]
6.7.5 with  2.3000.1015901307 same issue

**Comment by keef3ar** [comment]
downgrade node from 22.7.0. im use 20-alpine and proplem resolved

**Comment by anonphoenix007** [comment]
Thanks bro brothers,it is now fixed. the node version was declared in package.json to use 22.* and higher if available ,I specified to use the Version 20 and I changed baileys version to 6.6.0,also changed baileys version to 6.6.0 in my bot project package file.

**Comment by CrazyPrince** [comment]
> Thanks bro brothers,it is now fixed. the node version was declared in package.json to use 22.* and higher if available ,I specified to use the Version 20 and I changed baileys version to 6.6.0,also changed baileys version to 6.6.0 in my bot project package file.

Ok thanks ⭐️
