### ISSUE TITLE
[BUG] Pairing Code 

### ISSUE THREAD

**Issue by rizkanugrha** [WhiskeySockets/Baileys#997]
using WA v2.2413.51, isLatest: true
/root/gento-sw/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:59
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (/root/gento-sw/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:59:19)
    at sendNode (/root/gento-sw/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:78:16)
    at Object.requestPairingCode (/root/gento-sw/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:375:15)
    at async startSock (file:///root/gento-sw/srempet.js:81:14) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

Node.js v18.19.1
Exited with code: 1

**Comment by PATRICK297R** [comment]
update your baileys to latest version

**Comment by rizkanugrha** [comment]
> update your baileys to latest version

I've updated to version 6.7.7 but it's still like that

**Comment by rizkanugrha** [comment]
![Uploading IMG-20240823-WA0037.jpeg…]()
solve

**Comment by Maurifragapane** [comment]
> solved with code : makeWASocket.default({ version: [ 2, 3000, 1015901307 ], .... })

Work perfect with version: [ 2, 3000, 1015901307 ], and Baileys 6.7.7

Thanks
